### ISSUE TITLE
Hot Graphic ‘use graphics as pins’ layout broken

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1002]
I believe it’s a side effect of:
* https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/9e0ddd0414152624284990e81cc8774ffb7c54ef
* https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/3648e9a279cd69da4eca6f39e516e790c1546648.

**Comment by sarveshwar-gavhane** [comment]
@tomgreenfield  i have checked in the last year framework,layout broken issue was there before the above two PR gets merged to the component, i think we need to specify _height and _width to the image, what can be done ?

**Comment by tomgreenfield** [comment]
Hot Graphic [v2.0.0](https://github.com/adaptlearning/adapt-contrib-hotgraphic/tree/v2.0.0) appears fine to me. I'm using the [example JSON](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/example.json#L73-L152) and updating the image paths as appropriate.

Subsequent tagged releases can be remedied by removing this [`position: absolute`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/less/hotgraphic.less#L162).

Additionally, if using the latest code from master, the aforementioned [`display: inline-block`](https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/3648e9a279cd69da4eca6f39e516e790c1546648) definitely breaks the layout.

**Comment by tomgreenfield** [comment]
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/128
