### ISSUE TITLE
define @focus-outline in base.less

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1006]
@focus outline is not defined in the core theme so it will break compilation when this variable is not in the theme.
to fix this add:
@focus-outline: 3px solid orange;
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/less/base.less#L25

**Comment by hrajotia** [comment]
Apart from the above mentioned one below are the few other variable that also need our attention -
- [ ] @primary-color
- [ ] @ie8-max-width
- [ ] @device-width-medium
- [ ] @body-text-font-size

**Comment by brian-learningpool** [comment]
+1
