### ISSUE TITLE
trickle: update properties.schema

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1011]
`startText` and `finalText` is missing

https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/example.json#L25-L27

https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/properties.schema#L144-L160
https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/properties.schema#L303-L310

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-trickle/pull/69
