### ISSUE TITLE
focus sometimes errors jquery.a11y

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1015]
need to update #focuser so that it doesn't read

**Comment by moloko** [comment]
anything happening on this? been sat in the 'todo' column for quite a while

**Comment by tomgreenfield** [comment]
Is this referring to the below?

[`Uncaught jquery.a11y: Could not find the next focusable element`](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L429)

**Comment by oliverfoster** [comment]
yup
