### ISSUE TITLE
Move Tutor functionality to core?

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1019]
Should we move the Tutor functionality to core?  The rationale for this is:
- Tutor on its own just triggers calls to Notify anyway
- Question views/models are part of core already
- It would ease maintenance

**Comment by moloko** [comment]
I was wondering this the other day too. 

I guess the logic behind it being a plugin is that someone might want to use some other method of displaying question feedback, in which case they could just swap out Tutor for whatever other extension.

However, such things are all very well in theory but in practice if they don't get used then it just seems confusing. In particular I know we've seen a few people not realise that Tutor has to be installed & enabled.

**Comment by brian-learningpool** [comment]
Does anybody have any more thoughts on this?  I think it almost ties in with the work for moving a bare bones theme into core as well, and ensuring that things just work without unnecessary configuration.

**Comment by oliverfoster** [comment]
I've used this before to replace tutor. I'd like an option to disable the internal tutor functionality if we can manage that? Otherwise I'm onboard, it's a small usecase as Matt said.

**Comment by moloko** [comment]
Yeah, wherever the code for tutor-style feedback lives, we must have an option to be able to override that with different functionality.

For example we have a client whose design guidelines require that feedback be shown underneath the question - so we need to be able to handle situations like that easily.

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-tutor < this is a good example of inline/overlay feedback

**Comment by oliverfoster** [comment]
all agreed to leave separate
