### ISSUE TITLE
adapt-contrib-accordion - add classes to accordion-item

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1023]
Hey all I would like to be able to add a class to the `accordion-item` so to help with styling when an image is added. This would be in keeping with the `hot-graphic-pins`.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-accordion/commit/cb958d11a9a44029639ef3bb7a87b89d4dcdab09
