### ISSUE TITLE
Warning being generated in console when using 'custom' locking

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1025]
All still works fine, just getting a warning like:
> `AdaptModel.shouldLock: unknown _lockedBy ID "co-15" found on co-10`

Need to _.defer the call to `checkLocking` I suspect

**Comment by hrajotia** [comment]
@moloko below is extract from `contentObject.json` which I've used for cutom locking, For me its not throwing any error.
```json
{
    "_id": "co-15",
    "_parentId": "course",
    "_type": "page",
    "_classes": "assessment",
    "title": "Adapt Assessment",
    "displayTitle": "Adapt Assessment",
    "pageBody": "",
    "body": "",
    "_graphic": {
        "src": "course/en/images/menu_thumb.jpg",
        "alt": "Placeholder graphic."
    },
    "linkText": "View",
    "durationLabel": "Duration:",
    "duration": "2 mins",
    "_pageLevelProgress": {
        "_isEnabled": true
    },
    "_isLocked": true,
    "_lockType": "custom",
    "_lockedBy": ["co-10"]
}
```

Custom locking screenshot -
![image](https://cloud.githubusercontent.com/assets/6231183/14733509/1a27b646-0881-11e6-963b-bd0a6082c40a.png)

Is your implementation is same as above?

**Comment by oliverfoster** [comment]
"_lockType": "custom", is for the parent

**Comment by moloko** [comment]
yep as @oliverfoster says `_lockType` belongs in course.json

**Comment by oliverfoster** [comment]
If it would changing _lockedBy to something a little more placement orientated? Or change lockType likewise? _childrenLockType ?

**Comment by hrajotia** [comment]
So considering the above implementation, it turns out that if we call `Adapt.findById` before `'app:dataReady'` then it will throw error, So its better to remove `this.checkLocking();` from [setupModel](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L44) method.

**Comment by moloko** [comment]
@oliverfoster I'm fine with the name

@hrajotia yes that's right
