### ISSUE TITLE
Narrative - Mobile Item Content outside of Notify

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1029]
There have been a few internal requests of late to find alternative methods of displaying the item information of the narrative component on small devices.

The solution, though not 100% perfect, is to display the information outside of the notify event on small devices and instead either above / below the corresponding item image. The content information would likely have to be limited to one average sentence in length so not to take too much screen space.

Open question - Do you think this method is likely to be commonly used? 

I'd envisage that they'd be an attribute attached to the narrative component in the JSON which adds a unique class override for the styling whilst there'd be some JS to calculate the height of the tallest content item which in turn applies the height to all content items to avoid varying heights / jumping.

**Comment by corymayfield** [comment]
Do you have a link, wireframe or high fidelity mockup that you could show to demonstrate what the narrative component is. I am unfamiliar with the term.

**Comment by moloko** [comment]
@corymayfield https://github.com/adaptlearning/adapt-contrib-narrative

**Comment by moloko** [comment]
also https://community.adaptlearning.org/demo2/index.html#/id/c-30

**Comment by corymayfield** [comment]
We could do something very similar to the Google Primer e-learning app (https://www.yourprimer.com/). It's card based, and you essentially "swipe" right to move to the next card to which the "narrative" progresses. For desktop users we could think about having some kind of progress "action" to move forward.
![googleprimerreviewgfxmarketing1_zzz](https://cloud.githubusercontent.com/assets/5118156/15245848/5f66a312-194c-11e6-85aa-f042920d38e3.png)

**Comment by oliverfoster** [comment]
i think text below the image would do fine and an option to have no image but just text. swipe on mobile is a must.

**Comment by oliverfoster** [comment]
prototype of text under image
