### ISSUE TITLE
The _isAvailable property should propagate from parent objects to children

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1030]
If the `_isAvailable` attribute is set to `false` on an article, for example, it does not also set `_isAvailable` on blocks or components.  This can result in inconsistent page behaviours, e.g. a component showing in Page Level Progress, even though the component is not visible on the page.

It probably makes sense for the `_isAvailable` flag to propagate its values to child objects when it's not set to the default.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/74ec2c78bcaf4130be32e24c6319ca84156c9b87
