### ISSUE TITLE
Fix JS error when MCQ component loads with no items added

### ISSUE THREAD

**Issue by bell87** [adaptlearning/adapt_framework#1034]
Add some defensive programming to the MCQ component.
If a multiple choice question component has been added to a course without any "items" being added, the course page doesn't load due to a JS error.

**Comment by moloko** [comment]
as per #1036 would you mind adding an example of the error?

**Comment by bell87** [comment]
`Cannot read property 'length' of undefined - adapt-contrib-mcq.js (line 34)`
