### ISSUE TITLE
Fix JS error when Assessment Results component loads

### ISSUE THREAD

**Issue by bell87** [adaptlearning/adapt_framework#1035]
JS error prevents page from loading when Assessment results component is added without configuration.

**Comment by moloko** [comment]
as per #1036 would you mind adding an example of the error?

**Comment by bell87** [comment]
The error appears in the console: 
`Cannot read property get of undefined - adapt-contrib-assessmentResults.js (line 50)`

**Comment by tomgreenfield** [comment]
https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/21
