### ISSUE TITLE
Fix JS error when graphic component loads

### ISSUE THREAD

**Issue by bell87** [adaptlearning/adapt_framework#1036]
Add defensive programming around un-configured graphic component.

**Comment by moloko** [comment]
Would you mind sticking an example of the error on here? Helps as a reference later on...

**Comment by bell87** [comment]
Error appears in console: `Cannot read property 'large' of undefined - adapt-contrib-graphic.js (line 51)`

**Comment by tomgreenfield** [comment]
https://github.com/adaptlearning/adapt-contrib-graphic/pull/61
