### ISSUE TITLE
Feature request: pull data from SCORM

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1040]
Desperate to have my courses pull usernames, emails. names, whatever it can get, from SCORM, such as Moodle, to both personalise and validate within the course.

Uses could include in course certificates (Moodle's are rubbish!), emailing out (see second feature request), personalising learner experience and more!

**Comment by moloko** [comment]
Unfortunately it's generally just the user's name that SCORM makes available (weirdly always in military/private school-style format i.e. "Lastname, Firstname") but I think this is a great idea, it would allow for some nice personalisation of the course content to be able to refer to the user by name.

Ideally this would be done in a way that allowed it to be specified in different formats and from anywhere in the JSON e.g. 
```
body: "Hi there {{student_firstname}} and welcome to this course on data protection"
```

Big +1 from me for this feature request.

**Comment by moloko** [comment]
First stage of this is complete in that the spoor extension is now able to pull in what information SCORM makes available about the user - next stage is to make it easy to use that information within Adapt.

I think we need to get this data into the `_globals` object (with some sensible default for when testing without an LMS) then set up some handlebars helpers to allow that data to be inserted easily into the .json

**Comment by hmaffin** [comment]
Amazing! You really can just use {{firstname}} in the AT's text boxes to display the info (after that funky code you gave me went in the right place). 

Great stuff Matt!

**Comment by Deathjam** [comment]
Hi i am too looking to include this data, what is this funky code i need?

**Comment by brian-learningpool** [comment]
@moloko, should we add a `_globals.user` object, or what had you in mind?

**Comment by oliverfoster** [comment]
can we have an adapt api for this? something like:

```javascript
Adapt.global("propertyName", "value"); //setter
Adapt.global("propertyName"); //getter
```
```handlebars
{{global "propertyName"}}
```

**Comment by moloko** [comment]
I think it needs to be something in `_globals` so that we can set default values for when there's no LMS available

**Comment by oliverfoster** [comment]
Sounds fiine to me, as long as we're happy using the current globals object, we just need to expose it in the handlebars and make a quicker reference to it in on the Adapt object.

```javascript
Handlebars.registerHelper("include_globals", function(data) {
  data.root._globals = Adapt.course.get("_globals");
  return "";
}) ;
```
and
```javascript
Adapt.globals = Adapt.course.get("_globals");
```

?

**Comment by moloko** [comment]
quick update... I am finally on the case with this! It's going to require a LOT of changes (almost every single handlebars will need to change) but expect to see the initial PR to the framework popping up next week...

**Comment by hmaffin** [comment]
Woot!

**Comment by oliverfoster** [comment]
done in #1491
ta @moloko

**Comment by moloko** [comment]
reopening cause this is only half-done - still need to actually get the data from SCORM into the object in `_globals'

**Comment by moloko** [comment]
the .hbs templates in adapt-contrib-boxmenu also need updating

**Comment by moloko** [comment]
OK I think that's everything... please review and +1 if you're happy!

**Comment by moloko** [comment]
If testing, you will need to manually update adapt-contrib-vanilla to the latest MASTER

**Comment by hmaffin** [comment]
Sweet! I can't test easily but will try and setup a new version I can play with.  Thanks mr genius!

**Comment by hmaffin** [comment]
It's telling me that the 1040 version of the boxmenu is incompatible with framework 2.0.19

**Comment by moloko** [comment]
@hmaffin sorry about that, as discussed testing this sort of thing through the authoring tool is pretty tricky - best done with the framework itself really

**Comment by moloko** [comment]
AFAIK this is now done; although not all the plugins have been updated to allow for this to be used absolutely everywhere - for example, you could include the user's name in the body, instruction or feedback of an MCQ but not in an MCQ option label.

If you think any plugins would particularly benefit from having this added please log a separate ticket
