### ISSUE TITLE
Feature request : Emailing from course

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1041]
Whether it be just a contact form within the course or a sure fire way of getting assessment completions to be emailed to a teacher in the background (Moodle makes a hash of this!) - it would be just amazingly good, because Moodle sucks and Adapt rules.

Would require a "sendto" email address(es) list, amendable body text (either what comes from the input box or a pre-formatted template in the options for the component)

I can see this as a component AND an extension - the extension to send background performance based facts, and a component to send interface-based emails from the course.

**Comment by oliverfoster** [comment]
moved to forum https://community.adaptlearning.org/mod/forum/discuss.php?d=1617#p7292
