### ISSUE TITLE
adapt-contrib-blank issue : breaking course

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1042]
When I add a blank component to my course and preview it gets the Loading wheel of death and the following in Dev tools (nothing in Node window)... Only seems to be in courses that I try to add the blank component to now, not ones that already have it in...
![image](https://cloud.githubusercontent.com/assets/11558341/14991750/c5e40cdc-115a-11e6-8c6b-7efb17b9c8ec.png)

![image](https://cloud.githubusercontent.com/assets/11558341/14992128/633a0c6a-115c-11e6-9c27-8380d3b56ee2.png)

**Comment by moloko** [comment]
That's most odd, especially since the 'blank' component has not been touched since the v2.0.0 update in August 2015!

You're absolutely sure you added it properly AND configured it? If so, I think this might be an issue with the authoring tool rather than the framework...

**Comment by hmaffin** [comment]
Ok this seems to be something to do with the build process as when I went into C:\Adapt\adapt_authoring\temp\5614f85c4bd4be5018026e8f\adapt_framework\src\components\adapt-contrib-mcq there were folders and files missing. 

I added them in from C:\Adapt\adapt_authoring\plugins\content\component\versions\adapt-contrib-mcq\2.0.3\adapt-contrib-mcq and all works ok now.

**Comment by moloko** [comment]
I wonder if this is related to #1043 ?

**Comment by hmaffin** [comment]
Could well be - seems random!

**Comment by moloko** [comment]
does this still occur with framework v2.0.10? if not then it likely was #1043 causing it

**Comment by moloko** [comment]
not heard anything further on this so closing

**Comment by hmaffin** [comment]
Yep - seems fixed now! Sorry :)
