### ISSUE TITLE
issue: adapt-contrib-mcq - model answer still shows when set to false

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1045]
UPDATE : This seems to be to do with the true and false - If both options are set to true then the question not showing the model answer works as expected but as soon as I set one to false for my answers it misbehaves. Even though I have told it not to show the model answer if I have one option as true and one as false, the model answer still shows.

**Comment by hmaffin** [comment]
AT 0.1.7, Framework 2.0.9.
I added one MCQ and cloned it. I have all settings to false for model answer, feedback etc.
When I preview, the questions work as expected but when I edit the text of the cloned question (or add a second new question) the model answer and marking show even though they are still set to false, as below.

![image](https://cloud.githubusercontent.com/assets/11558341/15042201/f153f642-12b9-11e6-89a8-96cf69b4a476.png)

both have identical settings except the question text...
![image](https://cloud.githubusercontent.com/assets/11558341/15042214/050b566c-12ba-11e6-96f6-2decc6e35cf0.png)

**Comment by moloko** [comment]
could you send over the json that's generated for each of those MCQ components?

**Comment by hmaffin** [comment]
[component_json.txt](https://github.com/adaptlearning/adapt_framework/files/250381/component_json.txt)

**Comment by hmaffin** [comment]
OK further discovery - if you pick the wrong answer then you don't get feedback /model answer or a cross (marking) - and you CAN reset the question.

If you pick the true/right option, you cannot reset (which i guess makes sense) but you also see the marking and model answer. 

If I am doing a non-marking question i wouldn't expect to see marking for right OR wrong, and for you to be able to reset the question at any point.

**Comment by tomgreenfield** [comment]
A question displays marking once it's been completed i.e. when it's been answered correctly _or_ all of the attempts have been used.

`_canShowModelAnswer` determines the visibility of the Model Answer button when the question has been answered incorrectly on the final attempt. There is also a `_canShowMarking` attribute but I believe this only exists in the Assessment extension.

On a side note, if there's a question with no feedback, model answer or marking, and unlimited resets, what does the user gain from interacting with it? Could we get an idea of the use case please?

**Comment by hmaffin** [comment]
Gotcha. I guess that makes sense. 

Sure - we are looking to personalise a course so showing certain blocks based on your answer. So really we want a choice question rather than an answer question. I thought MCQ might offer that based on the fact you could turn off marking, feedback, model answer etc. 

Does that help?

**Comment by tomgreenfield** [comment]
Ah, we have done similar things but acheived them through custom plugins.

You could in theory have an MCQ with a high number of attempts where all of the options are incorrect. The snag is that it wouldn't necessarily complete so you'd have to consider other things like setting `"isOptional": true`.

**Comment by hmaffin** [comment]
yeah if you set all options to correct then it works ok, but the personalisation currently depends on what 
you have picked being right or wrong, so we either need to change the personalisation to listen for the text of an answer rather than it's correctness, or use CSS to hide the marking maybe, so clone the current MCQ option and fiddle with it to hide the marking.
