### ISSUE TITLE
create documentation for multi-language functionality

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#1052]
An [unlinked wiki page](https://github.com/adaptlearning/adapt_framework/wiki/Course-Localisation) has been created.  The title/URL may change before it goes live.

**Comment by lc-thomasberger** [comment]
todos:
- add example.json to LanguagePicker Plugin
- add readme to LanguagePicker Plugin
- create LanguagePicker Plugin wiki page
  - best pracitices Assessment 
- describe grunt translate:[export|import] task
- describe localization process
  - create master course
  - add LanguagePicker Plugin
  - export Language File
  - translate Language File
  - import and create sub languages
  - manually relink assets if required
give hint when grunt task is not used
Example how to use the Authoring Tool and the Framework to create a ML course

**Comment by chucklorenz** [comment]
draft [README](https://github.com/chucklorenz/demo-wiki/wiki/languagePicker-README) for adapt-contrib-languagePicker

**Comment by chucklorenz** [comment]
- Done: Draft README has become the [README](https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/master/README.md) in the adapt-contrib-languagePicker repo. 
- Done: [Course Localisation](https://github.com/adaptlearning/adapt_framework/wiki/Course-Localisation) wiki article is live.
- Upon release: Update [Compiling, testing and deploying your Adapt course](https://github.com/adaptlearning/adapt_framework/wiki/Compiling,-testing-and-deploying-your-Adapt-course) with this [revision](https://github.com/chucklorenz/demo-wiki/wiki/Compiling,-testing-and-deploying-your-Adapt-course) that adds new grunt commands

**Comment by oliverfoster** [comment]
Awesome
