### ISSUE TITLE
select lang folder for grunt build

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1053]
update grunt build process, so that a list of language folders can be defined that are used for the build

**Comment by dancgray** [comment]
Also see https://github.com/adaptlearning/adapt_framework/issues/370

**Comment by dancgray** [comment]
Building different lang folders seems to now be supported in RUB https://github.com/cgkineo/adapt-buildkit-rub, (which looks awesome BTW). @oliverfoster are there any plans for RUB to become more 'core'?

**Comment by oliverfoster** [comment]
um, that's a good question.
there are a few things i'd like to do with the framework and i'm trying to figure out how at the moment.

* separate + simplify the plugin architecture from adapt framework (this will allow us to greatly expand the Adapt ecosystem by reducing the complexity, upping the flexibility and engaging people in different architectural layers, which can make things more robust etc etc i hope)
* combine the build tool + plugin management into one utility (RUB is a work in progress which helps Kineo with its production line but is also a way of me exploring how to make command line utilities, it doesn't have plugin management in it yet. this idea of properly engaging plugin management is that version control and dependencies are really important to us getting the stack right and stable)
* create a bower registry with unregister functionality (almost done)

so, to answer your question... we could make rub core tomorrow... but it isn't a traditional build tool, in that it doesn't use grunt/gulp/etc (so is kinda frowned upon by traditional open source standards - rule 1: never make your own builder) and it is also not a very good solution to the overall problems we currently have.

**Comment by lc-thomasberger** [comment]
The idea behind this issue is that you can define the languages you would like to include into the build.
This might be useful if you create multiple ML-course bundles.
It is just an enhancement, to make life easier for the course developers.

`grunt build --languages="de,fr,it"` <-- will create a build, including only this languages

**Comment by dancgray** [comment]
+1, thanks for the explanation.
