### ISSUE TITLE
High-stepped slider layout issue

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1054]
The slider's layout isn't large or flexible enough to accommodate high (i.e., 4+ digit) numbers. See screenshot for example (1000 on the right-hand side).

**Comment by kineotesting** [comment]
![6](https://cloud.githubusercontent.com/assets/19309048/15186663/cba10bac-1795-11e6-939c-4a8d277e465b.jpg)

**Comment by moloko** [comment]
@lc-thomasberger what's your take on this? Obviously there's always going to be a point at which the vanilla theme is not going to be able to cope with the size of the number, so how much effort should we put into this?

**Comment by lc-thomasberger** [comment]
this is a leftover, when we did not had the ability to add steps and the slider was mostly used for 1-2 digit numbers.
Will need to change the shape of the slider-marker or highlight the numbers on the slider directly.

**Comment by sarveshwar-gavhane** [comment]
@lc-thomasberger  i think https://github.com/adaptlearning/adapt-contrib-slider/pull/103 fixed this issue right ?

**Comment by kineotesting** [comment]
Fixed
