### ISSUE TITLE
Safari number display issue

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1057]
Safari (desktop and tablet) isn't displaying high numbers (4 digits+) correctly. This is a Safari-specific issue.

![8](https://cloud.githubusercontent.com/assets/19309048/15208547/185aca1c-1824-11e6-8ba9-dce685814780.jpg)

**Comment by sarveshwar-gavhane** [comment]
https://github.com/adaptlearning/adapt-contrib-slider/pull/107

**Comment by lc-thomasberger** [comment]
i think this [PR](https://github.com/adaptlearning/adapt-contrib-slider/pull/103) also fixes this issue
