### ISSUE TITLE
c-75 inconsistent colour change

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1058]
Whereas the other sliders change colour to red or green depending on whether the user answered correctly, c-75 (Slider (no scale, marking or model answer)) only turns grey in both cases (this is after exhausting the two attempts).

**Comment by lc-thomasberger** [comment]
no-marking class is added to the component in the json.

This class is used by assessment (on the article) to hide visual Feedback. We might update styling to limit no-marking only to articles?

**Comment by moloko** [comment]
agree with @lc-thomasberger if the no-marking class is applied I'd expect this behaviour since the colouration of the slider is a form of marking
