### ISSUE TITLE
release languagePicker Plugin, add to adapt.json

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1064]
https://github.com/lc-thomasberger/mlTest/tree/master/src/extensions/adapt-languagePicker

Add to adaptlearning Repo?
Will this be a core plugin?

**Comment by chucklorenz** [comment]
Yes, this is a core plug-in (confirmed by Pete Smith 06-07-2016).
Draft [README](https://github.com/chucklorenz/demo-wiki/wiki/languagePicker-README) for adapt-contrib-languagePicker.

**Comment by lc-thomasberger** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/tree/feature/ml
https://github.com/adaptlearning/adapt_framework/tree/feature/ml
https://github.com/adaptlearning/adapt-contrib-languagepicker

**Comment by lc-thomasberger** [comment]
add to adapt.json
