### ISSUE TITLE
add translatable attribute to properties.schema

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1066]
update core plugins
Text that should be translated need to be marked with translatable. true

https://github.com/lc-thomasberger/mlTextExportImport/blob/export/src/components/adapt-contrib-accordion/properties.schema#L13

**Comment by brian-learningpool** [comment]
The list of plugins which require this are:
- [ ] adapt-contrib-text
- [ ] adapt-contrib-narrative
- [ ] adapt-contrib-media
- [ ] adapt-contrib-hotgraphic
- [ ] adapt-contrib-blank
- [ ] adapt-contrib-accordion
- [ ] adapt-contrib-graphic
- [ ] adapt-contrib-matching
- [ ] adapt-contrib-textInput
- [ ] adapt-contrib-mcq
- [ ] adapt-contrib-gmcq
- [ ] adapt-contrib-assessment
- [ ] adapt-contrib-assessmentResults
- [ ] adapt-contrib-trickle
- [ ] adapt-contrib-tutor
- [ ] adapt-contrib-pageLevelProgress
- [ ] adapt-contrib-resources
- [ ] adapt-contrib-slider
- [ ] adapt-contrib-spoor
- [ ] adapt-contrib-bookmarking

**Comment by moloko** [comment]
checked off spoor as no translatable properties in it

**Comment by moloko** [comment]
checked off tutor as has no translatable properties

**Comment by lc-thomasberger** [comment]
checked off assessment as has no translatable properties

**Comment by moloko** [comment]
the [properties.schema for assessmentResults](https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/properties.schema) doesn't seem to have been done

**Comment by lc-thomasberger** [comment]
open PR's:
https://github.com/adaptlearning/adapt-contrib-media/pull/144
https://github.com/adaptlearning/adapt-contrib-slider/pull/112
