### ISSUE TITLE
SRT files not showing on Media on iPhone

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#1070]
I have set up a media component that uses an srt file for the closed captions. This works correctly on desktop but does not appear on an iPhone.

When playing a media file on an iPhone the native player takes over and it becomes full screen, whilst we have the options for subtitles, when selected they do not display.

I have tested this with the vtt file and this works without issue so it only seems to be the srt files.

**Comment by brian-learningpool** [comment]
Hi @kevindoherty30,

This is a known issue with the mediaelement.js library which the media component uses.  It's best to use VTT files. 
https://github.com/johndyer/mediaelement/issues/1138
