### ISSUE TITLE
slightly odd alignment for labelStart and labelEnd

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1072]
Looks a bit odd that they are so offset to the beginning/end of the slider 
![slider screenshot](https://cloud.githubusercontent.com/assets/19309048/15208547/185aca1c-1824-11e6-8ba9-dce685814780.jpg)

**Comment by lc-thomasberger** [comment]
Leftover from the old design.
Should be an easy fix to align to the left/right borders of the scale.

**Comment by moloko** [comment]
can this be closed now?
