### ISSUE TITLE
Assessment extension - Hide the feedback button?

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1073]
In the Authoring Tool even if in Assessment settings I have show feedback set to false all it does is grey out the button.
Can we have it so that the button is not shown, and the Submit/Reset button is shown full width?

Something to do with _canShowFeedback for the component?

**Comment by LukaszGrela** [comment]
Yes, this flag could mark component with `no-feedback` class which then could be used to hide button.

```
.no-feedback .buttons-feedback {
    display:none;
}
```

Ofcourse you can do this right now with CSS only, if you want to hide the feedback for particular component just put a style with component id eg.

```
.c-005 .buttons-feedback {
    display:none;
}
```
in similar fashion the `button.buttons-action` needs to be modified to take full width.

**Comment by hmaffin** [comment]
AH that's excellent Lukasz thank you for the in-depth answer!

**Comment by hmaffin** [comment]
The CSS route is probably not ideal. It involves a lot of hand-adding classes to the theme-extras.less and has to be done for every component. I think perhaps more flexibility with the buttons might be useful. 

I am wondering if a new component might be a better idea - i'm trying to make one myself but not getting very far! - that offers a choice rather than a marked, feedbacked question.

**Comment by paul-mediakitchen** [comment]
Hi Helen

I used the following to hide the feedback button and make the other button 100% 

`
.assessment .buttons button.buttons-feedback {
    display:none;
}

.assessment .buttons .buttons-marking-icon {
    position: absolute;
    left: 96%;
}

.assessment .buttons button {
    width: 100%;
    float: left;
}`

I also adjusted the position of the tick/cross

**Comment by chetan-hajare** [comment]
PR - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/193

**Comment by chetan-hajare** [comment]
Raised 2 PRs: https://github.com/adaptlearning/adapt-contrib-vanilla/pull/194 and https://github.com/adaptlearning/adapt_framework/pull/1145
