### ISSUE TITLE
slider: RTL labelStart and labelEnd are not reversed

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#1077]
![screen shot 2016-05-24 at 11 00 14](https://cloud.githubusercontent.com/assets/6452430/15500803/52f9829e-21a2-11e6-9376-9107bd0d477f.png)

**Comment by moloko** [comment]
can this be closed now?

**Comment by tomgreenfield** [comment]
Cannot replicate in latest version of Slider.
