### ISSUE TITLE
update theme to match matching updates

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1078]
due to the changes to slider using a third party library the less files in the theme need to be updated. This changes will make sure that the variables (colors, padding, fonts) are applied correctly and match the whole vanilla theme.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/8a848a14ed3772e1de3d53dcb977019c89e37428
