### ISSUE TITLE
Add dev 'wrapper' for published course

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#1086]
A feature I've been wanting for a while (especially if used in conjunction with the AT) is some kind of container page for use when developing courses. This would be specifically aimed at users who aren't familiar/comfortable with brower devtools

Creating a separate HTML page in the framework seems like a sensible way to do this (as opposed to having it completely AT-based), as would also allow it to be used by those using the command line.

Possible features for this container:
1.  Hook for console functions to display a very noticeable visual notification <- this is the killer feature for me, a lot of non-tech users miss console errors, and wonder why they're presented with a blank white screen.
2. Toggle buttons to shrink the container to mobile/tablet/desktop dimensions (see https://github.com/adaptlearning/adapt_authoring/issues/858)
3. Allow navigation to specific page -- appreciate this can (and ideally _should_) be done using URL params, but this feature may not be possible if using a separate HTML page, which may make this landing page idea infeasible.

Sure this will play havok with tabbing, so no worries if it causes a lot of problems (I wouldn't expect the container to be tabbable at all, so if that helps.....)

**Comment by oliverfoster** [comment]
is this a framework issue? Could the AT not do 1 and 3 from the parent window already? item 2 is pretty hard to achieve without resizing the window manually.

**Comment by taylortom** [comment]
It's been argued that it doesn't really sit with either 😆 
Will close for now.

**Comment by oliverfoster** [comment]
i'd be more keep to develop a 'devtools' plugin specifically for Adapt
like a mix of @chris-steele 's devtools and some of the AT specific requirements

**Comment by taylortom** [comment]
Yeah, I think that's what I was thinking originally
