### ISSUE TITLE
contrib-trickle: add event to notify listeners when initial 'trickle render' of the page has finished

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1094]
Currently, if you return to a page that uses trickle - and where you have previously completed some of the 'trickled' content - the trickle plugin needs to spend some time 'untrickling' those sections of the page, but does not have an event for when this work is completed.

This causes problems for plugins like [keepScrollPosition](https://github.com/cgkineo/adapt-keepScrollPosition) which is trying to scroll down the page before all the page content that should be visible has been made visible. Adding an event would allow it to wait until trickle has finished its initial work on the page.

**Comment by LukaszGrela** [comment]
+1

**Comment by oliverfoster** [comment]
setupListeners: function() {
        this.listenTo(Adapt, {
            "pageView:preRender": this.onPagePreRender,
            "pageView:ready" : this.onPageReady,
            "remove": this.onRemove
        });
    },

    onPageReady: function(){

        setTimeout( this.fixPageResize , 500 );
    },

    fixPageResize : function(){

        $( "body" ).trigger( "mouseup" );
    },


^ use something like this with a debounced trickle:stepunlock
