### ISSUE TITLE
Consider using screen.width for iOS device calculations

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1096]
While testing a course in an LMS which used frames, I noticed that the `Adapt.device.screenWidth` was being set incorrectly -- it was detected as large rather than small.

Android devices seem to work as expected, so I'm wondering if we should tweak the code to make an exception for iOS so that expected sizing class gets correctly added?

**Comment by andrewhosgood** [comment]
Tested this on an iPad running iOS 9.3.2. Screen size in CSS pixels: 768 x 1024.

If you `alert( Adapt.device.screenWidth );` at https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/device.js#L11 and/or https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/device.js#L46, the method returns 768px regardless of orientation.

**Comment by oliverfoster** [comment]
Screen.width doesn't represent the viewport:
http://stackoverflow.com/questions/3437786/get-the-size-of-the-screen-current-web-page-and-browser-window
https://developer.mozilla.org/en-US/docs/Web/API/Screen/availHeight

Calculating the orientation and the width from screen.height, screen.width and window.orientation:
http://www.williammalone.com/articles/html5-javascript-ios-orientation/
http://menacingcloud.com/?c=orientationScreenWidth

I thought these might help.

**Comment by andrewhosgood** [comment]
It used to be with my medium/large breakpoint of 1000px that the iPad would display medium on portrait and large on landscape which worked well for layout (my breakpoints are a lot higher than standard - 640px, 1000px and 1428px).

Was this functionality was intended or would it be good to update it to work as it did? If you need, I might be able to look into it when I get some spare time if this is the case?

**Comment by brian-learningpool** [comment]
@oliverfoster, thanks for those links.  The PR above uses the orientation to determine the width on iOS devices.
