### ISSUE TITLE
Add css class to article/block/component when on screen

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1100]
As mentioned [here](https://community.adaptlearning.org/mod/forum/discuss.php?d=1439)

This will make it easy to add css based animations when a Element is scrolled into view.

```
"_onScreen": {
    "_isEnabled": true,
    "_classes": "bounceOutLeft",
    "_options": {
        "_percentFromTop": 25,
        ....
    }
}
```

Will need to decide if we should only add classes or also remove them ...

**Comment by andrewhosgood** [comment]
Maybe have a look at http://imakewebthings.com/waypoints/

**Comment by lc-thomasberger** [comment]
as for now add on-screen and off-screen classes
add to core and test if this causes serious performance issues

**Comment by moloko** [comment]
PR: https://github.com/adaptlearning/adapt_framework/pull/1320
