### ISSUE TITLE
adapt-contrib-assessment unresponsive warning in IE8

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1105]
Sometimes observed when assessment is reset. Problem largely confined to question model reset calls.

Has been addressed in projects such as ken16033. Related to #901.

**Comment by LukaszGrela** [comment]
I can confirm that assessment on reset on IE8 could cause unresponsive errors, sometimes even entering assessment page end up with the same error. By "Addressed" you mean there is a solution?

**Comment by chris-steele** [comment]
@LukaszGrela Yes the solution was to allow plugins (in this case the assessment plugin) to pause routing to perform non-blocking operations, but maintaining execution order. To fix other issues we also need to allow plugins to perform non-blocking operations prior to initialisation of the course. The changes required are generally in router.js, so when I do these I will also look at integrating your fix for removing views (#901).

**Comment by chris-steele** [comment]
@LukaszGrela please see https://github.com/adaptlearning/adapt-contrib-assessment/pull/69.
