### ISSUE TITLE
IE8 performance improvements

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1107]

**Comment by moloko** [comment]
maybe also look at https://github.com/adaptlearning/adapt-contrib-spoor/pull/128 ?

**Comment by chris-steele** [comment]
Two test packages have been prepared to demonstrate the improvements to Adapt to address performance issues in IE8 :

**Test 1** [adapt_v2.0.15_spoor_v2.0.13_assessment_v2.0.8.zip](https://github.com/adaptlearning/adapt_framework/files/661515/adapt_v2.0.15_spoor_v2.0.13_assessment_v2.0.8.zip)

**Test 2** [adapt_v2.0.16alpha_spoor_v2.0.15alpha_assessment_v2.0.9alpha.zip](https://github.com/adaptlearning/adapt_framework/files/661516/adapt_v2.0.16alpha_spoor_v2.0.15alpha_assessment_v2.0.9alpha.zip)

Both tests contain the same content. Content has been duplicated in places to bring the amount of content closer to what is typical of an Adapt course. The assessment contains 32 questions arranged into banks.

**Test 1** uses the version of Adapt prior to the inclusion of any improvements.

**Test 2** uses the latest version of Adapt with various improvements to fix IE8 performance issues. It also contains the following improvements waiting as PRs: [adapt_framework](https://github.com/adaptlearning/adapt_framework/pull/1359), [adapt-contrib-spoor](https://github.com/adaptlearning/adapt-contrib-spoor/pull/147) and [adapt-contrib-assessment](https://github.com/adaptlearning/adapt-contrib-assessment/pull/69).

The changes greatly reduce the occurrence of the slow script warning in IE8, but do not eliminate it entirely under certain conditions. For this reason the following is recommended:

1. Page: recommended maximum of 20 components.
2. Assessment: recommend maximum of 12 questions, optionally drawn from a bank of up to 32.

**Comment by moloko** [comment]
oops bit premature closing it, there's still one PR open https://github.com/adaptlearning/adapt-contrib-assessment/pull/69
