### ISSUE TITLE
adapt-contrib-media: Controls are missing when viewing YouTube videos in Firefox and IE Edge

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1109]
The standard play, pause and progress scrubber controls are missing when viewing YouTube videos in Firefox or IE Edge.

We're actually a few versions behind the latest version of mediaelement.js, which might have something to do with it.

**Comment by moloko** [comment]
@brian-learningpool is this now resolved with the new release of contrib-media?

**Comment by brian-learningpool** [comment]
The scrubber controls are there, though there are a few JS warnings on Firefox.
