### ISSUE TITLE
Scrolling bug when clicking on narrative images on iOS

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1112]
I've noticed an issue on iOS devices when you have multiple narrative controls on the same page.   I believe it might have something to do with `a11y_iosFalseClickFix()` in `jquery.a11y.js`.

**Steps to re-create**
1. Create or launch a course which has a page with three narrative items.
2. Open the course on an iOS device or via the Simulator.
3. Click on the narrative image (not the left or right controls)

**Expected result**
Nothing should happen.

**Actual result**
The page scrolls down to the next narrative.  Repeating step 3 on the narrative that has scrolled into view scrolls the page to the third narrative.

**Comment by brian-learningpool** [comment]
@oliverfoster, updating the Handlebars template for the Narrative to set `tabindex="-1"` resolves the issue.

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt-contrib-narrative/pull/164

**Comment by oliverfoster** [comment]
cool

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-narrative/commit/0024ddc109184fadd236abd7aebe13de05bff7c2
