### ISSUE TITLE
Question components no longer show the marking on submit

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1114]
When clicking the submit button on a question component the marking icons used to automatically show on each option. However after downloading and building the latest framework v2.0.10 this doesn't happen anymore. Was this functionality changed or is this a bug?

**Comment by moloko** [comment]
You're quite right @RobertPeek this is a bug

Confirmed that this was still working properly with Framework v2.0.9

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/bb2396f7837b07c3bead4fa868aa263b938cec52
