### ISSUE TITLE
Question bank assessment not restoring properly across SCORM sessions

### ISSUE THREAD

**Issue by webb-nickj** [adaptlearning/adapt_framework#1117]
When a question bank assessment is exited mid-attempt it is not restored properly when a new SCORM session is started. The restored assessment shows all the questions in the assessment and not just those that formed part of the attempt.

Steps to repeat:

1. Create an assessment with question banks - our setup comprises 10 banks, each with two questions. Questions are setup to show feedback and allow one attempt at each question per assessment attempt. The assessment has two attempts and is storing responses and scores via Spoor.
2. Start an attempt at the assessment (via LMS or scorm_test_harness.html) - 10 questions are shown.
3. Exit the course mid-attempt.
4. Restart the course and return to the assessment - now all question from all banks are shown, with feedback and marking shown for the questions already attempted.

**Comment by moloko** [comment]
I think [v2.0.6 of the assessment plugin](https://github.com/adaptlearning/adapt-contrib-assessment/releases/tag/v2.0.6) might fix this...

**Comment by webb-nickj** [comment]
Hi Matt - sorry - only just seen your reply.

I did test the updated adapt-assessmentArticleModel.js file when we spotted the bug, which didn't fix the problem for us. 

But I'll download the full plugin update tomorrow and test.

**Comment by webb-nickj** [comment]
OK - a quick test on our dev platform this afternoon suggests this is now fixed.

Thank you.

**Comment by moloko** [comment]
no problem thanks for confirming
