### ISSUE TITLE
forum post to encourage addition of "translatable"

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#1131]
"translatable" needs to be brought to the attention of developers so they can begin to add it to their plug-ins.  Below is some draft text for a post just to make it easier when the time feels right. Whoever posts should feel free to change it as suits them. Please don't forget to relink hyperlinks when you copy to the forum.
..............................................

**Developers: please add “translatable” to your plug-ins**

Beginning with v2.0.10, the Adapt framework will provide new core functionality that makes it easier to create courses in multiple languages: 
- new commands to export and import text so that it can be localised and new language versions created
- a new extension that gives the learner the ability to choose a preferred language.

The Grunt command for text export relies on a new property, “translatable”, to identify which fields to export. This command will look for “translatable” in the _properties.schema_ files of all plug-ins: components, extensions, menus, and themes. The core plug-ins have been updated already to include the “translatable” property. And documentation about [Course Localisation] (https://github.com/adaptlearning/adapt_framework/wiki/Course-Localisation) and the [Language Picker] (https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/master/README.md) is also available.

We encourage all developers who have plug-ins in the [Adapt plug-in registry](https://www.adaptlearning.org/index.php/plugin-browser/) and in other public repositories to incorporate this new functionality. Please examine the _properties.schema_ of core plug-ins to see how easy it is to add this property to your schema. Read the new documentation if you'd like to understand the broader context. And, if you haven't yet created a _properties.schema_, please make time to do so. You'll find help in the [Properties Schema] (https://github.com/adaptlearning/adapt_authoring/wiki/Properties-Schema) wiki article and from experienced developers in the [Adapt framework gitter room] (https://gitter.im/adaptlearning/adapt_framework?source=orgpage).

You've been so good to share your work with the community. Please let your efforts continue to make an impact by updating your plug-ins. Thank you!

**Comment by moloko** [comment]
thanks @chucklorenz - posted [here](https://community.adaptlearning.org/mod/forum/discuss.php?d=1469).
