### ISSUE TITLE
Update CLI readme

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#1134]
I have a README started with a new format: https://github.com/chucklorenz/demo-wiki/wiki/adapt-cli-RDME. I'll update this when work on the CLI is subsiding. Please let me know.

Notes/comments about new functionality can go in the original or in this one I've started. Any notes will be greatly appreciated.

**Comment by chucklorenz** [comment]
I have a README started with a new format: https://github.com/chucklorenz/demo-wiki/wiki/adapt-cli-RDME. I'll update this when work on the CLI is subsiding. Please let me know.

Notes/comments about new functionality can go in the original or in this one I've started. Any notes will be greatly appreciated.

**Comment by chucklorenz** [comment]
This is ready for review. Thanks, Tom G for your feedback. @chris-steele : would love to have you review.

**Comment by oliverfoster** [comment]
merged https://github.com/adaptlearning/adapt-cli/pull/107
