### ISSUE TITLE
Slider button div is misplaced compared to other questions

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#1143]
In slider button div is inside component-widget div
https://github.com/adaptlearning/adapt-contrib-slider/blob/master/templates/slider.hbs#L29

compared to here for MCQ
https://github.com/adaptlearning/adapt-contrib-mcq/blob/master/templates/mcq.hbs#L20

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/1e5275c3539982340be73d923a4424fc36083013
