### ISSUE TITLE
durationLabel property still present in contentObjects.json

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1148]
But as far as I can tell this is no longer used following [v2.0.3 of contrib-boxmenu](https://github.com/adaptlearning/adapt-contrib-boxmenu/releases/tag/v2.0.3)... so it should be removed to avoid confusion

**Comment by lc-thomasberger** [comment]
+1 to remove if not used.

Can we have value in globals as fallback if not set in contentObjects? If it should be blank set to false in contentObjects or remove from globals.

**Comment by moloko** [comment]
> Can we have value in globals as fallback if not set in contentObjects? If it should be blank set to false in contentObjects or remove from globals.
Sorry if I'm misunderstanding but I'm not sure that's relevant here as `durationLabel` is a label and so should never have been in contentObjects.json in the first place. Note that if `durationLabel` is not set in course.json the default value from the menu's properties.schema will get used instead.
