### ISSUE TITLE
Adapt MCQ: Allow a "Select ANY correct answer" option

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#1151]
There are 3 items, all of which have `"_shouldBeSelected": true` and you have `"_selectable": 1`.

Normally, if `_selectable` is larger than the number of items with `"_shouldBeSelected": true`, you are able to select all the correct answers. This is fine.

If `_selectable` is smaller than the number of items with `"_shouldBeSelected": true`, you can't select all the correct answers and will **always get the component partly correct**. In this instance, `_shouldBeSelected` should be the equivalent of "CAN be selected" and any correct answer will complete **correct**.

**Comment by moloko** [comment]
PR here: https://github.com/adaptlearning/adapt-contrib-mcq/pull/127

**Comment by andrewhosgood** [comment]
Alternative PR here: https://github.com/adaptlearning/adapt-contrib-mcq/pull/130

**Comment by oliverfoster** [comment]
very old now, closing
