### ISSUE TITLE
Trickle height clipping content when wrapper has padding top

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#1173]
When the wrapper element has padding-top, trickle clips the content short by that amount.

In https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/resize.js#L57-L61 I don't think you need to minus the `topPadding`, as the offset position is relative to the document anyway.

A better (and cleaner) solution might be to replace the code above with:

`$( '#wrapper' ).height( offset.top + height );`

**Comment by rlowry** [comment]
Thanks @andrewhosgood. Can confirm this resolves the issue.
