### ISSUE TITLE
Produce a buildInfo.json file with plugin version information as part of the build process

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1177]
Often when working with published Adapt courses it is difficult to ascertain which versions of the Adapt Framework and plugins are being used.  This is particularly a problem with minified code.  

With this in mind, it would be extremely useful to know if a course which was exhibiting some kind of issue was using a version of a plugin which had the issue fixed in a later version.  This would really speed up debugging.

After some discussion on the Gitter room, a `buildInfo.json` file was agreed as a logical place to put this data.  The purpose of this is to detail all plugins and their version numbers, e.g. a sample format might be:

``` javascript
{
  "adapt_framework": "2.0.10",
  "adapt-contrib-graphic": "2.0.3",
  "adapt-contrib-text": "2.0.1",
  // etc.
}

```

This could probably be implemented as a new grunt task.

**Comment by dancgray** [comment]
+1, @brian-learningpool this might be useful for import to [authoring tool](https://github.com/adaptlearning/adapt_authoring/issues/1387) so knowing the plugin type would be good:

``` javascript
{
  "adapt_framework": "2.0.12",
  "pluginTypes": [{
      "type": "component",
      "plugins": {
        "adapt-contrib-graphic": "2.0.3",
        "adapt-contrib-text": "2.0.1"
      }
    },
    {
      "type": "extension",
      "plugins": {
        "adapt-contrib-spoor": "2.0.11",
        "adapt-contrib-resources": "2.0.4",
        "adapt-contrib-trickle": "2.1.2"
      }
  },
  {
      "type": "menu",
      "plugins": {
        "adapt-contrib-boxmenu": "2.0.5"
      }
  },
  {
      "type": "theme",
      "plugins": {
        "adapt-contrib-vanilla": "2.0.3"
      }
  }]
}
```

**Comment by oliverfoster** [comment]
this is in:
```js
Adapt.build.toJSON();
```

[PR](https://github.com/adaptlearning/adapt_framework/pull/1684)

**Comment by oliverfoster** [comment]
Can we close this ticket?
