### ISSUE TITLE
Create "items" presentation component model

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1178]
All of these components use the same model behaviour
- Narrative
  * update transformations to css3 inline with dropping ie8-ie10
- Accordion (https://github.com/adaptlearning/adapt-contrib-accordion/pull/85)
- Hotgraphic
  * use [notify subviews](https://github.com/adaptlearning/adapt_framework/pull/1893) and itemscollection

Create a standard presentation component model for them

**Comment by oliverfoster** [comment]
any objection to me putting this in the core?

**Comment by moloko** [comment]
Could you also deal with #1365 at the same time?
