### ISSUE TITLE
View Model Code to Models - Create standard models

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1179]
We should create a series of core component models for standard model behaviour.
- This will reduce the footprint for bug fixing
- Facilitate reuse
- Standardise common behaviour

**Comment by oliverfoster** [comment]
we need a core model for each items, mcq and slider

the mcq one is done, but it still lives in the mcq

**Comment by oliverfoster** [comment]
graphic, text, blank and media still need doing.

**Comment by moloko** [comment]
> graphic, text, blank and media still need doing.

what do you envisage going into the models for those?

**Comment by oliverfoster** [comment]
Nothing, just the bog standard model. They just need to conform to the model / view separation standard. I'd like to kill off "view only" components.

**Comment by moloko** [comment]
Oh right, I see - something a bit like this?
```js
return Adapt.register('blank', {
        model: ComponentModel,
        view: BlankView
});
```

**Comment by oliverfoster** [comment]
Exactly. Then we can drop all that compatibility rubbish from QuestionView

**Comment by moloko** [comment]
Excellent. Would you be happy to keep the view code in adapt-contrib-blank.js - or would you want it moved to a separate .js file?

**Comment by oliverfoster** [comment]
It's fine in the main file I think. I'd prefer a separate file as an example for everyone to follow but it's really only a stylistic wish.
