### ISSUE TITLE
Add accessibility toggle button to navigation bar

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1182]
- To allow touch devices to toggle accessibility fully rather than having it always on.
- Must be the first tabbable item for desktops
- Need to add an appropriate icon to the vanilla fonts

**Comment by chris-steele** [comment]
I've spent a while reviewing this and conclude that this is not practical at the moment. One issue is that the order of setup in accessibility.js comes prior to the creation of the navigation bar. A further issue is the incompatibility with the adapt-contrib-languagePicker.
