### ISSUE TITLE
discussion about LESS

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1189]
vanilla less > core less

**Comment by aniketdharia** [comment]
As discussed Oli to take time this week to document the requirements and then we will discuss the next steps.

**Comment by oliverfoster** [comment]
# Theme LESS > Core LESS

The core and theme LESS is currently made up from many parts, i suggest we pull in some of the following pieces and rename/separate accordingly:

#### Core
  * core/reset.less
    * browser normalization

  * core/legacy.less
    * ie8 component responsive

  * core/base.less
    * accessibility styles
    * utility/functional (no-select/display-none/visibility-hidden)
    * MPABC structure (component only)
    * core-modules (notify/drawer/navigation/loading)  

#### Theme
  * theme/padding.less, theme/colors.less, theme/fonts.less, theme/generic.less
    * variable declarations for devices (small, medium, large)
    * variable declarations for common UI elements (button, font, icon, focus-outline, etc)
    * variable declarations for colour palettes (primary, secondary, tertiary, etc)
    * variable declarations for core-modules (navigation, drawer, notify, etc)
    * variable declarations for MPABC structure (menu, page, article, etc)
    * variable declarations for plugins (item)

  * theme/src/adapt-defaults.less
    * functional responsive mixins (.responsive-large-small-medium)
    * compatibility variable declarations (almost everything else)

  * theme/src/wrapper.less, theme/src/page.less, theme/src/article.less, theme/src/block.less, theme/src/component.less
    * MPABC structure (menu, page, article, block, component)
    * functional less (header responsiveness)

  * theme/src/focus.less, theme/src/fonts.less, theme/src/icons.less
    * functional less for DOM elements (html, body, :focus, .icon, ul, strong, select)
    * styling for text MPABC (menu, page, article, etc)

  * theme/src/navigation.less, theme/src/notify.less, theme/src/shadow.less, loading.less, theme/src/drawer.less
    * structure for core-modules (navigation, notify, etc)

  * theme/src/buttons.less
  	* styling for common DOM elements (button)
  	* styling for core-module (buttons) 


#### Suggested new structure

  * browser (core/less/) – DOM setup
    * brower.less (core/reset.less, core/base.less, theme/src/fonts.less)
      * all tag styles (except body font declaration)
      * all browser fixes (except icon fix)

  * variables (core/less/variables/) – all global variables
    * border.less (theme/generic.less)
      * all order and outline declarations
    * colours.less (theme/colors.less)
      * remove all color declarations (@white, @blue, etc) – unnecessary abstraction
    * devices.less (theme/generic)
      * widths
    * fonts.less (theme/fonts.less)
      * font variables
    * paddings.less (theme/paddings.less)
      * as is
    * compatibility.less (theme/src/adapt-defaults.less)
      * all redundant variable declarations


  * structure (core/less/structure/) – adapt content structure and styling
    * article.less (theme/src/article.less)
      * remove responsiveness queries?
    * block.less (theme/src/article.less)
      * remove responsiveness queries?
    * component.less (theme/src/component.less, core/base.less)
      * remove responsiveness queries?
      * combine all component styling
    * page.less (theme/src/article.less)
      * remove responsiveness queries?
    * responsive.less (theme/src/adapt-defaults.less)
      * responsive mixins
    * wrapper.less (theme/src/wrapper.less, core/base.less)
      * combine all wrapper styling

  * common (core/less/common/) – common UI structure and styling
    * accessibility.less (core/base.less)
      * move all accessibility less here
    * buttons.less (theme/src/buttons.less
      * take style for DOM buttons
    * focus.less (theme/src/focus.less)
      * as is
    * fonts.less (theme/src/fonts.less)
      * body font declaration
    * icons.less (core/reset.less, theme/src/icons.less)
      * combine all icon styles
    * shadow.less (theme/src/shadow.less)
      * as is
    * utility.less (core/base.less)
      * visibility-hidden, display-none, no-select

  * modules (core/less/modules/) – core modules styling and structure
  	* buttons.less (core/buttons.ess)
  	  * take style for question component buttons
    * drawer.less (core/base.less, theme/src/drawer.less)
      * merge all styles
    * loading.less (core/base.less, theme/src/loading.less) 
      * merge all styles
    * navigation.less (core/base.less, theme/src/navigation.less)
      * merge all styles
    * notify.less (core/base.less, theme/src/notify.less)
      * merge all styles

**Comment by oliverfoster** [comment]
After we've done that i think we need to normalize the declarations for top, left, bottom, right, like border, padding, etc

currently:
```handlebars
@item-padding: 20px;
@item-padding-top: @item-padding;
@item-padding-bottom: @item-padding;
@item-padding-left: @item-padding;
@item-padding-right: @item-padding;

@item-margin: 5px;
@item-margin-top: @item-margin;
@item-margin-bottom: @item-margin;

@block-padding: 60px;
@block-padding-top: @block-padding;
@block-padding-bottom: @block-padding;
.block-inner {
        padding: @block-padding-top 0 @block-padding-bottom;
        // reduce padding as screen width decreases
        @media all and (max-width: (@device-width-large + 20px)) {
            padding: (@block-padding-top / 2) 20px (@block-padding-bottom / 2);
        }
        @media all and (max-width: (@device-width-small + 20px)) {
            padding: (@block-padding-top / 3) 10px (@block-padding-bottom / 3);
        }
    }

@article-padding: 60px;
@article-padding-top: @article-padding;
@article-padding-bottom: @article-padding;
.article-inner {
        padding: @article-padding-top 0 @article-padding-bottom;
}
```

^ these seem a bit messed up

some have top, bottom but no left+right... needs some thought

**Comment by aniketdharia** [comment]
@oliverfoster agreed! I will assign this task to the designer. He will try to make the theme normalised as per the suggested changes and will add more thought to it as he progresses. 

Regarding paddings, we can add all the values and keep not used ones to zero in order to make it possible for programmatically update the theme values via the authoring tool as per requirements.

Segregating the Design from the framework would make it more robust for programmers as they need not worry about design. They can push the developed code to designers for making it beautiful.

**Comment by oliverfoster** [comment]
Cool. If the starting point is to keep everything for the core-modules, remove unnessecarry mixins like .button-text, etc, remove all plugin less and remove all the color definitions. So that the first stage is identical to the theme with some bits removed, then we can work on adding improvements afterwards?

**Comment by oliverfoster** [comment]
The fundamentals things for me are to reduce the complexity and provide a solid base. So all unnecessary abstractions that can be removed should be removed. primary, secondary etc can go once we've removed them from some of the plugins (or they can at least go into the compatibility section).

**Comment by oliverfoster** [comment]
The framework should build without a theme if we get it right.

**Comment by aniketdharia** [comment]
Agreed! I have assigned our designer to start looking into it. Will get back to you with an estimation.

**Comment by oliverfoster** [comment]
Cool.

@kirsty-hames also suggested that we take all the stuff from the theme plugins overrides and move anything that's important and needed for the plugins into the plugin less.

**Comment by aniketdharia** [comment]
@oliverfoster had a good start today. We were able to remove the dependencies. Now need to make few fixes in the build and dev grunt files. And then move towards moving the component less fixes back to the components. Once that is done, we can then start optimising the code.

Check the branch  -https://github.com/VYASSYS/adapt_framework/tree/feature/SNUG-10-remove-dependencies-of-theme-from

**Comment by oliverfoster** [comment]
hi Aniket, awesome, look good :+1:

you seem to be duplicating some of the work for grunt which is already in adapt_framework master. May I suggest you use master as the base rather than 2.0.11?

**Comment by aniketdharia** [comment]
ok cool.. will move this repo and replicate the master.

**Comment by aniketdharia** [comment]
corrected!

**Comment by sagarkachare** [comment]
Hi Oliver - 

Made few updates and renamed files to match the code inside it. Pl refer - https://github.com/VYASSYS/adapt_framework/tree/feature/1189---Less-Enhancements

**Comment by aniketdharia** [comment]
I have self-assigned this issue on behalf of @sagarkachare

**Comment by oliverfoster** [comment]
Hi guys, just gonna review the changes, give me a few hours and i'll write some notes :)

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/1201 < see notes on here

**Comment by oliverfoster** [comment]
sorry guys, i missed this: 

https://github.com/VYASSYS/adapt_framework/blob/feature/1189---Less-Enhancements/src/core/less/modules/buttons.less#L4-L56 < this section should still be in less/global/buttons.less

https://github.com/VYASSYS/adapt_framework/blob/feature/1189---Less-Enhancements/src/core/less/modules/buttons.less#L58-L141 < this section stays in less/modules/buttons.less

similar names, different uses.

**Comment by oliverfoster** [comment]
out of date. needs reissuing.
