### ISSUE TITLE
Feature request: Ensure lang code is valid when adding caption file

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt_framework#1191]
A few times we've been caught out with closed captions not displaying over media because we have not entered a language code when adding it (doh!).  It would be great if the authoring tool alerted you to the blank field when adding a caption file.

Realise this is probably a very low priority, but thought I'd suggest anyway.

![cc_lang](https://cloud.githubusercontent.com/assets/20811952/17361094/8a0e9804-5966-11e6-9265-4c3d28559dc9.jpg)

**Comment by brian-learningpool** [comment]
I agree, thanks for raising this.

**Comment by brian-learningpool** [comment]
Merged to `master`.
