### ISSUE TITLE
'Required' schema attributes need revisiting

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#1192]
We've just fixed the form validation in the authoring tool, which means that you're now unable to leave the page unless you've filled in the required fields. In some cases, the fields which have been set to 'required' seem slightly unnecessary.

Areas to look at:
- [x] Assessment: ID -- in the case that the assessment's not turned on for a given article 
- [x] MCQ: feedback -- in the case that feedback has been turned off
- [x] GMCQ
- [x] Matching
- [x] Slider
- [x] Text Input
- [x] Media: language code (see https://github.com/adaptlearning/adapt_framework/issues/1191)

**Comment by moloko** [comment]
just need to release all the affected plugins...

**Comment by moloko** [comment]
everything should be merged and released now
