### ISSUE TITLE
Adapt developed and experts

### ISSUE THREAD

**Issue by enzofsilva** [adaptlearning/adapt_framework#1202]
Hi.
I've gotten a request to consult on a project that needs someone to support an organization that is now introducing Adapt and needs to get their developers ramped up.
Is there a directory of Adapt experts anywhere?
Thanks.

**Comment by oliverfoster** [comment]
hi @enzofsilva,

could you try posting in our forums ? > https://community.adaptlearning.org/course/view.php?id=2

this space is for code issues only.

ollie
