### ISSUE TITLE
adapt-contrib-media: video playback freezes

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1205]
After clicking the play button, I selected about a second from the end on the playback bar and the video freezes on the loading animation. After returning to the menu and back into the topic where the video was the video does not load at all.

This was replicated by installing the adapt_framework v2.0.11, building and running the default course locally in IE11 on Windows 7.

**Comment by chetan-hajare** [comment]
Hi @RobertPeek I could not replicate this issue at my end. Can you please more elaborate the issue?

**Comment by RobertPeek** [comment]
Hi @chetan-hajare thanks for looking into this. Hopefully the screengrab below will help.

![adapt-contrib-media](https://cloud.githubusercontent.com/assets/7251995/17732778/6534002c-646b-11e6-82e1-88853e17ebad.jpg)

The video has froze after I clicked 24 seconds into the video. This is quite temperamental though and it did take me a few times to replicate again.

On another note the play/pause button is highlighted with the orange focus rectangle when it probably shouldn't be.

Hope this helps!

**Comment by chetan-hajare** [comment]
Hi @RobertPeek I tried to replicate the issue on different machines having same configuration but it didn't replicate. I suggest you to check it on another machine with same configuration. If the issue still persist, please let us know.

**Comment by moloko** [comment]
@RobertPeek could you also check to see if this occurs in the environment where your course will be delivered i.e. from the actual web server or LMS? Many problems with video result from the server itself - so you might find this issue is restricted only to you running the course locally using node server.

**Comment by oliverfoster** [comment]
i think this is more to do with grunt-server not serving videos properly as @moloko says.

closing until confirmed.
