### ISSUE TITLE
jquery.imageready skipping certain images

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1207]
There was an issue in a recent project where imageready wasn't waiting for an image to load because it already had a seemingly random height set.

Locally, on [line 43](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/imageReady.js#L43), I replaced

``` javascript
$this.height() > 0
```

with

``` javascript
$this.prop("naturalHeight")
```

Note: this check will always return falsy (`undefined`) in IE8.

**Comment by moloko** [comment]
is this still a problem?

**Comment by oliverfoster** [comment]
Nah, check is in already.
