### ISSUE TITLE
Feature request: expose media events

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt_framework#1209]
It would be great if when creating extensions we could listen for media events such as a video being played or a video finishing.

**Comment by lc-thomasberger** [comment]
https://github.com/adaptlearning/adapt-contrib-media/pull/159

**Comment by moloko** [comment]
@sharpb seeing as you logged this, do you want to review what @lc-thomasberger has done to make sure it meets your expectations?

**Comment by sharpb** [comment]
@moloko @lc-thomasberger Brilliant!  Great to get this added in.
