### ISSUE TITLE
contrib-media: closed captions don't display by default (firefox)

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1212]
In Firefox, closed captions aren't able to be displayed by default. Appears to be fine in other browsers.

**Comment by brian-learningpool** [comment]
@tomgreenfield, we do have an outstanding PR to bump the version of the library Media uses.  Is it still an issue in this version?
https://github.com/adaptlearning/adapt-contrib-media/pull/143

**Comment by tomgreenfield** [comment]
Yeah, it's something in the [override](https://github.com/adaptlearning/adapt-contrib-media/blob/master/js/mediaelement-and-player-accessible-captions.js) which needs fixing.

**Comment by moloko** [comment]
no longer relevant since mediaelement-and-player-accessible-captions.js has been deleted
