### ISSUE TITLE
Bug: Start controller with trickle cuts (media) component

### ISSUE THREAD

**Issue by sharpb** [adaptlearning/adapt_framework#1213]
I've setup a course (in the authoring tool) to go directly to the first page using the start settings.  This page contains a video (720x526).  Trickle is setup to automatically scroll to the next block once the video has completed (and it does this ok once the video has completed).  However the container doesn't size correctly to show all the video (the controls can't be accessed).  The same occurs if start controller settings are disabled and the page is accessed via the menu.

![example](https://cloud.githubusercontent.com/assets/20811952/17807513/0b4e175c-6603-11e6-9d1e-3b6fab7421fc.jpg)

**Comment by moloko** [comment]
this hasn't been reported since and everything has been updated pretty significantly since this was logged - so I'm going to go ahead and assume it's been resolved naturally.
