### ISSUE TITLE
SCORM Cross Domain compliant

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1214]
This is just a question, is there any plans to make the spoor extension cross domain compliant? I don't believe it is at the moment as I have had trouble connecting to an LMS from content hosted on the Amazon Web Service.

**Comment by moloko** [comment]
To the best of my knowledge this isn't something that can really be handled in the spoor extension - SCORM is inherently resistant to cross-domain communication. There's a good article about the challenges of making SCORM work cross-domain [here](http://scorm.com/blog/2013/04/solving-the-scorm-cross-domain-issue/)

I think our efforts would be better spent focussing on xAPI - as the design of this happily allows for cross-domain communication.

**Comment by RobertPeek** [comment]
Thanks for the quick reply, will keep an eye on the progress of the xAPI plugin.

Many thanks
