### ISSUE TITLE
Selective use of tutor once enabled

### ISSUE THREAD

**Issue by louisebennett** [adaptlearning/adapt_framework#1215]
At the moment, once you've enabled tutor, it is invoked across all relevant components, whether or not there is any feedback listed. Most of the time this is fine, but we will occasionally use components where feedback isn't relevant - because we're asking the student to rate themselves, for example. 

What we'd really love is to be able to deactivate tutor manually, much the same way as you can set a component as optional, or prevent it from being tracked as part of page level progress.

**Comment by brian-learningpool** [comment]
You can already disable feedback for an individual question component by setting `_canShowFeedback` to `false`.

**Comment by oliverfoster** [comment]
closing :D
