### ISSUE TITLE
adapt-contrib-assessmentResults: Fails to work as expected when part of an article Assessment 

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1218]
Currently the Assessment Results component fails to work if it's placed in the same article which has an enabled Assessment.

**Comment by moloko** [comment]
@brian-learningpool could you give a bit more detail about 'fails to work'?

**Comment by sarveshwar-gavhane** [comment]
it works fine at my end please elaborate more about it ?

**Comment by brian-learningpool** [comment]
Apologies both for the shocking vagueness of the original ticket(!) 

The issue is that when an Assessment Results component is placed in an article which has question components, the restoration of the suspend data seems to get a bit confused and the assessment results don't then display when the assessment is completed.

I recall speaking to @oliverfoster about this on the Gitter chat at the time and it appears to be by design that presentation components (like Assessment Results) should not be mixed with an assessment full of question components.  

In terms of an expected behaviour, for me even a console warning and something in the documentation to indicate that Assessment Results should not be be placed in the assessment itself would be a help.

**Comment by sarveshwar-gavhane** [comment]
please find the below image.
![assessmentresult](https://cloud.githubusercontent.com/assets/12641875/20300516/99851192-ab45-11e6-9e7a-f643b93dee4f.jpg)

**Comment by chris-steele** [comment]
This will be related to https://github.com/adaptlearning/adapt_framework/issues/1323. The fix does resolve the issue here, but I noticed that if trickle is used its control of `_isVisible` can interfere with assessmentResults use of the same property. It's an awkward thing to unpick so recommend we just go for the console warning and encourage results in a separate article.

**Comment by oliverfoster** [comment]
fixed with https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/63
