### ISSUE TITLE
accessibility: tabbing trap with trickle

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1220]
![trickle_bug](https://cloud.githubusercontent.com/assets/1228225/18201403/d2972f20-7101-11e6-8ead-865369b779d1.gif)

Scenario: complete block and trickle button appears. Attempt to tab to trickle button, but if block has two components and both are significantly different sizes and smaller one is last in block then tabbing to it causes window scroll, trickle button disappears and hence user can no longer tab to it (see attached screen capture).

**Comment by chris-steele** [comment]
An edge case I know, but I'd made that gif and wanted to use it.

**Comment by oliverfoster** [comment]
Need to turn off autoHide for best accessibility. 
Should I switch the default so that autoHide is off?

**Comment by oliverfoster** [comment]
done
