### ISSUE TITLE
Media component - excessive memory usage in IE11 win7

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#1223]
If you have multiple video (adapt-contrib-media) components in a course over several pages. Going back and forth between pages increments the memory used until the browser crashes.

To reproduce:
Duplicate the video component four times on page co-05. 
Duplicate co-05 so there are two "Presentation Components" pages, changing ID's to avoid collisions
After building course go back and forth between Presentation Components pages in IE11 Win7,

Having the memory profiler on helps.

**Comment by RobertPeek** [comment]
Hi @oliverfoster I hope you don't mind me directing this issue to you but I believe you were helping Dan with this.

As you may know he is away on holiday so in his absence i've picked this up and done some testing myself (I work with Dan at DeltaNet by the way). The fix above does seem to help however the memory increases when returning to the menu.

It also seems that the memory usage just increases throughout the duration of going through the entire course and hits the max when everything is viewed. So ultimately at some point depending on the size of the course and amount of images and video etc used the browser will deteriorate and crash.

Should the memory get cleared or at least reduce when returning to the course menu?

**Comment by oliverfoster** [comment]
Hi Robert,

Can you try the latest fix I've added to the above PR? It's not perfect - still leaks a bit - it does seem to be an issue with the way the DOM nodes are created and destroyed in mediaelementjs.

Ollie.

**Comment by RobertPeek** [comment]
Hi Ollie thanks for the swift response. I've tried the latest fix and it does still seem to leak.

Returning to the menu doesn't always seem to add data to the memory - it's quite random. Could be down to whether I play the video or not but either way it still seems to add to the storage at some point.

Should it be the case that returning to the menu shouldn't add anything to the storage?

In the image below - The first rise is viewing the first page and then the second rise is when returning to the menu.

![storage](https://cloud.githubusercontent.com/assets/7251995/18312032/80d987c6-74ff-11e6-94e3-c86930ede918.jpg)

I may try removing the video from one of the pages and see if the storage still increases when going back to the menu.

Cheers, Rob

**Comment by oliverfoster** [comment]
this is somewhat expected, you'll have to do the same action repeatedly to see if the memory is leaking. 

when the page is destroyed and before the memory is cleaned up, the browser has to rerender the menu, this causes the memory requirements of IE to peak and so it grabs some more memory to manage the processing. that memory will rarely be given back, it is reused though. (as far as i can gather). so the rises we should look out for are the ones that occur on every action, every time.

**Comment by RobertPeek** [comment]
Just tested without a video and no memory usage is added when returning to the menu after viewing a page without a video.

**Comment by oliverfoster** [comment]
yup, mediaelementjs constructs so many elements and attaches functions all over that it takes 7/8 mb/video, the correct destruction of these allocations is a big issue in IE as far as i can tell.

**Comment by RobertPeek** [comment]
This appears to stop the usage being added on the menu view.

Change:

this.mediaElement.player.remove();

To:

this.mediaElement.src = "";

Can you confirm if this is OK @oliverfoster

**Comment by oliverfoster** [comment]
cool. that seems to solve it all, those three things.

* i get a small memory leak if i get rid of the purge fix. so i'm gonna keep that one
* your src="" seems to work for freeing the video, so that stays
* player.remove is part of the mejs api, so that should've been in there always but has little impact on the memory problem - so i'm gonna keep it also

i'm happy with the pr if you are?

**Comment by oliverfoster** [comment]
the question is... does it stop it from crashing?! : O

**Comment by RobertPeek** [comment]
That is the big question indeed.... will test the component in a few courses and on other PC's and report back... fingers crossed!

**Comment by oliverfoster** [comment]
Good luck, looks promising.

**Comment by oliverfoster** [comment]
@RobertPeek / @dancgray  did you have luck with this?

**Comment by dancgray** [comment]
Don't think so. @RobertPeek used a basic HTML5 video component instead for the project. 

I'll see how much of an issue remains when I get more time.

**Comment by oliverfoster** [comment]
cool, ta dude

**Comment by brian-learningpool** [comment]
@oliverfoster can we close this?  I believe the changes have been merged in version 2.0.5 of the  Media component.

**Comment by oliverfoster** [comment]
yea, just waiting to see if Dan has had any luck, might need another PR on this issue.

**Comment by dancgray** [comment]
Just tested this and could not reproduce the issue so closing. Thanks @oliverfoster

**Comment by oliverfoster** [comment]
awesome 👍  thanks dan
