### ISSUE TITLE
grunt server not automatically launching course on Windows

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1227]
When you run the `$ grunt server` command the course does not automatically open in a browser on Windows (tested using Windows 10 with Firefox and Chrome as default browser). You can obviously open the course manually - but a novice user wouldn't know to do that, particularly as it's not clear what correct URL is.

Seems fine on OS X and Ubuntu

**Comment by moloko** [comment]
seems to be sporadic... not working for me or @lc-thomasberger but working for @tomgreenfield (Win 10, Firefox)

**Comment by finlayb** [comment]
Running Windows 10 and Chrome and this happens to me sometimes. Usually just run it a second time and it works.

**Comment by sarveshwar-gavhane** [comment]
tested on windows 10 with Firefox and Chrome as default browser on two different machine's with 2.0.12 version it works fine on one machine and but not on another.

**Comment by NayanK444** [comment]
I made following changes in connect.js file.
```
module.exports = function (grunt, options) {

  var port = grunt.option('port') || 9001;

  return {
    server: {
      options: {
        port: port,
        base: '<%= outputdir %>',
        keepalive:true,
        open: true
      }
    },
    spoorOffline: {
      options: {
        port: port,
        base: '<%= outputdir %>',
        keepalive:true,
        open: true
      }
    }
  }
}
```

**Comment by moloko** [comment]
@NayanKhedkar I just went to test this - only to find that it has started working again without me having changed anything, so I'm currently unable to verify whether these changes fix the problem or not!

I'll try again tomorrow

**Comment by NayanKhedkar** [comment]
@moloko I tested it on windows 10 with IE11, Firefox and Chrome as default browser on various machines.
It worked well even on those machines on which it was not working properly previously.

**Comment by moloko** [comment]
Well I keep trying but still it is working normally for me.

However, I did notice that if I modified connect.js as detailed above I'd end up with two instances of the course being opened...

**Comment by sarveshwar-gavhane** [comment]
https://github.com/adaptlearning/adapt_framework/pull/1317

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/39d2b8aa8cd1891adbb84581489985f72719140c
