### ISSUE TITLE
update 'core model attributes' documentation

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1236]
The [core model attributes wiki page](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes) needs a bit of an update. 

The attribute `_isEnabledOnRevisit` doesn't exist any more

 The following all need adding:
- `_isInteractionComplete`
- `_canReset`
- `_isResetOnRevisit`
- `_canShowFeedback`

Could do with a subsection for core attributes for components that inherit from questionModel. Although strangely some of these question-specific properties have been included in adaptModel (e.g. `_canShowFeedback`). Maybe we just divide up into common attributes and question-specific ones?

**Comment by chucklorenz** [comment]
@moloko @taylortom @tomgreenfield  I could use your feedback (and others') on the direction of this incomplete work: [draft-update-core-model-attributes](https://github.com/chucklorenz/demo-wiki/wiki/draft-update-core-model-attributes)

What had qualified an attribute to be called "core" has been a little unclear to me. And yet other attributes that needed documentation made it to the core model attributes wiki page. Seemed to me a better approach was to document all the model attributes and their defaults.

**Comment by moloko** [comment]
all done, thanks @chucklorenz
