### ISSUE TITLE
make status reset configurable 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1237]
config.json
```
_spoor._reporting._onSessionReset: "incomplete"
```

"" || false -> no reset
"incomplete" || "failed" --> reset

**Comment by moloko** [comment]
I think true/false is all that's required here - you're either going to reset to incomplete or leave it untouched

**Comment by lc-thomasberger** [comment]
sensible ... if it is only true / false I would call it `_shouldResetProgress` ... and it should maybe be a property of the languagePicker?

**Comment by moloko** [comment]
`_shouldResetStatus` would be better... I think if you're going to put it in the spoor config (if that's easier) then it should be more like `_resetStatusOnLanguageChange`?

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/ee7cbaa24db379b8fe100d7f5e135670492d5d81
