### ISSUE TITLE
adapt-contrib-spoor - error message is not clear to the end user

### ISSUE THREAD

**Issue by webb-nickj** [adaptlearning/adapt_framework#1238]
If Spoor can't connect to the API the error message  says

"An error has occurred: The course cannot connect to the LMS".

But if the user clicks either OK or Cancel the course still loads and the user is not told that their progress will not be tracked.

Could this error message be made configurable via the framework and authoring tool so it can be tweaked as necessary?

**Comment by moloko** [comment]
Excellent point. We've an extra reason to look at this now that we've release multi-language support for Adapt as currently you can't localise any of the SCORM error messages. Just need to figure out best way to do this...

We've also talked about adding an option to halt the course completely if the spoor extension doesn't make the initial connection to the SCORM API - presumably that would help a bit?

**Comment by webb-nickj** [comment]
Stopping the course from running would be a step in the right direction.

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt_framework/issues/1333
