### ISSUE TITLE
media: play/pause, spacebar, timeline

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1239]
Issue: Accessibility - keyboard only access. Expected behavior of the spacebar when player is in focus (play button and rail/playhead) is toggle play/pause. This does not seem to work when rail/play head is in focus.

Description: I am using a Mac with Chrome and Safari. The interesting thing is that the mediaelement.js on the http://mediaelementjs.com/ site does seem to work as expect with keyboard input (even when cycling through focus on other elements) the spacebar toggles play/pause.

**Comment by moloko** [comment]
although you can't use the spacebar when the rail has focus to toggle play/pause at the moment, this seems to be working fine in the develop branch... so it looks like something in that update has fixed this. certainly worth checking the develop branch a bit more or putting this on hold until that is released

**Comment by oliverfoster** [comment]
i was using the current master rather than develop to make the fix against.
awesome, if we don't need it i'm happy.
