### ISSUE TITLE
adapt-contrib-media (keyboard access - stuck in full screen)

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1243]
Issue: Using the "f" key on the media component in keyboard only mode will expand the component to full screen and then you can not exit.

Description: You are supposed to be able to hit the "f" key again to exit. In my scenario I am using audio only and actually turned off "fullscreen" for the player - yielding same results. Also in Safari - the "f" key does not work at all.

**Comment by chetan-hajare** [comment]
Hi @mldaq the "f" key toggles the fullscreen on chrome but on safari, the user have to use "Control+Command+F" to toggle the fullscreen. 
Please refer the [link](http://apple.stackexchange.com/questions/137361/shortcut-key-for-fullscreen-mode) to customize shortcut key for fullscreen at user end.

**Comment by mldaq** [comment]
@chetan-hajare - in Chrome I can go full screen with "F" key, but hitting the "F" key again does not toggle it back.

**Comment by chetan-hajare** [comment]
Hi @mldaq I have tested on Mac OS X EL Capitan version 10.11.5 , Chrome version 53.0.2785.116 and Safari version 9.1.1. It works fine. Please let me know the configuration used at your end.

**Comment by mldaq** [comment]
@chetan-hajare - just tested - macOS Sierra version 10.12 - Safari version 10.0  - Safari does seem to work when using "Control+Command+F" to toggle the fullscreen.
