### ISSUE TITLE
adapt-contrib-media (spacebar - toggle play/pause)

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1244]
Issue: Accessibility - keyboard only access. Expected behavior of the spacebar when player is in focus (play button and rail/playhead) is toggle play/pause. This does not seem to work when rail/play head is in focus.

Description: I am using a Mac with Chrome and Safari. The interesting thing is that the mediaelement.js on the http://mediaelementjs.com/ site does seem to work as expect with keyboard input (even when cycling through focus on other elements) the spacebar toggles play/pause.

**Comment by brian-learningpool** [comment]
There is a similar issue in #1239 which has an outstanding PR here:
https://github.com/adaptlearning/adapt-contrib-media/pull/156

**Comment by oliverfoster** [comment]
added comment to issue https://github.com/adaptlearning/adapt_framework/issues/1239

**Comment by oliverfoster** [comment]
@mldaq  this issue has been tested with the latest media component and is considered fix, could you verify?
