### ISSUE TITLE
adapt-contrib-media (Vimeo video not stopping on end frame) 

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#1248]
We have discovered an issue where our Vimeo Videos are not stopping on end end frame of the video but instead displaying the first frame of the video. The outro setting for the Vimeo videos is "Nothing" which should cause the video to stop on the last frame. 

This is occuring randomly when navigating to the page with the video. Once on the page if the issue occurs, it will continue to occur. Likewise if the video behaves correctly it will continue to do so.

The action that initiates the bug would appear to be related to the launching of the page with the video.

I have tried adding 2 different Vimeo videos to the page at the same time. Testing this shows that each video breaks independently. So video 1 may break but at the same time video 2 is not broken and each will remain in that state until you return to the menu. Opening the page with the videos again then randomly breaks or doesnt break each video independently.

**Comment by moloko** [comment]
Does this happen in any browser or a specific one?

FYI we are relying on a third-party player (mediaelementjs) which is itself loading yet another 3rd party player (vimeo)... so I think first order of business is to try and figure out where exactly the problem lies

**Comment by paul-mediakitchen** [comment]
Thanks Matt.

The issue is happening in all browsers. 
I saved the Adapt page files for the page with the videos to my local machine - and tested these both locally (in Firefox) and uploaded to my server and this worked correctly. Hence why I suspected it is due to the page loading.
Testing the video URL standalone in a browser works correctly
Also testing the video in an e-Learning session created with another development tool we use - the video behaves correctly and stops at the end frame
Here is an example video you can test with - I have added an image of some sheep racing at the beginning to help identify what is being seen
https://player.vimeo.com/video/183859236
So if you created a bare bones Adapt course and added the Media Component with this Vimeo Video - what will happen is sometimes the video will stop at end end and sometimes it won't 
It should stop at the end every time - as this is what the outro settings are set to in Vimeo

**Comment by paul-mediakitchen** [comment]
Related to my other tests, I have also done a test setting the Outro setting in Vimeo to "Text"
This should display a semi transparent black overlay with whatever text you specify in Vimeo.

My tests of this functionality within Adapt is proving there are issues on this front too.

Here is a link to an example:

http://mediakitchen.co.uk/adaptMediaTest2WithMenu

Sometimes I am getting the black overlay with the text
Sometimes I am getting only the text
Most of the time this overlay and text is appearing with the first frame of the video appearing instead of the last
And the really bad issue - sometimes the overlay text remains on screen when you press play on the video and remains on screen for the entire video.

So something is not behaving very well with Adapt and Vimeo combo:(

**Comment by moloko** [comment]
OK, I think I've got it and it's not Adapt/Vimeo that's particularly the problem - it seems to be [froogaloop.js](https://github.com/adaptlearning/adapt-contrib-media/blob/master/assets/froogaloop.js) that's the source of the problem in that if I comment out the code that pulls that in, the bug doesn't occur. Equally if I set up a standalone example using just mediaelement.js 2.21.2 it all works fine until I include the froogaloop code.

Looking at the the [Vimeo Player API github repo](https://github.com/vimeo/player-api) I can see that the froogaloop code is no longer supported, so we need to investigate what it would take to [migrate to the new code](https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md) - the immediate problem I can see is that it states that IE9 is the lowest version of IE it supports - whereas we are still committed to supporting IE8 for the time being :-(

As a quick fix, you could just take the froogloop stuff out - but doing so would mean you'd only be able to have 'inview' completion for Vimeo videos - it's froogaloop that allows the 'play' and 'ended' events to work...

**Comment by paul-mediakitchen** [comment]
Thank you Matt for taking the time to look at this issue for me. I really appreciate it.
You suggest a quick fix is taking the Froogloop stuff out. We are using the hosted Learning Pool Authoring Tool to create our courses. Would I be able to remove this Froogloop code from the published files that I download from the Builder? If so, is it simply a case of commenting out any reference to the Froogaloop library?

So just to clarify the issue, is Adapt using Froogaloop as part of the Media Component but due to Vimeo Player no longer supporting Froogaloop, it is causing the issue where it is not stopping at the end of the video? Is that correct? 

I did a quick test just renaming the froogaloop.js file within the assets folder of my downloaded (via Adapt Builder) files. This previously had the issue where the video was not behaving correctly at the end.
Now it appears to work correctly albeit with the following console error:
http://mediakitchen.co.uk/adaptMediaTest2WitnMenuNoFrrogaloop/assets/froogaloop.js Failed to load resource: the server responded with a status of 404 (Not Found)
adapt.min.js:124 You need to include froogaloop for vimeo to work

Here is the link to this test version.
http://mediakitchen.co.uk/adaptMediaTest2WitnMenuNoFrrogaloop

**Comment by moloko** [comment]
> So just to clarify the issue, is Adapt using Froogaloop as part of the Media Component but due to Vimeo Player no longer supporting Froogaloop, it is causing the issue where it is not stopping at the end of the video? Is that correct? 

That seems to be the case

> is it simply a case of commenting out any reference to the Froogaloop library?

I edited adapt-contib-media.js and commented out [this case statement](https://github.com/adaptlearning/adapt-contrib-media/blob/master/js/adapt-contrib-media.js#L131-L143)

If you can't make this sort of change you might be better off leaving the file in place and just deleting the contents of it.

Closing this and moving to #1257
