### ISSUE TITLE
adapt-contrib-spoor - learnerInfo not working

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1249]
Calls to retrieve the learnerInfo return undefined due to the incorrect case being used in the switch statement.

https://github.com/adaptlearning/adapt-contrib-spoor/pull/136

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/6121d6711fd96cb74d89129df68f2985318073df
