### ISSUE TITLE
contrib-media: add 'playsinline' option

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1250]
Safari in iOS10 finally added support for the `playsinline` attribute for HTML video on iPhone - so videos can now be set to play inline by default instead of going straight into the fullscreen player like they always have done up to now.

Whether playing videos inline on such a small screen is good idea or not is a different matter - but I think we should at least add a configuration option for this to allow course developers/designers to decide for themselves!

**Comment by lc-thomasberger** [comment]
https://github.com/adaptlearning/adapt-contrib-media/pull/160

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-media/commit/47d26f34963a393cb47c356fd49539cd04a87885
