### ISSUE TITLE
adapt-contrib-trickle auto scrolls when closing tutor

### ISSUE THREAD

**Issue by HenrikAabom** [adaptlearning/adapt_framework#1255]
Using Trickle with "Scroll Automatically" enabled will unlock the next step-lock and auto scroll to the next "_scrollTo" when closing a tutor popup. 
For instance, if you go back to a previous question to read the feedback again, it jumps then the next question and rolls over it.

**Comment by oliverfoster** [comment]
Thanks :)

**Comment by oliverfoster** [comment]
@HenrikAabom this stuffs should be fixed when we release trickle next. tutor has been released with its fix (v2.0.4). you should be able to test using the master version of trickle and the current release of tutor.

**Comment by HenrikAabom** [comment]
That fixed it, thanks Oliver

**Comment by oliverfoster** [comment]
cool, no problem. thanks for reporting it.
