### ISSUE TITLE
Style issue on buttons

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1266]
I have just tried the master branch of the adapt-contrib-vanilla theme and there is now a dotted outline on buttons when in v2.0.12 of the framework, please see screenshot below:

![sc](https://cloud.githubusercontent.com/assets/7251995/19108064/08d487a0-8ae7-11e6-9cb1-0356e86a596e.jpg)

This is also apparent on buttons in the narrative and other elements like the Page Level Progress.

I have tested in IE11 on Windows 7.

**Comment by tomgreenfield** [comment]
Hi @RobertPeek, this was an intentional change following https://github.com/adaptlearning/adapt_framework/issues/1230. You would need to modify the LESS if you'd like this to be hidden again.

**Comment by RobertPeek** [comment]
Ah thanks @tomgreenfield for the clarification, will change the LESS if I need to then.

Many thanks
