### ISSUE TITLE
Notify modal shows content scrolled to bottom when it appears (instead of being at top)

### ISSUE THREAD

**Issue by finlayb** [adaptlearning/adapt_framework#1268]
@oliverfoster provided the following temporary fix for this issue:

```
this.$('.notify-popup').css({
                    'height':'100%',
                    'top':0,
                    'overflow-y': 'scroll',
                    '-webkit-overflow-scrolling': 'touch'
                });

.delay(_.bind(function() {
                   this.$('.notify-popup')[0].scrollTop = 0;
}, this),500);
```

inserted here https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/notifyView.js#L108

**Comment by joe-replin** [comment]
Applying this fix seems to bypass setting the visibility state being set so the pop-up never appears visible, just the shadow. I've updated this temporary fix to: 

                this.$('.notify-popup').css({
                    'visibility': 'visible',
                    'height':'100%',
                    'top':0,
                    'overflow-y': 'scroll',
                    '-webkit-overflow-scrolling': 'touch'
                })

                .delay(_.bind(function() {
                    this.$('.notify-popup')[0].scrollTop = 0;
                }, this),50);

This does fix the top of the notify pop-up to the top of the mobile view, with the caveat being that it bypasses the fade-in animation.
