### ISSUE TITLE
RTL Slider

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1276]
In right-to-left orientation, the highlighted slider numbers are out of whack, i.e., they retain their left-to-right orientation in that they still count up from 1 on the left, and the numbers themselves are backwards.

![5](https://cloud.githubusercontent.com/assets/19309048/19231554/848961a6-8ed2-11e6-9a34-eb9f8ea2022c.jpg)

**Comment by NayanKhedkar** [comment]
PR:  https://github.com/adaptlearning/adapt-contrib-slider/pull/118

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/eefb7ffc435bc768de9f25bd3d1fb8db93132120 thank you @NayanKhedkar !
