### ISSUE TITLE
Language selector: changing rtl to ltr

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1277]
Changing from a rtl language to a ltr language seems to break the course a bit. After completing the first two topics and accessing the Assessment in Hebrew, I switched to English and most of the text, despite being the correct English text, was rtl-oriented and none of the navigation bar elements worked anymore (clicking on an icon would prompt the white screen overlay, but its  respective drawer would not appear).

Note: Switching from Hebrew to German breaks the layout but not the nav bar functionality.

![6](https://cloud.githubusercontent.com/assets/19309048/19231840/4b84f4c2-8ed4-11e6-8f33-cdbe07785c6a.jpg)

![7](https://cloud.githubusercontent.com/assets/19309048/19231820/1ddb9896-8ed4-11e6-8247-dd51585ca6c9.jpg)

**Comment by lc-thomasberger** [comment]
should be fixed with this PR: https://github.com/adaptlearning/adapt_framework/pull/1274

**Comment by kineotesting** [comment]
Confirmed fixed.
