### ISSUE TITLE
adapt-contrib-slider: New release?

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1278]
Is there a plan to Release a new version of this plugin with the latest changes?

Cheers!

**Comment by moloko** [comment]
yes of course at some point, I didn't really think there had been any particularly significant changes yet... specifically what changes were you referring to?

**Comment by RobertPeek** [comment]
This would be useful:

https://github.com/adaptlearning/adapt-contrib-slider/commit/8640b5e3f962c593e6096a3eceeac4096311b003

**Comment by moloko** [comment]
released as [v2.1.1](https://github.com/adaptlearning/adapt-contrib-slider/releases/tag/v2.1.1)
