### ISSUE TITLE
Hot graphic rtl pin position

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1279]
When viewing a hotgraphic component in rtl orientation, the pin positioning stays ltr, e.g, pin 1/3 is the leftmost and pin 3/3 is rightmost. Is it possible to change this? It's really just a usability issue, not a huge deal.

**Comment by lc-thomasberger** [comment]
not directly related to multilanguage Feature so I renamed the issue.

**Comment by moloko** [comment]
is this even a technical issue or more just down to the component not having been set up perfectly for rtl?

**Comment by moloko** [comment]
closing as I don't think this is a technical issue, it's just a case of the content not having been optimised for RTL
