### ISSUE TITLE
Language selector: Search

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1281]
Seen on F3:

The search function isn't working. Searching for a known term (like 'narrative' or 'component') doesn't bring up any results. Mentioning it as I don't know if it's a bug or it's just not been set up completely.

**Comment by lc-thomasberger** [comment]
Glossary only searches in term and description.
The mentioned keywords are not included. If you search for "Authoring" it displays entry about "About Framework".

**Comment by moloko** [comment]
mixup in functionality, tester thought this was [adapt-search](https://github.com/cgkineo/adapt-search)

**Comment by kineotesting** [comment]
Not a bug.
