### ISSUE TITLE
Language selector: MLP indicator

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1284]
If you complete the assessment (pass or fail) in one language and then switch to another (which wipes all in-course progress), the assessment MLP will show some progress even through the PLP and individual component progress bars will all be wiped.

![8](https://cloud.githubusercontent.com/assets/19309048/19242606/cda546c8-8f0b-11e6-8a9e-479ae8520559.jpg)

**Comment by moloko** [comment]
I think this is probably OK - after all it's reflecting that the user has made an attempt at the assessment and the assessment attempt should **not** be wiped if the user changes language (as this would allow the user to bypass the allowed number of attempts simply by toggling language)

anyone object to that?

**Comment by oliverfoster** [comment]
nullified by assessments reset on language change PR > https://github.com/adaptlearning/adapt-contrib-assessment/pull/75

**Comment by kineotesting** [comment]
Confirmed fixed.
