### ISSUE TITLE
Glossary [tablets and phones] Search input glitch rtl

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1285]
This doesn't happen on desktop, but when you type a word into the Search text box in rtl on the iPad, the first letter repeats at the start and end of the word (word used in screenshot is 'Adapt'):

![img_0193](https://cloud.githubusercontent.com/assets/19309048/19266121/fdffc4e4-8f9f-11e6-98a1-f177cadbc2f2.jpg)

**Comment by lc-thomasberger** [comment]
not strictly related to Language Picker so I updated the name.

**Comment by moloko** [comment]
moving to https://github.com/adaptlearning/adapt-contrib-glossary/issues/23
