### ISSUE TITLE
Language selector: [phones] Assessment MLP/PLP

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1286]
I can't seem to get the Assessment MLP or PLP to complete properly on 100% score in any language.The MLP always seems show as partially complete, and the PLP will only sometimes show complete. Also, on the iPhone 6 iOS 10, if I pass the Assessment with 100% score, exit the topic (not the course) and reenter, the nav bar loses functionality--selecting a nav button with cause the transparent white overlay to appear but not the relevant drawer.

Update: I'm only seeing this on uploads that have spoor enabled.

**Comment by lc-thomasberger** [comment]
issue with the nav bar is probably the same as described in this issue: https://github.com/adaptlearning/adapt_framework/issues/1277

So when you switch from rtl to ltr

**Comment by lc-thomasberger** [comment]
That's how I can replicate ths bug also on Desktop:
When the first attempt is 100%, PLP and MLP show a 100% score.
When first attempt fail and next attempt is 100%, MLP and PLP do not show a full 100%

**Comment by lc-thomasberger** [comment]
On every language change, [Adapt.assessment.register()](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/assessment.js#L203) is called.
For progress calculation, [total](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/master/js/PageLevelProgressNavigationView.js#L67) uses every Assessment and not just the ines for each language.

**Comment by oliverfoster** [comment]
try on line https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/assessment.js#L211
```
if (this._assessments._byAssessmentId.hasOwnProperty(assessmentId)) return;
```

**Comment by oliverfoster** [comment]
issue nullified by assessments reset on language change PR > https://github.com/adaptlearning/adapt-contrib-assessment/pull/75

**Comment by kineotesting** [comment]
Confirmed fixed, but now, if I fail the assessment, the PLP and MLP show as complete too (previously if you'd failed, they'd show partially completed as is standard I think).

**Comment by moloko** [comment]
I just tried failing the assessment on an older version of Adapt I had from back in August (framework v 2.0.11, assessment 2.0.6, PLP 2.0.6) and initially both the page-PLP and menu-PLP showed completed progress. It was only when I then went back into the assessment that they both updated. So maybe this has been an issue for a while?

**Comment by moloko** [comment]
same results on a copy of adapt I have from back in Sept (framework 2.0.12, assessment 2.0.6, PLP 2.0.7)

But I do get what Jen (@kineotesting) is saying though, I thought it showed as partially completed if you failed. Odd.

**Comment by lc-thomasberger** [comment]
Tested with Version 2.0.12 of the Framework and Version 2.0.6 of Assessment. So the Versions before the ML-feature work.

When you fail the assessment, PLP on the page with Assessment is full. When you go back to the Menu, MLP is also full. Matches the PLP, which is exactly what I would expect.

When I revisit the page with the Assessment, the PLP changes into "partial", when I go back to the Menu, MLP matches again the PLP value.
