### ISSUE TITLE
SCORM log pop up

### ISSUE THREAD

**Issue by RM4G00** [adaptlearning/adapt_framework#1292]
Anyone else experiencing when previewing content - SCORM log pop up

ScormWrapper::initTimedCommit
ScormWrapper::getValue: _property=cmi.suspend_data
ScormWrapper::getValue: returning
ScormWrapper::getValue: _property=cmi.suspend_data
ScormWrapper::getValue: returning
ScormWrapper::getValue: _property=cmi.core.lesson_location
ScormWrapper::getValue: returning undefined
ScormWrapper::getValue: _property=cmi.core.score.raw
ScormWrapper::getValue: returning undefined
ScormWrapper::getValue: _property=cmi.core.lesson_status
ScormWrapper::getValue: returning incomplete
ScormWrapper::getValue: _property=cmi.core.student_name
ScormWrapper::getValue: returning Test Student
ScormWrapper::getValue: _property=cmi.core.student_name
ScormWrapper::getValue: returning Test Student
ScormWrapper::getValue: _property=cmi.core.student_id
ScormWrapper::getValue: returning undefined

Anyway to remove?

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor#running-a-course-without-tracking-while-spoor-is-installed

**Comment by moloko** [comment]
or it's possible you've configured spoor so that window always displays - see `_showDebugWindow` in the [settings](https://github.com/adaptlearning/adapt-contrib-spoor#attributes)

**Comment by RM4G00** [comment]
Hi, 

Can you confirm if config.json is located via /adapt_authoring/conf 


Regards, 

Ross Mulgrew 

IT Systems Administrator | Allied Vehicles Ltd | 230 Balmore Road | Glasgow, Scotland 
Ext:1028 - DDI 0141-336-1028

**Comment by moloko** [comment]
Hi @RM4G00 - if you're using the authoring tool you should configure plugin settings via the authoring tool interface and not by editing the underlying files.
