### ISSUE TITLE
adapt-contrib-slider: .slider-scale-marker font size

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1293]
In the adapt-vanillia-theme button font size is 18px and body text size is 14px.

The label that hovers (.slider-scale-marker) is in a div so defaults to 14px. The numbers that appear on the lines are buttons that default to 18px. It seems like bad design to have the overlay font-size to be smaller. 

Could we fix this by setting the font-size of .slider-scale-marker to less variable @button-text-font-size?

<img width="152" alt="screen shot 2016-10-20 at 17 21 07" src="https://cloud.githubusercontent.com/assets/1676635/19568594/1a75f728-96ea-11e6-97a8-4f46dae25512.png">

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/b52a0777ae8e3c1c09c455596b788f6e2590bcd3
