### ISSUE TITLE
iOS 10 ignoring meta tag

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#1296]
http://stackoverflow.com/questions/37808180/disable-viewport-zooming-ios-10-safari

**Comment by oliverfoster** [comment]
we have decided to try and make adapt compatible with the pinch and zoom functionality rather than attempt to override this behaviour.

we need to explore those parts that need updating. at the moment it looks as though the fixed position items (notify, navigation bar, etc) are the biggest issues.
