### ISSUE TITLE
Persistent focus on button item

### ISSUE THREAD

**Issue by samumist** [adaptlearning/adapt_framework#1297]
A persistent mouse focus on those components with clickable items. When you click on a button, it shows up, very strange.

** Hotgraphic **
![hotgraphic](https://cloud.githubusercontent.com/assets/3883086/19713564/ac6abc0c-9b79-11e6-9e88-b2662d405293.gif)

** Narrative **
![narrative](https://cloud.githubusercontent.com/assets/3883086/19713579/c68cd548-9b79-11e6-9d3b-00ad1a22ec0c.gif)

I'm not sure if this is something with the new release as I haven't noticed this before.

Framework: 2.0.14
Browser: Mac Chrome 53.0.2785.89 (64-bit)

**Comment by tomgreenfield** [comment]
Hi @samumist, this was an intentional change following #1230. You would need to modify the LESS if you'd like this to be hidden again.

Although, this _is_ the third time this issue has been raised.

**Comment by samumist** [comment]
Thanks @tomgreenfield!
I didn't realise that it was intentional, sorry!
