### ISSUE TITLE
jquery v3

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1303]
http://jquery.com/download/

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/401a250219ca485d508ee6444e3cb7be49e3a504

**Comment by moloko** [comment]
Had to revert back to JQuery v2 as v3 isn't compatible with the version of rangeslider we're currently using in adapt-contrib-slider. 

Should be able to come back to this when we finally update to the latest version of rangeslider
