### ISSUE TITLE
contrib-slider: styling not applied when restoring answer from previous session

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1309]
When the slider restores the user's response from a previous session, it doesn't restore the styling.

Submitted slider:
![slider_submitted](https://cloud.githubusercontent.com/assets/1249597/20178002/5cd26800-a747-11e6-88c3-25cb977abac0.png)
Same component, in a subsequent session:
![slider_restored](https://cloud.githubusercontent.com/assets/1249597/20178017/69d2b000-a747-11e6-8a4e-4a6c1bcbd511.png)

Note that as of the time of writing, Slider is not able to restore the user's answer at all, PR [#116](https://github.com/adaptlearning/adapt-contrib-slider/pull/116) fixes this

**Comment by NayanKhedkar** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-slider/pull/118

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/eefb7ffc435bc768de9f25bd3d1fb8db93132120
