### ISSUE TITLE
Document the libraries and required folders

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1314]
We should update the "How to write a plugin" documentation to give reference to the `libraries` and `required` folders.  

The `/libraries` folder is the preferred location now for things like JavaScript libraries, etc.  Files here will be output to the `/libraries` folder.

Any files held in the `/required` folder, e.g. XML, etc. (see Spoor for an example) will be output at the root of the output directory.

**Comment by brian-learningpool** [comment]
Also document `preRemove` and `postRemove` events (see #1306)

**Comment by chucklorenz** [comment]
New section added to [Developing plugins](https://github.com/adaptlearning/adapt_framework/wiki/Developing-plugins#organizing-plug-in-files). Please review, especially the accuracy/appropriateness of my path notation in the column titled "output location." Feel free to edit directly.

**Comment by chucklorenz** [comment]
`preRemove1 and `postRemove` have been added to [Core Events](https://github.com/adaptlearning/adapt_framework/wiki/Core-Events). Please review and amend as you see fit.

**Comment by moloko** [comment]
just a few small amends, thanks @chucklorenz
