### ISSUE TITLE
Slider: wrong selection in RTL mode

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1318]
When the Slider is in RTL mode, if you submit without dragging it wrongly calculates the user's selection as `10` instead of `1`.

**Comment by NayanKhedkar** [comment]
https://github.com/adaptlearning/adapt-contrib-slider/pull/119

**Comment by NayanKhedkar** [comment]
https://github.com/adaptlearning/adapt-contrib-slider/pull/119
