### ISSUE TITLE
adapt-contrib-trickle: _completionAttribute - set as _isComplete by default?

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1322]
I think this should be the default value for this... struggling to think of when you would not want this to be set to `_isComplete` ?

**Comment by moloko** [comment]
agreed in the weekly standup that we should make this change

**Comment by chris-steele** [comment]
+1 will solve occasional issues: e.g. when `_spoor._tracking._shouldStoreResponses` is `true` questions have their `_isInteractionComplete` property restored on launch, but other components do not - this can cause trickle _to appear_ to behave inconsistently.
