### ISSUE TITLE
adapt-contrib-spoor: allow for dynamic properties in imsmanifest.xml

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1329]
now that we have the ability to have the CLI dynamically replace text in XML files with data from the course's JSON; we should implement this in imsmanifest.xml so that course authors don't have to manually populate this information.

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt-contrib-spoor/pull/146

**Comment by brian-learningpool** [comment]
PR merged, closing issue.
