### ISSUE TITLE
adapt-contrib-assessment: _resetType has no default value

### ISSUE THREAD

**Issue by oakis** [adaptlearning/adapt_framework#1330]
When creating an assessment without _questions._resetType set to a value it throws an error when trying to access that course. I suggest that you add a default value when no _resetType is present.

This is the error I´m getting:

adapt-assessmentArticleModel.js:465 Uncaught TypeError: Cannot read property '_resetType' of undefined(…)

**Comment by lc-thomasberger** [comment]
I can't replicate.

Even if [quesiton.reset](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L469) is called with a wrong resetType, the [questionModel](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/questionModel.js#L282 ) defines a default resetType

**Comment by oakis** [comment]
Try again without the property at all. When I got the error I didnt even have a _questions object.

**Comment by tomgreenfield** [comment]
I haven't really looked into this but we'll probably need to rethinking returning early [here](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L680).

**Comment by moloko** [comment]
fixed by https://github.com/adaptlearning/adapt-contrib-assessment/commit/e4c1c1b98745a1891388193905488f6b5962e8bf
