### ISSUE TITLE
Add support for ES5 via a shim in IE 8

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1335]
While we continue to support Internet Explorer 8, we should at least have a shim which allows us to use ES 5 JavaScript on our code.

Right now there are a few gaps and inconsistencies with IE 8's behaviour on standard ES 5 Javascript.

**Comment by oliverfoster** [comment]
i think that's a good idea for some basic bits, like Array.indexOf
But how far should we take this? Any suggestions for quantifying the boundaries would be good.

**Comment by brian-learningpool** [comment]
I think since we're almost in 2017, IE 8 support in "graceful degradation" mode is acceptable.

The shim at https://github.com/inexorabletash/polyfill/blob/master/es5.js looks promising.  It supports `Array.prototype.indexOf` and `Object.definedProperty` and is used by the Metor JS framework.

Here is the full list of functions:

- `Object. getPrototypeOf`
- `Object getOwnPropertyNames`
- `Object.create`
- `Object.defineProperty`
- `Object.defineProperties`
- `Object.keys`
- `Function.prototype.bind`
- `Array.isArray`
- `Array.prototype.indexOf`
- `Array.prototype.lastIndexOf`
- `Array.prototype.every`
- `Array.prototype.some`
- `Array.prototype.forEach`
- `Array.prototype.map`
- `Array.prototype.filter`
- `Array.prototype.reduce`
- `Array.prototype.reduceRight`
- `String.prototype.trim`
- `Date.now`
- `Date.prototype.toISOString`

**Comment by oliverfoster** [comment]
cool. almost all of those aside from the prototyping and date stuff are covered by underscore. otherwise, they're all used really infrequently. i'm happy to include if you think it'll give extra legs to es5?

**Comment by oliverfoster** [comment]
can you minify it before inclusion? 14kb > 8kb or so

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt_framework/pull/1346
