### ISSUE TITLE
contrib-assessment: assessment doesn't cope with _assessmentWeight not being set

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1341]
If you don't have a valid `_assessmentWeight` property configured on your assessment article, the score sent to the LMS is `NaN`.

The code needs to handle this property being absent better - either by warning the user with a `console.error` or by defaulting the value to `1`.

**Comment by chetan-hajare** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-assessment/pull/76

**Comment by moloko** [comment]
fixed by https://github.com/adaptlearning/adapt-contrib-assessment/commit/e4c1c1b98745a1891388193905488f6b5962e8bf thanks @chetan-hajare
