### ISSUE TITLE
contrib-slider: look at upgrading to rangeslider v2.3.0

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1350]
... seeing as [v2.3.0](https://github.com/andreruffert/rangeslider.js/releases/tag/v2.3.0) has a fix for the [bug where dragging the slider also selects surrounding text in IE, Edge and Firefox](https://github.com/andreruffert/rangeslider.js/issues/192)

**Comment by NayanKhedkar** [comment]
https://github.com/adaptlearning/adapt-contrib-slider/pull/119
