### ISSUE TITLE
contrib-vanilla: issues with the narrative indicators in the 'navigation in textarea' layout

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1351]
When `_hasNavigationInTextArea` is set to `true`, the `.narrative-indicators` div is poorly positioned. 

Not only does this look odd when there are more than around 8 items - but when there are more than 11 items it overruns the right nav button (see #1311)

Additionally, the default colour of the indicators in this theme is `#078292` which is the same as the background in this layout - so they're not even visible.

Screenshot with the progress indicators re-coloured red to show the layout problem:
![2016-12-02 20_01_21-adapt version 2 0 demonstration _ presentation components](https://cloud.githubusercontent.com/assets/1249597/20849045/c5625b32-b8cc-11e6-8277-28c607fb5e38.png)

**Comment by sarveshwar-gavhane** [comment]
PR:  https://github.com/adaptlearning/adapt-contrib-vanilla/pull/200 and https://github.com/adaptlearning/adapt-contrib-narrative/pull/169
