### ISSUE TITLE
pageLevelProgress: focus jump after navigating to component via PLP in IE9

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1354]
I noticed when testing the updates to contrib-matching that if you use the PLP to navigate to a component, focus first goes to the component's 'region' aria-label (as you'd expect) but, a split second later, is pulled back to the `.page-level-progress-navigation` button in the top navbar...

It seems fine in IE11, Firefox & Chrome; I haven't had time to check IE9 or 10 yet.

**Comment by oliverfoster** [comment]
closing as ie8-10 are now unsupported.
