### ISSUE TITLE
Revert issue 1095

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1355]
Issue #1095 (loading feedback) looks to have introduced an issue where a theme's Handlebars "loading" template is no longer used at all.  As such, merging the PR has inadvertently introduced what amounts to a breaking change.

I'm proposing that we revert, re-open the original issue and consider another approach.

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt_framework/pull/1356

**Comment by moloko** [comment]
done in 54dbb96a944e07c939cb123363ed103eec3fd7a6
