### ISSUE TITLE
adapt-contrib-spoor: refactor of wrapper.getISO8601Timestamp

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1363]
Assuming #1346 gets merged then it will add support for [date.toISOString()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), allowing us to either drastically simplify this function - or even remove it altogether.

Currently it returns the time in the format 2016-12-15T11:59:33 - but if SCORM 2004 accepts the format 2016-12-15T11:59:33.229Z then this function can be dropped altogether and just `new Date().toISOString()` used - otherwise it's just a case of keeping the function but changing it to:
```
var d = new Date().toISOString();
return d.substr(0, d.lastIndexOf("."));
```

**Comment by oliverfoster** [comment]
any news on this matt? @moloko

**Comment by moloko** [comment]
@oliverfoster indeed PR raised

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/dde4aeca80bbbfb20b56c19f2e8cc628a1ef51c1
