### ISSUE TITLE
expose components active item index 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1365]
Components with items should keep track of the active item in their model. This would enable us to listen to the change event and call actions in extensions. Furthermore, setting the components state, should be possible by setting a value for an active item index.

Example usecase: A custom audio extension can play audiotracks depending on the currently active item of a narrative component.

Core components with items:
- accordion
- narrative
- hotgraphic

**Comment by tomgreenfield** [comment]
Directly related to https://github.com/adaptlearning/adapt_framework/issues/1178.

**Comment by oliverfoster** [comment]
closed in https://github.com/adaptlearning/adapt_framework/pull/1638
