### ISSUE TITLE
adapt-contrib-trickle: Repeated use of the Show Feedback button breaks subsequent step-locking

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1366]
On a course which is using Trickle step-locking, for example in the following layout of MCQs:

- Question 1, gives a Continue button which unlocks Question 2
- Question 2, gives a Continue button which unlocks Question 3
- Question 3, etc.

I'm noticing that when I answer Question 1 (correct or incorrect, it doesn't matter) I get the Show Feedback and the Continue button as expected, and Question 2 is now visible.  However, if I scroll back up to Question 1 and click to Show Feedback again, the subsequent step-locking is broken, i.e. I can see Question 3 and beyond.

I think this may be a problem with the `isOriginStepLocked` function, and when it runs multiple times: 
https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/tutor.js#L50

**Comment by brian-learningpool** [comment]
I should have mentioned, it's multiple clicks of the Show Feedback button for Question 1 which will break step-locking.  The screen appears to reveal more until the locked questions are completely visible.

**Comment by oliverfoster** [comment]
yea, you've pretty much figured it out by the sounds of it in the gitter room: stepLockedId no longer refers to the locked component.

Looks like you just need to check the view.model.get("_id") is the stepLockedId?

**Comment by brian-learningpool** [comment]
The `view` is actually undefined though?  

I think the problem is more with the `onUnwait` function, and how the `trickle:unwait` event is triggered when the Tutor is closed.  This event doesn't appear to pass any identifier of the article or block which to identify whether it should scroll or not.

**Comment by oliverfoster** [comment]
i can't replicate this from your instructions.
it doesn't matter if i answer the second question or not.

assumptions:

* trickle (continue button)
* mcqs (attempts 1)
* assessment (can show feedback)

Steps:
1. answer question 1
2. close question 1 feedback
3. click question 1 trickle

Branch A:
A4. click question 1 show feedback
A5. answer question 2
A6. close question 2 feedback
A7. click question 2 trickle

Branch B:
B4. answer question 2
B5. close question 2 feedback
B5. click question 1 show feedback
B6. click question 2 trickle 


![branchb](https://cloud.githubusercontent.com/assets/7974663/21982939/88a9ef7e-dbe6-11e6-9922-0880e8d0ef5f.gif)
![brancha](https://cloud.githubusercontent.com/assets/7974663/21982938/88a792c4-dbe6-11e6-8f2b-bcd46b60dd8b.gif)

**Comment by brian-learningpool** [comment]
After going through the course it was identified that `_stepLocking._isEnabled` and `_stepLocking._isCompletionRequired` were both (incorrectly) set to `false`.  Thanks @oliverfoster!

Closing the issue.
