### ISSUE TITLE
accessibility - add option to disable automatic switching-on of accessibility on touch devices

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1370]
Quite often it's only a requirement to have accessibility on desktop browsers (usually only IE) so it would be useful to be able to disable the 'auto-on' feature for touch devices as accessibility on iOS can trigger bugs that don't appear on the desktop version.

For example, I had an iOS accessibility bug with [articleBlockSlider](https://github.com/cgkineo/adapt-articleBlockSlider) on a recent project where focus would always jump to the first component in the ABS on page load - but only on iOS. Obviously in an ideal world I'd fix the underlying issue with ABS, but since there was no iOS accessibility requirement for this project it was far easier (and cheaper!) just to disable accessibility for touch devices ;-)

**Comment by moloko** [comment]
this functionality can be removed should we ever manage to do #1182

**Comment by brian-learningpool** [comment]
@moloko, I noticed this issue was still open.  Are we ok to close?
