### ISSUE TITLE
Locking doesn't take into account availability of children

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1373]
In `adaptModel.js`, the locking functionality doen't check for `"_isAvailable": true` when setting `_isLocked`.

Would be useful to include a new function `getAvailableChildren()` since a collection is already requested in three other places in the file.

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
done in 2f43c2cdf9cfa073aba862879dd2cd224487b747
