### ISSUE TITLE
adapt-contrib-spoor: some question types can trigger a SCORM error under certain circumstances

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1376]
If you have `_shouldRecordInteractions` enabled in config.json and your course contains a 'choice' type interaction (e.g. MCQ, GMCQ) where the user is allowed to select more than 9 answers (and does so), a SCORM error will occur when the course tries to record the interaction.

This is because the datatype of cmi.interactions._n_.student_response is CMIFeedback, which, for 'choice' type interactions must be:
> one or more single characters separated by a comma. Legal characters are “0” to “9” and “a” to “z”.

An MCQ with, say, 15 possible selections allowed could therefore result in the spoor extension trying to set the student_response to "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15" which would trigger an "Incorrect Data Type" error.

Although this is a bit of an edge case, it would be good to see if we could avoid this - perhaps by switching to using 'a', 'b', 'c' for responses 10 and up?

**Comment by moloko** [comment]
Think this should only be an issue for SCORM 1.2 - SCORM 2004 doesn't have the same "0 to 9" restriction.

**Comment by brian-learningpool** [comment]
Hi @moloko, that sounds like a reasonable approach.

**Comment by moloko** [comment]
seems the same thing can happen for matching questions

**Comment by chris-steele** [comment]
PR for this here: https://github.com/adaptlearning/adapt-contrib-spoor/pull/177

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/9faae64fc83b8f9b9528fea70f7a803ece939239
