### ISSUE TITLE
adapt-contrib-resources: ability to rename file on download

### ISSUE THREAD

**Issue by dennis-learningpool** [adaptlearning/adapt_framework#1377]
When publishing via the authoring tool, all files, including resources, use the hashed filename that is used to store them on disk, instead of the meaningful filename that the user has given them. 

This makes it awkward for learners to locate their file when they click on a resource file that may have a name like "Ceiling Cat.jpg", but is downloaded as "abcdef0123456789.jpg". 

It would be good to support renaming of a hashed filename to the display name at the point it is downloaded. This would be less tricky than handling renames at publish-time from the authoring tool, since files with differing content may share the same display name, and could lead to clobbering in the output.

**Comment by moloko** [comment]
done in [Resources v2.0.6](https://github.com/adaptlearning/adapt-contrib-resources/tree/v2.0.6)
