### ISSUE TITLE
Glossary and Resources open directly with different icons on task bar

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_framework#1378]

**Comment by simondate** [comment]
@aniketdharia , this is possible with [Adapt-toolbox](https://github.com/deltanet/adapt-toolbox) however I would be in favour of it being implemented in core.

**Comment by oliverfoster** [comment]
Icon order will be important here

**Comment by aniketdharia** [comment]
@oliverfoster order should not be an issue... let us see if we can make it flexible..

**Comment by oliverfoster** [comment]
:+1:
