### ISSUE TITLE
Assets do not load correctly on Saba LMS

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt_framework#1379]
Page assets like videos, css files sometimes fail to load through Saba LMS

**Comment by brian-learningpool** [comment]
@aniketdharia, I've renamed the issue title for clarity due to the conflict with the Resources extension. 

Do you have any more detail on this one?

**Comment by aniketdharia** [comment]
@brian-learningpool when we launch the course on iPhone 6 in default browser and Safari on Mac, the framework sometime fails to load the assets like CSS, MP4s and Images.

**Comment by moloko** [comment]
@aniketdharia Kineo have access to the [Saba Cloud Content Lab](https://contentlab.sabacloud.com) so could do a quick test if you like... however I have to say I tested an Adapt course on there just three days ago and it worked fine.

What I do know is that Saba Cloud uses a `frameset` to display the content (for the 'New Window Standard Template' player template anyway) so obviously there are all the usual issues on Safari for iOS....

**Comment by oliverfoster** [comment]
any news on this @aniketdharia ?

**Comment by aniketdharia** [comment]
It is specifically in iPhone 6 Safari.. due to frameset.. tested it.. 😭

**Comment by moloko** [comment]
Tested two Adapt courses on Saba Content Lab just last week.... still no issues like this. Unless there is any indication that there's something wrong in Adapt itself I think we need to close this.

**Comment by aniketdharia** [comment]
Currently, I am closing this issue as it seems only restricted to iPhone 6 and SABA combination.
