### ISSUE TITLE
vanilla plugin not compatable message

### ISSUE THREAD

**Issue by NeilHS** [adaptlearning/adapt_framework#1382]
Upon installing framework first time and proceeding to create course via command prompt from folder location, after using the four default settings, the following message appears:
The plugin adapt-contrib-vanilla is not compatible with this version of Adapt. Installing it may cause unexpected behaviour.
[                 .] / runTopLevelLifecycles: sill install printInstalled

Creation process is then suspended.   I'm new to Adapt and any clarification would be welcomed.

**Comment by moloko** [comment]
@NeilHS when we've had other people report this it seems that it has been down to local IT restrictions (proxy, firewall - that sort of thing). Does that sound like it might apply in your case?

**Comment by NeilHS** [comment]
I'm using a single computer on a local network and I'll try adjusting some of my network settings.  Thank you for the response.

**Comment by NeilHS** [comment]
Resolved - used a different approach to work directly with adapt_authoring first which was successful vs. using adapt_framework.  I will try the AF at a later point.
