### ISSUE TITLE
MCQ/GMCQ - properties.schema _shouldBeSelected: 'false' is a better default?

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1383]
It's been mentioned that it might make sense for the `_shouldBeSelected` property should be defaulted to  `false` rather than `true`.  The rationale for this is that there are generally more false choices than true options.

Any thoughts on this?

**Comment by moloko** [comment]
Yep makes sense to me.

Also, I have to say having (finally!) started to use the authoring tool a bit more, I'm really preferring the use of the Checkbox input type for Boolean properties like this... Why make the user click twice when one click will do the job?

Actually it would be nice to see an option for a switch control like you get on iOS but appreciate I'm going way off topic now ;-)

**Comment by moloko** [comment]
> Also, I have to say having (finally!) started to use the authoring tool a bit more, I'm really preferring the use of the Checkbox input type for Boolean properties like this... Why make the user click twice when one click will do the job?
> 
> Actually it would be nice to see an option for a switch control like you get on iOS but appreciate I'm going way off topic now ;-)

Ah, I see this has already been covered in https://github.com/adaptlearning/adapt_authoring/issues/1380

**Comment by brian-learningpool** [comment]
PRs here:
https://github.com/adaptlearning/adapt-contrib-mcq/pull/132
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/107

**Comment by brian-learningpool** [comment]
PRs merged.
