### ISSUE TITLE
adapt-contrib-spoor: SCORM 2004 support

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#1387]
SCORM 2004 isn't currently supported in the authoring tool.

We'd need to:
- Expose the `_scormVersion` variable
- Support multiple sets of 'required' files

**Comment by moloko** [comment]
it is fairly straightforward to convert a course to SCORM 2004 following the instructions in the README for spoor; we therefore agreed that since this is so rarely required, manually amending the output is 'good enough' for those who need SCORM 2004 support
