### ISSUE TITLE
Allow ordering of drawer items

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1393]
It would be very useful to have control over the positioning of items which appear in the drawer.

**Comment by moloko** [comment]
also see #534

**Comment by barryo-learningpool** [comment]
Hi @ratnadeeprajput , Are you currently working on this? If not, do you mind if I give it a go?

**Comment by ratnadeeprajput** [comment]
@barryo-learningpool - sure, please proceed.

**Comment by barryo-learningpool** [comment]
Hi guys, I need some pointers on how to go about this.  Is it safe to assume that only "Extensions" will ever populate the drawer?  If not, do we need a hasDrawer flag on plugins?

And then does it seem like a good idea to have a sortOrder property on plugins/extensions or should we keep this separate somewhere?

**Comment by moloko** [comment]
> Is it safe to assume that only "Extensions" will ever populate the drawer?

Yes I think so.. I certainly can't think of an example of anything other than an extension putting content into the drawer.

>And then does it seem like a good idea to have a sortOrder property on plugins/extensions or should we keep this separate somewhere?

Yep that sounds sensible though maybe something more like `drawerOrder`. I would then add a third `order` argument to `drawer.addItem`.

In the event that two extensions have the same `drawerOrder` set I would suggest a 'you snooze you lose' policy in which the first one to register get the desired position and the runner-up gets added after it.

Extensions that don't pass `drawerOrder` argument to `drawer.addItem` should just be added to the end of the collection.

**Comment by barryo-learningpool** [comment]
@moloko Thanks for the pointers, much appreciated.

It seems ordering the collection by the drawerOrder attribute works quite nicely.

See my change and comments here: 
https://github.com/adaptlearning/adapt_framework/pull/1685

**Comment by oliverfoster** [comment]
I like this. We also need a left, right, center + order for the navigation bar.

**Comment by barryo-learningpool** [comment]
Cheers @oliverfoster. Is that covered in #1555 ?

**Comment by oliverfoster** [comment]
Yup, I just figure, whilst your brain is fresh on the subject you might like to tackle it?

**Comment by moloko** [comment]
this is now resolved in core, resources and glossary

Kineo have updated their [search extension](https://github.com/cgkineo/adapt-search) and [a message was posted in the community forums](https://community.adaptlearning.org/mod/forum/discuss.php?d=2701) asking people who maintain extensions that use to drawer to update their extension to support `_drawerOrder`

don't think there's anything more to do here...
