### ISSUE TITLE
adapt-contrib-assessment: Add some help text to properties.schema

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1395]
There is currently no help text for the attributes which are added to course.json.

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt-contrib-assessment/pull/81

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/3b2c0506f48a092ac271f7ded03ae7c21a83929b
