### ISSUE TITLE
SCORM Cloud - Narrative Component not being visited.

### ISSUE THREAD

**Issue by rbrooks91** [adaptlearning/adapt_framework#1397]
Hi all,

I came across an issue yesterday where I had an Adapt course with a narrative in it with 3 slides. When I open the course on SCORM cloud, the window is defaulted to open in a medium size screen, but I need to enlarge the screen to view it in large for desktop. The narrative doesn't check off the first item as visited (because it's waiting for you to open the popup). Then when you resize to large, it doesn't `_isVisited` the current item until you go through to the second or third slide and back to the first to trigger it being visited.

Hope this makes sense.

Thanks

Ryan

**Comment by moloko** [comment]
sorry just realised that we duplicated this in #2100 - this should be resolved by the v3.0.0 release of Narrative
