### ISSUE TITLE
Hotgraphic graphic src shouldn't be required

### ISSUE THREAD

**Issue by bell87** [adaptlearning/adapt_framework#1401]
Hotgraphic `_graphic.src` property is required which doesn't pass validation when `_useGraphicsAsPins` is set to true.

**Comment by bell87** [comment]
Issue fixed in this PR https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/135

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/87f1b7c101a27564d683698a0d67864b52a47b9c
