### ISSUE TITLE
version must be valid css-class

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1402]
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/device.js#L192

make sue that versions are added as a valid css-class (no . as delimiters) so that they can be used in css for styling.

E.g. `Version-8.0` --> `Version-8-0`

**Comment by oliverfoster** [comment]
all the classes should be lowercase also

**Comment by lc-thomasberger** [comment]
this might break existing themes though @oliverfoster

**Comment by moloko** [comment]
done in ca59e7abe5f3a4e602de2d247aedc26e37c5f161
