### ISSUE TITLE
Open Adapt in new window

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1403]
One approach to fix the iOS iFrame bug is to use a custom launch.html that opens the Adapt course in a new window on iOS devices.

The main purpose of this issue is to discuss if we should support this in the core Framework. Collect possible limitations and approaches to include this feature.

Some topics to discuss:
- Localisation of content
- Configuration options (only iOS, mobile, all, ...)
- Support LMS integrations (same Window, new Window, ...)
- Entry level (launch.html, before Adapt loads, ...)

Once done, we should define requirements for the Implementation. 

Related issues: #585 #751 
Community Post: https://community.adaptlearning.org/mod/forum/discuss.php?d=180

**Comment by oliverfoster** [comment]
Review the launch.html

Perhaps behaviour similar to the language picker on startup

**Comment by moloko** [comment]
could you have a look at [adapt-launchNewWindow](https://github.com/cgkineo/adapt-launchNewWindow) to see if that meets your requirements?

**Comment by moloko** [comment]
[adapt-launchNewWindow](https://github.com/cgkineo/adapt-launchNewWindow)  should do the job in most instances, please feel free to reopen if you disagree
