### ISSUE TITLE
Omit plugin .less files from Grunt build

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1407]
When the grunt builds it only includes the plugins that are required - thus saving many selectors helping avoid the ie9 limit. 

But within the vanilla theme there are less files for many components, accordion.less, mcq.less, etc that are compiled even if that component is not included in the course, bloating the course css.

With regards to the grunt build, can we add a further level of filter on the theme less files to exclude the less that's not required?

I understand that this may require that the vanilla less files be renamed, for example, accordion.less be renamed to adapt-contrib-accordion/accordion.less

**Comment by oliverfoster** [comment]
keep an eye on the AT with this one

**Comment by brian-learningpool** [comment]
I've moved this to for consideration in the v3 epic.
