### ISSUE TITLE
grunt server-scorm not working

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1408]
The command does not open the browser as before and when you open the browser manually it doesn't track. Fix coming up...

**Comment by moloko** [comment]
we did have a similar problem before - see #1227 

do you think the fix for that might have caused this?

**Comment by moloko** [comment]
ah, looks like there's an `open:true` missing from the `spoorOffline bit`

**Comment by danielstorey** [comment]
I tried that but it only opened the normal index file and didn't track. I don't know if the grunt-contrib-connect package has been modified recently but it looks like the "open" property also accepts a string value as the file you want to open. I have submitted a PR.

**Comment by danielstorey** [comment]
I think it may have done as it only stopped working for me fairly recently. It automatically opens for server but not the server-scorm command. I looked at the the grunt-contrib-connect documentation and the only time a path property is referenced is for defining the base path within an options object. The same page states that open also takes a string value which overrides the default index file. Take a look and see what you make of it.
