### ISSUE TITLE
adapt-contrib-spoor: SCORM 2004 scores

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1413]
The scores shouldn't be restricted to 0-100 values as used in SCORM 1.2. Whilst this will probably remain the most commonly used scores, we shouldn't limit the wrapper to this.

**Comment by danielghost** [comment]
See https://github.com/adaptlearning/adapt-contrib-spoor/tree/issue-1413

**Comment by oliverfoster** [comment]
decided not to fix as current solution is ok for the moment

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/pull/151

**Comment by oliverfoster** [comment]
will need to:

pull in the min and max scores from config.json
~~sort out scoreAsPercentage stuff~~

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/8dac855711b397036685a78363c2b3ec216e5bf2

is that all that was needed i.e. can this now be closed?

**Comment by moloko** [comment]
@oliverfoster does this:
> pull in the min and max scores from config.json

still need doing?

**Comment by oliverfoster** [comment]
i think so. it looks like it would need to change here:

https://github.com/adaptlearning/adapt-contrib-spoor/blob/8dac855711b397036685a78363c2b3ec216e5bf2/js/adapt-stateful-session.js#L168-L170
