### ISSUE TITLE
Add text to navigation buttons

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1418]
There are places where we use `<button>` elements, e.g. in the header navigation.  Some functionality is represented by icons (such as the Language Picker) or a widget (such as Page Level Progress) where it would be beneficial to see some text while hovering over.  

I know this would only work on desktop, but it would be worthwhile in refining the user experience for people who might not be used to the user interface and is a common practice on sites, e.g. GitHub use it for the Fork, Star or Clone or Download buttons.

**Comment by oliverfoster** [comment]
https://www.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/  

can we find a design solution for this rather than using a technical one?

**Comment by oliverfoster** [comment]
@brian-learningpool can i change this issue to "add text to navigation buttons"?

**Comment by oliverfoster** [comment]
Removing from accessibility v3 as buttons have appropriate aria labels.

**Comment by oliverfoster** [comment]
duplicate of #2497
