### ISSUE TITLE
Assessment results not consistently marked as complete in mobile app

### ISSUE THREAD

**Issue by ryanrolds** [adaptlearning/adapt_framework#1419]
Encountered an issue in the Android WebView where assessment results after a text question would not consistently be marked as completed. After some investigating I determined that when the virtual keyboard is displayed the page scrolls the text box up (the results being the next component) was causing the inview event to fire, but the component was not yet visible. This resulted in the inview event listener being unbound, but the component not being marked complete. Relevant code:

https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/js/adapt-contrib-assessmentResults.js#L145

https://github.com/adaptlearning/adapt_framework/blob/2f43c2cdf9cfa073aba862879dd2cd224487b747/src/core/js/models/adaptModel.js#L102

My solution was to wrap the listener unbinding in an check that confirmed the model was complete, delaying the unbind until the inview is no longer needed.

**Comment by ryanrolds** [comment]
Pull request: https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/27

**Comment by brian-learningpool** [comment]
Resolved in https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/27
