### ISSUE TITLE
Inview expiration check causing issues with text completion in an Android WebView

### ISSUE THREAD

**Issue by ryanrolds** [adaptlearning/adapt_framework#1420]
Quick/flick scrolls in an Android WebView showing a text component + trickle was resulting in a inconsistent marking of the text component complete.

After a bit of debugging I tracked it down to a loop expiration check in the inview/onscreen library (https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L208). It appears that poor performance and possibly some trickery inside of the WebView VM was causing the expiration check to get hit, preventing the text component from being market complete.

I was able to resolve the issue by commenting out the check. From the code it looks like there is a 1500ms threshold with the expiration. What purpose does this check serve and is it possible that 1500ms is too short a threshold for some situations/device?

**Comment by oliverfoster** [comment]
1.5s is the length of time after you stop scrolling, clicking, touching, resizing or pressing keys that the library will continue to check all the inview/onscreen listeners. it is especially important that the library stops checking the placement of html tags relative to the view-port, as quickly as possible, as doing so tends to cause reflows in the browser - which leads to all kinds of fun side effects.

1.5seconds is a pretty reasonable length of time for a browser to callback a final scroll event (it even works in ie8).

May i suggest you create the plumbing for Adapt to allow it to change the 1500 value via the config.json?

Add a config option at this line called something like "checkingTimeoutMS":
https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L347
```javascript
        options: {
            allowScrollOver: true,
            checkingTimeoutMS: 1500
        },
```

Allow ``hasExpired`` to use the new config option:
https://github.com/adaptlearning/jquery.onscreen/blob/master/jquery.onscreen.js#L200

```javascript
        hasExpired: function() {

            var timeSinceLast = (new Date()).getTime() - loop.lastStartEvent;
            if (timeSinceLast < config.options.checkingTimeoutMS) return;
            
            loop.stop()
            return true;
        },
```


Get Adapt to pass the configuration through:
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/app.js#L131-L135

```javascript
        var allowScrollOver = (adaptConfig && adaptConfig._allowScrollOver === false ? false : true);
        var checkingTimeoutMS = (adaptConfig && adaptConfig._checkingTimeoutMS !== undefined ?   adaptConfig._checkingTimeoutMS || 1500);

        $.inview.config({
            allowScrollOver: allowScrollOver,
            checkingTimeoutMS: checkingTimeoutMS
        });
```

Setup that value to something larger:
https://github.com/adaptlearning/adapt_framework/blob/master/src/course/config.json#L36

```json
    "_inview": {
         "_checkingTimeoutMS": 5000
    }
}
```

Make sense?

**Comment by oliverfoster** [comment]
this seems to be fixed now.
