### ISSUE TITLE
Completing an assessment resulting in progress reported on different assessment

### ISSUE THREAD

**Issue by ryanrolds** [adaptlearning/adapt_framework#1421]
Encountered an issue where not yet completed assessments were getting `_subProgressComplete` set to 1 when another assessment was completed. 

After debugging I determined it was caused by isComplete being hoisted and not reset of false between processing of pages.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/4ffaab2f6f527c38091d53f12bd856c837373823 - thanks @ryanrolds
