### ISSUE TITLE
adapt-contrib-slider: Support decimal steps

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1423]
For example, it should be possible to set a range from 1.0 to 2.0 in increments of 0.1.  Doing this currently results in an unexpected UI (the numbers don't step in increments of 0.1) and inconsistent behaviour.

**Comment by brian-learningpool** [comment]
See https://github.com/adaptlearning/adapt-contrib-slider/pull/121

**Comment by moloko** [comment]
this will also require an update to adapt-contrib-spoor as it doesn't currently seem to be capable of storing/restoring decimal values in the slider when `_shouldStoreResponses` is enabled

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/fcf06cfa551f95737526398c7f22a40a83901e4e / Slider 2.1.4
