### ISSUE TITLE
adapt-contrib-tutor: Add class to indicate which plugin invoked Tutor

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1427]
Previously some code was added to add specific classes based on the question state, namely  `correct`, `incorrect`, and `partially-correct`.  

It might be useful to also pass a class through to indicate the component/extension which invoked the Tutor.  This would allow more granular control over the layout for theme developers, e.g. if feedback on a Slider should be shown differently to feedback on a MCQ.

**Comment by oliverfoster** [comment]
Just an "_id" or something more?

**Comment by brian-learningpool** [comment]
I was thinking it could maybe add a class composed of the model `_type` and the `_component` or `_extension` attribute, e.g.  `component-mcq`.

**Comment by oliverfoster** [comment]
sounds nice. can we do origin id also?

**Comment by brian-learningpool** [comment]
Yes, this would allow us to tweak styling on specific feedback instances.  Good thinking.

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt-contrib-tutor/pull/60

**Comment by brian-learningpool** [comment]
All outstanding PRs merged.
