### ISSUE TITLE
adapt-contrib-slider track/thumb not working in iOS

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1441]
Cannot tap track or drag thumb along track to set value. Labels function as normal however.

Tested on iPad running iOS 9.3.5.

**Comment by moloko** [comment]
OK so I can replicate this if I grab the current framework & plugins - but if I try latest Slider with a copy of the framework I downloaded just before the Adapt Meetup (so from around 25th Jan) it works fine. Which suggests it's something outside of Slider that has caused this.

**Comment by moloko** [comment]
OK think I've tracked it down... looks like its the switch to jquery v3 that's broken it. 

If you switch back to v2 it starts working again. 

Note that you have to stop and restart `$ grunt dev` if you do this, the watch process doesn't seem to pick up the change to scriptLoader.js (even though the command line output makes it look like it is doing so)

**Comment by moloko** [comment]
Could be https://github.com/andreruffert/rangeslider.js/issues/239 ?

**Comment by moloko** [comment]
fixed by reverting back to using JQuery v2.2.3 in https://github.com/adaptlearning/adapt_framework/commit/2d82eebe94ad38dee518d5f1c14df0d77eabca89
