### ISSUE TITLE
logging module: when logging to the console, use the matching console functions if available

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1444]
since many of the browser developer tools consoles support `.info`, `.warn` and `.error` methods on the `console` object, it would be good to redirect to these rather than just using `console.log` all the time. 

In particular, messages logged via `console.error` allow for the stack trace to be shown - so is currently is more useful than simply doing `Adapt.log.error`.

**Comment by moloko** [comment]
@oliverfoster also could be worth taking a look at [this](https://www.sitepoint.com/logging-errors-client-side-apps/) as there's some useful looking stuff in there

**Comment by oliverfoster** [comment]
nice, ta 👍

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/d383e75b018708a500d1776663238376fa4359b9
