### ISSUE TITLE
package.json devDependencies need to upgrade

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#1445]
1. grunt-concurrent
2. grunt-contrib-jshint
3. grunt-jscs
4. grunt-jsonlint
5. jshint-stylish
6. less
7. requirejs
8. time-grunt
9. underscore-deep-extend

**Comment by canstudios-louisem** [comment]
I this is being done the packages should be moved to `dependencies` from `devDependencies` as they are needed in production.

**Comment by brian-learningpool** [comment]
@canstudios-louisem, I've raised a separate issue for the point raised in your comment.
