### ISSUE TITLE
infinite attempts + assessment failed + scorm status

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1448]
* The assessment will have infinite attempts if the "requireAssessmentPassed" value is set - which isn't ideal, sometimes you want to allow someone to fail.

https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L52-L59 < need to remove these lines

* ``_reporting._onAssessmentFailed`` value is somewhat broken in the sense that you may have more attempts left to achieve your "complete/passed" criteria. only a last-attempt failure should be reported as such.

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-stateful-session.js#L130 < need to check for 0 attempts left before sending the ``_onAssessmentFailed`` value

This should make the ``config.json`` easier to read and the behaviour behind it more consistent

**Comment by moloko** [comment]
OK so part 1 is done in https://github.com/adaptlearning/adapt-contrib-assessment/pull/89

Part 2 will be a bit trickier as, at the moment, spoor isn't told whether all attempts have been used up. so need to have a bit of a think about how that would work, specifically wrt to when there are multiple assessments.

**Comment by moloko** [comment]
will also need to revert https://github.com/adaptlearning/adapt_framework/issues/1446

**Comment by oliverfoster** [comment]
i can take that if you need?

**Comment by moloko** [comment]
reverting #1448 or part 2 or the original issue?
