### ISSUE TITLE
bookmarking visible check error

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1452]
https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/js/adapt-contrib-bookmarking.js#L187

doesn't work as intended as ``:visible`` selector is a bit weird. https://api.jquery.com/visible-selector/

@moloko suggests changing to ``measurements.onscreen`` instead. which is calculated as detailed here > https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/inview.js#L467-L475

**Comment by moloko** [comment]
just giving my alternative version a try on a project first to see how it fares in QA...

**Comment by moloko** [comment]
Cannot remember what project I did this on now but I never heard back so assume it worked OK... just need to try and remember exactly how I changed it :-(

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/jquery.onscreen/issues/22

**Comment by oliverfoster** [comment]
fixed in above prs
