### ISSUE TITLE
adapt-contrib-assessmentResults: reference to non-existent function isComplete

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1454]
https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/27 added a reference to a function `isComplete` but there is no such function

**Comment by oliverfoster** [comment]
Oh dear.

**Comment by ryanrolds** [comment]
My bad. Sorry. Not sure how I missed that.

**Comment by oliverfoster** [comment]
I feel like that every day.
