### ISSUE TITLE
assessment redundant line

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1456]
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/assessment.js#L299

@LukaszGrela discovered

**Comment by moloko** [comment]
as `isPass` is initialised with a value of `false` on line 285, the ternary statement on line 299 is completely redundant since it will do nothing if `isPass === false`

**Comment by oliverfoster** [comment]
Ta @moloko

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/f0704ab6fd617652344a1f32116af3bf20851b28
