### ISSUE TITLE
issue with PLP in a SCORM object - completing a page in different sessions

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1457]
We (Kineo QA) keep running into a PLP bug where the indicator doesn’t fill in for a page if you complete it in two sessions – eg do half the components on a page, exit, re-enter, carry on – PLP for that page will only fill in 90% despite all the individual elements filling in. This usually rights itself by going to the menu (where applicable) and returning to the page

**Comment by moloko** [comment]
@kineotesting would you mind add this comment to #1327 as it's directly related to that?

**Comment by kineotesting** [comment]
now added to #1327
