### ISSUE TITLE
grunt minifies course and config json unintentionally in two tasks

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1461]
create-json-config and schema-defaults both inadvertently strip the whitespace from the course.json and config.json files making them unreadable.

https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/create-json-config.js#L37
https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/schema-defaults.js#L66

vs

https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/tracking-insert.js#L48-L49

This, rather irritatingly means that I can't read the json of the course or config files, but I can for articles, blocks and components.

**Comment by tomgreenfield** [comment]
I'd +1 for minifying them all. I've had many cases in the past where I was mistakely editing the build files instead of src.

**Comment by oliverfoster** [comment]
I think we should have a separate task off the back of the "build" collection to do that and not do it in these tasks.

**Comment by moloko** [comment]
done in 020ceb547bb57fc06d7537a29e43aefded8f73c6
