### ISSUE TITLE
Can't install adapt-cli on Mac OSX (missing gcrypt.h)

### ISSUE THREAD

**Issue by abhinayar** [adaptlearning/adapt_framework#1465]
Adapt CLI throws error during installation via Terminal on Mac OSX
Seems to be missing header file (gcrypt.h)

LIBTOOL-STATIC Release/openssl.a
CC(target) Release/obj.target/libssh2/vendor/libssh2/src/agent.o
In file included from ../vendor/libssh2/src/agent.c:40:
In file included from ../vendor/libssh2/src/libssh2_priv.h:140:
In file included from ../vendor/libssh2/src/crypto.h:46:
../vendor/libssh2/src/libgcrypt.h:
40:10: fatal error: 'gcrypt.h' file not found
#include <gcrypt.h>
         ^
1 error generated.
make: *** [Release/obj.target/libssh2/vendor/libssh2/src/agent.o] Error 1
gyp

ERR!
build error

gyp
ERR!
stack Error: `make` failed with exit code: 2
gyp ERR!
stack     at ChildProcess.onExit (/usr/local/lib/node_modules/adapt-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp
ERR! stack
at emitTwo (events.js:106:13)
gyp
ERR!
stack     at ChildProcess.emit (events.js:194:7)
gyp
ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp
ERR! System Darwin 16.1.0
gyp
ERR!
command
"/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/lib/node_modules/adapt-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release"
gyp
ERR! cwd
/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit
gyp
ERR!
node -v v7.7.2
gyp
ERR!
node-gyp -v v3.5.0
gyp
ERR! not ok

node-pre-gyp

ERR!

build error
node-pre-gyp
ERR!
stack Error: Failed to execute '/usr/local/Cellar/node/7.7.2/bin/node /usr/local/lib/node_modules/adapt-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release' (1)
node-pre-gyp ERR!
stack
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/adapt-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp

ERR!
stack
at emitTwo (events.js:106:13)
node-pre-gyp
ERR!
stack
at ChildProcess.emit (events.js:194:7)
node-pre-gyp

ERR!
stack
at maybeClose (internal/child_process.js:899:16)
node-pre-gyp
ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp
ERR! System Darwin 16.1.0
node-pre-gyp
ERR!
command "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/lib/node_modules/adapt-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/adapt-cli/node_modules/nodegit
node-pre-gyp ERR! node -v v7.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.7.2/bin/node /usr/local/lib/node_modules/adapt-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/local/lib/node_modules/adapt-cli/node_modules/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
/usr/local/lib
└── (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhinayar/.npm/_logs/2017-03-14T20_41_23_489Z-debug.log

**Comment by oliverfoster** [comment]
duplicate https://github.com/adaptlearning/adapt-cli/issues/68
