### ISSUE TITLE
Add contentEditable divs to native space elements in jquery.a11y.js

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#1470]
The jquery.a11y.js file defines a list of "native space elements". The space bar can only be used inside these elements.

We would like to add a CKEditor to the preview page (http://ckeditor.com/). CKEditors exist within div[contenteditable=true] elements, so we need to add these elements to the list of native space elements so that the space bar can be used inside the CKEditor.

Info on the contenteditable property: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

**Comment by oliverfoster** [comment]
+1
