### ISSUE TITLE
updates to router.js causing problems with our pageIncompletePrompt extension

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1472]
PR #1460 has unfortunately stopped our [pageIncompletePrompt extension](https://github.com/cgkineo/adapt-pageIncompletePrompt) from working

The problem's down to [this change](https://github.com/adaptlearning/adapt_framework/pull/1460/files#diff-4739c5071451feed517e8facdb02d756R42) in that `_isCircularNavigationInProgress` never actually gets set to `false` - it either doesn't exist, or it does but it's set to `true`. So the `if` block never gets executed any more.

The quick fix would be to revert this line back to what it was... @brian-learningpool was there any technical reason for this change or did it just seem a more robust check to you? 

I'm happy to look at ensuring `_isCircularNavigationInProgress` is properly defined and always set to either `true` or `false`, this probably requires a fair amount more testing though...

**Comment by moloko** [comment]
I also noticed that a couple of instances in `handleRoute` where `arguments` is being used instead of `args` - should all instances be updated to `args`?

**Comment by brian-learningpool** [comment]
Hi @moloko, the `_isCircularNavigationInProgress` was causing problems with the plugin route.  I think `_isCircularNavigationInProgress`, if it should be a boolean, for clarity should be be `true` or `false`.  I should have ensured that in the original PR.

The other calls in `handleRoute` referring to `arguments` could also use `args` instead.
