### ISSUE TITLE
Add _classes to Language Picker extension

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1475]
When styling courses the Language picker 'launch' window lacks any custom preferences, there is an option within the configuration to change the icon that appears by changing a class, can another text area be added to add a class for styling to be pulled through? 

The class would be appended to the `languagepicker` containing `div`.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-languagePicker/commit/eb026867b546ab5f626bc52bcb8617bc83a8e053
