### ISSUE TITLE
Improve readability of link

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1477]
The hyperlink added in https://github.com/adaptlearning/adapt_framework/pull/1411 doesn't look good:
![link](https://cloud.githubusercontent.com/assets/922987/24143997/92ab5f34-0e23-11e7-9511-6f25b4a0f556.png)

Suggest:
* Changing `https://www.adaptlearning.org/index.php/adapt-framework` to something user-friendly like `here`
* Styling the anchor for contrast

**Comment by moloko** [comment]
I agree, I think it should be the full link that's shown though so I would favour styling it nicely.

It would also be great if we could have a better link - https://www.adaptlearning.org/framework would be my preference - but that's beyond the scope of this ticket

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/ad323fae4e68e9133e19cc75863be87d4322fe54
