### ISSUE TITLE
adapt-contrib-spoor extension's tracking validation

### ISSUE THREAD

**Issue by aleciavogel** [adaptlearning/adapt_framework#1479]
If you make the  `_trackingId` of a block or the `_latestTrackingId` in the course.json something dumb like 346500, you're gonna have a bad time. Found this out the hard way this morning.

Now, I haven't dived into this too much yet since I'm on a deadline for completing this course for a client and don't have any time at the moment, but is it really necessary for the trackingId of the current course to be logged to the console as a series of hyphens? I didn't count, but after my JS console nearly crashed, I scrolled up and found myself with hundreds of thousands of hyphens in my log. It seems to appear in a line in my console that looks like `SCORM.data.set('cmi.suspend_data') value: {"lang":"en","a11y":false,"completion":"-01010","questions":"","_isCourseComplete":false,"_isAssessmentPassed":false}`. Specifically, it was the `completion` property that was going into overdrive (notice the hyphen in front).

As soon as I changed all block tracking ID values to 1 in addition to the course.json _latestTrackingId, my console was suddenly hyphen-free.

Obviously this isn't a super urgent issue as courses rarely go over 500 blocks, let alone hundreds of thousands of blocks, but I think this could be handled better.

**Comment by oliverfoster** [comment]
That seems a strange thing to do.
Why would you start at 346500?

https://github.com/adaptlearning/adapt-contrib-spoor#add-tracking-ids <

**Comment by aleciavogel** [comment]
It's a unique number, is it not?

**Comment by oliverfoster** [comment]
No. No it's not. It's the placeholder for the last digit of the tracking IDs representing the blocks in an adapt page. It's usually the block count +/-1 

What is it you're trying to achieve?

**Comment by aleciavogel** [comment]
RE: what I was trying to achieve... It was an action on my part with unintentional consequences. That's all. I added a component to the components.json file for testing something, entered a random number for the block's trackingID, and that's what goofed everything up.

You haven't addressed the main issue in my post. Regardless of which number I chose as this placeholder, what is the purpose of all the hyphens? Furthermore, why is it even possible in the first place to have so many hyphens that it crashes the JS console? 

This begs the following question: why do the tracking IDs have to be populated in advance? Silly little errors like the one I listed above could be avoided entirely by skipping this extra step during authoring.

You mentioned in your last reply that the trackingIDs are a logical sequence of numbers. Yes, there's a grunt task that can automatically assign trackingIDs... but it seems a little odd that I need to include a trackingID for each block object in the blocks.json file while developing a course when I can just set each trackingID to the same value (usually I choose 1) and then the grunt task renumbers them. Doesn't seem super DRY tbh.

**Comment by oliverfoster** [comment]
It does seem rather strange that we have to enter tracking IDs before replacing them now that you mention it. I'm sure we can fix that. I'll have to check what happens myself before I can propose a solution to it. It's never really come up before but   the process is clearly a step too long. It's a valid point.

The reason for the dashes is a whole long story, the short version of which is : "it's a human readable way of checking, saving and restoring block completion". The latest tracking id tells us how many characters are used to represent the same number of course blocks, one character per block. The number of dashes/characters directly relates to the last tracking id.
Does that make any more sense?

**Comment by moloko** [comment]
@aleciavogel the tracking ids **don't** have to be populated in advance. When you're setting up blocks.json you can just leave them out entirely and the grunt dev/build tasks will add them for you if they detect that the 'spoor' plugin is installed. 

Or you can leave them in and just let them be duplicate values; the tasks will correct any duplicates for you:
![2017-03-22 10_33_02-cmder](https://cloud.githubusercontent.com/assets/1249597/24193648/f3e17bb8-0eea-11e7-9413-018aa9e231dd.png)

Or you can choose to manage the tracking ids manually.

Dashes are used to indicate an unused tracking id. For example, if `_latestTrackingId` is set to `4` and block.json only uses 0, 1, 2 & 4 then the tracking string will be something like 000-0 to reflect that tracking id 3 is unused. This is to allow for situations when I build a course that initially uses all the tracking ids but once it has been live for a few months, has some content removed. This needs to be done in such a way that the existing tracking data in the LMS does not become invalid.

**Comment by oliverfoster** [comment]
@moloko that'd explain why it hasn't been an issue before, thanks for checking.

**Comment by moloko** [comment]
The reason we use trackingids is down to a combination of SCORM 1.2 only allowing 4KB of storage for tracking data - and the authoring tool generating quite long page/article/block/component ids, `589304f9606b604774d0e4d2`, for example. 

If we were to attempt to store that data in the LMS as-is, it would be place too constraining a limit on the length of course you could create that would track without errors under SCORM 1.2. 

So, whilst this mapping of ids to blocks isn't ideal in some respects, it _is_ good at minimising the amount of bytes needed to store the course 'session state' on the LMS.

**Comment by moloko** [comment]
@aleciavogel can I close this now?
