### ISSUE TITLE
Locking doesn't account for optional models

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1486]
This essentially means they can become mandatory.

**Comment by moloko** [comment]
@danielghost could you give a bit more background/detail on this one?

**Comment by danielghost** [comment]
Previously the locking condition was just skipping over any unavailable models, as these don't need to be included when working out if it they are included as a requirement for a particular model being locked. We should also skip over any of the models in the list which are optional, otherwise these become mandatory in regards to unlocking the model being checked.

**Comment by moloko** [comment]
@danielghost is this still relevant or can it be closed now?
