### ISSUE TITLE
adapt-contrib-spoor: questions.js doesn't restore model values to the correct data type

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1495]
the function `releaseData` is not explicitly converting `0` and `1` to `false` and `true` - so if you attempt to use strict equality when checking these (restored) values you get unexpected results.

**Comment by oliverfoster** [comment]
@moloko Do you remember which properties you were seeing restored incorrectly?
This may be fixed with https://github.com/adaptlearning/adapt-contrib-spoor/pull/190

**Comment by moloko** [comment]
@oliverfoster yes, it was - I think - [all of these](https://github.com/adaptlearning/adapt-contrib-spoor/blob/719eff50dfdfaae9c528f6911a486597e227ee03/js/serializers/questions.js#L147-L151)

**Comment by olivermartinfoster** [comment]
Cool. This should be fixed with that or then. :+1: ta
