### ISSUE TITLE
Add _classes to Notify 'push'

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1496]
The Handlebars template is missing the `{{_classes}}` property which the standard Notify has, see https://github.com/adaptlearning/adapt_framework/blob/master/src/core/templates/notify.hbs#L1.

Adding this would allow more control over the styling of `notify:push`.

**Comment by moloko** [comment]
done in fca05d5dc6e45efe96209e382b78052fb169bcd5
