### ISSUE TITLE
vanilla font - proposed additional icons

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1498]
Proposal that we should add the following icons to the core vanilla font.
![1b4a0ae6-1623-11e7-8df4-6cd37ba76fa9](https://cloud.githubusercontent.com/assets/1249597/24555416/faed491a-1628-11e7-98f6-78169378b298.jpg)

**Comment by moloko** [comment]
done in 9042fe32cbde2a7c4129e53bb6fae20dc2e1d43a
