### ISSUE TITLE
adapt-contrib-matching: can't click on arrow to select 

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1501]
User is unable to click on the arrow of the drop down box, which causes confusion as that is the place they assume you need to click!

v 2.1.1, using vanilla theme and box menu on new course.
latest framework and AT.

**Comment by moloko** [comment]
confirmed, even with the latest updates to the vanilla theme.

the `.matching-select-state` div (which contains the tick and cross) looks to be the source of the problem - it's being displayed initially even though there's nothing visible inside of it
