### ISSUE TITLE
Inconsistency in reporting of Internet Explorer class

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1504]
Internet Explorer 8 and 9 add a class of `ie` where as Internet Explorer 10 and 11 add a class of `Internet Explorer`.  

It might be best to standardise these?  My preference would be for `ie`.

**Comment by oliverfoster** [comment]
Agree. As an addition to the current classes at the moment.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/1349/files#diff-75a42229138a2ed8b53d97a3d1598089L137
 
This is where it got removed

**Comment by tomgreenfield** [comment]
It's doubtful we need to keep the `internet explorer` class since it only surfaced by mistake after the removal of that [line](https://github.com/adaptlearning/adapt_framework/pull/1349/files#diff-75a42229138a2ed8b53d97a3d1598089L137).

**Comment by oliverfoster** [comment]
Fair enough.

**Comment by brian-learningpool** [comment]
Merged in #1506.
