### ISSUE TITLE
Assessment behavoir on second attempt

### ISSUE THREAD

**Issue by martinhoudini** [adaptlearning/adapt_framework#1508]
I'm using Assessment, Assessment Results and Trickle in this, so no difficult stuff!

You can actually see the bug in the Adapt showcase itself! https://community.adaptlearning.org/demo2/index.html#/id/co-15

So the bug is:

When you do an assessment and comes to the end, to the assessment result - the first time you do it the process is:
Last question, trickle button "Continue" -> Block "So, how did you do? Let’s find out." -> click on trickle button "Continue" -> Result block is shown.

But if you click on "Retry Assessment" and do it all again, the process is:
Last question, trickle button "Continue" -> Block "So, how did you do? Let’s find out." and result block is shown.

**Comment by oliverfoster** [comment]
The "So, how did you do? Let’s find out." block is not part of the assessment so it doesn't get reset when the assessment does.
Try using the "_isResetOnRevisit": "hard" property on that block to see if that gives better results? (You will have the inverse problem: The block will always be reset when you visit the page, even if the assessment isn't.)

**Comment by moloko** [comment]
@martinhoudini any update on this? can we close this off now?
