### ISSUE TITLE
Issue with Adapt.offlineStorage introduced in v2.0.18

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1510]
While testing a course with the Language Picker extension enabled the adapt content gets stuck on loading screen.

Seems to be a problem with Adapt.offlineStorage

**Comment by moloko** [comment]
@ciaranlp small thing but if you make formatting changes, could you do that as a separate commit? when you do it all in a single commit it makes it hard to see what code you've changed because of all the formatting changes.
