### ISSUE TITLE
General accessibility fixes

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1513]
1. move all aria labels to helper style from hacked:

from hacked: 
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/accessibility.js#L200
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L830
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L1247
```handlebars
<div class="page-inner article-container" role="main" aria-label="{{_globals._accessibility._ariaLabels.page}}">

    	<div class="page-header">
    		<!--  etc  -->
    	</div>

</div>
<div class="aria-label relative a11y-ignore-focus prevent-default" tabindex="0" role="region">{{_globals._accessibility._ariaLabels.pageEnd}}</div>
```

to helper; 
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/accessibility.js#L119-L125
```handlebars
<div class="page-inner article-container">
	{{{a11y_aria_label _globals._accessibility._ariaLabels.page}}}

    	<div class="page-header">
    		<!--  etc  -->
    	</div>

</div>
{{{a11y_aria_label_relative _globals._accessibility._ariaLabels.pageEnd}}}
```

2.  fix helpers to include an ``_isActive`` check
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/accessibility.js#L119-L137
```javascript
            Handlebars.registerHelper('a11y_aria_label', function(text) {
                return '<div class="aria-label prevent-default" tabindex="' + (config._isActive ? "0" : "-1") + '" role="region">'+text+'</div>';
            });

            Handlebars.registerHelper('a11y_aria_label_relative', function(text) {
                return '<div class="aria-label relative prevent-default" tabindex="' + (config._isActive ? "0" : "-1") + '" role="region">'+text+'</div>';
            });

```

3. use these helpers where applicable:
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/accessibility.js#L127-L137

4. redo ```ComponentView.renderState``` so that it updates the ``.accessibility-state`` node contents rather than removing and replacing the node, also add ``accessibility._isActive`` check for that tab index

**Comment by chris-steele** [comment]
> redo ComponentView.renderState so that it updates the .accessibility-state node contents rather than removing and replacing the node, also add accessibility._isActive check for that tab index

Addressed in https://github.com/adaptlearning/adapt_framework/pull/1834

**Comment by chris-steele** [comment]
> use these helpers where applicable:
> https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/accessibility.js#L127-L137

@oliverfoster I will look at using a11y_attrs_heading as part of #1833, is that OK?

**Comment by oliverfoster** [comment]
@ryan-lynch is going to have a look at #1833 unless you've already finished it @chris-steele

**Comment by chris-steele** [comment]
@oliverfoster @ryan-lynch I'm already on it guys

**Comment by moloko** [comment]
done in d5dc91318fad2a851c1e5434e0074cf3056fb6f4
