### ISSUE TITLE
xapi trackable state saving + restoring on models

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1523]
* ``trackable`` model value / function returning an array of trackable properties - flat, no hierarchy
* ``getTrackableState()`` model function returns current model state as json filtered by ``trackable``
* ``setTrackableState(state)`` model function restores model state as filtered by ``trackable``, rejecting data which doesn't match
* ``triggerTrackableState()`` model function performs an ```Adapt.trigger("state:change", this.getTrackableState());```
* ```"state:change"``` will trigger batched and debounced when the model changes so as not to interfere with existing code

**Comment by oliverfoster** [comment]
ComponentModel:
```
getTrackableProperties: function() {
    return {
        _isComplete,
        _isInteractionComplete,
        _userAnswer
    };
}
```

QuestionModel:
```
getTrackableProperties: function() {
    return _.extend({}, _.result(ComponentModel.prototype, "getTrackableProperties"), {
        _isSubmitted,
        _score,
        _isCorrect,
        _attemptsLeft
    });
}
```

**Comment by oliverfoster** [comment]
GETSTATE:

Object notation
```javascript
getState: function() {
    var trackable = this.getTrackableProperties();
    var json = this.model.toJSON();

    var args = _.keys(trackable);
    args.unshift(json);

    return _.pick.apply(_, args);
}
```

Array Notation:
```javascript
getState: function() {
    var trackable = this.getTrackableProperties();
    var json = this.model.toJSON();

    var args = trackable;
    args.unshift(json);

    return _.pick.apply(_, args);
}
```

**Comment by oliverfoster** [comment]
* we need to consider moving the tracking ids to the components and updating spoor + grunt accordingly. tracking ids are a useful way for maintaining version compatibility with minor course updates over time, i think it would be silly to remove them, having said that. it'd be great if we could, but using a non-integer index (such as the _id) introduces more complexity
* spoor needs to also track presentation component ``_userAnswers``

**Comment by oliverfoster** [comment]
I've made the libraries @moloko suggested to tidy up the default inheritance and copy calls [here](https://github.com/adaptlearning/adapt_framework/pull/1524/files#diff-d0d36b72b61f2440cb1e0f735ae0cb8dR28) and [here](https://github.com/adaptlearning/adapt_framework/pull/1524/files#diff-6e6e38fd58137c9df66a8359a5a7d273R18):  

They're located at:  
https://github.com/cgkineo/backbone.controller.results  
https://github.com/cgkineo/underscore.results  

Further reading at:  
https://lostechies.com/chrismissal/2012/10/05/extending-objects-in-underscore/  
http://backbonejs.org/#Model-defaults  
http://underscorejs.org/#result

**Comment by brian-learningpool** [comment]
Regarding the change to the tracking ID values and the associated grunt task, how about if we just add a suffix to the tracking numbers for components?  For example, if a block has a `_trackingId` of 19, the first component in that block could have a `_trackingId` of 19.1,  the second 19.2, etc.?

This could maintain backwards compatibility for SCORM tracking at the block level.

**Comment by oliverfoster** [comment]
We would need to keep the running count for each block, a ```_lastBlockTrackingId``` per block, so that any later components would carry on indexing upwards. If you replace a component at index 1 tracking id 19, it'd have the same id as the one it was replacing, potentially screwing up any pre-existing saved data. It would need to be  ```block._trackingId+"."+(block._lastComponentTrackingId++)```

It might be more work to do 19.1, 19.2 etc than to move them up one?

**Comment by oliverfoster** [comment]
I've updated the comments above to reflect the implementation ^

**Comment by brian-learningpool** [comment]
That's a good point about the count per block, I was thinking (selfishly) of the authoring tool.

**Comment by oliverfoster** [comment]
After a conversation Brian and I agreed that ``_trackingIds`` can remain as is for spoor and xapi can use the ``_id`` attribute to track model states. This may mean that we move the ``_trackingId`` ``reset``, ``remove`` and ``insert`` behaviour into the spoor plugin and out of the grunt task.

**Comment by oliverfoster** [comment]
I think the PR is ready to roll @brian-learningpool  https://github.com/adaptlearning/adapt_framework/pull/1524

I would say, instead of having xapi record all the states but iterating through the models, you should probably listen to ```Adapt.on("state:change", function(model, stateObject) {});``` That way we're only saving and restoring the changes over time. The ``stateObject`` now includes the ``_id`` as discussed, so you can map up the states by id and send only changed states over xapi.
