### ISSUE TITLE
double call to app:dataLoaded

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1532]
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/app.js#L75-L87

@chris-steele was this intentional? you did it with the async code and it went by unnoticed. i'll remove if not.

**Comment by chris-steele** [comment]
How odd, yeah looks like the first instance can be removed as there's not much use having the event triggered prior to models being assigned to their collections.

**Comment by oliverfoster** [comment]
Aight. I'll remove them both in turn and see what's what. Off hand I'd say the second should be removed to keep the behaviour consistent with its prior state. I'll see what it breaks.

**Comment by moloko** [comment]
@chris-steele @oliverfoster just to remind you that one of you still needs to sort this out...
