### ISSUE TITLE
spoor exceeds cookie limit on scorm_test_harness

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1535]
url encoding inflates storage requirements and is unnecessary:

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/offline_API_wrapper.js#L220-L226

**Comment by moloko** [comment]
just to elaborate - what should be about 2KB of 'raw' data inflates to over 4KB of data when URL-encoded... so the cookie will simply stop storing any more data...

**Comment by chris-steele** [comment]
Just tagging another issue into this one: https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/offline_API_wrapper.js#L242 does quite a number on Base64 encoding at times :/

**Comment by oliverfoster** [comment]
:\ can you see which characters? I can probably change the alphabet to accommodate.

**Comment by chris-steele** [comment]
Just the '+' character. Patched 403291 by changing to use '-' instead and works just fine.

**Comment by oliverfoster** [comment]
done in the pr
