### ISSUE TITLE
Is it possible to duplicate a complete course?

### ISSUE THREAD

**Issue by anneseller** [adaptlearning/adapt_framework#1538]
Hi Everyone,

I have installed the Adapt Learning Framework and am having lots of fun building my first course. The information on the Wiki and the forums is a big help, but I can't find an answer to this question:

**When I am finished building the course, will I be able to duplicate it?**

In other words, does an adapt command exist whereby I can create a new course based on an adapt course that already exists in the same directory on my computer? (i.e. C:\Users...Documents\Test Course>adapt duplicate course "_name of the new course folder in the same directory to which the files should be copied_")

(This would allow me to be able to just change the multimedia and text in the duplicated course without having to change any of the structure.)

I tried copying all of the files and folders into a new folder, giving it a new name and then pointing to that directory in the command line before running "grunt build", but this seems messy and also doesn't work properly. Perhaps I just have to save my modified theme as a new theme and then copy the other files?

Since I am a newbie, I would really appreciate any advice you can offer!

Many thanks,
Anne

**Comment by oliverfoster** [comment]
Copy + paste the test course folder.
Sometimes the node_modules folder can be a bit of a pain. So if out have troubles with the node_modules, copy everything but the node_modules folder and rerun "npm install" again as you would've done originally.

**Comment by moloko** [comment]
Equally you can setup a new course using `$ adapt create course`, then delete the `src/course` folder from your newly-created course, then copy over the same folder from the original course.

If you installed any additional plugins, you will need to install them again for the new course.

Then just run `$ grunt build` on the new course.

**Comment by moloko** [comment]
If you changed the theme in the original course, just copy that over to the new course as well.

Glad to hear you're enjoying working with Adapt. If you have further questions, do pop over to the [Framework chat room](https://gitter.im/adaptlearning/adapt_framework).

**Comment by anneseller** [comment]
Many thanks, Oliver and Matt, for your quick replies! I will try the
workarounds that you've suggested. Have a good weekend! - Anne
