### ISSUE TITLE
How to remove adapt framework completely

### ISSUE THREAD

**Issue by Foresight16** [adaptlearning/adapt_framework#1540]
Hi all can anyone point me in the right direction to completing remove the framework and pre-requisits using Command Line.

Thanks

**Comment by oliverfoster** [comment]
I think... it's as simple as:

1. deleting the files for the course / framework
2. uninstalling adapt-cli  
```bash
$ npm remove -g adapt-cli
```

**Comment by Foresight16** [comment]
Thanks very much Oliver, I've gone down a rabbit hole somewhere and having some problems, I'm a bit new to all this. I installed the Framework first then Authoring Tool. Working on my first course using the AT and just cant seem to 'Preview' my course at all. Am I correct in saying that the Framework isn't needed to use the AT? Thinking of removing everything and starting on just the AT again.

**Comment by oliverfoster** [comment]
My above answer is for the Framework only. 

The AT downloads the Framework + all the bits needed by itself, you're right, you don't need to do that bit.

If you're trying to 'uninstall' the Authoring Tool the process of "just deleting" may be somewhat complicated by the mongodb database. I'm not sure if a fresh installation will overwrite an existing database or leave it alone, @taylortom might be able to help?

**Comment by Foresight16** [comment]
@taylortom and @oliverfoster any help would be greatly appreciated hit a dead end with my knowledge. Read multiple forums posts now and tutorials but can't seem to pin down why I can't preview the course??

**Comment by oliverfoster** [comment]
As it's specifically to do with the preview functionality of the Authoring Tool. Could you add an issue here > https://github.com/adaptlearning/adapt_authoring/issues  ?

There are almost two different teams working on either side - and you may get a quicker answer.
Can I consider this question resolved: **"How to remove adapt framework completely"** ?

**Comment by taylortom** [comment]
The adapt CLI's still a prereq for the authoring tool I believe (forget exactly what it's used for...).

To uninstall the AT, it's as simple as removing the source folder, and dropping the MongoDB (you'll beed to use either the mongo, or a GUI to do this).

You'll obviously still have any non-adapt prereqs installed (e.g. node, mongodb, ffmpeg etc.).

**Comment by oliverfoster** [comment]
Lovely. @Foresight16 did you ask about your broken preview in the Authoring Tool channels?

**Comment by oliverfoster** [comment]
I always forget to mention that there's also that chat room:
https://gitter.im/adaptlearning/adapt_authoring
And the forum:
https://community.adaptlearning.org/mod/forum/view.php?id=56
