### ISSUE TITLE
adapt-contrib-matching: styling and iframe issues

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1543]
as dropdown is in the body, not the select2 container, it can cause issues with both styling and iframe positioning.

there is a way to switch the behaviour.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-matching/commit/8f639fa213879c7e23e1befebde76d5dfa46db2a

**Comment by oliverfoster** [comment]
fix from https://github.com/select2/select2/issues/4063
