### ISSUE TITLE
Support for VH and VW units please

### ISSUE THREAD

**Issue by webb-nickj** [adaptlearning/adapt_framework#1544]
Can we get support for VH and VW units added into Adapt please?

At the moment inview seems to be 'quirky' when VH units are used. Possibly other issues to.

**Comment by moloko** [comment]
is this still relevant following the v5 updates?

**Comment by webb-nickj** [comment]
> is this still relevant following the v5 updates?

I'm afraid we're a bit out of touch with the more recent versions of Adapt. If you're happy this is no longer an issue then I'm happy to close the issue.

**Comment by oliverfoster** [comment]
it should be better - depending on the browser support. will close until a specific use-case arises.
