### ISSUE TITLE
Graphic component example.json

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1549]
The image in the example.json does not load, suggest replacing with a new one. Perhaps the Adapt logo?

https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/example.json#L14

**Comment by akshay-bhavsar** [comment]
@simondate can we use this :
https://github.com/adaptlearning/documentation/raw/master/04_wiki_assets/adapt_framework/adapt-logo_208x200.gif

**Comment by brian-learningpool** [comment]
@akshay-bhavsar, yes, we can go with that.

**Comment by akshay-bhavsar** [comment]
@brian-learningpool  shall I make the changes and raise the PR

**Comment by moloko** [comment]
@akshay-bhavsar yes please do, thanks

**Comment by akshay-bhavsar** [comment]
thanks.

**Comment by akshay-bhavsar** [comment]
Please review this PR: https://github.com/adaptlearning/adapt-contrib-graphic/pull/64

**Comment by moloko** [comment]
the `small` image doesn't load either...

**Comment by simondate** [comment]
Also, 208x200 doesn't really seem very large!

**Comment by akshay-bhavsar** [comment]
@moloko the source for small image isn't adapt logo.
we can also use large image source for small one

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-graphic/commit/98944a5a8a0940f568580e6dbcb8401093ea5c81
