### ISSUE TITLE
Allow navigation elements to be controlled via the JSON

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1555]
It seems that there's quite a few things to do with the nav buttons you can't currently change without editing the theme, which isn't ideal even for Framework users and particularly not for Authoring Tool users.

For example, one of our course builders commented:
> For example on one page modules where the home button is stuck at the top left and it’s not needed. You can’t turn it off without [front end developer] input, so would be good to configure it in the json

Also see [this forum post](https://community.adaptlearning.org/mod/forum/discuss.php?d=2070)

**Comment by oliverfoster** [comment]
We need a huddle on this. There are some fundamental bits about the navigation api that need sorting out.... i.e. there currently isn't one.

**Comment by moloko** [comment]
@oliverfoster definitely. there's also quite a lot of possible combinations of setup to consider as well I fear.

**Comment by barryo-learningpool** [comment]
From @oliverfoster: 

> We also need a left, right, center + order for the navigation bar.

**Comment by barryo-learningpool** [comment]
I'm happy to work on this if we can get some kind of spec going

**Comment by barryo-learningpool** [comment]
@oliverfoster I assume with left, right and center you mean where the navigation bar appears in the header?  

BTW, the only navigation buttons I've found so far are back, home and drawer toggle.  At the moment "Home" only seems to appear if the theme defines it (it is not in the core navigation.hbs). Have I got this right?

**Comment by oliverfoster** [comment]
I meant that the items in the navigation bar need a left, right, center + order + visibility.
I'm not so worried about the placement of the navigation bar.

It would be nice if we had an API for registering navigation bar items and its actions, much like the drawer. 
That API should include something close to:
* Allowing an extension to add and remove an icon
* Position the icon left, right or center
* Order the icon within its position
* Add an icon tool-tip
* Handle the icon's mouse events

**Comment by chucklorenz** [comment]
Some code to be had here:
https://github.com/cgkineo/adapt-backButton
https://github.com/cgkineo/adapt-homeButton

l'd also like to see navigation be constructed to make use of flexbox, now that we've abandoned legacy browsers.

**Comment by moloko** [comment]
closing in favour of #2589

**Comment by olivermartinfoster** [comment]
Have added these requirements to #2589
