### ISSUE TITLE
adapt-contrib-assessmentResults: hard reset

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1558]
Looks like the results component will always implement a hard reset which can affect the course progress should a user return to an assessment even if the assessment itself is using a soft reset.

**Comment by moloko** [comment]
see https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/46

**Comment by moloko** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-assessmentResults/commit/125ea41f5db3c8609a76866848c6e8f68ddfcfad
