### ISSUE TITLE
Grunt check for new files added

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1567]
If you add a new file grunt does not process it. Would it be possible to enable it to?

**Comment by oliverfoster** [comment]
probs. might need to use an alternative to grunt-contrib-watch. like https://github.com/Andy2003/grunt-contrib-watch-chokidar

watching is notoriously difficult as it isn't supported uniformly across platforms.

**Comment by simondate** [comment]
Hmm that's annoying. I always forget to restart grunt when I add a new less file or plugin and end up spending 5/10 mins working out why it isn't applying styling 😡

**Comment by oliverfoster** [comment]
that's why i made rub

**Comment by simondate** [comment]
I was having some issue with Rub where when I added a plugin it couldn't find it (even if I restarted it) unless I went into the plugins.js file and added it there. Thought it would be better to go back to grunt as it is what the Authoring Tool uses.

**Comment by oliverfoster** [comment]
you needed the -f flag to force it to rebuild, if you add a plugin older than the current build it won't rebuild.

**Comment by oliverfoster** [comment]
closed. issue with operating systems + grunt-watch

**Comment by oliverfoster** [comment]
closed. issue with operating systems + grunt-watch
