### ISSUE TITLE
adapt-contrib-trickle - finish button should navigate back when page complete

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1568]
Very minor enhancement but when you get to the end of a trickle-enabled page and the finish button pops up clicking it doesn't do anything. I suggest the default behaviour should be to navigate back.

Am happy to provide the code for this if the consensus is that this is a good idea - in which case please assign this to me. Otherwise just close the issue and I won't take offence :)

**Comment by oliverfoster** [comment]
Perhaps adding `@ancestor` to the relative strings would help solve this issue. Then we could do `@contentobject+1` for next and `@ancestor` for parent and `@ancestor+/-1` for grandparent

**Comment by oliverfoster** [comment]
Decided rather than to allow `@ancestor-1` to instead allow `@menu` or `@page`, which seem more relevant and easier to use
