### ISSUE TITLE
hot graphic: Enhancement request - ability to change pin graphic

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#1574]
It would be useful to change the pin graphic as often the default pin is not appropriate.

**Comment by oliverfoster** [comment]
see #1575 ```_useGraphicsAsPins```

**Comment by barryo-learningpool** [comment]
It seems it would be useful to change the pin icon itself rather than use the graphic. See below for an example.
![screen shot 2017-06-06 at 11 08 07](https://cloud.githubusercontent.com/assets/28761622/26824249/7b2b2436-4aa8-11e7-93bc-dfd01293df60.png)

**Comment by moloko** [comment]
done in [hotgraphic v4.2.0](https://github.com/adaptlearning/adapt-contrib-hotgraphic/releases/tag/v4.2.0)
