### ISSUE TITLE
hot graphic: Enhancement request - ability to hide pin graphic

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#1575]
It would be great to have the option to hide the pin graphic. The hotspots could be part of the underlying background graphic.

**Comment by moloko** [comment]
@paul-mediakitchen I think this is something you can achieve using the `_useGraphicsAsPins` option. For some reason, there's nothing about this in the README but there is [an example in example.json](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/example.json#L74-L161)
