### ISSUE TITLE
.block-inner { padding: 0; } causes Trickle to act strange

### ISSUE THREAD

**Issue by aleciavogel** [adaptlearning/adapt_framework#1581]
I had this problem mostly on mobile devices, but it has been encountered on desktop as well in a different course I was working on.

When the block-inner class has a padding of 0, Trickle acts up ([screenshots](http://imgur.com/a/6cr9M)). Particularly, the contents of the wrapper move up and won't scroll back into view until I click the "Continue" button. As soon as I changed the padding to 1px, everything magically went back to normal. This only seems to occur during step-locking on blocks, not when Trickle is being used to navigate from one article to the next.

**Comment by aleciavogel** [comment]
Here's a gif of the same bug on another course. Once again, changing block-inner padding to 1px solves this.

![wvi_questions](https://user-images.githubusercontent.com/11688080/26888732-2c6e75fc-4b69-11e7-92e9-dd1402a340d2.gif)

**Comment by guywillis** [comment]
Hi @aleciavogel 

Does the issue still occur in the latest version?
