### ISSUE TITLE
router.js _isCircularNavigationInProgress reset issue

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1582]
_isCircularNavigationInProgress doesn't reset when canNavigate is set to true.
this is was found by resetting an assessment twice in quick succession (see #1584 and #1585)

note: circular navigation is when a course changes the url when it's not allowed to, the url must be corrected.

**Comment by oliverfoster** [comment]
i missed a recheck of canNavigate which broke pageIncompletePrompt https://github.com/cgkineo/adapt-pageIncompletePrompt/issues/13

**Comment by brian-learningpool** [comment]
Code has been merged to `master`, closing issue.
