### ISSUE TITLE
Determining component type

### ISSUE THREAD

**Issue by barry-learningpool** [adaptlearning/adapt_framework#1587]
There currently doesn't seem to be any way to programmatically determine what category a component falls into i.e. presentation or question. It would be good to have a property in the bower.json which dictates this.

**Comment by tomgreenfield** [comment]
Have you not had any luck with `model.get("_isQuestionType")`?

**Comment by barry-learningpool** [comment]
Sorry, should have been clearer. I'm talking about externally i.e. within the authoring tool

**Comment by moloko** [comment]
@barry-learningpool this probably needs to go in as an authoring tool feature request first... then when the AT folks have agreed how best to do this we can log an issue for any amends needed on the framework side.
