### ISSUE TITLE
Page Level Progress percentage completion

### ISSUE THREAD

**Issue by bell87** [adaptlearning/adapt_framework#1588]
Can the default value for `_showPageCompletion` be set to false and update the help text to make it more informative. 

I was seeing some strange % completion on page load, which I tracked down to incrementing the `pageCompletion.nonAssessmentCompleted` value here: https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/master/js/completionCalculations.js#L50 
setting `_showPageCompletion` to false it fixed it. Might be clearer to have default value as false.

**Comment by moloko** [comment]
hi @bell87 - see #1327

**Comment by bell87** [comment]
hi @moloko that's great I'll close this duplicate then. Thanks
