### ISSUE TITLE
spoor: offline_API_wrapper - switch to using localStorage API for storing tracking data

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1592]
Despite the improvements made in v2.1.0 (see [#1535](https://github.com/adaptlearning/adapt_framework/issues/1535)) it's still quite easy to exceed the storage limits of cookies - I've got a course with 75 components - most of which are questions - with `_shouldStoreResponses` and `_shouldRecordInteractions` enabled and the 4KB cookie storage limit is being exceeded after answering just 10 questions.

Switching to the localStorage API will increase the amount of data storage available to at least 5MB.

**Comment by oliverfoster** [comment]
https://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by moloko** [comment]
also http://arty.name/localstorage.html

**Comment by moloko** [comment]
closing as there seems to be no appetite for doing this
