### ISSUE TITLE
Minor issues with Assessment and Assessment Results properties.schema

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1593]
Having taken a closer look at the Assessment recently I think there are a few minor changes which could be made to improve the ease of configuring it in the authoring tool.

- The ordering seems upside down (this may be due to the old issue where schemas were displayed in reverse order).  More advanced settings like Question Banks appear at the top, where as more commonly used and obvious settings like the pass mark are further down.
- Help text is frequently missing
- In several places the wording is not consistent, e.g. Assessment ID (on article) -> Assessment Name in Assessment Results component
- Typo in the banking help text - "This is a comma-separated list of numbers corresponding to the number of questions to be drawn from each identified ~block~ bank"
- 'Quiz bank ID' needs a min value set on the range i.e. it's possible to set negative numbers as the ID - this has a knock-on effect this this ID is used as an array index value when determining '_split'
- It may actually be best to remove any references to 'quiz'
- By default it makes sense to have the assessment as percentage based
- The "Block Count" should be set to an empty string (or -1 or 0) to show all blocks

**Comment by moloko** [comment]
do you want to just make changes in https://github.com/adaptlearning/adapt-contrib-assessment/pull/86 and https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/29 ?

**Comment by brian-learningpool** [comment]
I will @moloko -- thanks.

**Comment by moloko** [comment]
I think this is all done now?
