### ISSUE TITLE
contrib-narrative: Swiping on touch devices

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1596]
It seems like a more natural interaction for learners to swipe through images rather than pressing a button on touch based devices.

**Comment by brian-learningpool** [comment]
I wonder should we add something like [HammerJS](http://hammerjs.github.io/) to core to facilitate this?

**Comment by simondate** [comment]
I just tried HammerJS on my Android phone and performance was pretty poor (1s delay). Is there a better library to use?

Is there any other components that could use the mobile events treatment?

**Comment by brian-learningpool** [comment]
AlloyFinger looks promising.  I believe there's a JQuery UI Touch Punch library too.  I can't really say at the minute what's better though.

Narrative is the core component most obviously missing gestures.

**Comment by brian-learningpool** [comment]
@simondate, I brought this up on this morning's framework call and the consensus was to go with JQuery Mobile's touch events.

**Comment by simondate** [comment]
Cheers @danielstorey . I'll be happy to work on actually implementing next week.

**Comment by brian-learningpool** [comment]
This is already implemented in https://github.com/adaptlearning/adapt-contrib-narrative/pull/174.

**Comment by oliverfoster** [comment]
@danielstorey would you be able to add the appropriate event listeners to the narrative to close this ticket?
