### ISSUE TITLE
contrib-slider: Issues in RTL courses

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1597]
Slider component settings - Scale: 1-5 Correct answer: 3.

* Resetting the component positions the slider to 5 instead of 1. 
* Clicking the slider area itself does not move the scale when I attempt to jump directly from 1-5 or 5-1, 2-4 or 4-2.

**Comment by sarveshwar-gavhane** [comment]
probably if this PR's gets merged https://github.com/adaptlearning/adapt-contrib-slider/issues/119 and  https://github.com/andreruffert/rangeslider.js/pull/245 resolved this issue.
remember https://github.com/adaptlearning/adapt_framework/issues/1318 issue

**Comment by moloko** [comment]
good point @sarveshwar-gavhane I had completely forgotten about that! @ryan-lynch could you see if the changes in adaptlearning/adapt-contrib-slider#119 solve the problems for you?

**Comment by ryan-lynch** [comment]
Hi @moloko - it appears to solve the majority of issues, however after resetting the component, clicking on the numbers no longer moves the slider.
