### ISSUE TITLE
adapt-contrib-media: update media:stop

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1598]
* on play trigger media:stop  ```onMediaElementPlay: function() { Adapt.trigger("media:stop", this); }```
* pass view to media:stop   ```Adapt.trigger("media:stop", this);```
* check if current view on media:stop   ```onMediaStop: function(view) { if (view.cid == this.cid) return; }```
* provide flag for trigger media:stop on play behaviour ```_stopOtherMediaOnPlay```

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-media/commit/fda9355b690280d1209782d134bcd5673a5aa85f
