### ISSUE TITLE
accessibility config: remove _shouldSupportLegacyBrowsers

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1599]
As far as I'm aware this setting is only applicable to IE8 so can be removed; as can any related code in accessibility.js

**Comment by AaronmcL** [comment]
Hi @moloko, would you like setupLegacy(), setupLegacyFocusClasser() and removeLegacyFocusClasser() removed?

**Comment by moloko** [comment]
@AaronmcL yes please

**Comment by moloko** [comment]
`_legacyFocusElements` and `revertLegacy` look like they can both go too

**Comment by akshay-bhavsar** [comment]
PR : https://github.com/adaptlearning/adapt_framework/pull/1624
