### ISSUE TITLE
Remove legacy CSS code for IE8 hack

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#1614]
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/less/legacy.less#L1
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/less/legacy.less#L18

**Comment by akshay-bhavsar** [comment]
@sarveshwar-gavhane 
We can removed the legacy file for this?

**Comment by sarveshwar-gavhane** [comment]
PR : https://github.com/adaptlearning/adapt_framework/pull/1626

**Comment by moloko** [comment]
#1626 seems to be broken, there's no source repository
