### ISSUE TITLE
Loading of pages with many articles/blocks/components causes many document redraws/reflows

### ISSUE THREAD

**Issue by ryanrolds** [adaptlearning/adapt_framework#1618]
Due to `adaptView.render()` using delay to separate rendering of the parent from the rendering of children (in `postRender()`) there is room for the browser will update the DOM causing a reflow with just about every child. On mobile devices this can greatly increase load times on large pages. The solution is to render as much as possible in to a [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment) before appending the document fragment (in this case the page element) to the main document.

PR #1617 shows how this can be done at the page level. To obtain the full benefit the rending of articles/blocks/components would also need to be adjusted to append to the DocumentFragment.

**Comment by oliverfoster** [comment]
Looking at the code (and from some experience with documentfragments) I think you could probably do this on the other side of the loading.

i.e. don't append to body until appropriate time > https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/router.js#L175

as far as i understand it, adding to a detached node doesn't cause reflows etc, so there isn't any need to add document fragments etc.

**Comment by ryanrolds** [comment]
Oh good catch. That is much better then trying to plumb it through all the levels. I was trying to do it what I thought was the top of the branch/page - that looks like a much better location.

**Comment by oliverfoster** [comment]
Might need to add a "attach me to my parent" event, or such so the parent knows when to act... but yea, might end up being cleaner?

**Comment by ryanrolds** [comment]
I will adjust my PR and test that approach. Thanks.

**Comment by ryanrolds** [comment]
@oliverfoster PR adjusted. I profiled the undelayed vs delayed attachment and I'm seeing signifciatly fewer redraws/reflows with the delayed approach. I didn't noticed any issue when testing. Pages load and change as expected.

**Comment by oliverfoster** [comment]
cool, contrib-media is usually the worst. it'd be worth testing this in ie8 to see if we want to hold off committing until the v3 release. can i suggest you make sure to test a page with particular attention to the media component?
the sequence of cascades is important here. preRender is not expected to be in the dom, render neither, but postRender is often used to measure sizes and the "ready" events are usually after postRender and imageready. so this may be a bit late in the cycle to add the page to the dom, it might need moving back a bit? i'll try and test with some slightly more complicated extensions, see what happens.

**Comment by ryanrolds** [comment]
Good points. You may be right an additional phase/event may be needed between render and postRender.

**Comment by ryanrolds** [comment]
Looking at the demo course the repo generates contrib-media with a video looks fine. The images shows up and the video plays. I do see an issue with the narrative component and the slider. Later in the week I will address those issues. If a new events is needed I will add them.
