### ISSUE TITLE
adapt-contrib-vanilla: page level progress navigation bar does not support rtl

### ISSUE THREAD

**Issue by dasistwas** [adaptlearning/adapt_framework#1623]
Page level progress bar fills up from left to right instead from right to left, when course is set to rtl.
![page-level-progress-bar-rtl](https://user-images.githubusercontent.com/1620975/27648835-26b40af0-5c30-11e7-991e-d3b34cf93d18.png)

**Comment by dasistwas** [comment]
Fixed in:
https://github.com/dasistwas/adapt-contrib-vanilla/commit/127654c8764f9157f2b9de9bca23c4b1a371d8bd

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/87d2e0ee97e8ec01e189c89663d4f47b6fd42b93
