### ISSUE TITLE
Narrative navigation buttons jump twice after a single click in Chrome on Android

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#1628]
Clicking on next and previous jumps two slides at a time. When I log inside `onNavigationClicked`, I get multiple calls, as shown below:

![blob](https://user-images.githubusercontent.com/13656761/27787822-1d0d4fb4-5fde-11e7-9b77-ee9f06541e34.png)

I think this is something to do with passive events in the latest versions of Chrome: https://www.chromestatus.com/features/5093566007214080

**Comment by chetan-hajare** [comment]
Hi @andrewhosgood 
I tried to replicate the above issue at my end, but it couldn't replicate. I tested the framework 2.1.3 on Android 7.0.0 using Chrome version 59.0.3071.125.
Can you please elaborate the issue more?

**Comment by andrewhosgood** [comment]
I think this must have been an error on my part - sorry!
