### ISSUE TITLE
adapt-contrib-assessment: Limit '_quizBankID' to >= 0

### ISSUE THREAD

**Issue by barry-learningpool** [adaptlearning/adapt_framework#1630]
Since this ID is used as the position in the '_split' attribute, it cannot be less than 0. This should be limited with a range validator and editor attributes

**Comment by ryan-lynch** [comment]
PR here:  https://github.com/adaptlearning/adapt-contrib-assessment/pull/93

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/3b1cf728a7b0586955e7867c2fc61b1c4889ffc2
