### ISSUE TITLE
grunt: post compile minification

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1634]
Minify all code in libraries that isn't already minified (these will be identified by being called *.min.js), offline_API_wrapper.js, templates.js and scriptLoader.js

**Comment by tomgreenfield** [comment]
As we're doing this, reckon we could minify the JSON too?

**Comment by barry-learningpool** [comment]
Absolutely @tomgreenfield , should I raise a separate issue or is it cool to do it as part of this one?

**Comment by tomgreenfield** [comment]
Happy for it to be included here 👍

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/e018fc5f91ebbefac902c73fb8dbbe25faf00c80
