### ISSUE TITLE
Update Bookmarking default text for Prompt Message 

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#1639]
The default text for the Prompt Message in the Bookmarking extension is "Bookmarking"

I would like to suggest the default is changed to something like the following:

"Would you like to return to where you left off?"

At least then if someone doesn't configure the settings it will still display nicely.

**Comment by moloko** [comment]
@paul-mediakitchen good spot, here you go: https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/29

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-bookmarking/commit/bc644054ba490604964b2940e6ce9a036ed3b42b

**Comment by paul-mediakitchen** [comment]
Thanks Matt - much appreciated.
