### ISSUE TITLE
Disabled NotifyView Esc keypress when accessibility is inactive

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1644]
Looks like a faulty condition allows the <kbd>Esc</kbd> keypress to still be setup when accessibility is not active.

**Comment by oliverfoster** [comment]
esc has two different uses. for accessibility it means "go to the top" for non-accessibility it means "close modal"

**Comment by danielghost** [comment]
Why do we want it to close the popup when accessibility, including the keyboard, is not enabled? The reason I found this was due to a video being shown in a popup, which could go fullscreen via the controls. In addition to exiting fullscreen mode, <kbd>Esc</kbd> also closed the popup.

I suppose you could make the same argument about closing fullscreen mode for videos, but that is a fairly standard user control that probably falls outside of accessibility, whereas I am not sure closing a model popup is.

**Comment by moloko** [comment]
> Why do we want it to close the popup when accessibility, including the keyboard, is not enabled?

For the reasons given in #938 

> The reason I found this was due to a video being shown in a popup, which could go fullscreen via the controls. In addition to exiting fullscreen mode, <kbd>Esc</kbd>also closed the popup.

OK I see where you're coming from now - yes, that's definitely a problem. The solution would be to have notifyView hook into the new `media:fullscreen:enter` and `media:fullscreen:exit` events that were added in v2.1.0 of adapt-contrib-media.

**Comment by oliverfoster** [comment]
might just need to block the esc key when fullscreen is entered and re-enable when exited. just two event listeners, a boolean flag ```this._isInFullscreen``` and a return statement up the front of the esc key event handler?

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-media/blob/master/libraries/mediaelement-fullscreen-hook.js < events in question

**Comment by oliverfoster** [comment]
@ryan-lynch to take this

**Comment by ryan-lynch** [comment]
I'm leaving this ticket as it seems to be a non-issue. Adapt does not currently have any support for displaying a media component within a popup.
