### ISSUE TITLE
AssessmentResults: Feedback Text and Retry Text should be TextArea

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1646]
Currently inputType is set to text. Better editing experience with TextArea.

https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/properties.schema#L51
https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/properties.schema#L73

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessmentResults/commit/2919720bcd6547c40cc15bc47f13760a343cda15
