### ISSUE TITLE
Documentation for _onScreen needed

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1652]
See https://github.com/adaptlearning/adapt_framework/issues/1100

Currently the only explanation for how this works is in the `help` property of the various core .schema files

Additionally this property is missing from the framework's versions of the core .schema files. Even though this doesn't cause any problems (as the framework only needs to know about 'translatable' properties) it would be better if they were included for consistency.

**Comment by moloko** [comment]
> Additionally this property is missing from the framework's versions of the core .schema files

#1812 resolves this

**Comment by guywillis** [comment]
First stab at documentation below (though not sure where this should sit).

<hr>

**\_onScreen** (object): The onScreen object that contains values for **\_isEnabled**, **\_classes**, and **\_percentInviewVertical**. The **\_onScreen** feature is best used with **blocks** and **components** though it can also be used with **contentObjects** and **articles**.

**\_isEnabled** (boolean): Turns **_onScreen** functionality on and off. Acceptable values are `true` and `false`.

**\_classes** (string): CSS class name to be applied to the location that **\_onScreen** is attached to. The class name is responsible for attaching the animation, and any associated styling required, to the element and must be predefined in one of the Less files. The standard values found in Vanilla's `_animations.less` are `fade-in`, `fade-in-top`, `fade-in-bottom`, `fade-in-left`, and `fade-in-right`. The direction in each of the class names defines the animation start point, e.g. `fade-in-right` states that the animation fades in from right to left until the element sits within its natural position.

**\_percentInviewVertical** (number): This value determines the percentage on screen the element must be before the animation is triggered. The default value is `33`.

**Comment by guywillis** [comment]
Documentation added to https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes
