### ISSUE TITLE
Favicon missing from preview 

### ISSUE THREAD

**Issue by canstudios-ashu** [adaptlearning/adapt_framework#1654]
404 appears when previewing content, unable to find the favicon.

**Comment by moloko** [comment]
Adapt doesn't specify a favicon anywhere. 

It seems Chrome always tries to load one from the server and so you'll always get a 404 in Chrome when you open the developer tools.

You could suppress it by adding 
```html
<link rel="icon" href="data:;base64,iVBORwOKGO=" />
```
to index.html in the core framework, the version in spoor and main.html and scorm_test_harness.html but that seems like quite a faff to get rid of a 404 error in just one browser that only appears if you're previewing with the developer tools open ;-)

**Comment by canstudios-ashu** [comment]
I never knew that about chrome! Thanks for the quick reply - is there a particular reason there isn't a favicon in the preview, such as the one used in the authoring tool?

**Comment by moloko** [comment]
No, not particularly.
