### ISSUE TITLE
Slider Component - feedback configuration

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1658]
On other question components there is the ability to hide feedback by setting **Display Feedback** to **False** this is not the case with slider component. 

This should be added to Slider Component.

**Comment by moloko** [comment]
I think that it just needs adding into properties.schema, example.json and README.md

It's also missing from example.json for all the other question components (MCQ, GMCQ & TextInput)

And missing from the README for MCQ and GMCQ

If you do a PR for Slider I'll sort out the others

**Comment by moloko** [comment]
PR here: https://github.com/adaptlearning/adapt-contrib-slider/pull/124

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/e0650c15ddc7c6ad82d6e80abfb339fdc00137ac
