### ISSUE TITLE
adapt-contrib-slider: doesn't fully reset when previously answered correctly

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1662]
`_isAtLeastOneCorrectSelection` remains true when returning to a previously correctly answered slider. This causes the wrong marking and feeback to be displayed.

Additionally, this could probably do with a general tidy up and renaming of attributes to align it more with other question components.

**Comment by chetan-hajare** [comment]
Hi @danielghost I am looking into the issue but could not replicate. Could you please elaborate it more or steps to produce the issue?

**Comment by moloko** [comment]
was duplicated by #1895 and fixed in [v2.2.0](https://github.com/adaptlearning/adapt-contrib-slider/releases/tag/v2.2.0)
