### ISSUE TITLE
adapt-contrib-textInput has no demo.gif

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1663]
there's a link to one (https://github.com/adaptlearning/documentation/raw/master/04_wiki_assets/plug-ins/images/textInput01.gif) in the README but it's a 404

**Comment by sarveshwar-gavhane** [comment]
@moloko could you please close this issue ?

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/documentation/commit/137c61baa09e3678cdd0b28d40b924498f6ed33e
