### ISSUE TITLE
adapt-contrib-trickle: block defaults are disabled in AT

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1672]
The example json states that `_isEnabled` and `_button._isEnabled` both default to true.

In the framework this is correct, meaning I can set `_isEnabled` on the article, leave out trickle settings on blocks and the extension just works.

However, when using the Authoring Tool, block defaults are false, meaning that both have to be manually enabled on each block in order for trickle to work.  This is both time consuming and inconsistent with the documented settings.

**Comment by kineopete** [comment]
The change requested in this ticket keeps cropping up as a source of aggravation for authoring tool users. I can see why we made the change, but as Simon Date points out here - https://github.com/adaptlearning/adapt_authoring/issues/1803 - full step locking of blocks is only one possible way of using Trickle, and almost certainly not the most common one.

The best fix remains this - https://github.com/adaptlearning/adapt_authoring/issues/1505 - but until the authoring tool team can get round to it please can we change the defaults back as a quick fix?

**Comment by moloko** [comment]
@kineopete see https://github.com/adaptlearning/adapt-contrib-trickle/pull/92
