### ISSUE TITLE
 adapt-contrib-narrative (Accessibility Issue)

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1673]
Narrative component - You may need to get into Jaws to see this one for yourself. If you tab through the component you can get though all of the items, but after you've viewed the last item, the tab order takes you through all of the alt text for all graphic items before it completes. The accessible users asked why are they going through this again they already went though this content. They were confused. I am wondering if it is in the narrative-slider clearfix - it is showing the alt text again, but in the code we have aria-hidden.

![screen-shot-2017-07-17-at-5 15 40-pm](https://user-images.githubusercontent.com/15389177/28321699-85c28fd0-6b99-11e7-8fc1-41247e29b39a.png)

In addition, it appears that all of the body text in most if not all components get repeated twice. When tabbing - text is repeated between paragraphs and at the end of your text. And, titles mention that they are clickable.

**Comment by oliverfoster** [comment]
@mldaq could you test the above pr?
