### ISSUE TITLE
add _globals._accessibility._ariaLabels.home ariaLabel

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1677]
Not seeing an aria-label global setting for the home button in the authoring environment. - _globals._accessibility._ariaLabels.home

**Comment by moloko** [comment]
@mldaq there's no reference I can see anywhere in the framework to `_globals._accessibility._ariaLabels.home`

I think mostly when people want a home button instead of the back button they just change the value of `_globals._accessibility._ariaLabels.previous`

**Comment by oliverfoster** [comment]
is this an issue that still needs solving?

**Comment by moloko** [comment]
closing due to long radio silence
