### ISSUE TITLE
adapt-contrib-media: _preventForwardScrubbing only works on first click of the scrub bar

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1681]
The '_preventForwardScrubbing' feature only works on the first click of the scrub bar. If you click the scrub bar a second time towards the end of a video it lets you jump to that point.

Logging the 'maxViewed' variable in the console on the 'onMediaElementTimeUpdate' function shows the variable is set to the point you first clicked on the scrub bar - so then when you click on the scrub bar a second time it allows you to jump to that position.

**Comment by moloko** [comment]
Just had a little test of this and can replicate, seem to be to do with the amount of time between clicks i.e. I can double-click the seek bar and, more often than not, that will cause it to seek forward to that point on the second click.

**Comment by oliverfoster** [comment]
this is an unresolvable known issue as far as i can tell
