### ISSUE TITLE
adapt-contrib-matching: error highlighting broken in v2.1.1 in Firefox

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1682]
the change made in https://github.com/adaptlearning/adapt-contrib-matching/pull/101 to move the select2 dropdown from where it was sitting outside of the `.wrapper` and into the select2 element has broken the display of the error outline:
![matching_error_outline_broken](https://user-images.githubusercontent.com/1249597/28429713-8ddaf7b0-6d75-11e7-96b2-b07445214105.png)

It seems that the dropdown element has a really odd size and position - particularly when closed - which is causing the error outline to be a really odd size.

After a bit of experimentation I discovered that changing the `.error` css from:
```css
outline: 1px solid @validation-error;
```
to:
```css
border: 1px solid @validation-error;
```
fixes it - but does result in a slight shift of the page content when the class is applied, which was why [I was asked to change](https://github.com/adaptlearning/adapt-contrib-matching/pull/102#pullrequestreview-34792460) from `border` to `outline` during code review... 

Unless anyone can think up a better fix then switching back to `border` might be the best solution?

**Comment by tomgreenfield** [comment]
Quick note for anyone testing this: I can only replicate in Firefox.

**Comment by tomgreenfield** [comment]
Box shadow?
```css
box-shadow: 0 0 0 1px @validation-error;
```
Note: may want to target Firefox only since it's not supported in IE8.

Reference: https://stackoverflow.com/a/15077889.

**Comment by moloko** [comment]
@tomgreenfield thanks for the info, very useful

how about this? https://github.com/adaptlearning/adapt-contrib-matching/pull/106

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-matching/commit/987b5fdb3ae8f7ed313bbd1ea30a7fa343b9bd63
