### ISSUE TITLE
Should adapt-contrib-boxMenu version be v2.1.0 (not v2.0.6)

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1686]
...to reflect new dependency on v2.1.0 of framework?

**Comment by moloko** [comment]
maybe... we're kinda getting the hang of when to change what. could you be more specific about why you think it should be 2.10?

**Comment by chris-steele** [comment]
Just with the adapt-cli update task, I was testing with framework 2.0.18 and it seemed like i should be able to specify a semver like ~2.0.5 and expect patch-level changes to correspond with patch level changes to the framework, but of course 2.0.6 is a patch level change to the menu that requires a minor version change in the framework. I'm no authority on this though, hence the question!

**Comment by moloko** [comment]
it's a perfectly reasonable question... I was just interested in getting a more detail as to why, with the intention of drawing up a list of rules as to what sort of change triggers what sort of version number update.

there won't ever be a direct correlation between framework version and plugin version though.. it just so happens that at the moment quite a few match; the only reason for that it that it was only in June we started trying to make an effort to stick to semver-style versioning - prior to that we pretty much just always incremented the last number of the version regardless of what changes had been made :-(
