### ISSUE TITLE
adapt-contrib-blockslider - content height

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1687]
The height does not seem to auto adjust based on the content being viewed. This leaves a large white space (or background) between the content in the block slider and the next content on the page. Is there a way to set this to have the article height adjust to the content in the block?

**Comment by simondate** [comment]
@mldaq This isn't a core extension. You should create your issue here: https://github.com/LearningPool/adapt-contrib-blockslider/issues

**Comment by oliverfoster** [comment]
or here: 
https://github.com/cgkineo/adapt-articleBlockSlider

**Comment by moloko** [comment]
@mldaq if in doubt, look in bower.json where there _should_ be an 'issues' property that has a URL for where you can log issues.

closing due to this not being a plugin that is maintained by the core team

**Comment by mldaq** [comment]
@moloko - sorry, thanks.
