### ISSUE TITLE
adapt-contrib-blockslider | Trickle Issue

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1689]
When using the blockslider with Trickle there is an issue with the continue button showing up when you are on the second to last block - if you are using components that do not require input (graphic, text). If you look at the progress bar it also shows that all items in the block slider are complete - even though you have not view the last item. We've also noticed that if your last block contains a component that does require an interaction and Trickle is set where that component has to be completed than it appears to work fine.

**Comment by chetan-hajare** [comment]
Hi @mldaq the Trickle extension is used when the content author wants a single block to be viewed restricting the next blocks i.e. page won't scroll until the current block gets completed. Resolving this issue might create dependencies on each other. 
Suppose if we implement functionality similar to trickle within blockslider extension without using trickle extension, would it be good? For e.g. the next arrow button and the tabs would be disabled. On completing the current block/component, the next arrow/tab would get enabled for that block.
Your suggestion will be helpful in resolving the issue.

**Comment by moloko** [comment]
TBH this isn't really the fault of Trickle or anything in core Adapt (except inasmuch as the current setup of Adapt doesn't allow for something like ABS to be built in easily).

@mldaq if this is still a problem could you log an issue [here](https://github.com/cgkineo/adapt-articleBlockSlider/issues/new) and one of the Kineo devs can support you with a workaround for this?

**Comment by mldaq** [comment]
@moloko - added the issue on the Kineo side.
