### ISSUE TITLE
Sample course does not render inside IFRAME on IE 9

### ISSUE THREAD

**Issue by AaronmcL** [adaptlearning/adapt_framework#1690]
It's throwing this error in the console while the page gets stuck on the loading screen:
`Object doesn't support property or method 'apply'`

I think it's coming from the `_addToConsole` function as if I add a try-catch on the call to `console.log.apply()` the course renders fine.

**Comment by brian-learningpool** [comment]
This is actually already resolved in https://github.com/adaptlearning/adapt_framework/pull/1612.
