### ISSUE TITLE
adapt-contrib-trickle/adapt-contrib-pageLevelProgress (PLP) interaction

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1691]
There is a general event order issue when these two extensions are used together. It is possible for the user to open PLP before trickle has finished manipulating the visibility of content. This can mean that items in PLP are incorrectly disabled. A simple solution that has been employed is to listen for `_isVisible` changes:

`this.listenTo(this.collection, 'change:_isVisible', this.render);`

**Comment by moloko** [comment]
is this still relevant @chris-steele ?
