### ISSUE TITLE
Utilize bower fully

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1702]
### Description
[Bower](https://bower.io/) is a dependency resolving plugin manager almost perfectly suited to our requirements (at the moment). Currently we aren't using it to resolve plugin dependencies, only to resolve plugins from a registry and download them. By allowing bower to resolve dependencies we can have a hierarchy of dependent plugins. 

### Tasks
1. Unify plugins folders into one
2. Modify adapt-cli to use bower dependencies correctly and install into unified folder
3. Modify grunt tasks to build plugins in correct order (components, extensions, menus, themes)

### Potential outcomes
* core can be fragmented into: boot loader, plugin manager, data layer, presentation layer
* plugin functionality can be better resolved and unified into dependent stacks, solving the relationships between narrative+hotgraphic or mcq+gmcq, etc
* clearer and looser code coupling
* remove bulk of plugin manager code from AT + solve plugin dependency issues

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-cli/issues/74

**Comment by canstudios-louisem** [comment]
Something to be aware of; [NPM Migration Path](https://github.com/bower/bower/issues/2467)

**Comment by oliverfoster** [comment]
ta @canstudios-louisem
