### ISSUE TITLE
Update plugins' framework dependency 

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#1704]
Currently most plugins depend on version 2.

Example: https://github.com/adaptlearning/adapt-contrib-blank/pull/28.

Core bundle **(please only tick once released)**:
- [x] Accordion
- [x] Assessment
- [x] Assessment Results
- [x] Blank
- [x] Bookmarking
- [x] Box Menu
- [x] GMCQ
- [x] Graphic
- [x] Hot Graphic
- [x] Language Picker
- [x] Matching
- [x] MCQ
- [x] Media
- [x] Narrative
- [x] Resources
- [x] Page Level Progress
- [x] Slider
- [x] Spoor
- [x] Text
- [x] Text Input
- [x] Tutor
- [x] Trickle
- [x] Vanilla

**Comment by oliverfoster** [comment]
i believe this is done, just gonna check through them all to make sure 👍

**Comment by oliverfoster** [comment]
all done
