### ISSUE TITLE
hotgraphic: indices calculations shouldn't use the dom order

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1705]
* ~~it is possible to have double popups when clicking twice~~
* indices should not be found using ```jquery(selector).index()``` they should use a ```data-adapt-index``` property or similar

**Comment by AaronmcL** [comment]
Hi Oliver, do you have the steps  to replicate the double popups issue ? As far as the other issue is concerned i have a PR ready to go.

**Comment by oliverfoster** [comment]
not really (i'm not even sure i meant the hotgraphic now looking at it...), consider it gone.

**Comment by brian-learningpool** [comment]
A PR for is at https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/143

**Comment by moloko** [comment]
closing because this will definitely be resolved by at least one of the several hot graphic PRs!
