### ISSUE TITLE
Select2 repository inactive, move to the new fork "Selectwoo"

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1707]
Select 2 seems to have been inactive for approximately 6 months, check out the comments on the bottom of this [thread](https://github.com/select2/select2/issues/3744). A fork of this has been created which aims to improve accessibility [here](https://github.com/woocommercese/selectwoo) 

We should test it out and switch to using it, it appears they have created it with backwards compatibility in mind.

**Comment by claudiulodro** [comment]
I saw this was referenced in the original issue. :) Here's a write-up on switching over if you need it: https://woocommerce.wordpress.com/2017/08/08/selectwoo-an-accessible-replacement-for-select2/

**Comment by oliverfoster** [comment]
@claudiulodro any idea of long term support from the selectwoo community.

**Comment by alexweissman** [comment]
Hey folks,

I've recently been added as a maintainer of Select2, so I have the ability to merge PRs and create releases.  I'd like to help get the project back on track, but I can't do it alone!  I've reached out to the WooCommerce folks, to see if we can merge some of their work back into the main repo.

Would you guys also be interested in helping to revive Select2?

**Comment by oliverfoster** [comment]
I certainly don't have the experience enough with SelectWoo or Select2's codebase to help make that a success, but the Adapt community has invested quite some time integrating Select2 into Adapt, so I'd be rather thankful for any clarity on its future. 
We don't use the bleeding edge stuff, more the stable releases. I'm sure I could test release candidates? What effort do you need in the next months? @alexweissman

**Comment by alexweissman** [comment]
@oliverfoster so I think the first task is to rewrite and expand the existing documentation.  I've taken a stab at it [here](http://docs.select2.org).  Pending Kevin's approval we can point the official documentation here, and I can put it up in a new repo under the `select` organization.

The next thing would be to start reviewing some of the many bug fix PRs and start merging them in for a revision release ASAP.

**Comment by moloko** [comment]
closing as matching component no longer uses Select2
