### ISSUE TITLE
Add new getInteractionObject() function to questionModel.js

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1710]
In readiness to support xAPI I'm proposing that a `getInteractionObject()` is added to QuestionView.js, and implemented in question components the same way as `getResponse` and `getResponseType()` currently are.

The purpose of this function is to return an object containing the extra properties which could be appended to an xAPI `object.definition` object.  For example, a `choice` interaction could return:
```
{
  choices: [],
  correctResponsesPattern: []
}
```

**Comment by oliverfoster** [comment]
Please put it on the model. I'll plumb it in to make it backwards compatible for components without models.

**Comment by brian-learningpool** [comment]
Sure thing. 👍

**Comment by oliverfoster** [comment]
Is this waiting on me? @brian-learningpool

**Comment by moloko** [comment]
can I close this now that this has been added to the framework? I know we're still waiting on reviews and merges for the changes to the various question components but I think those can be done as and when and shouldn't hold up the v3 framework release

**Comment by brian-learningpool** [comment]
@moloko, this is ok to close.  It would be good to get some eyes on the associated plugin PRs (listed here: https://github.com/adaptlearning/adapt_framework/pull/1713) though.
