### ISSUE TITLE
page transitions

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1712]
issue: adapt can't load two contentObjects together as there is one global remove event. changing the url triggers a remove event which destroys all contentObjects and creates a new one

solution: make the remove events either/both hierarchical and/or location specific
1. hierarchical: where applicable page.remove cascades to article, block, component allowing a page to be destroyed in isolation
2. location specific: so that a global "remove/preRemove/postRemove" event is triggered and a "remove:co-100/preRemove:co-100/postRemove:co-100" style event is triggered. this allows for page specific remove listeners to be destroyed (article, block, component) whilst keeping global ui specific remove event listeners (navigation, drawer, etc)

**Comment by guywillis** [comment]
@oliverfoster Can this issue be closed now due to this recent addition? 

https://github.com/adaptlearning/adapt_framework/issues/2768

**Comment by oliverfoster** [comment]
yes, august 2017... wowsers....
