### ISSUE TITLE
adapt-contrib-mcq - Accessibility improvements

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1715]
When a user selects an option in the MCQ component, the screen reader just reads out "internal link" It should read out something meaningful. e.g. "Selected option text"

**Comment by oliverfoster** [comment]
that should be catered for by the form element. if it isn't reading "selected" or "checked/unchecked" it has recently been broken.

**Comment by ryan-lynch** [comment]
@oliverfoster I've tested it out and when you highlight an option it reads out "Tick box not ticked". When you actually select one, it just reads out the option. It should update the user for clarity. e.g. "Selected option A"

**Comment by ryan-lynch** [comment]
PR for this [here](https://github.com/adaptlearning/adapt-contrib-mcq/pull/136)
