### ISSUE TITLE
adapt-contrib-media Queuing of transcript open and close

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1718]
If you repeatedly open and close the inline transcript. The open and close animation will continue until it has performed it for every button click. I noticed other components like the Accordion do not queue actions like this.

This is low priority as it only occurs when you are trying to break the course 😆

**Comment by oliverfoster** [comment]
https://api.jquery.com/stop/

**Comment by moloko** [comment]
https://api.jquery.com/stop/collaborate/and/listen/

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/29362439-ea8b47ee-8283-11e7-84d2-fe7376c95ea3.png)

isn't it just....

**Comment by moloko** [comment]
https://api.jquery.com/stop/hammertime/
or even
https://api.jquery.com/stop/in/the/name/of/love

OK I'm done now

**Comment by sarveshwar-gavhane** [comment]
PR : https://github.com/adaptlearning/adapt-contrib-media/pull/174
