### ISSUE TITLE
jquery.a11y - allow more style elements

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1722]
Currently anything other than `<b> <i>  <abbr> <strong>` gets converted into a tabbable block of text

https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L25

Can we add the remainder from here:

https://www.w3schools.com/html/html_formatting.asp

ie `<em> <mark> <small> <del> <ins> <sub> <sup>`

**Comment by oliverfoster** [comment]
+1
