### ISSUE TITLE
jquery.a11y - insert accessible text with single call

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1723]
It's quite common for components to dynamically insert text using `$(selector).html(someText)`

In order to make this text accessible we need to add another call `.a11y_text()`

Wouldn't it be nice if one could accomplish this in one single call, perhaps by passing an argument into the above i.e. `.a11y_text(someText)`?!

**Comment by oliverfoster** [comment]
as mentioned on previous issue, i like this idea, the syntax below does the same thing a little less concisely:

```javascript
$(selector).html($.a11y_text(someText));
$(selector).html(someText).a11y_text();
```

**Comment by danielstorey** [comment]
I started doing that for a component I'm working on, then when it got to the 8th one I thought a helper might be called for!
