### ISSUE TITLE
Hot graphic - custom pins

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_framework#1728]
Our content team have requested the ability to add custom pins.

I have created a pr with the changes [here](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/142)

**Comment by moloko** [comment]
This needs to be checking alongside both https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/140 (seems fairly similar in intent) and https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/136 (going to give someone quite a lot of re-work)

**Comment by canstudios-nicolaw** [comment]
I am now working on this issue and will raise a new PR soon
