### ISSUE TITLE
Hot Graphic - play audio on pin click

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_framework#1730]
We would like to be able to play audio when you click on a pin.

I understand this would require adding similar functionality to narrative as well for mobile use.

**Comment by moloko** [comment]
one option here would be to have hot graphic/narrative broadcast events at the appropriate time, allowing for you to include an audio extension that used those events.

not sure we're quite ready to get into the whole including audio in Adapt thing just yet - believe me that's a giant can of worms!

**Comment by sarveshwar-gavhane** [comment]
@canstudios-louisem  we had developed similar components as you mentioned.
https://github.com/ExultCorp/adapt-hotGraphicWithAudio/tree/develop

**Comment by sarveshwar-gavhane** [comment]
@tomgreenfield  @moloko  @oliverfoster  do we really need audio functionality in core hot graphic component ??

**Comment by moloko** [comment]
I think it would be best handled by an extension. If we need to modify the hot graphic component to make that easier to do then we should definitely do that.

**Comment by chetan-hajare** [comment]
Yes @moloko, using extension we can be apply it to any component.

**Comment by brian-learningpool** [comment]
I agree with @chetan-hajare and @moloko.  This should be handled by a separate audio extension, or by a new hot graphic component, not by the core hot graphic itself.

**Comment by sarveshwar-gavhane** [comment]
@brian-learningpool  completely agree not by the core hot graphic itself. we can achieve using an extension likes/probably  https://github.com/cgkineo/adapt-audio

**Comment by oliverfoster** [comment]
we could find a slightly more generic way of triggering events on user interactions. a bit like tutor. then make an extension to handle rendering the audio/video interface (cos users need controls) achievable but needs some thought.
it's a slightly bigger issue in my opinion, it'd be nice to have a better mechanism of hooking into the interactions we already have.

**Comment by sarveshwar-gavhane** [comment]
we can add media element and player library to the globally, and use that library for media as well as audio functionality,we can write a view which trigger events on user interaction, a bit like tutor or make an extension

**Comment by oliverfoster** [comment]
closing as solution provided and stale
