### ISSUE TITLE
Add images to feedback

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#1734]
It would be nice if support could be added for images to be displayed in question feedback.

It would need to be possible to add an image for each of the main 5 feedback types (correct, incorrect final etc.) as well as add an image for option specific feedback.

Images would need to have alt text and attribution.

One image would be uploaded per feedback, not a large and a small. (I think this would be ok, as I have noticed some components don't require both a large and a small image).

Images would not be mandatory.

This will require changes to the framework, vanilla theme and tutor extension, as well as changes to existing question components.

![imagefeedback](https://user-images.githubusercontent.com/25502448/29414646-415b7380-8358-11e7-85b0-ff1c774664a2.png)

**Comment by canstudios-nicolaw** [comment]
I have only included PRs to add image support to mcq feedback. I would appreciate if I could get an opinion on existing code - I will make PRs for other question components as soon as the community is happy with the direction this is heading in.

**Comment by moloko** [comment]
@canstudios-nicolaw is this something you'd still like to get in?

**Comment by canstudios-nicolaw** [comment]
@moloko yes I am, apologies I've been a bit inactive lately, I've been working on non-adapt projects here. I will see if we can get this tied off in the next couple of weeks.

**Comment by moloko** [comment]
this has been inactive for some time now; I propose that we close the existing PRs and, if this still seems like a useful addition, redo the work using a Notify 'subview'
