### ISSUE TITLE
adapt-contrib-graphic: don't require that the 'small' image is specified as well as large

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1736]
a lot of the time we find we're just setting these to load the same image i.e. the 'small' image is same as the 'large', resulting in an annoying amount of copy-pasting and pointless duplication.

it would be great if it was possible to specify only the 'large' image in situations where you don't need to have a 'small' version

**Comment by tomgreenfield** [comment]
Have only tested in Chrome but specifying just `_graphic.src` works for me.

**Comment by tomgreenfield** [comment]
It's worth remembering that in the authoring tool we already have the 'autofill' functionality for this very purpose.

**Comment by moloko** [comment]
If just specifying `_graphic.src` works OK then that's perfect, we can just communicate to people that they can do that instead.

I've given it a quick check in IE11 and it seems fine, I'll do a bit more testing tomorrow.
