### ISSUE TITLE
Core + Plugins - Move instruction text to core schema

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1743]
At present, the instruction text schema property is self contained in each individual component rather than housed globally in the core ```component.model.schema```

This issue will affect all core component schemas.

* [ ] adapt-contrib-accordion
* [ ] adapt-contrib-assessmentResults
* [ ] adapt-contrib-gmcq
* [ ] adapt-contrib-graphic
* [ ] adapt-contrib-hotgraphic
* [ ] adapt-contrib-matching
* [ ] adapt-contrib-mcq
* [ ] adapt-contrib-media
* [ ] adapt-contrib-narrative
* [ ] adapt-contrib-slider
* [ ] adapt-contrib-text
* [ ] adapt-contrib-textInput

* [ ] adapt-contrib-confidenceSlider
---
Core schema that needs updating:
- [ ] component.model.schema

**Comment by dancgray** [comment]
@guywillis is the proposal to remove instruction from each of the core plugins schema and move to the component schema? If so will this cause issues for authoring tool users who have existing courses?

We will need to make sure it's backward compatible in the AT with existing courses.

**Comment by guywillis** [comment]
Apologies if my intentions were not clear. 

That is indeed the aim, and yes, it is highly likely to cause issues with existing courses if users update. 

I see this ticket more of a future development amend rather than an immediate fix.

**Comment by moloko** [comment]
So, component model.schema in the authoring tool's develop branch now has its own instruction property. Is there something we need to do on the framework side to make sure authoring tool users don't have problems?

**Comment by tomgreenfield** [comment]
@moloko, I think we need the framework's component schema updated if not just for the grunt translate tasks?

We're looking into writing a migration script on the authoring tool side before work begins on the plugins.

@guywillis, can you confirm there are no other changes apart from schema?

**Comment by guywillis** [comment]
@tomgreenfield That's correct, no other changes.

**Comment by chris-steele** [comment]
@guywillis @taylortom is this issue still relevant? I see instruction is still absent from component.model.schema and is present in each plugin schema so nothing seems to have changed in 4 years!

**Comment by guywillis** [comment]
For me, yes. It's confusing that instruction text appears in a different section within the authoring tool.

**Comment by taylortom** [comment]
We've got better schema inheritance in the v1.0.0 authoring tool, and this has been fixed in the new schema.json files. 

It's very unlikely that we'll be making any changes like this in the old schemas, so happy for this one to be closed. 

@guywillis is your comment referring to inconsistencies in the order of the instruction text field in different schemas?

**Comment by guywillis** [comment]
It is, @taylortom. In my mind the instruction text is an integral part of core and should be placed alongside the body property.
