### ISSUE TITLE
Core + Plugins - Move '_supportedLayout' to core schema

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1744]
At present, the '_supportedLayout' schema property is self contained in each individual component rather than housed globally in the core ```component.model.schema```

This issue will affect all core component schemas.

* [ ] adapt-contrib-accordion
* [ ] adapt-contrib-assessmentResults
* [ ] adapt-contrib-blank
* [ ] adapt-contrib-gmcq
* [ ] adapt-contrib-graphic
* [ ] adapt-contrib-hotgraphic
* [ ] adapt-contrib-matching
* [ ] adapt-contrib-mcq
* [ ] adapt-contrib-media
* [ ] adapt-contrib-narrative
* [ ] adapt-contrib-slider
* [ ] adapt-contrib-text
* [ ] adapt-contrib-textInput

* [ ] adapt-contrib-confidenceSlider
---
Core schema that needs updating:

* [ ] component.model.schema

**Comment by danielstorey** [comment]
I recently worked on a component where the spec was to force the component to be displayed full-width. I therefore used the _supportedLayout schema property to achieve this.

Would moving it to component.model.schema prevent this or would defining the property on an individual component override the core schema?

**Comment by moloko** [comment]
@danielstorey is right - you do need to be able to control at component level what settings `_supportedLayout` presents to the user. Might be best to leave this as-is.

**Comment by guywillis** [comment]
I agree, @danielstorey. 

Though I would be intrigued to know whether you could overwrite an attribute in component.model.schema with an attribute of the same name in the component schema.

**Comment by guywillis** [comment]
@tomgreenfield has kindly tested out what a schema override would look like within the tool and it's certainly not pretty.

Closing ticket as, @danielstorey has quite rightly pointed out, you may want purely single / full width components.
