### ISSUE TITLE
textInput : doesn't show green (correct) tick on correct answer selection

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#1755]
steps to replicate issue
1.  enter wrong answer in input box 
2.  submit the question
3.  see correct answer 
correct(green) tick doesn't appear but when you click on my answer it will show incorrect icon(red) tick.

**Comment by moloko** [comment]
Looks like textinput.less needs a little amend round about [here](https://github.com/adaptlearning/adapt-contrib-textInput/blob/master/less/textinput.less#L84-L91)...

**Comment by NayanKhedkar** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-textInput/pull/93
