### ISSUE TITLE
Add ItemsQuestionComponentModel

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1760]
In light of @tomgreenfield 's sterling work on creating ItemsComponentModel I'd suggest there is a strong use case for doing something similar for a question component.

Many question components use an `_items` array and operate on it similarly, leading to a fair bit of repeated code. Things like:
Setting `_isCorrect` for individual items
Setting `_isCorrect` on the component based on the number of items for which `_isCorrect === true`
Setting `_isAtLeastOneCorrectItem` to determine the return value of `.isPartlyCorrect()`

`.isCorrect()` and `.isPartlyCorrect()` could then be abstracted out.

Something for V4? #1703

**Comment by oliverfoster** [comment]
lovely suggestion. may i suggest you start with the mcq? bring that model into core. we can carry on with this any time as it's not breaking.

**Comment by oliverfoster** [comment]
there are a few categories of question component, i'd like to get into core:
(ItemsQuestionModel) mcq/gmcq: select boolean for each/an item(s)  
(MatchsQuestionModel) matching: select index for each items options
(RangesQuestionModel) slider: select values from range(s)  (numberic/textual)

I have a feeling items could probably describe matching with the addition of item options but whether slider could be described by an extension to items is another question. if we generated the items from the ranges specified (assuming a numeric range was given) it would work, but i'm not sure we'd want to inherit from items to make ranges... not without good reason.
there are obviously a heap more i don't know of.

**Comment by oliverfoster** [comment]
I've got someone to take on ItemsQuestionModel, so fingers crossed, we'll have ourselves a new model.
