### ISSUE TITLE
Custom hotgraphic component

### ISSUE THREAD

**Issue by amruta-thakur** [adaptlearning/adapt_framework#1766]
Can we have a hot graphic component in which, when each pin is clicked it will open the new component in popup?

**Comment by amruta-thakur** [comment]
Please have look at custom hot graphic component and extension which supports its functionality:
https://github.com/amruta-thakur/adapt-customHotgraphic
https://github.com/amruta-thakur/adapt-multiQuestion

**Comment by oliverfoster** [comment]
nice idea, i need to find time to look at this 👍

**Comment by amruta-thakur** [comment]
Thanks @oliverfoster, please have a look at it whenever you got a chance.

**Comment by sarveshwar-gavhane** [comment]
@amruta-thakur  this will be a very good enhancement, 
but can we have this feature in existing hotgraphic component instead of creating a new component, 
for example can you define one attribute when we enabled true that hotgraphic component will behave differently like clicking on pin , it will open a new component inside a popup.

**Comment by oliverfoster** [comment]
we don't have an open source option to open components inside popups yet @sarveshwar-gavhane 
but there is a set of prs outstanding where that might be possible in future. 

* https://github.com/adaptlearning/adapt_framework/pull/1841

**Comment by sarveshwar-gavhane** [comment]
thanks for the Link @oliverfoster sounds good. 
@amruta-thakur you might be follow above path as suggested,

**Comment by amruta-thakur** [comment]
@sarveshwar-gavhane:  Yes this is possible to change the settings of Hotgraphic default component and make it work like Custom-Hotgraphic. Soon I will share that kind of example as well.
@oliverfoster : Yes I agree, till this point there is no open source option to open components inside the popup, we have to make some core changes to make this work. I have gone through the suggestion and that was really helpful. 
Thanks!

**Comment by oliverfoster** [comment]
closed as has been long possible to render components/blocks/articles in the notify
