### ISSUE TITLE
Accessibility UI

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#1769]
I think creating something similar in Adapt would be a nice feature - http://brightonmuseums.org.uk/booth/

The option to change contrast and background images etc.

**Comment by moloko** [comment]
I like the idea of being able to hide background images

With the colour contrast stuff I believe most people who have a requirement to be able to do something like this will already have software to do so... either the functionality built into the OS or 3rd party tools.

**Comment by oliverfoster** [comment]
@chucklorenz where did you get to with high contrast and Adapt? Is there a need to provide support for it? If not we can put that to be for the moment.

**Comment by chucklorenz** [comment]
You may put this to bed for the time being, yes.

**Comment by oliverfoster** [comment]
When implementing the accessibility button need to leave space for a potential settings modal. I think that'd leave some space for things like this in the future.

**Comment by chris-steele** [comment]
Definitely agree with background image toggle. I've seen many Adapt courses in which the bg imagery is far too distracting.

**Comment by oliverfoster** [comment]
At the moment background images are theme specific as there is no standard Adapt behaviour for adding background images. Do we want to / should we add that mechanism into Adapt?

**Comment by oliverfoster** [comment]
Removing this from epic as needs more thought.

**Comment by oliverfoster** [comment]
closing in favour of operating system tools
