### ISSUE TITLE
Incorrect version number in package.json release 2.2.0

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#1791]
Looks to me like the framework's version number in v2.2.0's package.json is incorrect. It reads:
"version": "2.1.3"

**Comment by moloko** [comment]
You're correct, it's 2.1.3: https://github.com/adaptlearning/adapt_framework/blob/v2.2.0/package.json#L3

**Comment by tomgreenfield** [comment]
More worringly, it looks like GitHub has binned off the other commits that used to be in this release, e.g. to `adapt.json`, after we rebranched legacy.

**Comment by akshay-bhavsar** [comment]
PR : https://github.com/adaptlearning/adapt_framework/pull/1793

**Comment by moloko** [comment]
@akshay-bhavsar I'm not sure that's going to do it. to fix this, I think we'd need to:
* create a new branch based on the 2.2.0 tag
* amend the version number in package.json (might as well sort out changelog.md too as that wasn't quite right either)
* delete the current 2.2.0 release and tag
* create a new 2.2.0 release and tag
* delete the branch

@tomgreenfield does that sound about right?

**Comment by tomgreenfield** [comment]
If it were purely down to me I would suggest not to bother with the effort to fix this – I'd bin off the 2.2.0 release. Not to mention that with the final step of deleting the branch, we'll probably hit the same issue of losing commits again.

May sound brutal but we don't have any hard dependencies on it; the plugins mostly look for `>=2` or `>=2.2` etc.

**Comment by moloko** [comment]
@tomgreenfield I'm with you on that one, either leave it as is or bin it off. anyone else have an opinion?

**Comment by oliverfoster** [comment]
i like turtles

**Comment by moloko** [comment]
@chucklorenz we discussed this one on the framework call today and decided it wasn't worth trying to fix
