### ISSUE TITLE
Mobile - Style the address bar color

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1792]
Modern mobile device browsers allow the theming of the address bar. Since Adapt courses usually have a Navigation bar it should be easy for it to just match `@navigation-color` with an option for the course creator to change the colour or disable it.
https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/#color_browser_elements

**Comment by moloko** [comment]
Interesting, although I have a feeling much of what's mentioned in that link only works if you've done something like 'save to home screen'... in iOS anyway. But I may well be wrong, it's been ages since I played around with anything like that.

**Comment by moloko** [comment]
@simondate there doesn't seem to be any interest in this so I'm going to close...
