### ISSUE TITLE
Replace aria span with aria helper

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1794]
At present, some of the template files have the 'old' method of defining an aria label which uses the span tag.

```
<span class='aria-label prevent-default' tabindex='0' role='region'>{{_globals._accessibility._ariaLabels.drawer}}</span>
```

I believe a 'new', friendlier, aria helper has been created which can be used to replace the existing method.

```
{{{a11y_aria_label _globals._accessibility._ariaLabels.drawer}}}
```

**Comment by oliverfoster** [comment]
Ongoing issue. Need to tackle all components.
Core was done with https://github.com/adaptlearning/adapt_framework/pull/1940

**Comment by oliverfoster** [comment]
Lined with https://github.com/adaptlearning/adapt_framework/issues/2084

**Comment by oliverfoster** [comment]
closing as work has moved to #2084
