### ISSUE TITLE
Framework: Ability to turn accessibility state on / off

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1795]
At present, the accessibility state for each component is always rendered and read out. 

This means that, if you had an optional graphic component with no defined alt text, the accessibility state would read the component as complete even though the user has not previously tabbed through an image.

Suggestion:
Add config to turn on / off the accessibility completed state on a component by component basis. 

```
{{#if _disableAccessibilityState}}
{{else}}
<div class="accessibility-state">
	{{#if _isComplete}}
	<span class="aria-label a11y-ignore-focus prevent-default" id="buttons-aria-label-complete" role="region" tabindex="0">{{a11y_normalize title}} {{_globals._accessibility._ariaLabels.complete}} {{#if _isQuestionType}}{{#if _canShowFeedback}}{{#if _isCorrect}}{{_globals._accessibility._ariaLabels.correct}}{{else}}{{_globals._accessibility._ariaLabels.incorrect}}{{/if}}{{/if}}{{/if}}</span>
	{{else}}
	<span class="aria-label a11y-ignore-focus prevent-default" id="buttons-aria-label-incomplete" role="region" tabindex="0">{{a11y_normalize title}} {{_globals._accessibility._ariaLabels.incomplete}}</span>
	{{/if}}
</div>
{{/if}}
```

**Comment by moloko** [comment]
I thought you could already do this by adding a class of `no-state`?

**Comment by oliverfoster** [comment]
it can, but guy is right, it would be better if it fit into the normal adapt abstractions

**Comment by moloko** [comment]
done in 2b434143bc94b0c46d8f26ddcabd74cb7f21dddb and documented [here](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes#component-model-attributes)
