### ISSUE TITLE
grunt: replace task doesn't allow for custom replacement

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1798]
the following isn't possible because _.pick is hard coded:
```xml
<manifest identifier="@@course._projectCode_@@course._projectCodeSubId_manifest">
```

**Comment by oliverfoster** [comment]
@brian-learningpool 
can i remove the _pick from here https://github.com/adaptlearning/adapt_framework/blob/master/grunt/config/replace.js#L43-L44
course.json and config.json are both distributed with the final product, this restriction is unnecessary and stops custom attributes from being used in the string replacements

**Comment by brian-learningpool** [comment]
By all means, yes.

**Comment by oliverfoster** [comment]
ta :+1:
