### ISSUE TITLE
hotgraphic pin-class

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1799]
Hotgraphic pins should have a custom class applied for better styling.

**Comment by tomgreenfield** [comment]
This has been fufilled in https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/140 – I'm just getting @guywillis to give it some eyes.

**Comment by lc-thomasberger** [comment]
Will close the issue as a duplicate.
Thanks @tomgreenfield for pointing to the issue!
