### ISSUE TITLE
contrib-assessmentResults: onAssessmentComplete function appears to be redundant

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1808]
I can't see any code (or event handler) that calls this - appears to be completely redundant.

**Comment by tomgreenfield** [comment]
Yeah, I think this was only used in [Assessment Results Total](https://github.com/adaptlearning/adapt-contrib-assessmentResultsTotal/blob/develop/js/adapt-contrib-assessmentResultsTotal.js#L70).
