### ISSUE TITLE
Rework plugins:ready

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1810]
We need a reliable way of determining whether all plugins are ready.

Currently plugins:ready can fire a number of times. Add a bunch of extensions and stick a console.log [here ](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/adapt.js#L57).

In my understanding this is down to one plugin triggering `plugin:endWait` before another has had the chance to call `plugin:beginWait`

Maybe there needs to be stricter rules on when a plugin can trigger `plugin:beginWait`?

**Comment by danielstorey** [comment]
I'll give that a go. The other issue is that if no plugins present use `plugin:beginWait/endWait` then listening for `plugins:ready` could leave you waiting a rather long time...

**Comment by oliverfoster** [comment]
we'd want core to do at lease one beginWait + one endWait on loading and navigation
