### ISSUE TITLE
Can't determine if data from Spoor has been loaded

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1811]
The current way seems to be testing for offlineStorage's ready status [e.g. here](https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/master/js/adapt-languagePicker.js#L31-L35). But what if the offlineStorage model is ready but the data hasn't been loaded yet?

If `plugins:ready` was more reliable we could listen for this but there are currently issues with that (#1810).

It would be great to have a specific trigger for this purpose

**Comment by brian-learningpool** [comment]
Something like this would be good to have for the xAPI work.  

It would be very useful if there was a global event to indicate that the course state had been restored.

**Comment by danielstorey** [comment]
See https://github.com/adaptlearning/adapt-contrib-spoor/pull/164

**Comment by danielstorey** [comment]
Does simply listening to `adapt:start` resolve this?

**Comment by oliverfoster** [comment]
Yes, it should do.
