### ISSUE TITLE
replace .touch with .touch-only device

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#1820]
It makes no sense that devices like the Microsoft Surface are registered as `.touch` devices, when most users will probably use them with a trackpad or mouse and keyboard. It makes more sense there should be a `.touch-only` class which triggers on mobile OS devices.

**Comment by oliverfoster** [comment]
how do we prommatically identify the devices or features which constitute ```.touch-only``` whilst excluding MS Surface devices?

**Comment by simondate** [comment]
Exclude windows devices from being `.touch-only` ? I don't think there are any windows only tablets?

**Comment by oliverfoster** [comment]
What about windows phones?

**Comment by oliverfoster** [comment]
Or internet explorer?

**Comment by moloko** [comment]
Windows Phone is actually a separate OS... not sure how it identifies itself though. We do have one for testing here at Kineo so we could have a look

I know in Windows 10 you can switch it between tablet and desktop mode:
![2017-09-29 16_42_28-](https://user-images.githubusercontent.com/1249597/31023917-42023a68-a535-11e7-851b-817585de832c.png)
Not sure if that makes any difference? Option is greyed out for me since I'm using a desktop. Again, we have a Surface so we could test this.

**Comment by oliverfoster** [comment]
are we going to start targeting specific devices again like ie8, for fixes?

**Comment by brian-learningpool** [comment]
Is there any thing in Bowser JS which we can use here, @simondate?

**Comment by simondate** [comment]
I couldn't find anything else apart from what's on [the repo's README](https://github.com/lancedikson/bowser).

We could either try and use the OS tags to create our own custom class (only use `.touch` on mobile OS's) or look into other libraries.

**Comment by moloko** [comment]
the `.touch` class is there to flag a browser that is 'touch-capable' so it is logical that IE11 on a Surface tablet should have this class.

@simondate could you give us an overview of the problem this is actually causing for you?

**Comment by simondate** [comment]
@moloko Many Windows laptops/tablets/convertibles have touch screens but these users are more likely than not using a trackpad or mouse as their input device. The `.touch` class denies these users a hover state on buttons and icons.

**Comment by brian-learningpool** [comment]
Isn't that just a theme/styling issue, though?  It's not possible to hover on a tablet or phone so there shouldn't be problem with leaving the hover styling in?

**Comment by oliverfoster** [comment]
Because there is no hover on tablet. It acts as ":active" instead, which means it gets ":hover" on a tap but it doesn't leave when you let go.

**Comment by simondate** [comment]
Has anyone put any more thought into this?

**Comment by tomgreenfield** [comment]
If it's _just_ the hover states you're interested in, replacing `.no-touch` with a [variable](https://github.com/cgkineo/adapt-coverMenu/blob/refactor/less/coverMenu.less#L3) that omits the two main mobile OSs works well.

**Comment by simondate** [comment]
So just do a find and replace across the whole theme and change `.no-touch` to `:not(os-android), :not(os-ios)` ?

Is this something we want to apply to Vanilla?

**Comment by oliverfoster** [comment]
Can you get some stats on mobile operating system coverage? Then at least we can feel secure in the knowledge that we're not breaking anything too big.

**Comment by simondate** [comment]
https://www.statista.com/statistics/266136/global-market-share-held-by-smartphone-operating-systems/

Android and iOS make up 99.8% of the market. But we can add `windowsphone`, `firefoxos` and `blackberry` (for Tom G ;) ) too.

**Comment by simondate** [comment]
I'll try and get around to creating a PR tomorrow.

**Comment by moloko** [comment]
sorry I'm late to the party here but I think this should include `windowsphone` since that is officially supported by Adapt (whereas `firefoxos` and `blackberry` are not)

**Comment by oliverfoster** [comment]
closed as very out of date
