### ISSUE TITLE
"Uncaught ReferenceError: jQuery is not defined" error originating from imageReady

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1821]
When using the latest version of the framework (ccf3ca1)

First time I tried it, it loaded fine in Safari for iOS11, Firefox, IE11 and Edge - but failed in Chrome

Downloaded a fresh copy of the framework (because I had slightly modified it on my previous download) and tried again, this time it failed in Firefox with the same error but worked fine in Chrome, IE11, Edge and Safari/iOS11.

Pretty sure this is down to the functions `loadJQuery` and `checkJQueryStatus` having been removed from scriptLoader.js by #1762

**Comment by danielstorey** [comment]
I concur. Just having the same problem and tracked it down to the PR that @moloko mentioned.

I suspect it has do with jquery now being loaded asynchronously and thus creating a race condition. When loading in chrome and I perform a number of refreshes I get a varying number of errors, and sometimes it loads without error.

**Comment by moloko** [comment]
It is definitely loaded before anything else gets loaded but i don’t think it is getting parsed in time i.e. the file has downloaded but `window.jquery` doesn’t always exist by the time libraries like imageReady try to set themselves up

**Comment by moloko** [comment]
@danielstorey does #1822 fix it for you?
