### ISSUE TITLE
Update adapt.json to have correct versions

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1828]
At the moment the manifest states that any version of the core plugins are compatible. This is not the case and all core plugins should now have the framework dependency listed in their bower.json manifests. Let's update adapt.json to indicate the version/range required for each plugin. This will allow us to drop some legacy code with magic numbers from adapt-cli (see https://github.com/adaptlearning/adapt-cli/pull/77)

**Comment by moloko** [comment]
@chris-steele is there a PR for this? I see it's blocking https://github.com/adaptlearning/adapt-cli/pull/77

**Comment by chris-steele** [comment]
@moloko sorry, have done it now: https://github.com/adaptlearning/adapt_framework/pull/1866
