### ISSUE TITLE
Add aria-level to all headings

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1833]
http://www.maxability.co.in/2015/04/aria-level-property/

* add a global config for default component, block, article, page and menu levels
* allow overrides on each instance from the json (including component items, such as accordion item titles, etc)
* use helpers where appropriate for defining headers ``a11y_header`` or such might be useful

**Comment by chris-steele** [comment]
Done in https://github.com/adaptlearning/adapt_framework/pull/1836
