### ISSUE TITLE
adapt-contrib-slider IE10/11 selection bug

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#1844]
When adjusting the slider in IE10/11, if you hover the mouse over the numbers above then all of the text on the component becomes selected.

![image](https://user-images.githubusercontent.com/19267399/31663620-9af4cf92-b33a-11e7-8bf8-416899853570.png)

**Comment by moloko** [comment]
see #1350

**Comment by moloko** [comment]
Until that's sorted, you can patch by changing [this line](https://github.com/adaptlearning/adapt-contrib-slider/blob/master/js/adapt-contrib-slider.js#L46) to:
```
onSlide: _.bind(this.handleSlide, this),
// hack to fix IE11 bug where moving the slider handle causes text around the slider to be selected
onInit: function() {
		$('.rangeslider__handle').on('mousedown touchstart mousemove touchmove', function(e) {
				e.preventDefault();
		});
}
```

**Comment by moloko** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-slider/pull/127

**Comment by moloko** [comment]
fixed by https://github.com/adaptlearning/adapt-contrib-slider/commit/b2ada3032d0d53734a929d90fbe000b3e69e77e3
