### ISSUE TITLE
Add an optional callback to the scrollTo and navigateTo

### ISSUE THREAD

**Issue by nilssanderson** [adaptlearning/adapt_framework#1851]
It would be useful if we had a callback from the **scrollTo** and **navigateTo**, as we could, for example, flash an element once it had been scrolled to or update an extension once the element is in view.

This would stop the need in using a delay function to accommodate the navigation time, which can be very unreliable.

**Comment by tomgreenfield** [comment]
Have you tried using the below?
```js
Adapt.once("page:scrollTo", callback);
```
I use this in one of my extensions to flash an element.

**Comment by nilssanderson** [comment]
Thanks @tomgreenfield will give that a go!

**Comment by NayanKhedkar** [comment]
Adapt.scrollTo has a onAfter callback for work that runs after the animation finishes. 
```
// Syntax: Adapt.scrollTo(element, options);
Adapt.scrollTo('.a-05', {
    onAfter: function() {
        console.log('trigger this after page has scrolled');
    }
}) 
```

**Comment by moloko** [comment]
@nilssanderson can this be closed?

**Comment by nilslp** [comment]
Yes, thank you to all replies!
