### ISSUE TITLE
resources - force download does not work as expected on iOS devices 

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1852]
on iOS devices, resources open in the same tab as you are currently using as iOS have restricted file downloading.

I think it's an acceptable workaround to open all iOS resources in a new tab.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-resources/blob/master/js/adapt-contrib-resourcesView.js#L54 < line in question
