### ISSUE TITLE
Spoor - '_shouldStoreResponses' should default to 'true'

### ISSUE THREAD

**Issue by barry-learningpool** [adaptlearning/adapt_framework#1857]
Since `_shouldStoreResponses` has a direct impact on restored assessment completion, I think it would be worthwhile for it to be defaulted to true.

There is a possible issue here that whenever this property is set to false, a user can attempt an assessment an unlimited number of times (when attempts are limited).

This is due to the fact that when the course data is restored from Spoor, it isn't detected as having been so in the Assessment extension (due to the lack of `_isSubmitted` being set), see https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L543

I think we may need a more robust way of determining if questions have been restored.

**Comment by moloko** [comment]
> Since _shouldStoreResponses has a direct impact on restored assessment completion, I think it would be worthwhile for it to be defaulted to true.

I can't think of a good reason why it shouldn't default to `true` so yes, I would agree that maybe it would be a good idea to do so.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/ae493b7ee57971ca63eb6aa2a3e4eab1c6dcbbeb
