### ISSUE TITLE
Re-visit scriptLoader.js to tidy up and avoid two network requests

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1859]
Some work has already been done on v3 to remove IE8/9 references from scriptLoader.js, but I think it would be worth spending some time to examine exactly what this is currently doing and what it _should_ be doing in the new version.  

Some points to note:
- 2 requests for adapt.min.js
- 2 requests for require.js
- 2 requests for jquery.v2.js  (Why are we still using this version if v3 drops support for IE 8?)

**Comment by oliverfoster** [comment]
range slider has issues i believe @brian-learningpool

**Comment by moloko** [comment]
argh sorry clicking the wrong button

yes we tried updating to jquery v3 but it caused problems with range slider, there is a ticket somewhere...

btw it was jquery v1 that was included for ie8 support, this has now been removed from the master branch

**Comment by moloko** [comment]
here's the issue related to the JQuery v3/Slider incompatibility https://github.com/adaptlearning/adapt_framework/issues/1441

**Comment by oliverfoster** [comment]
need to look at removing / updating modernizr also.
it has dropped its yepnope loader... so will probably cause a large number of issues

**Comment by oliverfoster** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/83c223b732b31f34ddf9d67778d477f2949e84a0
