### ISSUE TITLE
can we add "_suppressMarking" in article.json

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#1860]
it would be good to add this attribute in article.json, usually user don't aware of this.

**Comment by sarveshwar-gavhane** [comment]
i have noticed this during last project our instructional designer need such feature but graphic designer doesn't aware of that we have such feature in adapt due to it was missing from article.json.

**Comment by NayanKhedkar** [comment]
PR : https://github.com/adaptlearning/adapt_framework/pull/1861
