### ISSUE TITLE
update to JQuery 2.2.4?

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1862]
Changes: https://github.com/jquery/jquery/compare/2.2.3...2.2.4

**Comment by brian-learningpool** [comment]
I guess we could easily do that.  I'd really like us to go to 3 if possible though, i.e. if rangeslider can be made compatible.

I think if we're go with JQuery 2.2.x for version 3 of the framework we're unlikely to get an opportunity to safely bump it until v4.

**Comment by moloko** [comment]
i don’t think it would be a breaking change to introduce jquery v3 later (without having to wait until v4 i mean)

**Comment by brian-learningpool** [comment]
There is a chance of introducing breaking changes in plugins though by going to JQuery 3 between versions 3 and 4, like what happened with rangeslider.

**Comment by moloko** [comment]
You could say that about any change we make though! To me, a 'breaking change' is where we know for sure that the change will break stuff, not where there's a chance it might.

**Comment by moloko** [comment]
anyway I'm trying to get things kick-started on the slider issue, if we can get that in then there's no blocker to updating to Jquery v3 and this all becomes moot

**Comment by oliverfoster** [comment]
:+1: mooted
