### ISSUE TITLE
Double Aria Label Argument

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1863]
Slightly niche but it would be great to be able to support multiple aria label arguments for Accessibility.

For example:

If I wanted to piece together multiple sections of language to form a new aria label without creating new and custom JSON nodes, I would have to manually write the statement like the below:

```
{{#if duration}}
<span class="aria-label" tabindex="0" role="region">{{{_globals._menu._boxmenu.durationLabel}}} {{{duration}}}</span>
{{/if}}
```

It would be awesome to be able to do something like the below:

```
{{#if duration}}
{{{a11y_aria_label _globals._menu._boxmenu.durationLabel duration}}}
{{/if}}
```

**Comment by oliverfoster** [comment]
merged
