### ISSUE TITLE
Course build - Error while processing courses/.../.../build/imsmanifest.xml file

### ISSUE THREAD

**Issue by vongrad** [adaptlearning/adapt_framework#1867]
When building a course, I get an error "Error generating preview, please contact an administrator". After checking the logs, it seems to be an issue with parsing imsmanifest.xml file, more specifically it seems that grunt-replace does not replace the placeholders in this file correctly.

node: v5.12.0
npm: 3.8.6
grunt-cli: 1.2.0
grunt: 1.0.1
grunt-replace: 1.0.1

adapt-framework: v2.2.2
adapt_authoring: v0.4.0 

Any ideas how this could be fixed will be greatly appreciated.

server-0 error: [14 Nov 2017 10:43:08 +01:00] exec error: Error: Command failed: grunt server-build:prod --outputdir=courses/592d32149e661f7aa86be57c/59bb7dccd2f0c3cba1e859e9/build --theme=592d393912072515c2e2ad54 --menu=adapt-contrib-boxMenu
server-0 error: [14 Nov 2017 10:43:08 +01:00] stdout error: Running "server-build:prod" (server-build) task
server-0 Running "_log-vars" task
server-0 The following will be included in the build:
server-0 - 592d393912072515c2e2ad54
server-0 - adapt-contrib-boxMenu
server-0 - adapt-quicknav
server-0 - adapt-contrib-tutor
server-0 - adapt-contrib-spoor
server-0 - adapt-contrib-bookmarking
server-0 - adapt-contrib-pageLevelProgress
server-0 - adapt-contrib-resources
server-0 - adapt-contrib-blank
server-0 - adapt-contrib-narrative
server-0 - adapt-contrib-accordion
server-0 - adapt-contrib-graphic
server-0 - adapt-contrib-text
server-0 - adapt-contrib-hotgraphic
server-0 - adapt-contrib-matching
server-0 - adapt-contrib-slider
server-0 - adapt-contrib-mcq
server-0 - adapt-contrib-flipcard
server-0 - adapt-contrib-media
server-0 >> Using source at "/home/adaptlearn/sites/itkartellet.dk/adaptlearn/temp/592d32149e661f7aa86be57c/adapt_framework/src/"
server-0 >> Building to "courses/592d32149e661f7aa86be57c/59bb7dccd2f0c3cba1e859e9/build/"
server-0 >> Using theme "592d393912072515c2e2ad54"
server-0 >> Using menu "adapt-contrib-boxMenu"
server-0 Running "copy:index" (copy) task
server-0 Copied 1 file
server-0 Running "copy:courseAssets" (copy) task
server-0 Running "copy:courseJson" (copy) task
server-0 Running "copy:coreAssets" (copy) task
server-0 Copied 3 files
server-0 Running "copy:componentAssets" (copy) task
server-0 Created 2 directories, copied 19 files
server-0 Running "copy:componentFonts" (copy) task
server-0 Running "copy:extensionAssets" (copy) task
server-0 Running "copy:extensionFonts" (copy) task
server-0 Running "copy:menuAssets" (copy) task
server-0 Running "copy:coreFonts" (copy) task
server-0 Copied 3 files
server-0 Running "copy:menuFonts" (copy) task
server-0 Running "copy:themeAssets" (copy) task
server-0 Created 1 directory, copied 8 files
server-0 Running "copy:themeFonts" (copy) task
server-0 Running "copy:scriptLoader" (copy) task
server-0 Copied 1 file
server-0 Running "copy:libraries" (copy) task
server-0 Copied 19 files
server-0 Running "copy:required" (copy) task
server-0 Copied 17 files
server-0 Running "less:compile" (less) task
server-0 screen size: { large: 1024, medium: 759, small: 519 }
server-0 Running "handlebars:compile" (handlebars) task
server-0 >> 1 file created.
server-0 Running "javascript:compile" (javascript) task
server-0 Running "replace:dist" (replace) task
server-0 Warning: Error while processing "courses/592d32149e661f7aa86be57c/59bb7dccd2f0c3cba1e859e9/build/imsmanifest.xml" file. Use --force to continue.
server-0 Aborted due to warnings.
server-0 Execution Time (2017-11-14 09:43:06 UTC)
server-0 loading tasks           51ms  ▇ 3%
server-0 copy:componentAssets    52ms  ▇ 3%
server-0 copy:componentFonts     21ms  ▇ 1%
server-0 copy:required           70ms  ▇▇ 3%
server-0 less:compile           415ms  ▇▇▇▇▇▇▇▇ 20%
server-0 handlebars:compile     254ms  ▇▇▇▇▇ 13%
server-0 javascript:compile        1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
server-0 loading grunt-replace   25ms  ▇ 1%
server-0 Total 2s
server-0 error: [14 Nov 2017 10:43:08 +01:00] Error: Command failed: grunt server-build:prod --outputdir=courses/592d32149e661f7aa86be57c/59bb7dccd2f0c3cba1e859e9/build --theme=592d393912072515c2e2ad54 --menu=adapt-contrib-boxMenu
server-0 error: [14 Nov 2017 10:43:08 +01:00] Error: Command failed: grunt server-build:prod --outputdir=courses/592d32149e661f7aa86be57c/59bb7dccd2f0c3cba1e859e9/build --theme=592d393912072515c2e2ad54 --menu=adapt-contrib-boxMenu

**Comment by oliverfoster** [comment]
the replace task is happening too early in the build process

**Comment by oliverfoster** [comment]
this is due to the inclusion of the property:
```json
"themeSettings": null
```
in the course.json

this causes issues with the applause library used in grunt-replace at line:
https://github.com/outaTiME/applause/blob/master/src/applause.js#L134
causing line:
https://github.com/outaTiME/applause/blob/master/src/applause.js#L156

**Comment by oliverfoster** [comment]
it seems that under certain (as yet unknown) conditions https://github.com/adaptlearning/adapt_authoring/blame/master/plugins/content/course/model.schema#L590 < this bit of the schema seems to be coming out as:
```json
"themeSettings": null
```
at the moment it seems the course will remain broken as that attribute persists in the database

**Comment by oliverfoster** [comment]
outaTiME/applause#10 < bug and fix suggested to applause

**Comment by tomgreenfield** [comment]
@oliverfoster, it may well be a different `null` field causing aggro, since `_themeSettings` is usually [omitted](https://github.com/adaptlearning/adapt_authoring/blob/master/lib/outputmanager.js#L35) from the output.
