### ISSUE TITLE
Recommended approach for 'libraries' folder in v3?

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1870]
Following on from https://github.com/adaptlearning/adapt_framework/issues/1868, I noticed that the globbing pattern in the Grunt copy task would copy `libraries` in any of the plugin directories like so:
- ./libraries
- ./tests/libraries
- ./js/libraries

I think for v3 we should come up with a standard approach for the location of external libraries.  I'd vote for a libraries folder at the plugin root.  This could lead to a slightly more performant copy task and improve code readability across different plugin codebases.

**Comment by oliverfoster** [comment]
agreed, that was how i'd originally wanted it.

so that we have:
```
plugin
   > libraries    :   build/libraries/
   > required     :   build/
   > fonts        :   build/adapt/css/fonts/
   > assets       :   build/assets/   |   build/adapt/css/assets      (needs sorting out)
   > js           :   build/adapt/js/adapt.min.js
   > templates    :   build/templates.js      (probably needs moving somewhere a little nicer)
   > less         :   build/adapt/css/adapt.min.css
```

**Comment by moloko** [comment]
can this be closed now?
