### ISSUE TITLE
Changing Dest of menuAssets in Grunt task

### ISSUE THREAD

**Issue by ciaranlp** [adaptlearning/adapt_framework#1874]
Currently in `grunt/config/copy.js` `menuAssets` **dest** is set to `dest: '<%= outputdir %>assets/'` this should be brough into line with `menuFonts`, `themeFonts` and `themeAssets` that all point to `Adapt/css/[respective-folder]`for example `themeAssets` has `dest: '<%= outputdir %>adapt/css/assets/'`

**Comment by oliverfoster** [comment]
i think all of the asset folders should go to adapt/css/assets not just menu and theme.
it seems silly to have two asset folder locations as we do at the moment. one at  build/assets and one at build/adapt/css/assets.

there isn't a proposal where we could change the location of this folder without breaking any existing plugins. except duplicating the assets over both folders.

**Comment by oliverfoster** [comment]
I had a little more of a think around this...
Assuming that:
* we want to unify the assets folders
* stop code from breaking
* warn people to update their code

We could probably:
* get grunt to output all assets to adapt/css/assets (or move the adapt.css and invert that)
* add a less preprocessor to warn of occurrences of ```../../assets/``` in the LESS source files by path
* after the less is compiled into css, add a css postprocessor to correct the occurances of ```../../assets/``` to ```assets/```

**Comment by oliverfoster** [comment]
any thoughts on this @ciaranlp ?

**Comment by ciaranlp** [comment]
I like the idea of having all assets in one place and the css file moved to root

**Comment by oliverfoster** [comment]
cool. we'd have to move the font and assets folders to root, but that's quite doable.
it would be easier in the first instance to unify them into adapt/css/assets, as fewer things have to change, but i'll happily unify them at /assets instead if we can all agree

any objections? @moloko @brian-learningpool @lc-thomasberger @tomgreenfield @taylortom @dancgray @danielstorey

**Comment by oliverfoster** [comment]
### Changes required
When moving root/adapt/css/adapt.min.css to root/adapt.min.css
* All index.html s need changing as this file is referenced directly
* Change grunt to output all fonts to root/fonts/ instead of  root/adapt/css/fonts
* Change grunt to output all assets to root/assets
* Add less preprocessor to change "../../assets/" references to "assets/" and warn about deprecation

**Comment by oliverfoster** [comment]
@ciaranlp can you have a look at the above pr? see if that helps.
don't install spoor to test, i haven't done a pr for the link tag change in spoor yet.

**Comment by ciaranlp** [comment]
Yes @oliverfoster will do

**Comment by oliverfoster** [comment]
Ta man. Let me know if it's not suitable as a solution to your specific issue. I'm trying to solve your problem along with the outstanding double assets folder issue at the same time.

**Comment by nilslp** [comment]
@oliverfoster all seems to be working dandy! +1

Prompts:
<img width="466" alt="screen shot 2018-01-25 at 10 46 10" src="https://user-images.githubusercontent.com/1729773/35384537-808d286c-01bd-11e8-8be3-02487b9a6f17.png">

1 Error LESS file from prompt
<img width="532" alt="screen shot 2018-01-25 at 10 49 11" src="https://user-images.githubusercontent.com/1729773/35384563-8f17ef66-01bd-11e8-91cd-07a0669c072a.png">

Paths fixed after compilation
<img width="444" alt="screen shot 2018-01-25 at 10 49 24" src="https://user-images.githubusercontent.com/1729773/35384575-9c3d5dc0-01bd-11e8-8374-8ba6e8a7fc8c.png">

**Comment by oliverfoster** [comment]
I'll fix it so it only outputs one error per file. That should be enough.

**Comment by oliverfoster** [comment]
@nilslp can you approve the pr? > https://github.com/adaptlearning/adapt_framework/pull/1932
