### ISSUE TITLE
contrib-tutor: Title not display title in feedback

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_framework#1876]
Tutor is showing the components title not display title in the feedback notify.

**Comment by chetan-hajare** [comment]
Hi @canstudios-louisem 
We are using the title in the feedback since the beginning of the development of the Adapt framework. The page level progress extension also uses title to represent component in the drawer. If we think to change the feedback title to display title, we might have to consider the page level progress extension too. @brian-learningpool @moloko @oliverfoster @lc-thomasberger Can you please provide your suggestions on this?

**Comment by oliverfoster** [comment]
i think the feedback should be able to specify a title.

**Comment by oliverfoster** [comment]
need to expand this object to take titles, body text, images etc
https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/components.json#L424

**Comment by tomgreenfield** [comment]
Related: https://github.com/adaptlearning/adapt_framework/issues/1734.

**Comment by lc-thomasberger** [comment]
For PageLevelProgress it is actually good to use title instead of displayTitle (long titles do not work with Drawer), so I think we should stick with this behavior.
For questions a separate title field would be nice. It should default to the component's title if it is not specified.

**Comment by canstudios-louisem** [comment]
Being able to set the feedback's notify title would fix this issue for us really. Most of the time we just want it to say `Feedback` or similar.

**Comment by oliverfoster** [comment]
@canstudios-louisem  one for _partlyCorrect, corract and incorrect? Or just a general title per component?

**Comment by chetan-hajare** [comment]
I would prefer a general title per component. What do you think about this @canstudios-louisem ?

**Comment by chetan-hajare** [comment]
PR: https://github.com/adaptlearning/adapt_framework/pull/1954

**Comment by canstudios-louisem** [comment]
Thanks for your work on this @chetan-hajare much appreciated :+1:

**Comment by moloko** [comment]
should all be done now that https://github.com/adaptlearning/adapt-contrib-mcq/pull/139 is in.
