### ISSUE TITLE
adapt-contrib-slider: in RTL mode on iOS the number on the marker flips over

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1878]
When the marker is moving from one step to another, the number on the marker flips over:

![slider_rtl_issue_ios](https://user-images.githubusercontent.com/1249597/33212788-867844a4-d11c-11e7-926f-07039d2b35cb.gif)

This may be down to my test using an LTR language that's been forced into RTL mode? Be good if someone can verify this!

Tested on iOS11 iPhone and iPad.

I have checked to see if https://github.com/adaptlearning/adapt-contrib-slider/pull/119 fixes this but it doesn't.

**Comment by chetan-hajare** [comment]
PR -https://github.com/adaptlearning/adapt-contrib-slider/pull/129
