### ISSUE TITLE
adapt-contrib-media: toggleCaptionsButtonWhenOnlyOne

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1883]
When using `"toggleCaptionsButtonWhenOnlyOne": true`, it looks like the toggle functionality works (only tested on desktop), but there are issues with how the language selector appears regardless. I am guessing the issue is related to https://github.com/adaptlearning/adapt-contrib-media/blob/master/less/mep.less#L575-L577.

I haven't looked to see whether this has been fixed in the latest MediaElement or whether it is something related to our implementation of the .less, but I am pretty sure it used to work before we updated MediaElement a while back. Should we look to include another update of those files?

**Comment by moloko** [comment]
Unfortunately updating MediaElement is rarely an easy task...! Going forward we don't really need to use it any more, we mainly had it for IE8 support.

**Comment by moloko** [comment]
For the benefit of others, you can prevent the 'captions selector' popup from being displayed by adding the  the following to media.less:
```css
.mejs-captions-selector {
    display: none !important;
 }
```
