### ISSUE TITLE
adapt-contrib-matching: page bottom hidden dropdown

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1889]
it's possible to have the dropdown overhang the bottom of the page or the trickle limit

**Comment by oliverfoster** [comment]
take code from:
 https://github.com/adaptlearning/adapt-contrib-matching/blob/issue/1889/libraries/select2.js#L4141-L4175
https://github.com/adaptlearning/adapt-contrib-matching/blob/issue/1889/libraries/select2.js#L4183-L4196
https://github.com/adaptlearning/adapt-contrib-matching/blob/issue/1889/libraries/select2.js#L4253-L4328

and apply to:
https://github.com/adaptlearning/adapt-contrib-matching/blob/issue/1889/libraries/select2.js#L6061-L6074

**Comment by moloko** [comment]
steps to replicate/screenshot would be helpful here - if only so we can test that https://github.com/adaptlearning/adapt-contrib-matching/pull/109 fixes the issue

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-matching/commit/0afea7a00556f7c92ed2d58d32367258bfb0b4a3
