### ISSUE TITLE
contrib-slider: doesn't reset properly when used in an assessment

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1895]
Taken from [this post on the forums](https://community.adaptlearning.org/mod/forum/discuss.php?d=2526)

If you answer the slider question correctly but fail the assessment, reset for another try then answer the slider incorrectly, it marks as correct.

![screenshot](https://user-images.githubusercontent.com/1249597/33776634-f29f0550-dc39-11e7-8bcc-94743f1b089f.gif)

Looks like the property `_isAtLeastOneCorrectSelection` is not getting reset.

**Comment by tomgreenfield** [comment]
Sorry I'm late to the party. I have a feeling that [`resetUserAnswer()`](https://github.com/adaptlearning/adapt-contrib-slider/blob/master/js/adapt-contrib-slider.js#L342-L347) would be a better fit for this amend.

Will make a PR shortly so we can test.
