### ISSUE TITLE
adapt-contrib-assessmentResults: retry text and button doesn't reset

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1903]
Retry text and button doesn't reset when the retry button is clicked.
The retry button should only be available after completing an assessment not when returning from a reset assessment in the same session.

Pre 1st attempt:
![image](https://user-images.githubusercontent.com/7974663/33950350-11aab118-e024-11e7-893e-fab5d0f04f87.png)

1st attempt:
![image](https://user-images.githubusercontent.com/7974663/33950439-51b6f014-e024-11e7-9892-52b09ddb9c6b.png)

1st attempt retry / pre 2nd attempt:
![image](https://user-images.githubusercontent.com/7974663/33950488-727f93dc-e024-11e7-8fb7-f3d917808873.png)

**Comment by oliverfoster** [comment]
thanks @chetan-hajare

**Comment by chetan-hajare** [comment]
You're welcome :)
Actually while assigning the issue to myself, I didn't see that you have already resolved the issue.
