### ISSUE TITLE
adapt-contrib-assessment: add preReset, postReset and restored events

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1904]
Allows extensions to configure the assessment at various stages of the reset process.

[Example extension](https://github.com/cgkineo/adapt-assessmentAttempts)

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/1841c92e8cb49fb5959d02e8462a539851b7d094
