### ISSUE TITLE
adapt-contrib-spoor: stops offline_API saving cmi.interactions.

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1905]
Causes a storage full warning very quickly when testing. cmi.interactions is also read only, so it's unnecessary to store the values (except for testing cmi.interactions).

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/d7940a74caef62e10bd207880f90688b74716b78
