### ISSUE TITLE
core/schema/component.model: _isResetOnRevisit missing

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1912]
The `_isResetOnRevisit` attribute doesn't seem to be exposed within the Authoring Tool. Is there a reason for this?

The need to set this at a component level is fairly uncommon, but it can be required. For example, when question responses are restored across sessions via `_shouldStoreResponses`, you may wish to disable this for particular questions or only restore responses for passed assessments and therefore need to override this via `_isResetOnRevisit` on the relevant components.

We should allow `true`, `false`, `"soft"` and `"hard"` values.

**Comment by moloko** [comment]
> Is there a reason for this?

I'm sure I asked this same question recently but I can't find any reference to that now!
