### ISSUE TITLE
adapt-contrib-textInput: clicking the 'clear' icon that IE11 adds has no effect

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1913]
### Subject of the issue/enhancement/features
IE11 adds an X icon into the input fields (once they contain user input), clicking this presumably should clear the input field contents but it does not

### Your environment
* Framework & AT
* IE11
* windows 10
* textInput plugin v2.1.1 (current release)

### Steps to reproduce
input some text into the text input component ;-)

### Expected behaviour
Either have the text cleared on clicking the icon or [hide the icon](https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs)

### Actual behaviour
clicking the icon causes it to disappear (until more text is added) but has no other effect
### Screenshots (if you can)
![text_input_ie11_clear_icon_bug](https://user-images.githubusercontent.com/1249597/34782733-82755836-f621-11e7-9e8e-9c7b616372f1.png)

**Comment by oliverfoster** [comment]
ooo, that's is a gorgeous bug report.... love it...

**Comment by tomgreenfield** [comment]
![simple](https://user-images.githubusercontent.com/922987/34784262-b3f9267c-f625-11e7-847e-b8c60dbe523e.png)

**Comment by NayanKhedkar** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-textInput/pull/92
