### ISSUE TITLE
Drawer icon is removed when changing language

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1917]
### Subject of the issue
When creating a multi-language course the Drawer icon is removed when you change language mid-way through a course.

### Your environment
* Framework version 2.2.3
* IE11
* Windows 7

### Steps to reproduce
- Download and install the latest version of the framework (2.2.3)
- Duplicate the course/en folder and rename to 'de' for German.
- Enable language picker in config.json
- Build and preview course.
- Choose the English version on the language picker.
- Open language picker on the nav bar.
- Change language to German.

### Expected behaviour
Drawer icon should remain in the nav bar.

### Actual behaviour
Drawer icon is removed from the nav bar.

**Comment by moloko** [comment]
confirming that I can replicate this (in Firefox, Chrome and IE11) - seem to be down to #1819, at least if I revert the changes from that PR the drawer icon no longer disappears when changing language, though presumably changing that also re-introduces [the issue it was meant to fix](https://github.com/adaptlearning/adapt_framework/issues/1817)

**Comment by tomgreenfield** [comment]
Following the fix in https://github.com/adaptlearning/adapt_framework/pull/1910, this can probably be resolved by the following:

* Changing lines 21–32 of [`drawer.js`](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/drawer.js#L21-L32) to
  ```js
  Adapt.on('adapt:start', function() {
  	new DrawerView({collection: DrawerCollection});
  });
  ```

* Getting `drawerView.js` to remove itself on a language change a la the [Close](https://github.com/cgkineo/adapt-close/blob/master/js/adapt-close.js#L9) extension

* Changing lines 42–45 of [`adapt-resources.js`](https://github.com/adaptlearning/adapt-contrib-resources/blob/master/js/adapt-contrib-resources.js#L42-L45) to
  ```js
  Adapt.on('app:dataReady', initResources);
  ```
