### ISSUE TITLE
assessment: new _allowResetIfPassed setting doesn't work with _isResetOnRevist

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1925]
### Subject of the issue/enhancement/features
The new `_allowResetIfPassed` setting works fine if you reset the assessment using the retry button in the assessment results but not if you go back to the menu and back into the assessment (when `assessment._isResetOnRevist` is enabled)

### Your environment
* Framework
* any browser
* any device/OS

### Steps to reproduce
Using adapt-cli, download the master branch of the framework then update the assessment extension to the master branch (as the new `_allowResetIfPassed` setting hasn't been released yet). 

In articles.json, on article a-15, set `_assessment._allowResetIfPassed` to `true` and ensure that `_assessment._isResetOnRevisit` is also set to `true`.

In components.json set `_allowRetry` to `true` for the 100 score band in c-150.

Build and run the course, pass the assessment.

### Expected behaviour
Since you can reset the assessment by using the reset button in the assessment results I would also expect the assessment to reset if you go back to the menu then back into the assessment (since `_isResetOnRevisit` is enabled)... just like it does if you fail.

### Actual behaviour
The assessment will not reset if you pass then go back to the menu and back into the assessment, it will only reset if you use the retry button or if you fail then go back to the menu etc.

It looks to me as if some changes will need to be made to `_setupAssessmentData` in adapt-assessmentArticleModel.js - assuming others agree with me that it should reset on revisit, anyway!

**Comment by sarveshwar-gavhane** [comment]
yes @moloko it should reset.
```(assessmentConfig._isResetOnRevisit && (state.allowResetIfPassed || !state.isPass)) || force === true```

**Comment by akshay-bhavsar** [comment]
PR #106

**Comment by akshay-bhavsar** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-assessment/pull/106

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/8e0468cc73d342e5ddb71cea919b4f898c57ca33
