### ISSUE TITLE
adapt-contrib-media fails to load streaming videos over file: protocol

### ISSUE THREAD

**Issue by mediabounds** [adaptlearning/adapt_framework#1926]
### Subject of the issue/enhancement/features
When an Adapt course is running over the file: protocol, streaming media (such as a YouTube video) fails to load because adapt-contrib-media attempts to load the content using a relative protocol (regardless of how the source was entered).

### Your environment
* adapt-contrib-media 2.1.1
* iOS 11 UIWebView

### Steps to reproduce
1. Create a course and add an adapt-contrib-media component
2. Set the source to a YouTube video
3. Run the course over the file: protocol

### Expected behaviour
The video should play because a valid source was provided.

### Actual behaviour
The video does not play because adapt-contrib-media changes the source to use the current protocol.

### Screenshots (if you can)
n/a

Pull request submitted:
https://github.com/adaptlearning/adapt-contrib-media/pull/176

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-media/commit/e10b18cb739c1125b1329df435ea8fb71aa53a47
