### ISSUE TITLE
adapt-contrib-accordion - jumps/scrolls when opening in IE 11

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1927]
An issue has been reported with the accordion component causing "stuttering" when opening and closing the component in IE 11. 

### Expected behaviour
Accordion opens smoothly

### Actual behaviour
The page stutters and scrolls away from the component

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-accordion/commit/e8193ad94f0cbdad4b9ef329b771f5f50cc45b10
