### ISSUE TITLE
Slider + rangeslider + jquery v3

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1930]
### Subject of the issue/enhancement/features
Adapt needs to upgrade to jquery v3.
As I understand it, slider's current version of rangeslider doesn't support jquery v3. Need to investigate and update if possible.

### Related issues
#1303

**Comment by lc-thomasberger** [comment]
Would be good to try if we can use nativ input type=range for the Slider. [Browser support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) looks good. 
Biggest issue will be a similar [cross browser design](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/). This [demo](https://codepen.io/chriscoyier/pen/FtnAa) works and looks good in IE, Chrome and Firefox.

**Comment by oliverfoster** [comment]
Matt Leathes @moloko 13:22
regarding #1930 when we first updated to JQuery v3 it created a problem with rangeslider.
specifically adaptlearning/adapt_framework#1441
but now we've updated to a newer version of rangeslider it should be fixed
needs testing though

**Comment by oliverfoster** [comment]
@lc-thomasberger do you agree with Matt that the current rangeslider and jquery v3 are compatible? If so I'll close this and open a new one for your suggestion?

**Comment by oliverfoster** [comment]
yup, confirmed, jquery v3 support was added in version 2.2.1 we use 2.3.1
new issue https://github.com/adaptlearning/adapt_framework/issues/1939
