### ISSUE TITLE
assessmentResults: always does a 'hard' reset

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1933]
The assessment results component always does a 'hard' reset, regardless of what the assessment's `_resetType` is set to.

In the situation that I have, the course contains an assessment as the penultimate topic - but it does not matter whether the user passes or fails it so the pass mark is set to 0. 

They should, however, be allowed to keep retrying the assessment - but if they do, access to the last topic is (re-)locked because the assessment results component does a 'hard' reset - which causes the completion of the contentObject it's in to be reset, which then causes the final topic to be locked again.

**Comment by oliverfoster** [comment]
Can you do this independently of the assessment config? So that assessment results can soft / hard reset itself. It might come in handy independently?

**Comment by moloko** [comment]
well the short answer is I probably could but don't have the time...

**Comment by danielghost** [comment]
Duplicate of #1558

**Comment by moloko** [comment]
so it is, well spotted @danielghost
