### ISSUE TITLE
Grunt "build-config" task issues

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1944]
### Subject of the issue
Testing the latest `master` branch indiciates two issues with the `build-config` task:

### Your environment
* Adapt Framework (`master` - 93a8448136ec8c9512268668c7755abc5f9c4a01)
* Not browser specific
* Mac OS

### Steps to reproduce
Preview a course in the authoring tool (v4), which runs a command similar to the following in the framework:
`grunt server-build:dev --outputdir={outputPath} --theme={themeName} --menu={menuName}`

### Expected behaviour
1. The course should build without `Cannot find module` warnings/errors.  
2. All plugins installed in the framework folder should not be detailed in the `build.min.js`.  This Grunt task should respect the config.json `build.includes` array.  What is the purpose of displaying all plugins if they're not included in the build? 

### Actual behaviour
1. `Error: Cannot find module` appears in the output log for certain plugins (see screenshot), even though the plugin's bower.json file does exist.
2. The `plugins` attribute details every single plugin installed on my system.    

### Screenshots
<img width="568" alt="screen shot 2018-01-26 at 09 50 10" src="https://user-images.githubusercontent.com/1327471/35435428-9d213804-0282-11e8-9385-1c5c277572ef.png">

**Comment by brian-learningpool** [comment]
@oliverfoster, @nilslp was testing #1932 and thought this might be related, where it's actually an issue in code that's already been merged to `master`.

**Comment by oliverfoster** [comment]
Cool. Will pick this up next week. Is it fatal at the moment?

**Comment by brian-learningpool** [comment]
Hi @oliverfoster, no, and I wouldn't say it's urgent.
