### ISSUE TITLE
contrib-vanilla: graphic components if they are in an assesment on mobile

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_framework#1945]
https://github.com/adaptlearning/adapt-contrib-vanilla/blob/b1ce977c048ec6477eda57024a161ee177f63005/less/src/theme-extras.less#L72 looks to be some old code that just never got removed.

**Comment by moloko** [comment]
still present in latest vanilla theme, see https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/custom/theme-extras.less#L67-L75

anyone object to me just removing that style?

**Comment by moloko** [comment]
I think this may have been resolved as part of the v5 update... @guywillis ?

**Comment by guywillis** [comment]
@moloko That's correct, graphic components are no longer hidden in assessments on mobile.
