### ISSUE TITLE
_showPrompt is missing from adapt-contrib-bookmarking schema

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#1947]
### Subject of the issue
adapt-contrib-bookmarking schema is missing _showPrompt value

### Expected behaviour
In the authoring tool, should be able to configure bookmarking to return to bookmark position without prompt.

### Actual behaviour
_showPrompt option is not available in AT so by default prompt is always shown.

**Comment by dancgray** [comment]
See https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/32

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-bookmarking/commit/744d89012a38b08b3f04fb1aedd8eef61c82a073
