### ISSUE TITLE
add custom class to notfiy 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1957]
### Notify should accept custom classes
Since Notify accepts now a custom view, it will need better styling support. For instance HotGraphic will need to reset the background-color of the popup. This will only work if a class can be set at the top level of Notify.

```
            Adapt.trigger("notify:popup", {
                _view: new HotgraphicPopupView({
                    model: this.model
                }),
                _isCancellable: false,
                _classes: ' hotgraphic' // will be added tho notfiyView.$el
            });
```

**Comment by lc-thomasberger** [comment]
_isCancellable hides the close button and also disables close by clicking on the backdrop. 
I think it would be good to have more fine grained options here:
`_showCloseButton`   
`_closeOnBackdrop`    

`_isCancellable` would set both values for backwards compatibility.

**Comment by oliverfoster** [comment]
could you split _isCancellable out before we document the subview stuff? @lc-thomasberger 
now is the time to do that.
