### ISSUE TITLE
Allow assessment completion to be excluded from display elements such as page level progress

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#1960]
### Subject of the enhancement
It was possible to exclude assessment completion status from display elements like page level progress using _assessment. _requireAssessmentPassed. As this has quite rightly been removed we could do with some way of indicating how assessment status should be displayed.

Suggest adding a setting to assessment with clearer intention.

**Comment by dancgray** [comment]
See https://github.com/adaptlearning/adapt_framework/issues/1328

**Comment by oliverfoster** [comment]
This includes being allowed to revert to the original behaviour: Have each assessment component represented in the PLP.

**Comment by oliverfoster** [comment]
resolved with https://github.com/adaptlearning/adapt-contrib-assessment/pull/104
