### ISSUE TITLE
Scriptloader - Incorrect file path on build

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#1961]
When I downloaded the latest master branch of the Framework, I encounter an error when trying to run a grunt build. The error relates to an incorrect file path for adapt.css. 

I believe I have traced the issue to the following chunk of code and could be resolved by wrapping it in a document ready.

https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/scriptLoader.js#L4-L14

Framework, master branch

**Comment by oliverfoster** [comment]
Tut tut... amateur mistake!
