### ISSUE TITLE
install of adapt-cli fails with libssh2

### ISSUE THREAD

**Issue by zeigerpuppy** [adaptlearning/adapt_framework#1964]
On Debian Jessie with Node v8.9.4

Installation of adapt-cli fails with the error below.
It looks like something may be out of order in the install sequence as the target dir `/usr/lib/node_modules/adapt-cli/...` doesn't exist.

```
ls /usr/lib/node_modules
```
```
npm
```

--------------------------

```
sudo npm install -g adapt-cli
```

```
[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/openssl/openssl
/usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/libssh2/configure: line 2059: config.log: Permission denied
/usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/libssh2/configure: line 2069: config.log: Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/lib/node_modules/adapt-cli/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.20.3 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.20.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by moloko** [comment]
a few linux users have reported that installing nodejs-legacy has helped with problems; equally [some have said installing libssl-dev has helped](https://community.adaptlearning.org/mod/forum/discuss.php?d=1976#p9309)

you might also try an older version of node - 8.9.4 became the LTS version only fairly recently as so the Adapt CLI hasn't had much testing against it. v6 is likely to be the most-used version at the moment.

**Comment by zeigerpuppy** [comment]
Thanks for the tip, I have reinstalled with nodejs 6.13.0.
I also made sure that `libss-dev` and `build-essential` were installed as gcc is needed. 
With these changes the build worked fine.
