### ISSUE TITLE
Minification issues

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1966]
### Subject of the issue
`adapt/js/adapt.min.js` should be minified by uglifyjs
`adapt/js/build.min.js` shouldn't be minified by uglifyjs as it is json

es6 is currently not supported by a released version of [grunt-contrib-uglifyjs](https://github.com/gruntjs/grunt-contrib-uglify/issues/482#issuecomment-312860523)
this means the javascript command doesn't minify the adapt.min.js file properly due to a `let` statement in the `notify` module

also remove ie8 support from uglifier

**Comment by brian-learningpool** [comment]
I think we should remove the`let` statement to resolve this, and review and update the code for v4 (or a later version of v4) rather than introducing ES 6 piecemeal.

**Comment by oliverfoster** [comment]
cool, i'll have a look through the core bits as i go, any plugin containing es6 will break after i reinstate minification. so could be a bit of a hassle

**Comment by oliverfoster** [comment]
https://swizec.com/blog/fun-surprise-uglifyjs-cant-es6/swizec/7272

**Comment by moloko** [comment]
find it a bit depressing that we can't use the only two bits of ES6 that are actually supported in ALL current browsers but there you do, I guess there's little we can do.

**Comment by oliverfoster** [comment]
v5 I'm going for webpack. So we're not far.
