### ISSUE TITLE
Spoor: Use new offlineStorage:prepare event

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1970]
As per PR https://github.com/adaptlearning/adapt_framework/pull/1968, Spoor should initialise offlineStorage in response to the new `offlineStorage:prepare` event, and not `configModel:dataLoaded`.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/b237c888f09c61d327138648a0fe871387aa47c3
