### ISSUE TITLE
accessibility: wrapping white-space as tabbable region

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1977]
### Subject of the issue/enhancement/features
This [line](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L236) doesn't trim white-space and skip empty sections. So between `<ul>` and `<li>` tags there can appear tabbable regions.

**Comment by moloko** [comment]
done in f94be40b089e6c9f2aaaa3361f7a435dd8a76bc3
