### ISSUE TITLE
Assessment - force selection of new questions from bank

### ISSUE THREAD

**Issue by timnewham** [adaptlearning/adapt_framework#1980]
Hi - first post here, semi-literate consultant rather than technologist here!

Current behaviour for assessments with a bank of questions appears to be:

1. Select x questions randomly from the bank
2. On re-try, select x questions randomly from the bank at random
3. Repeat until no more re-tries allowed

For higher-stakes assessment, we have a requirement to avoid the same question appearing in more than one try for any one learner (obviously limited by the size of the question bank).

The analogy is: rather than put the question back in the bank once it's been attempted, remove it from the bank so it can't appear in this learner's next attempts.

we have programmers who can work on this (we're waiting for end-client budget) but wanted to check whether any one else is interested in contributing to the specification, or is working on this already?

Thanks,

Tim @ Think

**Comment by oliverfoster** [comment]
We had this once I think but we had to revert it, you can still make out the shadow in the code that's there. The trouble was that one tends to run out of questions.
Having this behaviour as a configurable options would be preferable as it requires some diligent scripting and some thought to ensure the assessment is setup correctly with enough questions.
Thanks for volunteering 👍

**Comment by moloko** [comment]
I actually had to do this (avoid recycling questions until they've all been shown) on a project fairly recently, looking back at the code I made it work by adding
```js
if (this._questionBanks) return;
```
Just above [this line](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L206)

Assuming you're launching the course from an LMS you'll also need to enable `_shouldStoreResponses` for the spoor plugin to get it to remember what questions have been answered across 'sessions'.

**Comment by moloko** [comment]
FYI the requirement for the above project was that there were two questions in each bank (and several banks). On your first attempt it would randomly grab one from each bank to present to the user. On the next attempt it would grab the other one. After that it would simply start the process again (i.e. begin recycling questions).

Hope this helps.

**Comment by timnewham** [comment]
Thanks both. Loving the Adapt community already :)
