### ISSUE TITLE
Spoor: attemptsLeft attribute is getting reset on revisit.

### ISSUE THREAD

**Issue by chetan-hajare** [adaptlearning/adapt_framework#1982]
### Subject of the issue
The attemptsLeft attribute is getting reset on revisiting the non-submitted question.

### Your environment
All browsers

### Steps to reproduce
Test below scenario on SCORM 1.2
Suppose a MCQ component has 2 attempts and the user attempts a wrong answer and reset the question and close the course. On launching again, the question is shown unattempted(as expected). The user again attempts the wrong answer and again it provides reset button.

### Expected behaviour
On revisiting, if the user again attempts the wrong answer, the number of attempts left of that MCQ component should decrease and marked as complete with wrong answer as the user had already attempted the question twice.

### Actual behaviour
On revisiting, if the user again attempts the wrong answer, it provides reset button.

**Comment by moloko** [comment]
@chetan-hajare the problem here is that the spoor extension is only triggering a 'save' of the data when the question is completed - which only happens when you get the question right or use up all your attempts.

You could modify [this bit of adapt-stateful-session.js](https://github.com/adaptlearning/adapt-contrib-spoor/blob/719eff50dfdfaae9c528f6911a486597e227ee03/js/adapt-stateful-session.js#L95-L97) to:
```js
if (this._shouldStoreResponses) {
  this.listenTo(Adapt, {
    'questionView:showFeedback': this.onQuestionComponentComplete,
    'questionView:disabledFeedback': this.onQuestionComponentComplete
  });
}
```
Then you've just got the problem of [this bit of code in questions.js](https://github.com/adaptlearning/adapt-contrib-spoor/blob/719eff50dfdfaae9c528f6911a486597e227ee03/js/serializers/questions.js#L65-L68) - commenting that out _appears_ to work OK - but that's only after a _very_ cursory bit of testing!! I'd prefer if @oliverfoster (who wrote questions.js) could take a quick look and see if he can think of any undesirable impact of that change...

**Comment by chetan-hajare** [comment]
Agree with you @moloko 
Let's wait for the @oliverfoster comment

**Comment by oliverfoster** [comment]
This all sounds fine.

I would stop [question.js](https://github.com/adaptlearning/adapt-contrib-spoor/blob/719eff50dfdfaae9c528f6911a486597e227ee03/js/serializers/questions.js#L65-L68) from trying to save the `_userAnswer`:

Change:
```js
          if (component['_isInteractionComplete'] === false || component['_isComplete'] === false) {
            //if component is not currently complete skip it
            continue;
          }

          var hasUserAnswer = (component['_userAnswer'] !== undefined);
          var isUserAnswerArray = (component['_userAnswer'] instanceof Array);

          if (hasUserAnswer && isUserAnswerArray && component['_userAnswer'].length === 0) {
            hasUserAnswer = false;
            isUserAnswerArray = false;
          }
```
To: 
```js
          var isIncomplete = (component['_isInteractionComplete'] === false || component['_isComplete'] === false);
          var hasUserAnswer = (component['_userAnswer'] !== undefined);
          var isUserAnswerArray = (component['_userAnswer'] instanceof Array);

          if (isIncomplete || (hasUserAnswer && isUserAnswerArray && component['_userAnswer'].length === 0)) {
            hasUserAnswer = false;
            isUserAnswerArray = false;
          }
```

**Comment by akshay-bhavsar** [comment]
Could this be another possible solution at [adapt-stateful-session.js](https://github.com/adaptlearning/adapt-contrib-spoor/blob/719eff50dfdfaae9c528f6911a486597e227ee03/js/adapt-stateful-session.js#L95-L97)??

if (this._shouldStoreResponses) {
this.listenTo(Adapt.components, 'change:_attemptsLeft', this.onQuestionComponentComplete);
}

**Comment by moloko** [comment]
@akshay-bhavsar I _think_ so, would need to do some further testing to figure out for sure though. I did think about that but wasn't sure how it would work if you had a question set to `_attempts: -1` (infinite attempts)

Worth mentioning that with either suggested change you could actually drop `this.onQuestionComponentComplete` and attach directly to `this.saveSessionState` (as there should be no need for the `if (!component.get("_isQuestionType"))` check that's the only other line of code in `onQuestionComponentComplete`

**Comment by oliverfoster** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-spoor/tree/v3.5.0
