### ISSUE TITLE
add 'hide from menu' option

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1983]
As is evidenced by [this discussion](https://gitter.im/adaptlearning/adapt_framework?at=5a82fbb64a6b0dd32bc68d85) we have no standard method for stopping a page from being displayed on the menu. 

It would therefore be useful to add something to Adapt to handle this situation.

Suggest adding a property `_hideFromMenu` as a property of contentObject and then implementing this in [boxmenu](https://github.com/adaptlearning/adapt-contrib-boxmenu/)

**Comment by tomgreenfield** [comment]
Suggest using the already available `_isHidden`.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/d3f942fdbdf2f69fd9bf2e3b59e7869c15a71f31 - using `_isHidden` instead of creating a new property, as per suggestion
