### ISSUE TITLE
adapt-contrib-spoor: Tweak stateful session code to call model rather than view functions

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1990]
The Adapt model should take precedence in any check for the following methods:
- getResponseType()
- getResponse()
- isCorrect()

A fallback to call these methods on the view should be left in place.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/69f6ff6e05be632941a591a3d59c7df3a966b300
