### ISSUE TITLE
adapt-contrib-media: image too large w article-reveal

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2000]
When Media is used within Article Reveal, the poster image/widget is displayed too wide--until "device:resize".

I'm working on a Mac with OS X 10.11.6, using Chrome version 64.0.3282.186

### Steps to reproduce
1. Load up cgkineo's kitchen-sink.
2. Add a new block containing Media at full-width.
3. Build and run.
4. Navigate to Article Reveal and open it.
5. Media component is correct width but the widget with poster image extends beyond it.

![screen shot 2018-03-06 at 6 32 34 pm](https://user-images.githubusercontent.com/9489014/37065535-2678742c-216f-11e8-9595-d795158488e0.png)

While article-reveal is not core, I believe Media's code can easily accommodate a fix and is warranted by article-reveal's wide use.

I wish my understanding of Media were deeper, but I was able to overcome the problem by adding another selector in this function:
```javascript
onScreenSizeChanged: function() {
          //this.$('audio, video').width(this.$('.component-widget').width());
          this.$('audio, video, .mejs-container').width(this.$('.component-widget').width());
 },
```
The `.mejs-container` selector was pulled from `onDeviceResize()`.

**Comment by moloko** [comment]
@chucklorenz can I close this? I think it's really a problem with article reveal rather than media, as discussed [here](https://community.adaptlearning.org/mod/forum/discuss.php?d=33560)

**Comment by chucklorenz** [comment]
Yes, @moloko . I agree. Thanks
