### ISSUE TITLE
assessment: passed, infinite attempts, retry doesn't reset assessment

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2012]
### Subject of the issue
[This line](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L438) trips up [this code](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L630) when the assessment is passed but the [feedback band in assessment results](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/components.json#L1050) has a retry button. This is as the assessment refuses to reset when the retry button is clicked because the assessment `_isAttemptsLeft` returns `false` and as the [assessment results doesn't calculate the attempts left in the same way](https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/js/adapt-contrib-assessmentResults.js#L225).

### Expected behaviour
The retry button should always reset the assessment unless there are no attempts left.

### Suggested fix
The show marking and feedback once passed should check if the assessment is passed, not if the assessment has attempts left.

**Comment by chris-steele** [comment]
Yes, we need the expected behavour you mention @oliverfoster because we sometimes want to allow users who have passed to better their scores.

**Comment by moloko** [comment]
looks to have been dealt with via #1809
