### ISSUE TITLE
refactor/v5 - Theme

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2020]
Refactor theme js, less, and hbs files so that they conform to the BEM (http://getbem.com/) and SMACSS (https://smacss.com/) naming schemes. 

Current progress can be found at: https://github.com/adaptlearning/adapt-contrib-vanilla

- [x] colours
- [x] fonts
- [x] spacings
- [x] widths
- [x] buttons/icons
- [x] buttons/questions
- [x] buttons/marking

**Comment by markusd1984** [comment]
I think the correct link is https://github.com/adaptlearning/adapt-contrib-vanilla

I suggest that the "Feedback" button should be configurable or by default not visible when not used, for a more clear user experience. 

No point in showing it if the button can't be used in that scenario when disabled. Avoids confusion which I'm sure some people will try to click it :)

**Comment by guywillis** [comment]
v5 refactor is largely done and now merged with master.

@markusd1984 There have been updates to the Framework and Vanilla to automatically hide the feedback button and adjust the style of the submit button and marking icon when `_canShowFeedback` is set to false. 

For reference:
Issue with screenshots of before and after: https://github.com/adaptlearning/adapt_framework/issues/2627
Framework commit: https://github.com/adaptlearning/adapt_framework/commit/4d49814285a8b9a2c568d19456af14cb3eaec4be
Vanilla commit: https://github.com/adaptlearning/adapt-contrib-vanilla/commit/889d35dcdf6c5a4b0be4d96a707b502572be58e7

Closing issue.
