### ISSUE TITLE
Incorrect bookmarking when trickle is enabled

### ISSUE THREAD

**Issue by chetan-hajare** [adaptlearning/adapt_framework#2023]
### Subject of the issue
Incorrect bookmarking when trickle is enabled

### Steps to reproduce
Suppose an article has a trickle enabled, the user visits the first 5 blocks/components out of 7 blocks of that article and on 6th block the user close the browser. On revisit, the user clicks yes on bookmarking. The focus scrolls to second block instead of 6th block.

### Expected behaviour
On revisit, the user clicks yes on bookmarking. The focus should scroll to 6th block i.e. wherever the user has closed the browser.

**Comment by loudoweb** [comment]
It seems I have the same issue. The rooter seems to be set correctly, but after that the page scrolls to a random block instead of the bookmarked block. Did you find anything to fix the issue?

**Comment by NayanKhedkar** [comment]
Fixed:PR[#88](https://github.com/adaptlearning/adapt-contrib-trickle/pull/88)

**Comment by NayanKhedkar** [comment]
@loudoweb  any chance you could test this out?

**Comment by akshay-bhavsar** [comment]
I have faced the same issue, and i tried with https://github.com/adaptlearning/adapt-contrib-trickle/pull/88
it fixed the problem.

**Comment by loudoweb** [comment]
It seems to fix the bug.

**But** I have a regression: When I enter for the first time o ContentObject, sometimes the first block has unvisible trickle, so I need to scroll to go to the next block. Everything else is fine.

I'm using Adapt 2.1.2 so maybe the problem doesn't occur in last Adapt version.

**Comment by NayanKhedkar** [comment]
@loudoweb are you sure? before the **fixed** same thing didn't happened with you.Which component are you put into the first block(presentation/question)?

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-trickle/commit/5ad940dbdea016b596f6570e2880a0a0ec87f2f9

**Comment by loudoweb** [comment]
I've tested with graphic and text components as first block.

Before the fix, I had the trickle button in all blocks. With the fix, the first block doesn't have a trickle button (and well, I must say that sometimes, maybe 30%, the trickle button appears, so it's freaking weird) and the second block is already unlocked but other blocks are ok.
