### ISSUE TITLE
Framework 3.0.0 breaks the flipcard component

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_framework#2027]
### Subject of the issue/enhancement/features
For some reason when updating to Framework 3.0.0 it breaks the flipcard components animation to flip and text no longer is seen on the back of the flip card.

### Your environment
* Framework: v3.0.0
* Chrome/Firefox/Safari/Edge/Opera/IE11
* Windows/Mac

### Steps to reproduce
Inserted the flipcard component in the Framework also tried in the authoring tool with the same results

### Expected behaviour
Flipcards should animate on click and turn to reveal text on back.

### Actual behaviour
When a card is clicked there is no animation any more and the text on the back is gone.

### Screenshots (if you can)
<img src="https://user-images.githubusercontent.com/10455453/37409295-57875870-2774-11e8-9fc6-74f8181d6df5.jpg" border="0" />

**Comment by mike-st** [comment]
[https://github.com/ExultCorp/adapt-contrib-flipcard](url)

**Comment by tomgreenfield** [comment]
Some of Modernizr's feature detections were [removed](https://github.com/adaptlearning/adapt_framework/pull/1936/files#diff-f5623ddc8fb85794ab1eccc1b1557855R2) when the library was upgraded and Flipcard has a hardcoded check for [`csstransforms3d`](https://github.com/mike-st/adapt-contrib-flipcard/blob/master/js/adapt-contrib-flipcard.js#L76) support.

**Comment by moloko** [comment]
hi @mike-st that's not surprising - the change in major version from 2.x to 3.0 denotes 'breaking changes' so some plugin authors may well have to update their plugins to make them compatible with v3 of the framework.

if you installed flipcard via `$ adapt install` you should have been warned that it's not necessarily going to be compatible

It's really something for the plugin's author to resolve. I see you've logged an issue [here](https://github.com/ExultCorp/adapt-contrib-flipcard/issues/12) already so this duplicate isn't really necessary.
