### ISSUE TITLE
Matching question select2 library can be updated

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#2030]
### Subject of the issue/enhancement/features
We encountered a small bug on iPhone safari that was fixed by updating the matching component's select2 library from 4.0.3 to 4.0.5. 

The issue that we had was quite specific, but I think it makes sense to upgrade this library in case it could cause any other odd issues.

### Your environment
Matching component version - 2.1.4
iOS version - 11.2.6
This bug cannot be reproduced on a desktop browser it must be reproduced on a mobile device
We have noticed this with a range of iPhones running Safari

### Steps to reproduce
This issue is very specific and only occurs when keyframe animations are present on the page and when a matching question component has 2 or more attempts allowed to answer them.

Upon the first selection of answers, the drop-down menu for each of the options that contain the answers is visible.

If the user's answer selections are wrong, it will ask to reset the question and have another attempt. This is where the bug occurs.

Upon resetting the question and clicking on the drop-down menu for any of the options, the drop-down menu will be invisible to the user. The arrow for the drop-down options will point upwards as if the menu has been opened, but none of the answer options will be displayed. It seems like they are there, if you were to click on the empty space where the drop-down menu should be, it will recognise that you have made a selection and will display whatever invisible answer you had clicked on, but it won't show the actual drop-down menu with the options.

The browser on my phone that I have used is Safari. This issue does not happen on desktop safari/chrome/firefox.

**Comment by moloko** [comment]
what version(s) of iOS does this occur on?

**Comment by canstudios-nicolaw** [comment]
Apologies, I've added an iOS version that I know was affected, there may be more (but the person I would need to ask is on leave today).

I should probably also mention the keyframe animation was applied to a `:before` element, I'm not sure if it would make a difference but this issue seems specific enough that it might.

**Comment by oliverfoster** [comment]
Have removed select2 as not accessible and library is not maintained.
Replaced with native implementation.
