### ISSUE TITLE
adapt-contrib-vanilla: add style for blockquote

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2037]
as the text editor in the authoring tool supports adding `<blockquote>` the framework should really have some styling support for this element

**Comment by simondate** [comment]
PR for Vanilla - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/218

@moloko do you think this should be added into core? Just noticed that we already (refrence it in `reset.less`)[https://github.com/adaptlearning/adapt_framework/blob/master/src/core/less/reset.less#L17 ] with the `quotes` property being overriden. 

quotes - https://www.w3schools.com/cssref/pr_gen_quotes.asp

**Comment by moloko** [comment]
@simondate I'm really not the person to be asking about best practice for styling ;-)

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/216fc42b1b78c714dd41b3c8f07e63dc9fdf3f5c
