### ISSUE TITLE
adapt-contrib-assessmentResults: breaks when no feedback bands are specified

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#2039]
If no bands are specified in the component config then Handlebars.compile errors out, potentially preventing the page from loading.

### Steps to reproduce
Create a course with a question, assessment and assessmentResults component with a `_bands: []`  property
Submit the question
Exit and then revisit the page

### Expected behaviour
The course should not break. Pages should load as normal.
If this is a user config error then at the very least there should be a console warning.

### Actual behaviour
The course sticks on the loading screen
A handlebars error is thrown "You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined"

**Comment by moloko** [comment]
Happy to take a look at this @danielstorey - or are you already doing so?

**Comment by sarveshwar-gavhane** [comment]
well caught. @danielstorey are you working on this ? 
probably  ```  if (!feedbackBand) return; ``` will resovle this.
