### ISSUE TITLE
spoor: cmi.interaction tracking broken in spoor v3.0.0

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2046]
It looks like #1990 is the cause of the problem - specifically the function `onQuestionRecordInteraction` in adapt-stateful-session.js is checking to see if the relevant function exists on the model by doing:
```js
var responseType = typeof questionView.model.getResponseType === 'function' 
                 ? questionView.model.getResponseType()
                 : questionView.getResponseType();
```
Unfortunately since questionModel.js include an 'abstract' implementation of `getResponseType`, the code `typeof questionView.model.getResponseType === 'function' ` will always return `true`.

At this point in time, ~all the question components - event those that have been updated to model/view - have `getResponseType` and `getResponse` defined in the view, not the model.~ the only question components with 'concrete' version of these functions defined on the model are MCQ & GMCQ.

For all other question components, the 'abstract' functions in questionModel.js always get called rather than the 'concrete' implementations in the question components' view.

**Comment by oliverfoster** [comment]
A link to the above referenced [code](https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-stateful-session.js#L170).

`questionView.model.getResponseType` [always exists](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/questionModel.js#L331) as it is declared on the inherited class. The above referenced ternary won't ever fall into the false side.

We need to check if the function defined on the model instance is the dummy function from the questionModel class.
```js
define([
	'core/js/adapt',
	'./serializers/default',
	'./serializers/questions',
	'core/js/enums/completionStateEnum',
	'core/js/models/questionModel',
], function(Adapt, serializer, questions, COMPLETION_STATE, questionModel) {
```
^ add this
```js
var model = questionView.model;
var isModelFunctionInherited = (model.getResponseType === questionModel.prototype.getResponseType);
var isViewFunctionAvailable = (questionView.getResponseType !== undefined);

var responseType = isModelFunctionInherited && isViewFunctionAvailable
                 ? questionView.getResponseType()
                 : model.getResponseType();

```
^ change the function checker ternary to something like this

That should also allow to remove all `questionView.getResponseType` declarations without causing issues in spoor.

**Comment by brian-learningpool** [comment]
If we're (slowly) removing getResponseType() from the views couldn't we just switch the precedence?
```js
var responseType = typeof questionView.getResponseType === 'function' 
                 ? questionView.getResponseType()
                 : questionView.model.getResponseType();
```

Or does the question view compatibility code (https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/questionView.js#L380) prevent that?

**Comment by moloko** [comment]
@brian-learningpool I was thinking along those lines myself, I'm just struggling a bit with keeping track of all this what with the view compatibility code, backwards-compatibility support and so on! I think I just need to get in and do some debugging to find out what works...

**Comment by moloko** [comment]
actually from what I'm seeing there's probably no need to do any checking here at all... the 'question view compatibility code' seems to be doing all the work already so I think it's just a case of calling `questionView.getResponseType()` (etc) and letting that code handle it all... @oliverfoster does that sound about right to you?

**Comment by moloko** [comment]
So from what I can see, reverting the changes made in #1990 would fix this...

**Comment by oliverfoster** [comment]
although that would work, the compatibility code is not meant to supply a method for new code to interact with the view in lieu of direct model interaction.

**Comment by brian-learningpool** [comment]
Won't the compatibility code also be removed at some point?  I thought this was intended as a facade while this model/view split is in progress.

**Comment by oliverfoster** [comment]
The end goal it that spoor reads the data from the model.

By making spoor use the view always and then the view through the compatibility layer it means that we are quite far from the goal.

We can certainly do that as it'll be an easy fix. It means we'll have to come back later when those functions are permanently removed from the view.

**Comment by moloko** [comment]
> It means we'll have to come back later when those functions are permanently removed from the view.

Yes but not for quite some time. The compatibility layer will need to be left in place for a fair while after we have fixed all the core question components - as we'll need to give plugin authors a deprecation warning and time to update their code...
