### ISSUE TITLE
update to underscore v1.9.x?

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2047]
looks like it has a few useful new additions...
http://underscorejs.org/#1.9.0

**Comment by lc-thomasberger** [comment]
Should we move to lodash instead? .... it should be much faster than underscore.

**Comment by oliverfoster** [comment]
[lodash vs all](http://danieltao.com/lazy.js/comparisons.html).
lodash does have much extended functionality.
[underscore usage is in decline](https://lgtm.com/blog/lodash_vs_underscore). 
[lodash definitely probably fully supports backbone.](https://github.com/jashkenas/backbone/blob/1.2.1/index.html#L602-L613)

**Comment by tomgreenfield** [comment]
Ready when you are, @moloko.

**Comment by oliverfoster** [comment]
lodash vs breaks with underscore btw. i found out to my detriment the other day. no pluck only map.

**Comment by brian-learningpool** [comment]
So the idea is to go to v1.9.1?

**Comment by moloko** [comment]
@brian-learningpool that's the plan. We're currently on v1.8.3 (released April 2015!) and v1.9.1 is the latest version.

I'll give it a quick test against OOTB adapt first in a few browsers and report back, we can decide whether to proceed or not from there.
