### ISSUE TITLE
adapt-contrib-vanilla: remove .gitignore

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2060]
### Subject of the issue/enhancement/features
The presence of .gitignore causes SVN commits to fail. Suggesting that we remove them from all plug-ins that still have them.

### Your environment
* adapt-contrib-gmcq ver 3.0.0 (#2059)
* adapt-contrib-vanilla ver 3.0.0
* adapt-contrib-narrative ver 2.1.0 (#2061)

### Steps to reproduce
1. Include component in build
2. Commit build to SVN repository

### Actual behaviour
Build fails because SVN doesn't accept .gitignore files

### Rationale
* Consistency. The majority of plug-ins don't have a .gitignore
* Annoyance. I keep forgetting to check this each time I include them and it's driving me craaaaaaaaazzzzzzy when I got to commit.

**Comment by tomgreenfield** [comment]
I'd highly recommend that your SVN client be set up to ignore `*.gitignore` files. In TortoiseSVN this can be achieved via _Settings > General > Global ignore pattern_.

That being said, I agree that these particular `.gitignore`s shouldn't exist.

**Comment by chucklorenz** [comment]
On a Mac and using Versions, but tracked it down. Thanks for the push, @tomgreenfield

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/f79b33fb7114e89bb8ad1d6745ce876269286c08
