### ISSUE TITLE
contrib-vanilla: block-title-font-size and article-title-font-size variables

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2063]
Currently the `.article-title` and `.block-title` are assigned the same font size as the `.component-title` https://github.com/adaptlearning/adapt-contrib-vanilla/blob/f79b33fb7114e89bb8ad1d6745ce876269286c08/less/src/fonts.less#L48

Seems like this could be easily fixed by introducing 2 new variables that are increased by 2-4 px each

**Comment by moloko** [comment]
@simondate in vanilla v5 there are now variables that allow you to set the article/block/component title font sizes individually (via _font-config.less). They are currently all set to 2.5rem, though.

Can I close this?
