### ISSUE TITLE
Is there any reason why all components don't have the option of mobile instructions?

### ISSUE THREAD

**Issue by jose-campos-sr** [adaptlearning/adapt_framework#2068]
Just wondering if there is a reason for that. The narrative does have it but the core components.hbs doesn't. Ideally the components.hbs would have both and a fallback, and the corresponding one would be shown using CSS. Would this cause a screen reader issue?

**Comment by lc-thomasberger** [comment]
Usually mobile instruction is only available when the component is different on mobile or desktop. For instance Hotgraphic gets replaced with narrative on mobile devices, so instructional designers can define different instruction texts for each device type.
