### ISSUE TITLE
contrib-narrative/-hotgraphic mobileInstruction only works with instruction

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2069]
### Subject of the issue/enhancement/features
The `mobileInstruction` attribute works by replacing the `instruction` text. But if `instruction` hasn't been assigned there is nothing to replace so it's never loaded in.

### Steps to reproduce
*  Create a narrative or hotgraphic
*  Set a `mobileInstruction` but not a `instruction`

**Comment by simondate** [comment]
##  suggested fix

Have two separate HTML attributes and use CSS media queries to hide/show the correct one. This is also probably more performant than a Jquery call.

**Comment by NayanKhedkar** [comment]
PR: https://github.com/adaptlearning/adapt_framework/pull/2093

**Comment by moloko** [comment]
done in f99f798
