### ISSUE TITLE
Standardise naming convention for helpers in Framework

### ISSUE THREAD

**Issue by ryangadams** [adaptlearning/adapt_framework#207]
Helper Functions should either be camelCased or underscore_separated but not both.

**Comment by taylortom** [comment]
is this referring to [handlebars helpers](https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/helpers.js)?

**Comment by oliverfoster** [comment]
yup

**Comment by oliverfoster** [comment]
i went with "_" rather than camel case, there were more of them (see [resource](https://github.com/adaptlearning/adapt-contrib-resources/blob/master/js/adapt-contrib-resourcesHelpers.js))
