### ISSUE TITLE
ItemsComponentModel has obtuse implementation

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2071]
### Subject of the issue/enhancement/features
The way the `ItemsComponentModel` is written with regards to `_items` breaks backward compatibility with existing functionality unnecessarily.
`_items` is replaced by a Collection of Models which makes any existing code relying on `_items` being an array of objects stop working [at this line](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/itemsComponentModel.js#L30)
`toJSON` is then overridden to compensate, [at this line](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/itemsComponentModel.js#L8-L13)

### Expected behaviour
`_items` should return an array of objects.
`_children` should represent the collection, as with the other models.

**Comment by moloko** [comment]
I think this is all done now?
