### ISSUE TITLE
add better error handling for grunt translate:export

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2098]
### Subject of the issue/enhancement/features
Currently if an error occurs when running the `grunt translate:export` task, no detail is given, making it extremely challenging to debug

### Your environment
* framework
* CLI

### Steps to reproduce
Not sure yet, will add if user finds out source of problem

### Expected behaviour
A useful error should be displayed allowing the developer to pin-point if not the exact source of the problem then at the very least which plugin is failing

### Actual behaviour
The task halts providing very little in the way of useful information - see screenshot

### Screenshots (if you can)
![2018-05-24 11_36_36-gitter](https://user-images.githubusercontent.com/1249597/40480735-4e0acb5a-5f47-11e8-8279-62bfdaf30e71.png)

**Comment by moloko** [comment]
Just to note that in this particular instance one/some/all(?) of the core .schema files was missing - this was due to [a bug in the Authoring Tool's 'export' functionality](https://github.com/adaptlearning/adapt_authoring/issues/1512) which has since been fixed.

**Comment by moloko** [comment]
@oliverfoster by any chance did your recent work on #2736 do anything to improve this?

**Comment by oliverfoster** [comment]
Yes, it only loads schemas available. So no, it won't warn if they are missing.
