### ISSUE TITLE
Able to generate an additional launch page which launches Adapt in a popup 

### ISSUE THREAD

**Issue by svenlaux** [adaptlearning/adapt_framework#210]
In order to make Adapt SCORM packages work more easily with Moodle (and stay responsive), the option to generate an additional launch page, which launches the main Adapt content in a popup is needed. Ideally this would be implemented as a grunt publish option.

This additional launch page should be referenced in the imsmanifest.xml file. 

Additional info on the context at: https://community.adaptlearning.org/mod/forum/discuss.php?d=180

**Comment by derekc** [comment]
Just curious.  I have got here from the discussion linked to above.  Is there any progress on this?

**Comment by hmaffin** [comment]
Yes I would like to see this incorporated into the download of courses too as a configurable option - currently one has to unzip the package, paste in your own custom pages and then rezip before uploading.

**Comment by moloko** [comment]
Adding the file in isn't a problem, it's amending imsmanifest.xml to point to it that's the problem. Easy to do if you're using the framework - but there's no way to do this with the authoring tool as things stand.

**Comment by moloko** [comment]
It would also be useful to have the ability to set this additional page to launch the course in a new window only on certain platforms... for example on iOS only since that's the platform that generally has issues with content being displayed in an `<iframe>` or `<frameset>`.

**Comment by moloko** [comment]
see the [adapt-launchNewWindow extension](https://github.com/cgkineo/adapt-launchNewWindow)
