### ISSUE TITLE
adapt-contrib-narrative: completion issue

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2100]
### Steps to reproduce
If the component is initially rendered at small or medium screen sizes, and then subsequently resized to large, the narrative is not complete upon visiting all items.

### Actual behaviour
Under the above conditions, the component only completes when returning to the first item again. Essentially the `setStage` method needs to be called during the resize to set the current item (in this case first item) to `_isVisited`.

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-contrib-narrative/pull/182

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-narrative/commit/a5f4eb262de118be89531e4d27a52f34bc922015
