### ISSUE TITLE
adapt-contrib-text: completion status

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#2109]
### Subject of the enhancement

If the Text component is used within a Blockslider on the last block, completion on the Article is triggered before the Text component has come into view.

The inview completion for the Text component is calculated with VisibleY, could it perhaps also check for VisibleX [here](https://github.com/adaptlearning/adapt-contrib-text/blob/dd2830cf3d9033d4d7f7e21f536e533c2b8cb97c/js/adapt-contrib-text.js#L53)?

**Comment by jamesrea83** [comment]
Just had a look at this one, and I'm unable to replicate now. I can't track down what's fixed it, but think this issue can be closed.
