### ISSUE TITLE
Recommended eslint

### ISSUE THREAD

**Issue by Enngage** [adaptlearning/adapt_framework#2116]
Hi,

We installed our course with adapt-cli using

`adapt create course "My Course"`

And we wanted to use eslint to help us keep the code clean. There isn't any default eslint in the installed project and code seems to be inconsistent (i.e. double quotes vs apostrophes, missing spaces, extra spaces ...) Can you provide us with the eslint config you are using or any other way of keeping the code clean and consistent?

**Comment by moloko** [comment]
You can run `grunt jshint` but you'll just get a huge pile of errors. 

Personally I use [VSCode](https://code.visualstudio.com/) together with the [JSHint extension](https://github.com/Microsoft/vscode-jshint) and the following configuration:
```json
{
  "esversion": 6,
  "funcscope": true,
  "latedef": "nofunc",
  "-W065": false
}
```
You can find the Adapt styleguide [here](https://github.com/adaptlearning/documentation/blob/master/01_cross_workstream/style_guide.md)

I don't think we have a particular rule about single vs double quotes, personally I tend to go with single quotes for selectors/property names and double for actual string values e.g. `myobj['someprop'] = "some value";`

We are slowly trying to get the code up to more modern standards, it's just a slow process. We were still supported IE8/9/10 until this year - and sadly will have to support IE11 for some years yet 😢

**Comment by Enngage** [comment]
Awesome, will take a look. Thanks for quick response :-)
