### ISSUE TITLE
Loading course data

### ISSUE THREAD

**Issue by Enngage** [adaptlearning/adapt_framework#2117]
Hi, 

As far I understand it, you expect that all data related to the course is in a form of a `json` files (`articles.json`, `blocks.json` ...) which need to be generated **prior of building the course**, is that correct? We wanted to load data externally rather than from the files so that we don't need to rebuild the package each time something changes in the course. Is this supported in some form? 

The other major problem I have is also the fact that even though you have all course information you need available during build time, the browser still makes GET requests to get the data - why is it this way? We might have quite large courses and the JSON can easily get over 20MB of data, do you expect that these should be loaded by client (browser) when accessing the course (same thing goes for reloading a page)?

Would be really grateful for any feedback you can provide, thanks!

**Comment by moloko** [comment]
hi @Enngage - if you have questions about the functionality of Adapt would you mind asking them in [the forums](https://community.adaptlearning.org/mod/forum/view.php?id=4) or in whichever one of the [chat rooms](https://gitter.im/adaptlearning) is most appropriate? 

No, you don't need to rebuild the course every time you change the json. If you are using the adapt-cli, the build/dev process merely copies the json files into the build folder - which you could do by hand. equally you could have a look at [rub-cli](https://github.com/cgkineo/rub-cli) which doesn't require you to have a copy of all your json and assets in the src folder - so you only have to rebuild if you change the less/js/hbs. You can also build multiple courses from the same src which can be very handy.

Yes, it is necessary for the course to load the JSON files at run-time. The course content has to be stored and loaded from somewhere, so keeping it separated out into json files like that is good practice as it separates content from code.

**Comment by moloko** [comment]
@Enngage any chance we could continue the conversation [here](https://gitter.im/adaptlearning/adapt_framework)? just a bit easier to ask questions in slightly more 'real time' of a chat environment. you can log in with your github account.
