### ISSUE TITLE
Trickle issue with JAWS w.r.t. new incomplete content aria

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2135]
### Subject of the issue
JAWS reads “incomplete content above” after completing an assessment question and moving to the next question. Related to recent addition of aria label ‘incomplete content’.

### Your environment
* Framework 3.0.0
* IE11
* Windows 7

### Steps to reproduce
Use JAWS 17/18 to complete an assessment question (where trickle is enabled).

### Expected behaviour
The text “incomplete content above” should only read if trickle is locked.

### Actual behaviour
(already described)

**Comment by chris-steele** [comment]
@kirsty-hames is this description OK with you?

**Comment by kirsty-hames** [comment]
@chris-steele, yep perfect thanks

**Comment by oliverfoster** [comment]
Must have a no button configuration for this to be replicated.

**Comment by oliverfoster** [comment]
done

**Comment by chris-steele** [comment]
Sorry folks, looks like this needs to be reopened. Issue #120 in uk-lcel-406405 (client trac) brought this ticket to my attention. It's also replicable in OS. The odd way to replicate it is to have full-width questions. Any ideas?

**Comment by oliverfoster** [comment]
Nobody but the Kineo people know what the client trac is. Could you explain the issue in more detail, perhaps open a new ticket? Listing the framework version, trickle version, trickle config, page layout quirks, how to replicate etc.

**Comment by chris-steele** [comment]
@oliverfoster client trac was for your benefit in case you were the one picking it up. Anyway all you need to do to replicate is take the OS course and make one of the questions in the assessment a full width component. After you select submit you will hear the "incomplete content" message.

**Comment by oliverfoster** [comment]
This ticket is for framework 3. It sounds like you're on fw v4? Are you using the master version of trickle of a release version?

**Comment by oliverfoster** [comment]
Can I close this issue, fix it in the course and then bring it back into public if it needs it? It'll need a new ticket and the information here isn't sufficient for others to agree to a pr.

**Comment by chris-steele** [comment]
It's for v4 master, yes.
