### ISSUE TITLE
Row with [Graphic + Multiple Choice Question or Multiple Choice Matching] not responsive

### ISSUE THREAD

**Issue by canstudios-louisem** [adaptlearning/adapt_framework#2136]
_From @trueschool on June 15, 2018 17:14_

# BUG Template

Hi all -- my colleague and I noticed that, when we have a row containing a graphic + either a multiple choice question or multiple choice MATCHING question, the image disappears in the responsive phone view rather than floating under or above the other component. It stays visible in "desktop", "tablet", and "phone landscape" views, but in "phone portrait", it's gone without a trace. Is this a known issue?

## Expected Behaviour

I expect the graphic to responsively nest above or below the question component as usual when viewed on any device viewport size. 

## Actual Behaviour

Graphic disappears when viewed in phone portrait layout. 

## Steps to Reproduce
1. Create an assessment with a row containing a graphic component and a mcq component
2. Shrink down to phone portrait layout
3. Wonder where your image went

## Versions
  - Authoring Tool Version: unknown
  - Framework Version: unknown
  - Operating System: Mac and Windows
  - Browser: Chrome and IE 11

_Copied from original issue: adaptlearning/adapt_authoring#1988_

**Comment by moloko** [comment]
This isn't a bug, it's just the way the vanilla theme is configured to handle graphic components that are part of an assessment article, see [this class in theme-extras.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/src/theme-extras.less#L67-L75)

This can either be disabled or overridden - whatever is most convenient.

If you have the same setup outside of an assessment, the graphic won't be hidden.
