### ISSUE TITLE
Couldn't Install Adapt

### ISSUE THREAD

**Issue by ashithvl** [adaptlearning/adapt_framework#2140]
### Subject of the issue/enhancement/features
Hi, Installed grunt-CLI globally and using node version 6x.
When I tried to run npm install -g adapt-cli, its throwing error

![image](https://user-images.githubusercontent.com/21255050/41574096-a05a6518-739d-11e8-905f-ed2dedb0c7d5.png)

**Comment by moloko** [comment]
this seems to me to be more a problem with Nodist - which I note doesn't seem to be actively maintained at this time - it doesn't seem to be handling setting up the 'junction point' correctly so it's failing to install nodegit cause it thinks the path is "C:\Program"

If you need a node version switcher then [nvm-windows](https://github.com/coreybutler/nvm-windows) works and is actively maintained

**Comment by ashithvl** [comment]
Tried the recommended nvm and still couldn't get adapt installed
![image](https://user-images.githubusercontent.com/21255050/41635381-0f5ac836-7466-11e8-8f28-a76049c97d34.png)

**Comment by moloko** [comment]
that screenshot still shows 'nodist' in the path...

**Comment by moloko** [comment]
@ashithvl maybe download a 'clean' VM from [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) so that you can do the setup from scratch without fear of something you have previously installed causing problems?

**Comment by ashithvl** [comment]
Isn't there a way to remove `nodist` completely from my system?
