### ISSUE TITLE
Expose framework version in DOM

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2143]
Suggest exposing the framework version as a data attribute:
```html
<html data-adapt-framework-version="3.1.0">
```
This would allow us, amongst other things, to style specific versions of framework. For example, the CSS selector for v3.x would be:
```css
[data-adapt-framework-version^="3"]
```
Inspired by https://github.com/adaptlearning/adapt_authoring/issues/1944.

**Comment by oliverfoster** [comment]
:O

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt_framework/pull/2144
