### ISSUE TITLE
_useGraphicsAsPins broken styling

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2145]
### _useGraphicsAsPins configuration is broken without further styling
_useGraphicsAsPins renders images as CSS background-images. Both the targeted element and parent are empty so the CSS width: 100% height: 100% don't do anything. This renders collapsed items so no images are displayed. Should these be img tags instead?

**Comment by moloko** [comment]
@kirsty-hames I checked `_useGraphicsAsPins` during my testing of https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/147 and it was working fine this morning, so I think this may have been fixed in the v3.0.0 release of HotGraphic I did a few hours ago?

**Comment by moloko** [comment]
as we've found this was down to there being two `_classes` properties, only one of which actually works... see #2146
