### ISSUE TITLE
Adapt Demo Course doesn't load 'Presentation Components' page

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#2147]
After downloading the latest Framework and running locally the Presentation Components page hangs on the loading screen. All other pages load ok.

It seems the Narrative component is causing a loading issue (screenshots below).

### Your environment
* fw 3.1.0
* IE11
* Windows 10

### Steps to reproduce
Download latest framework v3.1.0, install in the usual manner and run grunt server to view.

### Expected behaviour
Selecting the Presentation Components menu item should load the page.

### Actual behaviour
The Presentation Components page hangs on the loading screen.

### Screenshots

![image](https://user-images.githubusercontent.com/7251995/42036251-d5015628-7adc-11e8-9c87-97eda897d999.png)

![image](https://user-images.githubusercontent.com/7251995/42036285-efe2e2cc-7adc-11e8-9e46-106ae3c80845.png)

**Comment by moloko** [comment]
@RobertPeek if you use the framework master branch it should work as expected; I will be releasing a new version of the framework fairly shortly.

**Comment by RobertPeek** [comment]
Ah yes Ok I will do that. I can see the fix in the master branch now.

Cheers @moloko

**Comment by moloko** [comment]
no problem @RobertPeek and apologies for the mistake, v3.2.0 has been released now
