### ISSUE TITLE
Revert hotgraphic popup to notify styling.

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2148]
### Subject of the issue
Mimicking the old popup seems a bit heavy handed and unnecessary.

**Comment by moloko** [comment]
I would certainly like to see this updated now the ItemsModelComponent work is done

I think it would help everyone to see some mockups of what this might look like?

**Comment by oliverfoster** [comment]
I don't have the graphics skill to do mockups nor the power to request any, it would be easier for me to do the work and have everyone critique it.

**Comment by moloko** [comment]
@oliverfoster i don't think it requires any graphics skills just use of a mockup application such as invision etc. Nor was I suggesting it was something you needed to do just because you logged this issue!

**Comment by guywillis** [comment]
Whilst refactoring the latest version of the hotgraphic component I set up, what I think, the default structure and layout of the hotgraphic pop up in notify should look like:

<img width="1199" alt="screen" src="https://user-images.githubusercontent.com/11569678/42277855-b3c0dae8-7f90-11e8-820d-8e28a0023ee8.png">

(I'm aware there are two close buttons in this screenshot. It potentially looks like we can try the hotgraphic one as it's no longer required)

**Comment by guywillis** [comment]
As of v5 the Hotgraphic item pop up no longer mimics the old style and instead uses the standard Notify styling. See example below:

<img width="1201" alt="screen" src="https://user-images.githubusercontent.com/11569678/72883993-46c61300-3cfd-11ea-816d-a401533afece.png">
