### ISSUE TITLE
Ampersands from course title are not properly escaped when generating tincan.xml file

### ISSUE THREAD

**Issue by mediabounds** [adaptlearning/adapt_framework#2149]
### Subject of the issue/enhancement/features
Ampersands from course title are not properly escaped when generating tincan.xml file.

### Your environment
* 3.0.0 (AT/Framework)
* adapt-contrib-xapi

### Steps to reproduce
(I'm using the Adapt authoring tool--though the issue would impact building courses from command line too)
1. Install the adapt-contrib-xapi extension
2. Create a new course that contains an ampersand in the title
3. Add the adapt-contrib-xapi extension to the course
4. Build and download the course
5. Open and look at the tincan.xml file (or try to run it through a validator)

### Expected behaviour
The ampersand in the course title should be rendered `&amp;`

### Actual behaviour
The ampersand is rendered `&` causing invalid XML.

**Comment by moloko** [comment]
@mediabounds please could you see if https://github.com/adaptlearning/adapt-contrib-xapi/pull/29 helps?

FYI could you log future issues for adapt-contrib-xapi [here](https://github.com/adaptlearning/adapt-contrib-xapi/issues/new)?

**Comment by mediabounds** [comment]
Yep! That solves it.
I opened it here because I assumed it was a problem with a grunt task in the framework...I hadn't thought of just wrapping it in CDATA. Thanks!
