### ISSUE TITLE
adapt-contrib-media closed caption is not available for touch devices.

### ISSUE THREAD

**Issue by akshay-bhavsar** [adaptlearning/adapt_framework#2151]
### My environment
* version 3.1.0 (AT/Framework)
* Chrome
* Touch + Android/IOS

### Expected behaviour
CC button should appear in media player on touch device also. 

ScreenShot is as below: 
![screenshot_2018-07-03-11-55-03-220_com android chrome](https://user-images.githubusercontent.com/26135970/42202608-ae665744-7eb9-11e8-8883-572e6d86979d.png)

**Comment by moloko** [comment]
Works fine on iOS v11.4

![issue-2151-ios-v11 4](https://user-images.githubusercontent.com/1249597/42210034-1a5856ee-7ea8-11e8-8420-de28ccbd73e7.png)

**Comment by moloko** [comment]
I don't have an actual Android device to test on but in the Chrome device emulator it works OK:
![issue-2151-chrome_emulator](https://user-images.githubusercontent.com/1249597/42210267-99952270-7ea8-11e8-8d68-39b3aad011de.png)

**Comment by akshay-bhavsar** [comment]
yes you are correct, but when i tested on actual android device it is not appearing.
Please find above attached screen-shot.

**Comment by moloko** [comment]
@akshay-bhavsar is this issue still occurring?

**Comment by chetan-hajare** [comment]
The issue is not occuring on Android/iOS devices.
