### ISSUE TITLE
remove course from Framework-Repository 

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#2152]
### Subject of the issue/enhancement/features
I think we should move the demo content to its own Repository. This would make "sharing" different examples also a lot easier. We might also support different starter templates or allow the creation of custom templates.

This will also make live for the AT easier, as the default course must be deleted.

###  Expected behaviour
Creation of a new course should start with an empty course or course template.

**Comment by oliverfoster** [comment]
related to #2363
