### ISSUE TITLE
enhancement/themeRefactor - 'grunt dev' device size defaults

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2153]
I have changed the default large / medium / small device width dimensions from being px based (900 / 760 / 520) to em based (56.25 / 47.5 / 32.5) as part of the theme refactor. 

As a consequence, I have encountered a bug with the `grunt dev` command whereby if I amend a `.json` file then the defaults revert back to the px based values even though I have updated the defaults in `configModel.js` and `theme.json` to be em based. 

![image](https://user-images.githubusercontent.com/11569678/42220081-dd794242-7ec5-11e8-9b3f-ce2c6d3ab595.png)

**Comment by oliverfoster** [comment]
### To reproduce
1. Edit json save,
2. Edit less, save
3. ????
4. Bug
