### ISSUE TITLE
Trickle - Switch to using core behaviour

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2176]
### Subject of the issue
* jquery.resize is now included in the framework and can be removed from trickle
* [getDescendants](https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/lib/adaptModelExtension.js#L22) can be matched with [getAllDescendantModels](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L328)
* [findRelative](https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/lib/adaptModelExtension.js#L63) is matched with [findRelativeModel](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L413)
* [parseRelativeString](https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/lib/adaptModelExtension.js#L155) is matched with [Adapt.parseRelativeString](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/adapt.js#L291)

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-trickle/commit/7d45fc02094275e2250de690bdd23d92d6c42be1
