### ISSUE TITLE
accessibility: Notify height larger than expected

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2179]
This is caused by the focus guard. Tested on the accessibilityv4 branch.

<img src='https://user-images.githubusercontent.com/922987/43071613-4687490a-8e6b-11e8-9f68-d7ec111f4da7.png' width='350'>

**Comment by oliverfoster** [comment]
fixed by moving focus guard to outside of notify body by switching to template based inclusion https://github.com/adaptlearning/adapt_framework/commit/d5dc91318fad2a851c1e5434e0074cf3056fb6f4#diff-bd1b77dd473c66d0462300639078b5a4R51

**Comment by oliverfoster** [comment]
merged
