### ISSUE TITLE
Notify broken in legacy branch

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2183]
User cannot close Notify and gets stuck.

Probably related to https://github.com/adaptlearning/adapt_framework/pull/2115.

**Comment by brian-learningpool** [comment]
The problem is with this line:
https://github.com/adaptlearning/adapt_framework/pull/2115/commits/15220cd0c252d09056cdfa7c95060baba24df216#diff-50fb8c8046fd19708b379d70257f0e76R173

`if (this.isOpen) return;` was actually `if (!this.isOpen) return;` in the original fix.

**Comment by moloko** [comment]
my bad, shouldn't have skipped the review process on that legacy PR
