### ISSUE TITLE
Facilitate component-style sub views

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2185]
### Subject of the enhancement
In some places in Adapt we inject DOM elements from one extension into another. This practise isn't possible with frameworks like VueJS and React. We need to allow instantiation of registered 'component style' views in Adapt.

### External examples
VueJS: https://vuejs.org/v2/guide/components-registration.html
React: https://reactjs.org/docs/components-and-props.html#composing-components

### Expected outcome
This should allow us to move to a more appropriate style of injection, ready for future frameworks, without changing too much. 

#### Handlebars
Pass the Adapt model by id.
```html
{{subview name="menu:progress" id=this._id}}
```
Create a model from the data specified.
```html
{{subview name="component:completionIndicator" model=this}}
```
#### JavaScript
```js
var MenuProgress = Backbone.View.extend({
    initialize: function() {

    }
});
Adapt.subviews.register("menu:progress", MenuProgress);
```

**Comment by Link2Twenty** [comment]
When it comes time to pick a framework it may be worth looking here for pros and cons https://custom-elements-everywhere.com/
