### ISSUE TITLE
Outstanding accessibility PRs

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2206]
For accessibilityv4 branch https://github.com/adaptlearning/adapt_framework/tree/accessibilityv4

All PRs build out into release candidate: https://github.com/cgkineo/accessibility-v4

Need +1s from non-Kineo members on some PRs.

Kineo members:
@moloko 
@chris-steele 
@tomgreenfield 
@kirsty-hames 
@oliverfoster

**Comment by moloko** [comment]
PRs needing non-Kineo review:
https://github.com/adaptlearning/adapt-contrib-media/pull/183
https://github.com/adaptlearning/adapt-contrib-mcq/pull/142
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/155
https://github.com/adaptlearning/adapt-contrib-graphic/pull/67
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/116
https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/39
https://github.com/adaptlearning/adapt-contrib-glossary/pull/36
https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/83

**Comment by oliverfoster** [comment]
New release candidate with all above prs included: https://github.com/cgkineo/accessibility-v4

**Comment by oliverfoster** [comment]
New release candidate with all above prs included: https://github.com/cgkineo/accessibility-v4

**Comment by oliverfoster** [comment]
Republished release candidate: https://github.com/cgkineo/accessibility-v4

**Comment by oliverfoster** [comment]
Closing in favour of https://github.com/adaptlearning/adapt_framework/issues/1946
