### ISSUE TITLE
accessibility: improvements to correct/model answer functionality

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2215]
Following a suggestion from a client on reviewing an accessible Adapt course, it was felt that this could be improved by allowing the 'correct/model answer' button to be made available to screen reader users, in combination with assigning descriptions for the ticks and cross images.

Naturally this is mainly focussing on MCQ/GCMQ and bit more thought will be needed for more questions like Slider, but it still sounds like a good suggestion.

**Comment by oliverfoster** [comment]
description moved to #2241
