### ISSUE TITLE
add option to prevent tracking/bookmark data from being discarded when switching language

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2216]
If you have a multi-language course where you know for sure all the languages have _exactly_ the same content structure then it would be useful to allow a learner to be able to switch languages without all the progress data and bookmark data being discarded.

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/32
@moloko can you give a try?
