### ISSUE TITLE
adapt-contrib-spoor: finish - SCORM 2004

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2222]
Should we consider only triggering the API.Commit during the `terminate` method (https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/libraries/SCORM_API_wrapper.js#L393) for SCORM 1.2 - SCORM 2004 triggers an implicit commit of the data during the API.Terminate on the LMS.

This shouldn't matter, but the Cornerstone OnDemand LMS purposefully returns null early from the API.Commit as the browser unloads, instead waiting for the implicit commit of the API.Terminate - this raises the "Course could not finish" error (https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/scorm/wrapper.js#L314). The LMS shouldn't be making the assumption here to ignore the API.Commit and return a null value and a 391 error code, but I don't see them amending the API to prevent this. This also means Adapt doesn't actually trigger the API.Terminate, although this is still being handled, presumably by the LMS when it detects this unexpected event.

I haven't seen this issue in other LMSs, but due to the popularity of CSOD, it might be worth considering limiting the current functionality to SCORM 1.2 only, where an implicit commit in the LMSFinish isn't part of the standards.

As per the SCORM 2004 RTE:
>There is typically no benefit in calling Commit(“”) immediately prior to calling Terminate(“”). It does no harm since there would be nothing new to commit during the Terminate(“”) function call.

**Comment by moloko** [comment]
@danielghost interesting, I always thought that SCORM 1.2's LMSFinish call included an implicit call to LMSCommit but having checked the docs I can see no reference to that at all, accordingly I think it's entirely appropriate to only call `scorm.save` when `scorm.version === "1.2"`.

Strictly speaking this is an issue that should be handled over at the pipwerks repository (and I think you should still log it there) BUT Phil seems to have gone very quite of late so we may end up having to amend directly in this repo anyway

**Comment by pipwerks** [comment]
Hi guys. Been juggling work/life lately, haven't been doing much with my open source projects. This is an interesting scenario you bring up. I don't see any issues with accepting the proposed changes.

FWIW I have rewritten the wrapper many many times over the years (improved code style, modularity, flow, etc.) but never released the newer versions because this one has proven to be pretty reliable, though not very pretty. :) I appreciate your taking the time to help keep it in shape.

Thanks

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/06d1d9289b11303a77087ab62ffad2c0b54d3234
