### ISSUE TITLE
Update documentation to include accessibility compatibility

### ISSUE THREAD

**Issue by canstudios-matth** [adaptlearning/adapt_framework#2226]
### Subject of the issue/enhancement/features
With the updates to accessibility certain features may be lost; for example, page scrolling is more difficult now the tab model is no longer used. These issues can be mitigated by ensuring the correct screen reader and browser combination.

It would be good if the documentation states the supported combinations.

**Comment by moloko** [comment]
done, see https://github.com/adaptlearning/adapt_framework/wiki/Accessibility-v3-%E2%86%92-v4#browser-and-screen-reader-compatibility
