### ISSUE TITLE
Adapt Create Course > Cannot Read Property 'split' of null

### ISSUE THREAD

**Issue by marissalt** [adaptlearning/adapt_framework#2242]
Subject of the issue/enhancement/features
I'm installing the framework for the first time. I get to the "adapt create course" line. Everything runs like normal until "installing adapt dependencies" I then get this error:
"Oh dear, something went wrong. I'm terribly sorry. Cannot read property 'split' of null"

Your environment
OS: MacOS 10.12.6
Node Version v6.0.0
Framework version: 2.1.0

Steps to reproduce
adapt create course > 
...installing adapt dependencies
~/AdaptTest change to ~/AdaptTest/my-adapt-course
Oh dear, something went wrong. I'm terribly sorry. Cannot read property 'split' of null

**Comment by moloko** [comment]
@NayanKhedkar Chris Jones hasn't worked on this in ages, @chris-steele has been doing all the recent work on the adapt-cli

@marissalt I don't suppose you're able to check using Node v8? that's the recommended version for use with adapt-cli

**Comment by NayanKhedkar** [comment]
@moloko  I have tested command ```adapt create course```  on NodeV8 I got same message
![screenshot](https://user-images.githubusercontent.com/16237837/46865916-ecbd7900-ce3c-11e8-8187-f195d7205029.png)

**Comment by NayanKhedkar** [comment]
@chris-steele what do you think about [arguments(null, properties.localDir)](https://github.com/adaptlearning/adapt-cli/blob/develop/lib/promise/installAdaptDependencies.js#L18)

**Comment by moloko** [comment]
@chris-steele am i right in thinking that [adapt-cli v2.1.1](https://github.com/adaptlearning/adapt-cli/releases/tag/v2.1.1) addresses this issue?

**Comment by chris-steele** [comment]
@moloko Yep I think this might be fixed. I noticed it today while I was (finally) integrating pull/48

**Comment by chris-steele** [comment]
@NayanKhedkar apologies for not replying I did see this issue and sort of coincidentally fixed it while doing something else today.

**Comment by chris-steele** [comment]
@marissalt would you might updating to v2.1.1 and checking this issue is fixed for you?

**Comment by NayanKhedkar** [comment]
@chris-steele No problem.

**Comment by marissalt** [comment]
@chris-steele It works for me now! Thanks so much!

**Comment by moloko** [comment]
thanks for confirming @marissalt 

nice job @chris-steele & @NayanKhedkar
