### ISSUE TITLE
Fix context logic in compile helper

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2243]
https://github.com/adaptlearning/adapt_framework/blob/6a40ae3a6c98e3abf4d3203707c76327eeb44fb7/src/core/js/helpers.js#L107-L110

The `this` context should take precdence over context passed by Handlebars.

Leaving this one here for you as suggested, @oliverfoster. Hopefully you can add to the description as needs be.

**Comment by moloko** [comment]
does this still need doing?

**Comment by oliverfoster** [comment]
Yes
