### ISSUE TITLE
_requireAssessmentCompleted on individual content objects

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#2246]
This is more of a question at this stage but if `_completionCriteria._requireAssessmentCompleted === true` and `_lockType === 'sequential'` would it be good to require any assessments on a page to be passed before unlocking the next page?

Currently the page unlocks regardless, when all components have been set to complete.

**Comment by danielstorey** [comment]
Ok perfect, I missed that. Thanks!

**Comment by moloko** [comment]
@danielstorey hardly your fault, we don't really do much to announce new features outside of major framework/AT releases... really need to get better at that.

**Comment by danielstorey** [comment]
Ha no worries. Serves me right for not keeping in the loop...
