### ISSUE TITLE
adapt-contrib-spoor: Add ability to dynamically set the identifier in manifest.xml

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2247]
### Subject of the enhancement
In imsmanifest.xml the identifier is currently set to 'adapt_manifest'.  Some LMSs require that this is a unique value.  I'm proposing that we add a new property to Spoor to allow the user to specify this, with a default value of adapt_manifest in line with current behaviour.

Essentially this leaves it up to the user to configure (if required) but it means that editing the XML file by hand is no longer required.

### Your environment
Adapt Framework v3.2.1

### Steps to reproduce
Create any Adapt course in the framework or authoring tool.

### Expected behaviour
The user should have the option to specify the manifest identifier.

### Actual behaviour
The identifier is hard-coded to 'adapt_manifest'.

**Comment by moloko** [comment]
Interestingly, having looking at the SCORM docs I don't think there is a requirement for this to be completely unique - I think it's probably just a classic example of the LMS developers having interpreted the SCORM 1.2 CAM document oddly.

This is what the SCORM 1.2 CAM has to say on the matter:
> An identifier, provided by an author or authoring tool, that is unique within the Manifest

That said, it's not exactly a big problem doing this so let's just go for it anyway

**Comment by moloko** [comment]
Contrary to [what I said in the chat](https://gitter.im/adaptlearning/adapt_framework?at=5bd9b8f5538a1c1971502f8f) I don't think - reading the docs - that it's necessary for the `default` attribute of the `<organizations>` node and the `identifier` attribute of the `<organization>` node to be completely unique... suggest we just leave them set to `"adapt_scorm"` for now?

**Comment by brian-learningpool** [comment]
PR here: https://github.com/adaptlearning/adapt-contrib-spoor/pull/182
