### ISSUE TITLE
Schema defaults not being produced

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2248]
### Subject of the issue
The [`schema-defaults`](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/schema-defaults.js) grunt task reads and writes [*course.json*](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/course.json) from the source folder (*src/course/en/course.json*) to the output folder (*builds/en/course.json*) [at these lines](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/schema-defaults.js#L61-L73). The [`copy`](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/config/copy.js) grunt task reads *course.json* from the source folder and overwrites the *course.json* in the output folder at [these lines](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/config/copy.js#L38-L47). The `copy` grunt task is run after the `schema-defaults` grunt task in both the [`dev` grunt task](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/dev.js#L9-L10) and the [`build` grunt task](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/build.js#L8-L11). 
The `copy` grunt task overwrites any changes made by the `schema-defaults` grunt task.

### Your environment
* Current master framework with current master plugins
* Google Chrome
* PC, Windows 10

### Steps to reproduce
1. Download and install Adapt Framework
2. Run grunt dev

### Expected behaviour
1. The build/en/course.json `_globals` object should be populated with missing properties schema attributes.

### Actual behaviour
1. **Hotgraphic**'s new `"popupPagination"` aria label should appear in [*course.json*](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/course.json) at `_globals._components._hotgraphic.popupPagination`, having not been included in the currently available [*course.json*](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/course.json#L44-L47) but being listed in the [current hotgraphic schema](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/properties.schema#L15-L23).

### Screenshots (if you can)
![image](https://user-images.githubusercontent.com/7974663/47850083-f139d980-ddcb-11e8-9f3f-544a0e3135b4.png)
![image](https://user-images.githubusercontent.com/7974663/47850568-9608e680-ddcd-11e8-9fab-322ab5951dfa.png)

**Comment by oliverfoster** [comment]
nope, I'm an idiot.

**Comment by moloko** [comment]
could you include Steps to reproduce/Expected behaviour/Actual Behaviour? makes it a lot easier to test the fix if it's crystal clear what the original issue is

**Comment by oliverfoster** [comment]
Hows that? ;)
