### ISSUE TITLE
check to see if swfobject JS library still required or not

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#225]
flash content should only be loaded by media element, which doesn't require this... so I think it's no longer required but there might be something else that needs it that I'm not aware of

**Comment by oliverfoster** [comment]
Still used for audio plugins from adapt classic.

**Comment by moloko** [comment]
surely if only required by a plugin then it is the responsibility of the plugin to add it?

**Comment by oliverfoster** [comment]
agreed

**Comment by moloko** [comment]
has been removed in develop branch, closing issue
