### ISSUE TITLE
adapt-contrib-tutor: construct class name in sync with component

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2257]
@guywillis This might need your talented eyes.

This suggestion is intended to bring a small degree of organization and ease to styling feedback.
 
Please compare the standard component name that heads up the [mcq.less](https://github.com/adaptlearning/adapt-contrib-mcq/blob/enhancement/themeRefactor/less/mcq.less#L1) with the [class name that tutor constructs](https://github.com/adaptlearning/adapt-contrib-tutor/blob/enhancement/themeRefactor/js/adapt-contrib-tutor.js#L40) to reference the calling plug-in.

Tutor has no LESS file. If I want to style feedback based on the calling plug-in, it makes sense (to me) that the styles/rules should reside in the LESS of the calling plug-in, e.g., mcq.less. I'm wondering if tutor.js could construct the class in #L40 using the top-level `m-mcq`.  That way we can use the `&` selector and nest the class neatly into the plug-in.less structure.

The issue is that much clearer in the master branch because tutor constructs `component-mcq` but mcq.less begins with `mcq-component`.

**Comment by guywillis** [comment]
Hi @chucklorenz,

You raise a logical, and sensible, suggestion. 

I would imagine the classes were originally set up this way to stop any contamination between the component and pop up (the MCQ LESS used some very generic selectors). So long as unique class names were maintained between the component and pop up I see no reason why Tutor couldn't be changed to use the `.m-mcq` class.

**Comment by guywillis** [comment]
Hey @chucklorenz 

I believe this functionality is now present in the Tutor plugin. 

When answering a question the top level notify element gets assigned the following classes: `notify is-incorrect is-component is-mcq`. 

The `is-[MARKING]` class changes depending on what the status of the question. Values should be either `is-correct`, `is-incorrect`, or `is-partially-correct`. 
https://github.com/adaptlearning/adapt-contrib-tutor/blob/master/js/adapt-contrib-tutor.js#L15

The `is-[TYPE]` class states which type of plugin caused the notify. Values should be either `component` or `extension`. 

The `is-[PLUGIN]` class changed depending on what component triggered the notify pop up. Usually a question type like `is-mcq` or `is-matching` etc.
https://github.com/adaptlearning/adapt-contrib-tutor/blob/master/js/adapt-contrib-tutor.js#L34
