### ISSUE TITLE
Slider component not giving the correct answer feedback

### ISSUE THREAD

**Issue by BillGilmoreLP** [adaptlearning/adapt_framework#2259]
### Subject of the issue/enhancement/features
When the user slides the button over the correct answer and submits, it says the answer is wrong. When you click 'show correct answer' it shows the answer previously marked incorrect is actually correct.

### Your environment
* Adapt 321
* Chrome Mac Version 70.0.3538.77
* Mac Book Pro

### Steps to reproduce
Log into Adapt
Create a course - title and description
Add a page - title and description
Add slider component and configure:
Scale Start: Enter 0
Scale End: Enter 10
Correct Answer: e.g. choose 5
Show indicator numbers: toggle this to OFF
Save and preview the module

### Expected behaviour
When you toggle the show indicator for numbers to OFF, once the module is previewed it will not show the numbers on the scale.

### Actual behaviour
When you preview the module it is still showing the numbers on the scale even though you have toggled this to OFF.

### Screenshots (if you can)
No need for a screen shot, the setupModelItems(); in sliderModel.js is trying to compare a sting to an integer so the model for the data used to compare the correct answer is set incorrectly and thus evaluates to false when true.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-slider/commit/16ce623194cc0f7c3c4c9b1d712de64e05b2f701
