### ISSUE TITLE
onWindowUnload event is not handled properly for IE EDGE

### ISSUE THREAD

**Issue by manju4ever** [adaptlearning/adapt_framework#2261]
### onWindowUnload event is not handled properly on IE EDGE
Let say, we are on /dashboard, and we navigate to another page /lesson/1, now after going through some contents, we perform a **Hard Refresh**, now we are supposed to go to /lesson/1, but the IE EDGE takes us to /dashboard, which was not expected.

This is happening possibly because Adapt is not handling **_onWindowUnload** event when it comes to IE EDGE, after debugging, we found that **Adapt.device.browse**r value says **"Microsoft Edge"**.  Here it is not supposed to call the unload event handler

### Your environment
* Adapt Version: 2.0.18
* IE EDGE
* Windows 10 x64

### Expected behaviour
Should not call the **onWindowUnload** handler. It should behave same as the older versions of Internet Explorer

### Actual behaviour
Should return null  for IE EDGE

**Comment by amansingh7010** [comment]
Acknowledged, facing the same issue.

**Comment by moloko** [comment]
@manju4ever sorry where does the code shown in that screenshot originate from? I cannot see any (recent) version of the spoor plugin that contains the `if` statement shown in your screenshot.

**Comment by manju4ever** [comment]
Apologies @moloko, seems to be an issue on our end. Im closing this.
