### ISSUE TITLE
contrib-media : add poster image for mp3

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2264]
I've had clients who have requested poster images for mp3 files. They have built in the AT and have been suprised that no image shows. It makes sense to add it as an option. If the poster image exists show it. If not leave as it is currently.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-media/commit/38c3def1921cbe2c7a71fcdb6ee8e388118e8eb5

I expect it won't be long before someone points out that you can't initiate playback by clicking on the poster image like you can with video, but let's sort that out when it does come up!
