### ISSUE TITLE
move inview logic into ComponentView

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2269]
Since the assessmentResults, blank, text, graphic, hotgraphic, narrative & media components all implement `inview` it seems like a sensible idea to move as much of the logic as possible into ComponentView. And now seems like quite a good time to do it!

The implementation in adapt-contrib-text seems like a pretty good starting point - particularly in terms of how it allows some flexibility as to what the 'inview element' should be.

I think we would need three functions:
1. ~~`setupInviewListener`~~`setupInviewCompletion`
1. `onInview`
1. `removeInviewListener`

Plus a model property `inviewElementSelector`

If that sounds OK by everyone I'm happy to pick this up.

**Comment by oliverfoster** [comment]
Yup, perfect.

**Comment by brian-learningpool** [comment]
@moloko, is this something which is intended to go into v4?

**Comment by moloko** [comment]
@brian-learningpool yep that's the idea
