### ISSUE TITLE
Enhancement request - ability to have many points on slider

### ISSUE THREAD

**Issue by BillGilmoreLP** [adaptlearning/adapt_framework#2274]
### Subject of the issue/enhancement/features
Currently if the user has too many points on the slider they appear on top of each other and it looks broken. For example of the slider range is 0 - 100 it will appear like this:
https://drive.google.com/file/d/19mew74aRFXvnlQEnkW-H9F8q2pALsmyO/view?usp=sharing

I was thinking we could add a 'simple mode' toggle, or use JS to detect how many items are in the range and dynamically add the 'simple mode'.

The simple mode would show the first, last and every nth child of the range. So it would look more like this:
https://drive.google.com/file/d/18WDNm1ChUiMoZijcDt0TXhwlZWdMxheK/view?usp=sharing

### Your environment
* Adapt 3.2.1
* Chrome
* Macbook Pro

### Steps to reproduce
Create the slider component and enter a large range of numbers, EG: 0 - 100

### Actual behaviour
The numbers on the range will stack and be unreadable:
https://drive.google.com/file/d/19mew74aRFXvnlQEnkW-H9F8q2pALsmyO/view?usp=sharing

### Enhanced behaviour
The numbers on the range are readable but also the indicator shows what the user is about to select
https://drive.google.com/file/d/18WDNm1ChUiMoZijcDt0TXhwlZWdMxheK/view?usp=sharing

**Comment by BillGilmoreLP** [comment]
Hi @brian-learningpool @nilslp  @moloko  @tomgreenfield 

What do you think of the request I have made here, would this be worth developing?

It came from a ticket created by our QA team when they found the previous issue of the answer model not being correctly set. Thanks

**Comment by moloko** [comment]
Hi @BillGilmoreLP this issue has already been raised by @brian-learningpool via https://github.com/adaptlearning/adapt_framework/issues/2011 and resolved by slider v2.3.0

**Comment by BillGilmoreLP** [comment]
Thanks @moloko  I'll look into this

**Comment by nilslp** [comment]
@moloko I think @BillGilmoreLP means that we could possible have a slightly different simplified option on top of the fix in #2011, using a basic set of ranges (as opposed to 0 [first] and 100 [last]).

Instead of 0,1,2,3,4...100, every 10 or similarly calculated intervals; 0,10,20,30,40...100?

We have fixed up the slider that it will be able to show 0 and 100, but this is a follow on suggestion.
Not sure if it is required but just wanted to clarify that distinction.

**Comment by moloko** [comment]
@nilslp indeed, I just wanted to make sure @BillGilmoreLP was aware of the existing PR

It does feel to me like it _might_ bit of a niche requirement...? I'd be inclined to say that the nature of the question being asked here means that slider might not be the right kind of interaction and numeric input/stepper would be better suited instead? Just my opinion though, be interested to hear others'.

**Comment by nilslp** [comment]
👌 thats perfect, was unsure if it would really be a requirement so thats good to get other feedback.
Thanks for the clarification and I think its probably fine to not pursue this one.
