### ISSUE TITLE
core plugins: more descriptive descriptions

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2276]
Perhaps we could have a more descriptive description than "a bookmarking extension" https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/bower.json#L9

The first paragraph from the Readme would work https://github.com/adaptlearning/adapt-contrib-bookmarking#adapt-contrib-bookmarking

**Comment by moloko** [comment]
seems reasonable, it’s definitely not the greatest description as-is! i’ll change it tomorrow

**Comment by simondate** [comment]
There are a few more extensions I've noticed that could do with some improvements:

- [ ] Bookmarking https://github.com/adaptlearning/adapt-contrib-bookmarking
- [ ] Language picker https://github.com/adaptlearning/adapt-contrib-languagePicker
- [ ] MCQ https://github.com/adaptlearning/adapt-contrib-mcq

I think we could just copy something from the Markdown of each of these plugins. I'm happy to create a PR if you agree @moloko

**Comment by moloko** [comment]
If you have time that would be great, just bear in mind that (AFAIK) there's a 140 char limit on the description

**Comment by moloko** [comment]
MCQ's description seems OK though, surely everyone knows what a multiple choice question is?

**Comment by simondate** [comment]
Yes, sounds good. MCQ was just a suggestion as it doesn't really cover what it's options like if it allows multiple answers. But I guess this might be a bit too much information and can be discovered once the course builder dives into the settings/README

**Comment by moloko** [comment]
all done now I think?
