### ISSUE TITLE
adapt-contrib-assessmentResults: Component does not complete again after being reset

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2286]
### Subject of the issue
The Assessment Results component does not complete after completing initially and being reset, e.g. after an initial attempt at the assessment.

### Your environment
* Adapt Framework v2.3.0
* Assessment Results v2.4.0

### Steps to reproduce
1. Create a course with page level progress and a page with a simple assessment and assessment results configured to retry on the next article.
2. Fail the assessment and click the "Retry" button on assessment results.  Have another go at the assessment.

### Expected behaviour
The assessment results component does not complete on the second attempt.

### Actual behaviour
The assessment results component would complete as normal.

###  Background
This is due to the unbinding of the inview handler as soon as the component completes the first time.  It's a one line fix to add this in when the assessment is reset.  However, if the assessment is reset outside of the Assessment Results component we have no way of re-attaching the listener.  I think for this to work Assessment Results would possibly need to listen for a `reset` event from the Assessment it's been linked to.  

@moloko or @oliverfoster, do you have any thoughts?

**Comment by moloko** [comment]
That's strange, this is working OK for me... have you tried it with [this](https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/47) in place? possibly that's making a difference...

**Comment by brian-learningpool** [comment]
Hi @moloko, your PR does actually correct it since the `postRender` runs immediately following a render.   I believe this will affect other versions which don't have this though.

**Comment by moloko** [comment]
Hi @brian-learningpool I don't seem to be able to replicate this at all... 

I'm creating a brand new course using the adapt-cli which gives me FW v3.2.2 with assessmentResults v2.4.0 then building and running that. 

I fail the assessment and check that the results component has set to completed (also check that the inview function is no longer being triggered). Click retry and check that the results component completion resets then try the assessment again. No matter whether I fail or pass, the results component still marks as completed once 'inview'.

I've also tried adding the new `_routeToAssessment` setting just in case that was affecting it but that doesn't make any difference either.

**Comment by moloko** [comment]
Sorry just realised you are using FW 2.3.0, I'll try again using that

**Comment by brian-learningpool** [comment]
Hi @moloko, are you using the `master` branch or the released version of Assessment Results v2.4.0?  I'll test on v3.2.2 also.

**Comment by moloko** [comment]
the released version

**Comment by moloko** [comment]
same results using FW 2.3.0

**Comment by brian-learningpool** [comment]
@moloko sorry for the delay in getting back to you on this.  It appears to be an issue when the assessment is reset outside of the Assessment Results, e.g. from an extension like Assessment Single Submit or similar.

**Comment by moloko** [comment]
Ah OK I see

Given this:
> your PR does actually correct it since the postRender runs immediately following a render

And assuming that PR is no good for you because you need the fix to be Adapt v2 compatible, would a solution be to add the `inview` listener from `postRender` rather than using the "events hash"?

**Comment by brian-learningpool** [comment]
@moloko, just revisiting this and I think since 4.0.0 has been released and this is not an issue in v3 we can close this ticket.
