### ISSUE TITLE
Hot Graphic popup doesn't open. 

### ISSUE THREAD

**Issue by NayanKhedkar** [adaptlearning/adapt_framework#2287]
### Subject of the issue
Hot Graphic popup doesn't  open on first time build the course by(**grunt dev** or **grunt build**).

### Your environment
Adapt Framework v3.2.2
Hot Graphic v3.0.1

### Steps to reproduce
Create the course with the mentioned versions and try to build the course with (**grunt dev** or **grunt build**) visit the hotgraphic component and try to open popup.

### Expected behaviour
Popup should open on hotgraphic pin click.

### Actual behaviour
Popup doesn't open on hotgraphic pin click.

**Comment by akshay-bhavsar** [comment]
@NayanKhedkar same issue face by me.

**Comment by moloko** [comment]
same here. on FF I get the following error in the console:
> Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined

**Comment by moloko** [comment]
Figured it out, this is effectively a duplicate of #2248

#2249 fixes this (@akshay-bhavsar if you could go +1 this we can get that merged) - but perhaps we should also add that property into src/course/en/course.json ?

**Comment by NayanKhedkar** [comment]
Refer :#2248
