### ISSUE TITLE
Change example trickle behaviour to _autoHide:false

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2292]
### Subject of the issue
Trickle isn't accessible if the button only appears when on screen.
The default course should reflect that.

**Comment by moloko** [comment]
Given the changes that were made in https://github.com/adaptlearning/adapt-contrib-trickle/pull/94 should we not change [L65 of button.js](https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/button.js#L65) to `false` to match? That way the default course wouldn't need updating, it would automatically have the correct behaviour.
