### ISSUE TITLE
Accessibility: Voiceover reading text twice as group 

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2296]
There is a 'quirk' in Voiceover on Mac OS that reads a text area twice as a group when there's a `<br>` present in that text area. 

Example:
```
<div>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br><br>In ac urna convallis, dignissim nisl interdum.
</div>
```

This would read `Lorem ipsum dolor sit amet, consectetur adipiscing elit.` twice and treat it as a group, before then reading `In ac urna convallis, dignissim nisl interdum.` as the next readable element. 

In case anyone needs to resolve this issue, adding `role="text"` to the container element reads the entire text area as one. 

https://axesslab.com/text-splitting/

**Comment by oliverfoster** [comment]
Closed as for reference only
