### ISSUE TITLE
Restart with updated config

### ISSUE THREAD

**Issue by mauricevancooten** [adaptlearning/adapt_framework#2298]
### How do I re-strart AdaptLearning after I have updated the config.js file?

My user has entered the wrong password three times and is not getting the reset email. I suspect this is because the SMTP email settings are not configured. How do I restart Adapt once I've updated the config file with the new SMTP settings?

If you have a sample config file with SMTP settings that will be helpful.

**Comment by lc-thomasberger** [comment]
Hello,
this is the wrong repository. You are referring to the [adapt authoring tool](https://github.com/adaptlearning/adapt_authoring) I assume.

You can find the support config options for SMTP here:
https://github.com/adaptlearning/adapt_authoring/wiki/Configuring-the-Authoring-Tool#smtpmail-options

Once you made changes you will need to restart the application. This depends on how you started the application (`node server.js`).
