### ISSUE TITLE
Building off Vanilla theme & licensing

### ISSUE THREAD

**Issue by Floppy** [adaptlearning/adapt_framework#2310]
I think this is the right place for this issue - apologies if not. 

The documentation states that if you want to develop an Adapt theme, the best way is to fork the Vanilla theme and build off that: https://github.com/adaptlearning/adapt_authoring/wiki/Modifying-the-Vanilla-Theme

However, the Vanilla theme is GPL, meaning that any theme that uses it as a base has to be released openly under the GPL too. Now I've got no problem doing that in principle, but our fork will likely have things like company logos in, and so on, which we can't really release for reuse under the GPL.

I think at the moment that to be compliant with the license of Vanilla, if we don't want to (or can't) release our theme under the GPL, we can't use Vanilla and would actually have to reimplement the theme from scratch.

Previously when I've created open source code that I expect people to build off and use commercially, I use a more permissive license like MIT. I don't expect you to do that for me, obviously, but I'd suggest that it's worth considering more generally.

**Comment by oliverfoster** [comment]
You can just copy it into your own repo. You don't need to fork.

**Comment by Floppy** [comment]
Thanks @oliverfoster - that would still violate the GPL if we didn't release openly under the same license though.

**Comment by oliverfoster** [comment]
(As far as I gather) You don't have to release it publicly under GPL but you do have to include a GPL license with the derivative work when you distribute it.

**Comment by Floppy** [comment]
You're right re logos, etc, but going by the summary on https://choosealicense.com/licenses/gpl-3.0/ (as they summarise it better than I could) I think it's a bit more severe than I thought and would even cover the courses that use vanilla: 

> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. 

So any derivation of the vanilla theme, and I think even a course built using such a derived version, would all need to be released under the GPL. I think that strictness and virality is the whole *point* of the GPL (in my understanding).

side note: LGPL would allow use of Vanilla (or a derived theme) in a non-GPL'd course, though a derived theme would still need to be LGPL.

**Comment by oliverfoster** [comment]
Why don't you start a new theme using Vanilla as your inspiration?

**Comment by Floppy** [comment]
Looking at their FAQ: "an organization can make a modified version and use it internally without ever releasing it outside the organization."

But, "if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL."

I think this covers the case of building a course that uses a GPL theme, too: https://www.gnu.org/licenses/gpl-faq.html#LinkingWithGPL

**Comment by oliverfoster** [comment]
Are you planning on releasing it to the public?

**Comment by Floppy** [comment]
@oliverfoster that's my fallback plan if we can't use the actual Vanilla source as the base, because of the license, though obviously there's a lot in there that's helpful to get us started, so I'd rather not. If this is intentional, that's totally fine, but it might be worth a note in the docs that derivations of Vanilla can't be released publicly without being GPL'd themselves.

Yes, our courses will be public.

Though now I've checked the adapt framework license as well, and I see that's *also* GPL... hmm.

**Comment by Floppy** [comment]
That's interesting, because any course build with Adapt includes the framework - it's an essential components. I think (again from my reading, I'd love to be wrong on this) that any public course built with adapt should technically be released under the GPL.

I'm going to read up a bit more, see what I'm missing.

**Comment by oliverfoster** [comment]
Drupal certainly thing you're right.
[Points 9 + 10 ](https://www.drupal.org/about/licensing#drupal-license)

**Comment by Floppy** [comment]
Hm, that's a pretty good explanation - good find.

**Comment by oliverfoster** [comment]
Kudos to @kineopete for the info btw. I'm just repeating what he's explained to me whilst he travels home.

**Comment by Floppy** [comment]
Thanks for looking into it, and good to know it's being talked about. So that we can continue our work here (and explain to my boss), can I confirm that the _intent_ of the Adapt community is that the framework (and the Vanilla theme as part of that) is intended to be used to build public content that's not itself released under an open source license? Even though it might _technically_ be a breach of the license to do so? That might have to do for now until the license conversation can be had...

**Comment by oliverfoster** [comment]
I can't give you that legal assurance I'm afraid. 

But yes, as far as I understand it.

**Comment by Floppy** [comment]
Understood that's not a legal statement, but that is probably all we can get for now. Thanks for your help.
