### ISSUE TITLE
Progress Bar JS: Create an update event to pick used in theme JS

### ISSUE THREAD

**Issue by BillGilmoreLP** [adaptlearning/adapt_framework#2313]
### Subject of the issue/enhancement/features
The 'adapt-contrib-pageLevelProgress' extension updates the percentage of completion as goals are ticked off and the page is scrolled. I need to add an event here (every time the progress is updated) so that I can execute a function in my theme JS file. Would this be possible please?

### Your environment
* version (AT/Framework) Adapt 3.2.1
* which browser and its version Chrome
* device(s) + operating system(s) MacBook Pro

### Steps to reproduce
Preview a course that uses page progress extension, as you progress through the page the progress moves up towards completion.

### Expected behaviour
Each time the progress is updated I would like an event to fire that I can listen for in my theme JS file.

### Actual behaviour
No event (that I can listen for in my theme JS) is fired as the progress is updated.

**Comment by BillGilmoreLP** [comment]
Yes @brian-learningpool mentioned this might be a feature of the new version. 
That is great i'll keep developing my JS and switch out my function watching for DOM changes and switch in this new `pageLevelProgress:update` when i'm finishing this feature. 
Thank you @moloko

**Comment by moloko** [comment]
saying that I can't actually find the code that broadcasts this event anywhere..! may just be having a dumb moment, this is my first day back at work ;-)

**Comment by BillGilmoreLP** [comment]
moloko.reboot('2019');
=]

**Comment by oliverfoster** [comment]
Could you try https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/111 with https://github.com/adaptlearning/adapt_framework/pull/2315 please?
