### ISSUE TITLE
Add 'scoreToPass' to object triggered by 'assessment:complete' event

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2318]
### Subject of the enhancement
It would be good if the state triggered by `assessment:complete` included the `scoreToPass` property.  This could then be useful in feedback for components such as Assessment Results.

### Your environment
Adapt Framework v3.2.1

### Steps to reproduce
1. Complete an assessment.

### Expected behaviour
The object triggered by `assessment:complete` includes the `scoreToPass` property.

### Actual behaviour
No such property exists on the course-wide assessment state.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-assessment/commit/1b941ab2403b5f9b8873312d1507aac127a4e83d
