### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nakaravi** [adaptlearning/adapt_framework#2328]
Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

localhost/:1 Failed to load resource: the server responded with a status of 404 (Not Found)
![image](https://user-images.githubusercontent.com/9427718/51470872-1d497300-1d9b-11e9-91e1-bc59130d4d4a.png)

**Comment by moloko** [comment]
hi @nakaravi as per the issue template, please could you describe:
* the issue in more detail
* your environment
* steps to reproduce

etc.
