### ISSUE TITLE
adapt-contrib-narrative: 'stealing focus' when accessibility is active

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2330]
### Subject of the issue/enhancement/features
As per [this forum post](https://community.adaptlearning.org/mod/forum/discuss.php?d=3561)

### Your environment
* Framework v3 & Narrative v3.0.0/3.0.1
* any browser/device/os

### Steps to reproduce
Enable accessibility on a page with a narrative component (or enable accessibility then navigate to any page containing a narrative component)

### Expected behaviour
Narrative should not 'steal focus'

### Actual behaviour
Focus jumps to the narrative component on page load

**Comment by jamesrea83** [comment]
I can replicate this in firefox & edge, but oddly not in chrome.

**Comment by moloko** [comment]
Issue is caused by `this._isInitial` being changed to `false` by the time the `onTransitionEnd` callback handler executes.

An easy fix would be to change the following line of `moveSliderToIndex` from:
`if (Adapt.config.get('_disableAnimation'))`
to:
`if (Adapt.config.get('_disableAnimation') || this._isInitial)`
So as to match the current master branch of this component.

**Comment by moloko** [comment]
Just to note that, in order to fix, we would need to create a branch from the 3.0.1 tag, fix it there, then release from that branch as 3.0.2

**Comment by brian-learningpool** [comment]
Fixed in Narrative v3.0.2.
