### ISSUE TITLE
Accessiblity issue with JAWS screen Reader

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_framework#2334]
### Subject of the issue/enhancement/features
When using Framework V4 with [JAWS screen reader](https://www.freedomscientific.com/Products/Blindness/JAWS) in accessible mode. When I tab through your example course it no longer tabs to titles, body or instruction text in the course therefore not reading it out to the accessible user. 

### Your environment
4.0 (Framework)
Chrome Version 71.0.3578.98
Windows 10

### Steps to reproduce
Install version 4 of framework, grunt build, grunt server

### Expected behaviour
In accessible mode using JAWS it use to tab to the Title, body and instructional text and then read it to the accessible user.

### Actual behaviour
Doesn't read or tab to title, body or instruction text

**Comment by oliverfoster** [comment]
Hi @mike-st.

I'm just producing some documentation on this subject, apologies for their late arrival.
We have defaulted to standard browser tabbing and proper use of the screen reader's virtual cursor.
You'll need to acquaint yourself with JAWS navigation keys and modifiers:

Quick ref:     
left = move backward
right = move forward
space = make selection
h = cycle through headings
r = cycle through regions
q = go to main content
esc = exit forms mode or dismiss notify

References:
https://webaim.org/resources/shortcuts/jaws
https://www.freedomscientific.com/Content/Documents/Manuals/JAWS/Keystrokes.pdf
https://tink.uk/understanding-screen-reader-interaction-modes/  

I hope you find it much more usable than it was in v3. Please let me know if you have issues.

Kind Regards,

Ollie.

**Comment by mike-st** [comment]
Thanks very much @oliverfoster I see what you mean now. I will give this a good through test. To be honest forgot about short cuts as I haven't used them in quite some time. Appreciate the references.
