### ISSUE TITLE
reset.less select, input, textarea font issue

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt_framework#2347]
### Subject of the issue/enhancement/features
I noticed recently that the font in html textarea's, select's and inputss look awful like times new roman. Just wanted to point this out as it is not pulling the Vanilla's theme's inherit font. Issue seems to be in the "reset.less" file on line 31... example (select, input, textarea {font: 99% sans-serif;})

### Your environment
Framework Version 4

### Expected behaviour
html textarea's, select's and input's should pull on the Vanilla Theme's inherit font.

### Actual behaviour
Times New Roman is displaying instead. Icky :)
![reset_less_font_issue](https://user-images.githubusercontent.com/10455453/52304096-db562a80-295f-11e9-8879-5942706dd28d.jpg)

**Comment by moloko** [comment]
Seems fine in the [Adapt v4 demo](
https://adaptlearning.github.io/v4demo/#/id/co-10):
![a008590e-d02e-45da-a8a2-878c64d82824](https://user-images.githubusercontent.com/1249597/52306116-db215380-298e-11e9-89a8-fc97494339da.jpeg)

In safari for ios anyway...

Could you let us know what browser you’re using and what version of the:
* framework
* vanilla theme
* textInput 

You’re using?

**Comment by moloko** [comment]
Weird, I've checked in FF, Chrome and IE11 now too and can't replicate your results.

I completely agree that really it should be explicitly set to the standard Adapt font-family rather than defaulting to what's in reset.less

What's bugging me is why you're seeing what's quite clearly a serif font when reset.less clearly specifies 'sans-serif'?

**Comment by mike-st** [comment]
Hi Guys,

My apologies on this one it seems my chrome got corrupted some how maybe too many chrome extensions not sure. I have reset to factory default and it fixed the problem. I will close this as it has nothing to do with the framework. Thanks for looking into it none the less
