### ISSUE TITLE
Narrative 4 error with framework 3

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2348]
```console
Missing helper: "a11y_aria_image"
```
Due to https://github.com/adaptlearning/adapt-contrib-narrative/commit/2e60914e6313a2ba2d2c1b254aa0da1b5cdf0bc8.

Just needs an interim release for (non-accessible) framework 3 compatibility and then a subsequent release at some point with a bumped framework dependency.

**Comment by brian-learningpool** [comment]
Narrative has been re-tagged as v4.0.0 with the correct framework dependency.
