### ISSUE TITLE
adapt-contrib-assessment: On retry autocomplete correct option

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2349]
Would it be possible to add a feature where if an assessment is failed and retaken any questions they got correct first time around are kept correct?

**Comment by moloko** [comment]
a bit like the ‘reset only incorrect answers’ feature of the matching component? 
interesting idea, though perhaps one that sounds easier to implement than it actually will be

**Comment by akshay-bhavsar** [comment]
any updates?

**Comment by moloko** [comment]
@akshay-bhavsar I'll raise it in the call shortly.

**Comment by akshay-bhavsar** [comment]
Sure matt!

**Comment by simondate** [comment]
@akshay-bhavsar I created this plugin that has the functionality https://github.com/simondate/adapt-assessmentKeepCorrect

@moloko did you discuss this on the call? Happy to assist this week with merging into core.

**Comment by moloko** [comment]
@simondate we did and the conclusion we came to was that we weren't happy adding something this to core given that:
* it could cause issues if used under the wrong circumstances
* you can achieve the same effect either with a simple one-line amend to adapt-assessmentArticleModel.js (for FW users) or via an extension like yours (for AAT users)
* no-one's particularly clamouring for it

**Comment by moloko** [comment]
@simondate you could probably simplify your assessmentKeepCorrect extension greatly by just having it re-write the `_resetQuestions` function on-the-fly, something along these lines maybe?
```js
Adapt.articles.forEach(function(article) {
    if (!article._resetQuestions) return;
    article._resetQuestions = function (callback) {
        var assessmentConfig = this.getConfig();
        var syncIterations = 1; // number of synchronous iterations to perform
        var i = 0, qs = this._currentQuestionComponents, len = qs.length;

        function step() {
            for (var j = 0, count=Math.min(syncIterations, len-i); j < count; i++, j++) {
                var question = qs[i];
                if (question.get('_isCorrect')) continue;
                question.reset(assessmentConfig._questions._resetType, true);
            }

            i == len ? callback() : setTimeout(step);
        }

        step();
    }
});
```
The slight challenge you'd have is figuring out when to run that code as you need to be applied _after_ the assessment extension has set itself up...

**Comment by simondate** [comment]
@moloko so I would be overriding the function? I knew you could override models, views in Backbone but didn't know it would work with specific functions too.

What would be the best way to figure out it had been applied? Some kind of loop that  every 100s checks if an assessment exists and if one is found then runs the code above then?

**Comment by moloko** [comment]
yep you can both override and extend functions - in fact you can see examples of the latter in [adapt-assessmentArticleExtension.js](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleExtension.js) - it extends the `initialize` method of both `ArticleView` and `ArticleModel` in order to be able to inject the assessment functionality into them. The code I supplied above then overrides one of those functions.

You don't need to figure out it had been applied, just run the code at the appropriate moment, generally just a case of picking the [appropriate startup event to hook into](https://github.com/adaptlearning/adapt_framework/wiki/Core-Events)

**Comment by simondate** [comment]
Thanks for all the tips Matt. I've just merged the change. What a reduction in code!

**Comment by simondate** [comment]
> @simondate we did and the conclusion we came to was that we weren't happy adding something this to core given that:
> 
> * it could cause issues if used under the wrong circumstances
> * you can achieve the same effect either with a simple one-line amend to adapt-assessmentArticleModel.js (for FW users) or via an extension like yours (for AAT users)
> * no-one's particularly clamouring for it

Shall I close this issue since it won't be merged to core and a plugin that achieve it exists already?
