### ISSUE TITLE
Hot graphic component: Arrows are still displayed when there is only 1 item

### ISSUE THREAD

**Issue by kilianLearningPool** [adaptlearning/adapt_framework#2350]
### Subject of the issue/enhancement/features
If you only include one item with the Hot Graphic Component, an arrow still appears to go the next item. This could be addressed by setting the `_hidePagination` to true if `_items.length` is 1.

### Your environment
* 3.3
* Chrome, Firefox, Edge, IE11.
* iOS Tablet and Mobile, plus Chrome, Android Tablet and Mobile.

### Steps to reproduce
Create a course and add a Page
Go into the page and add the Hot Graphic component
Under 'Main hotgraphic' add an asset.
Click save and Preview the course

### Expected behaviour
The arrow to go the next item is not displayed.

### Actual behaviour
The arrow is displayed.

### Screenshots
<img width="930" alt="screen shot 2019-02-11 at 11 50 59" src="https://user-images.githubusercontent.com/42141299/52561473-68cbcb80-2df3-11e9-9146-d8526ead1ec0.png">

**Comment by akshay-bhavsar** [comment]
@kilianLearningPool Can you please try with "adapt-contrib-hotgraphic" version "4.0.0".
which is latest version of component.
Issue is not replicating at my end with this component version.

**Comment by moloko** [comment]
good call @akshay-bhavsar - have also tried with v4.0.0 of hotgraphic and it does seem to be fixed in that release.

**Comment by moloko** [comment]
@kilianLearningPool if you're logging a bug about a plugin, please could you include the plugin version number as well as the FW version?

**Comment by kilianLearningPool** [comment]
Hi @akshay-bhavsar and @moloko yeah I was on an older version of the plugin, tried with v4.0.0 and didn't have the issue.
