### ISSUE TITLE
adapt-contrib-spoor enhancement request/proposal

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#2355]
We have someone potentially interested in adapt content but they have a hard requirement on how assessment scores get written out to the LMS. 

They only want the assessment score to get written out after the user has passed the assessment or, in the case of failure, when they have reached their final attempt.

Before we would even commit to this we wanted to gauge the appetite for modifying the spoor extension to include a setting for this. Our view would be to include a setting on the spoor extension that would suppress the score being sent back unless they passed or all attempts are exhausted.

Do you think this is something that could be used by other people and would be worth enhancing the spoor for?

**Comment by moloko** [comment]
I'll have a word with my colleagues here at Kineo but personally I'm not aware of this ever coming up as a requirement.

I thinking it would be fairly easy to write an extension that would handle this, either by 'monkey patching' the `submitScore` function in spoor or by setting the `_tracking._shouldSubmitScore` setting to `false` to prevent spoor from submitting the score and instead have your own extension handle it.

**Comment by chris-steele** [comment]
To my knowledge this hasn't come up as a requirement before for us, but it should not be difficult to implement and we will gladly review a PR. I would recommend the suggested approach of setting `_tracking._shouldSubmitScore` to `false` and handling this externally to avoid coupling spoor to assessment or another plugin.

**Comment by brian-learningpool** [comment]
Hi @kevindoherty30, I'm closing this ticket as the requirement in this case is slightly too niche.  As suggested above, the behaviour could be accomplished via an extension that bridges the two plugins rather than coupling Spoor to Assessment.

**Comment by kevindoherty30** [comment]
Hi @brian-learningpool , yeah no problem, thanks for the feedback on this one @moloko & @chris-steele
