### ISSUE TITLE
adapt-contrib-vanilla: Update to be editable in authoring tool 

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#2359]
### Subject of the issue/enhancement/features
A future release of the authoring tool (currently pegged 0.8.0) will contain a new feature which will allow themes to be edited. More information here: https://github.com/adaptlearning/adapt_authoring/issues/2187

Vanilla should be updated so that it's colour variables are exposed in the authoring tool for editing.

Both Vanilla 3.0.0 and 4.0.0 will be updated as there will be authoring tools running v2 of the framework until multiple framework support is finished.

**Comment by moloko** [comment]
I think this is done now?

**Comment by canstudios-nicolaw** [comment]
Yes it can
