### ISSUE TITLE
Drop 'src/course' folder in favour of 'build/course'

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2363]
### Advantages
* makes src folder "code only"
* unifies build pathways across AAT and Fwk
* deduplicates course assets when stored on disk
* allows developers to concentrate on build output
* simplifies grunt code

### Suggested timeline
Release with v6

**Comment by tomgreenfield** [comment]
Please also include cleaning of build folder.

Reference: https://github.com/adaptlearning/adapt_authoring/issues/2235.

**Comment by guywillis** [comment]
:+1:
