### ISSUE TITLE
Adapt v5 - LESS refactor overview

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2364]
v5 PRs and Issues

## PR Review Links

Framework: [PR](https://github.com/adaptlearning/adapt_framework/pull/2516/files?w=1) needs 2 more reviews
Boxmenu: [PR](https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/91/files?w=1) needs 2 more reviews
Vanilla: [PR](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/238/files?w=1) needs 2 more reviews 

Accordion: [PR](https://github.com/adaptlearning/adapt-contrib-accordion/pull/95/files?w=1) needs 1 more review
AssessmentResults: [PR](https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/54/files?w=1) needs 1 more review
Blank: [PR](https://github.com/adaptlearning/adapt-contrib-blank/pull/33/files?w=1) READY
ConfidenceSlider: [PR](https://github.com/adaptlearning/adapt-contrib-confidenceSlider/pull/45/files?w=1) READY
GMCQ: [PR](https://github.com/adaptlearning/adapt-contrib-gmcq/pull/121/files?w=1) needs 1 more review
Graphic: [PR](https://github.com/adaptlearning/adapt-contrib-graphic/pull/74/files?w=1) needs 1 more review
Hotgraphic: [PR](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/180/files?w=1) needs 2 more reviews
Matching: [PR](https://github.com/adaptlearning/adapt-contrib-matching/pull/120/files?w=1) needs 2 more reviews
MCQ: [PR](https://github.com/adaptlearning/adapt-contrib-mcq/pull/150/files?w=1) needs 1 more review
Media: [PR](https://github.com/adaptlearning/adapt-contrib-media/pull/203/files?w=1) needs 2 more reviews
Narrative: [PR](https://github.com/adaptlearning/adapt-contrib-narrative/pull/196/files?w=1) needs 2 more reviews
Slider: [PR](https://github.com/adaptlearning/adapt-contrib-slider/pull/141/files?w=1) needs 1 more review
Text: [PR](https://github.com/adaptlearning/adapt-contrib-text/pull/55/files?w=1) needs 1 more review
TextInput: [PR](https://github.com/adaptlearning/adapt-contrib-textInput/pull/99/files?w=1) needs 2 more reviews

Assessment: [PR](https://github.com/adaptlearning/adapt-contrib-assessment/pull/121/files?w=1) needs 1 more review
Bookmarking: [PR](https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/37/files?w=1) READY
Glossary: [PR](https://github.com/adaptlearning/adapt-contrib-glossary/pull/43/files?w=1)  Needs 1 review (non-core plugin)
LanguagePicker: [PR](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/38/files?w=1) needs 2 more reviews
PageLevelProgress: [PR](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/116/files?w=1) needs 2 more reviews
Resources: [PR](https://github.com/adaptlearning/adapt-contrib-resources/pull/62/files?w=1) needs 2 more reviews
Spoor: [PR](https://github.com/adaptlearning/adapt-contrib-spoor/pull/185/files?w=1) READY
Trickle: [PR](https://github.com/adaptlearning/adapt-contrib-trickle/pull/99/files?w=1) needs 2 more reviews
Tutor: [PR](https://github.com/adaptlearning/adapt-contrib-tutor/pull/64/files?w=1) needs 2 more reviews

-----

## Issues

Core 
https://github.com/adaptlearning/adapt_framework/issues/2018

Components
https://github.com/adaptlearning/adapt_framework/issues/2016

Extensions
https://github.com/adaptlearning/adapt_framework/issues/2017

Menu
https://github.com/adaptlearning/adapt_framework/issues/2019

Theme
https://github.com/adaptlearning/adapt_framework/issues/2020

Drop 'src/course' folder in favour of 'build/course'
https://github.com/adaptlearning/adapt_framework/issues/2363

Allow multiple menus
https://github.com/adaptlearning/adapt_framework/issues/1902

-----

#### Consistent naming convention - BEM inspired
* http://getbem.com/ 
* [Documentation](https://cityandguilds-my.sharepoint.com/:w:/g/personal/guy_willis_kineo_com/EdUCjFblZotKqgKvKFQPQ4QB6RKsNX00meEQbDu1F6qCKw?e=Ax3Hdc)

#### Global, reusable, classes - SMACSS inspired
* https://smacss.com/ 
* [Documentation](https://cityandguilds-my.sharepoint.com/:w:/g/personal/guy_willis_kineo_com/EfZLz5c_es5Nn8ofQdTP8ikB2p4pK8ONtBMfpsSTByIt0Q?e=UrtBKo)
* c21438bfe4717524afc61748891f351bde4a281c
* b8ad2d24901ea76b72633403b93653d28d1ef993

#### Updated reset less - changed to [normalize](https://necolas.github.io/normalize.css/)
* be865ed6c6dbd319bf004fa174950ef6f65a30e7

#### Overhaul of unit measurement - PX to EM's
* 4d9dc2bd37009118f344c5405ff459a508a767fa

#### Created menuItemView from menuView
* 62d75442ef7000bc800999b93b533bb83c6068ed

#### Standardised CoABC structure
* f479e3ec9ad344ce77a0ed1d94c3e35cfa7bb0e2
  * Content object - set up article container as it's own element
  * Content object - header only renders if any of displayTitle, body, or instruction is present
* 3b8fd124d4573673c12bcd3082432367397d09c1
  * Article - set up block container as it's own element
  * Article - header only renders if any of displayTitle, body, or instruction is present
* 678e18cd816a1225e3e21b69f01b64bf2e72cdbb
  * Block - header only renders if any of displayTitle, body, or instruction is present
* e8a37722939e06139adefc320c6911d6bdd0c2bd
  * Component - header only renders if any of displayTitle, body, or instruction is present
  * Component - updated left / right css from float to flex
  * Component - forced all components to render their name in lowercase 

#### Updated checkScreenSize function and defaults
* 4d9b2ef9b840f5312635885b260a2d7fe19363e6
* 808bb28b6d107541409d8174136c2747a79d6037

#### New loading animation
* 2f320b0d7aa8ebdea0b2eaafc86a51a2b225cdff

#### Optimised buttons.hbs
* a855623fffd1e475e0bcea9b68c4c87210628f54
* 4bc3ed29a3957ecc90c0be8482794d9778231e63

#### Icon updates
* e555ea60da44cc48c80cf11367e212491a285b78
  * Updated definitions + added new icons for MCQ checkbox
  * Set up icons for SVGs - future

#### questionView className function mirrors componentView
* 20e33cf35cbcf3094dc9e2ccb613c5bbd9c01046

#### Moved addDirection and disableAnimation from configModel to app.js
* dc043e465674feec9b28ca9bdb7e00b09ec2e322

#### Created drawerItemView from drawerView
* b2665604f2a5f71f122b5292371f1009b74e5eb9

#### Removed RTL component prepend 
* 5b9433225895261ffeafe88602789cc5af6db404
  * Flexbox inherits body language direction so no longer require dom manipulation

--

#### Open Source plugins LESS rewritten to conform to new standards
  * Support EM's by default
  * Removed redundant / old LESS - optimised
  * Removed 'theme' orientated LESS - fewer overrides required to theme, plugins contain structural LESS

#### BoxMenu
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/f88257f1beee5da8258a62085b615dde9378e94e
  * Renamed js file
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/dcf24042f2c0fc864d37938b381f4b63bc9c6d08
  * Named less and hbs files
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/79be439173733dd69bb2e2a448015c50f8206d3a
  * Split itemView js into a new file
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/dc9152ff24e1312a3894d1d333c23465964bfc52
  * Split css into menu and item files
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/d31f1db6758526b7706f973a0c26c2d98f29d106
  * Added generic classes 
* https://github.com/adaptlearning/adapt-contrib-boxmenu/commit/0ee0eb48e15ab2c7609d954f85494b05290b2f9e
  * Utilised newly optimised menuView and menuItemView

#### Vanilla
* https://github.com/adaptlearning/adapt-contrib-vanilla/commit/b1dd3be6a55a93bc2176fa1e23365f59ccaa3711
  * Converted values to EMs

#### Accordion
* https://github.com/adaptlearning/adapt-contrib-accordion/commit/d9cf0ae22f6c98e43be5b4f0610dd087ea389f53
  * Implemented left / right image alignment

#### Hotgraphic
* https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/d80abba1f990a6e0eb0852b5253646f7bee954d6
  * Implemented left / right image alignment
  * Implemented hide image in desktop pop up

#### Slider
* https://github.com/adaptlearning/adapt-contrib-slider/commit/c8a71d27698dedc764d5441242075bd00e51cc8c
  * Reworked and renamed structure and classes - less confusing to read, better organisation

#### Text Input
* https://github.com/adaptlearning/adapt-contrib-textinput/commit/ca6b60f20f1eacc3d07022e1e2b86554be55121a
  * Amended structure

#### Trickle
* https://github.com/adaptlearning/adapt-contrib-trickle/commit/cce1a74acfcb295b4b5de843f47d5e746f440485
  * Amended Trickle page height calculation
* https://github.com/adaptlearning/adapt-contrib-trickle/commit/85766cef40c69bd640d7f020ba3523b8a3953237
  * Implemented new method to add an icon to the trickle button

#### Tutor
* https://github.com/adaptlearning/adapt-contrib-tutor/commit/9169345b9bde267d3869c91a9b4c37773cac31fe
  * Forced all components to render their name in lowercase in tutor pop up

**Comment by oliverfoster** [comment]
@guywillis Can we/I begin to close the v5 issues and project?

**Comment by guywillis** [comment]
v5 refactor is largely done and now merged with master.

Closing issue.
