### ISSUE TITLE
adapt-contrib-hotgraphic: item pin _classes only available for _useGraphicsAsPins 

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2367]
Pin item _classes are only applied if _useGraphicsAsPins is enabled. Ideally the _classes attribute should be available regardless. 

In addition, there isn't any schema helper text so it's not obvious this is only available with _useGraphicsAsPins.

**Comment by moloko** [comment]
> Pin item _classes are only applied if _useGraphicsAsPins is enabled

Actually just having tested this it isn't strictly true. 

The class(es) specified in `_items[n]._graphic._classes` are only applied if `_useGraphicsAsPins` is enabled but the `_items[n]._classes` are always applied (but only in the popup)

**Comment by moloko** [comment]
Which means the schema help text for `_items[n]._graphic._classes` is wrong; it currently says:
> Allows you to specify custom CSS classes to be applied to the popup item

Presumably that should be moved to `_items[n]._classes` and the help text for `_items[n]._graphic._classes` should be changed to something like "Allows you to specify positioning classes for when this component is in 'graphics as pins' mode"

**Comment by moloko** [comment]
And neither of these two `_classes` properties are documented in README.md...!
