### ISSUE TITLE
adapt-contrib-pageLevelProgress - multiple indicators when switching languages

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2368]
### Your environment
* Framework v4, master branch
* Chrome v72, Mac OSX

### Steps to reproduce
Enable PLP, enable PLP indicators (at any level), enable language picker and change languages from the navigation bar. 

### Expected behaviour
A single plp indicator renders at each level

### Actual behaviour
Multiple plp indicators render at each level

### Screenshots
<img width="390" alt="screen1" src="https://user-images.githubusercontent.com/11569678/53627960-b6bd3d80-3c01-11e9-9612-226a99a4703d.png">
<img width="451" alt="screen2" src="https://user-images.githubusercontent.com/11569678/53627961-b6bd3d80-3c01-11e9-8365-207706dc0dce.png">

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/112

**Comment by NayanKhedkar** [comment]
@guywillis Can you please confirm it?

**Comment by guywillis** [comment]
Thanks @NayanKhedkar, I shall review your change as soon as I can.

**Comment by guywillis** [comment]
Hi @NayanKhedkar,

I have reviewed your amend and encountered a problem.

Use case:

* I have two courses - course one (C1) has PLP enabled, course two (C2) has PLP disabled
* I load C1 and can see PLP is active
* I switch to C2 using LanguagePicker's drawer quick switch
* C2 is rendering PLP when it shouldn't be

Alternative use case:

* I load C2 which has PLP disabled so no progress bars render
* I switch to C1 using LanguagePicker's drawer quick switch
* C1 is not rendering PLP when it should be

**Comment by NayanKhedkar** [comment]
Thanks ! @guywillis  okay got it . I need to be try with other ways like @moloko  suggested [Link](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/112#issuecomment-469752504)

**Comment by moloko** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/dcd8f589d9008f1503fcef99134799f6b2a2de80
