### ISSUE TITLE
adapt-contrib-slider: model answers when no scale

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2369]
### Subject of the issue/enhancement/features
Model answer indicators don't seem to make complete sense when there is no scale on the slider.

### Steps to reproduce
Set `"_showScale": false` and choose an incorrect position on the slider. When showing the correct answer, the `slider-modelranges` just look like random blobs without the scale to align to, especially if `"_showNumber": false`.

### Expected behaviour
Would it make more sense to have the correct range shown as an overlay on the slider itself to show the correct range, rather than showing the middle position of the range and the current model answer indicators? Visually it would work regardlesss of the scale settings.

**Comment by moloko** [comment]
I'm not sure TBH, I'd be tempted to file this under 'inappropriate choice of settings'. I'm struggling to figure out when you would choose this particular combination. Do you have an actual use-case where this came up as being a problem?

**Comment by oliverfoster** [comment]
still relevant? @danielghost
