### ISSUE TITLE
Trickle rewrite

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2372]
### Discussion
Please leave comments/suggestions on this issue.

#### Problem description
Trickle is currently a grotesque collection of interlocking use-cases; it is over engineered, hard to maintain, prone to bugs and difficult to configure.

**Comment by oliverfoster** [comment]
#### Suggested fix
* A component version of trickle.

##### Features
* Integrate with `_isLocked`
* Change `AdaptView.addChildren` to allow partial rendering

##### Pros
* Easier to maintain
* Easier to configure

##### Cons
* More components to configure (costly to the AT user)

**Comment by oliverfoster** [comment]
@canstudios-paulh i can't remember if you had any other concerns about a component version of page locking, would you mind adding anything else you had?

**Comment by canstudios-paulh** [comment]
Sorry I can't remember the proposed workflow? Are you proposing adding a "trickle component" between every interactive component?

**Comment by oliverfoster** [comment]
As a replacement for the trickle extension, yes.

**Comment by canstudios-paulh** [comment]
To me it feels inherently wrong for trickle to be a component - I imagine components are "black box" content types that I can put in a block to see some content. Components should not affect other components. Extensions provide overall behavioural changes to the course.

My gut feeling is that this approach would be horrible in the AT at the moment. Each trickle component would likely need its own block, and would behave like other components - so it would have a block title, body etc then component title, body instruction, classes and all the other settings etc just so the user can indicate a stopping point.  What do these mean for a trickle component? 
Is this optional? 
Is this available? 
Is this hidden? 
Is this visible? 

Of the top of my head spec: I'm pretty sure I would like all my trickle buttons to work the same way in a given course, so I would like one project level extension with a setting page where I can specify the overall behaviour (auto scroll,scroll speed, the button label, etc...). Then I would like a block setting to say if this block is a trickle breakpoint. I don't need an article breakpoint - I can use the one on the last block in the article. IF there were any settings on the article, I would like to be able to override the course setting with something more specific - (I was really thrown originally that the article settings were for a button at the end of the article). It might be good if I could set the default behaviour for blocks in this article (trickle on or off) then use a block level setting override this. 

Any use?

**Comment by oliverfoster** [comment]
Ta, perfect.

**Comment by moloko** [comment]
closing in favour of https://github.com/adaptlearning/adapt_framework/issues/2890
