### ISSUE TITLE
v5: Linting / Code styles

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2377]
### Subject of the issue
* Remove [jscs and jslint](https://github.com/adaptlearning/adapt_framework/commit/316cd5771d1ba21d4ff7a820f4cdc2b03b8f05c6) as [jscs](https://www.npmjs.com/package/jscs) is deprecated 
* Use eslint or an eslint derivative (https://standardjs.com/#standardjs--the-rules or https://github.com/standard/eslint-config-standard/blob/master/eslintrc.json)
* Add npm/grunt task to allow systems integration

**Comment by oliverfoster** [comment]
I'm not sure about using standardjs as a package. I think if we stick with eslint and start with the standardjs config removing the no colons requirement.
All of us use colons, it'll get in the way even though it makes a lot of sense to only use them where they're necessary.

**Comment by tomgreenfield** [comment]
Current reference: https://github.com/adaptlearning/documentation/blob/master/01_cross_workstream/style_guide.md.

**Comment by nilslp** [comment]
> Current reference: https://github.com/adaptlearning/documentation/blob/master/01_cross_workstream/style_guide.md.

Is this something that we will need to keep or will we be running with the standard eslint config as @oliverfoster has mentioned?

**Comment by moloko** [comment]
@nilslp i’d be tempted to keep that so that people can view the style guide in ‘human readable’ format rather than having to work through a config file trying to figure out what the rules are

@oliverfoster agree that eslint looks like the better option

**Comment by oliverfoster** [comment]
@nilslp found https://prettier.io/ which is a code formatter rather than a linter. It's got good integration with editors and git hooks.
Basically instead of requiring people to code in the right style the style will be applied automatically, on save with an extension or on commit with git hooks.
It doesn't to linting so won't help with errors but it does apply the style instead of reporting it.
Might be a better idea?
