### ISSUE TITLE
v5: Standardising indentation

### ISSUE THREAD

**Issue by nilslp** [adaptlearning/adapt_framework#2381]
### Subject of the issue/enhancement/features
The first step for the v5 refactor work is to standardise the indentation to 2 spaces for each repository. All the v5 PR's will be merged into the v5 branches in each repository.

Hopefully we can get them approved ASAP so the other work can be submitted for PR's.
Credit to @guywillis who has done the bulk of the work in the refactor.

==================================================

### Core - Indentation PR's
- [x] adapt_framework - https://github.com/adaptlearning/adapt_framework/pull/2382

### Components - Indentation PR's
- [x] accordion - https://github.com/adaptlearning/adapt-contrib-accordion/pull/91
- [x] assessmentResults - https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/51
- [x] blank - https://github.com/adaptlearning/adapt-contrib-blank/pull/31
- [x] gmcq - https://github.com/adaptlearning/adapt-contrib-gmcq/pull/119
- [x] graphic - https://github.com/adaptlearning/adapt-contrib-graphic/pull/72
- [x] hotgraphic - https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/163
- [x] matching - https://github.com/adaptlearning/adapt-contrib-matching/pull/117
- [x] mcq - https://github.com/adaptlearning/adapt-contrib-mcq/pull/148
- [x] media - https://github.com/adaptlearning/adapt-contrib-media/pull/193
- [x] narrative - https://github.com/adaptlearning/adapt-contrib-narrative/pull/190
- [x] slider - https://github.com/adaptlearning/adapt-contrib-slider/pull/140
- [x] text - https://github.com/adaptlearning/adapt-contrib-text/pull/54
- [x] textInput - https://github.com/adaptlearning/adapt-contrib-textInput/pull/98
- [x] confidenceSlider - https://github.com/adaptlearning/adapt-contrib-confidenceSlider/pull/44
- [x] pointGMCQ - https://github.com/adaptlearning/adapt-contrib-pointGmcq/pull/18

### Extensions - Indentation PR's
- [x] assessment - https://github.com/adaptlearning/adapt-contrib-assessment/pull/117
- [x] bookmarking - https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/35
- [x] languagePicker - https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/36
- [x] pageLevelProgress - https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/114
- [x] resources - https://github.com/adaptlearning/adapt-contrib-resources/pull/61
- [x] spoor - https://github.com/adaptlearning/adapt-contrib-spoor/pull/183
- [x] trickle - https://github.com/adaptlearning/adapt-contrib-trickle/pull/96
- [x] glossary - https://github.com/adaptlearning/adapt-contrib-glossary/pull/38
- [x] triggered - https://github.com/adaptlearning/adapt-contrib-triggered/pull/25

### Menu - Indentation PR's
- [x] box - https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/88

### Theme - Indentation PR's
- [x] vanilla - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/233

**Comment by guywillis** [comment]
v5 refactor is largely done and now merged with master.

Closing issue.
