### ISSUE TITLE
Language Picker breaks tracking.js module completion criteria

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2386]
### Subject of the issue
When using a multi-language course (with the Language Picker extension enabled), the tracking configuration doesn't correctly set the `_completionCriteria` from the config.json.  This is due

### Your environment
* Adapt Framework v3.5 (though v4 is also affected)
* Chrome
* OS X

### Steps to reproduce
1. Create a course with the Language Picker extension enabled and more than one language.
2. Launch the course and select a language.

### Expected behaviour
`_completionCriteria` would be correctly read from config.json.

### Actual behaviour
`_completionCriteria` is not read.  The `configModel:loadCourseData` event is never fired.

**Comment by moloko** [comment]
reopening as this needs to be fixed in v3 as well (ideally)

**Comment by brian-learningpool** [comment]
Fixed in v3.5.1 and merged to `master`.
