### ISSUE TITLE
adapt-contrib-narrative: Text-only mode

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#2393]
### Subject of the issue/enhancement/features
It is mandatory for each narrative item to have both text and a graphic, with these being displayed side-by-side.

At Can, we have found it very useful to have the option of a text-only mode. This is an option in the properties which, when enabled, hides any item graphics and makes the text boxes full width.

![Screenshot from 2019-03-21 15:24:58](https://user-images.githubusercontent.com/25502448/54766363-0c7a7980-4bf3-11e9-9a70-6ecefae914be.png)

We originally implemented this on a version of narrative which is fairly old now so I would be looking at essentially re-implementing this. If there are suggestions to make this easier to manage/maintain/test I'm open to discussion.

I would expect this to be a top-level flag which, if enabled, would hide item graphics (both visibly and to screen readers). Less would be used to expand the text box width to the full screen.

This would be implemented in the latest version of narrative (v4.0.0).

**Comment by SteveX** [comment]
I would use this. My suggestion would be that it would be more generally useful if it worked on each individual item in this way:

If there is no image the text is displayed full width.
If there is no text the image is displayed full width.
If there is no image and no text the item title is displayed larger middle centred.

**Comment by moloko** [comment]
@canstudios-nicolaw any plans to continue with this - or shall I close?

**Comment by canstudios-nicolaw** [comment]
No (I think after a discussion in Gitter) we concluded it would be best to resolve with Custom Less as there wasn't much support for adding this to core narrative.
