### ISSUE TITLE
adapt-contrib-resources: add option to circumvent cross-domain issues

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#2397]
### Subject of the issue/enhancement/features
A large number of our Adapt courses are viewed on a different domain that the domain that the content is stored on. We use a forked spoor that includes HACP AICC functionality.
The resources extension uses Javascript that is prohibited from working cross-domain.
We would like an enhancement to the adapt-contrib-resources extension to be able to implement all resource links as standard html hyperlinks similar to how it works for IE when force download is enabled.

### Your environment
Adapt authoring tool v0.6.5
Adapt framework 4.0.1.

### Steps to reproduce
To reproduce the issue,  test Adapt course in an iFrame where the content is coming from a different domain than the domain the course is launched from. The Adapt course should include the adapt-contrib-resources extension and include some resources, both external URLs and internal assets such as a PDF.

### Expected behaviour
The resource should open in a new tab/window or download

### Actual behaviour
Nothing happens and there is a cross domain error in the console

**Comment by moloko** [comment]
also see #1853

**Comment by moloko** [comment]
should be fixed by [resources v3.0.2](https://github.com/adaptlearning/adapt-contrib-resources/releases/tag/v3.0.2)
