### ISSUE TITLE
Incorrect "Unknown" lesson status when completing assessment and course in different attempts

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2398]
### Subject of the issue
Reported by @muthuselvan86 on Gitter.  If a course has an assessment and course content tracked as part of the completion criteria, in instances where the assessment is completed first, the session closed and then resumed, when the rest of the course content is completed the lesson status is incorrectly showing as "Unknown".

### Your environment
* Adapt Framework v3/4

### Steps to reproduce
As above.

### Expected behaviour
A "Completed" status would be written to the LMS.

### Actual behaviour
An "Unknown" status is being written because the assessment is not found.

**Comment by muthuselvan86** [comment]
Hi @brian-learningpool , @moloko ,

Please consider this scenario as well, lets say when a user directly  try(without completing the lessons) the assessment and got "failed" and in another session if he completes all lesson the success status shows "Unknown" Ideally it should be "Failed". I doubt this bug could be happening on tracking.js but i just started checking.
