### ISSUE TITLE
adapt-contrib-bookmarking: authoring tool 'level' defaults

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2401]
are all set to `'page'` which is probably the least-useful setting

suggest `'component'` would be the better default here

also think it might be worth removing the option to set `_level` on the course object since, for authoring tool users, this will always be overridden by the setting on the contentObject. 

alternatively we add a new `_level` setting of `'inherit'` that is only available at contentObject level and is set as the default

**Comment by oliverfoster** [comment]
`inherit` would be nice

**Comment by moloko** [comment]
yeah I like the `inherit` option best of all tbh.... maybe we give it a try here and then implement in trickle if it works out?
