### ISSUE TITLE
adapt-contrib-trickle: fails to detect completion of first block when it only contains a text component

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2405]
I believe this is inconsistent behaviour; perhaps I'm misunderstanding how Trickle works??

### Subject of the issue/enhancement/features
When first block in page has Text and Graphic and Trickle is enabled, Trickle button appears and prevents progress. When Graphic component is eliminated, Trickle button never appears and the learner has access to the first and second blocks. 

### Your environment
* Framework v4.1.0
* Chrome Version 73.0.3683.86 (Official Build) (64-bit)
* Windows 10
* FW v410
* config.json: `"_completionAttribute": "_isComplete"`

### Steps to reproduce
- Standard install of FW v410
1. Add Trickle to the first two blocks
```
"_trickle": {
            "_isEnabled": true
        }
```
2. Build and see that the Trickle button is displayed.

Compare with:
1. Remove Graphic component from the first block
2. Build and see that the Trickle button is not displayed.

### Expected behaviour
I'd expect both scenarios to behave the same--preferably with Trickle displayed in both cases.

### Actual behaviour
Trickle was not displayed when Text was the only component.

### Screenshots (if you can)
further below

### My motivation  
(Client is using FW v322) Client wants the first section of the page to be Trickled. It will contain a title (phrase) and a background video. Trickle cannot be applied to a page header, so I want to minimize/hide page header elements and allow the first block to be the first visible section. I would put a Text component in that first block with opening text (displayTitle or Body). Then I'd apply a class to the block's Trickle button to set it apart from the subsequent buttons. As it stands, I have been unable to get the Trickle button to appear on the first block when there is only a Text component. Am I misunderstanding Trickle's behaviour??

First case:
![issue-1](https://user-images.githubusercontent.com/9489014/55594067-4035c300-570c-11e9-8d49-7446e260f8bd.PNG)

Second case:
![issue-2](https://user-images.githubusercontent.com/9489014/55594068-4035c300-570c-11e9-83da-2b56750e01a4.PNG)

**Comment by akshay-bhavsar** [comment]
Issue is not replicating at my end.
i have tried with mentioned settngs.




![untitled_demo1](https://user-images.githubusercontent.com/26135970/55611238-8dfd0a80-57a2-11e9-96ff-3bb52c98bbff.gif)

**Comment by chucklorenz** [comment]
Restarted my computer and tested it again with a separate install. Same results.

**Comment by chucklorenz** [comment]
Wondering if Trickle needs the Graphic's download time in order to render/deploy correctly.

**Comment by chucklorenz** [comment]
More evidence that this seems to be an issue of the time Trickle needs to get the first block right:
- Replaced Text with Narrative; Trickle always appeared as one would guess since it is interactive
- Replaced Text with Graphic (total 2 Graphics side by side); Trickle button appeared as expected
- Replaced Graphic with Blank; Trickle button did not appear (same as when Text alone) 
- Replaced Graphic with Text (total 2 Texts side by side); Trickle button did not appear (same as when one Text)

**Comment by oliverfoster** [comment]
I think it's because those components complete before trickle has finished setting up and so it ignores them.

**Comment by oliverfoster** [comment]
fixed with above pr
