### ISSUE TITLE
adapt-contrib-hotgraphic: question rather than issue

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#2406]
### question rather than issue
Hotgraphic "_items_graphic" has "title" attribute in property.schema. How we can relate the same attribute in frameworks _graphic attribute as we don't have any such implemented in .hbs as well as example.json
 
Link : https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/properties.schema#L207-L215

**Comment by sarveshwar-gavhane** [comment]
any thought on this ?

**Comment by tomgreenfield** [comment]
I was under the impression this field was removed in Hot Graphic 2.

See the [template](https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/2957263050f96b895d9993e1f585e94296fa2a96#diff-a153ae0599734dca69f765c21c6b5230R32) and [example JSON](https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/cfc26f25f938142ed7d96d296ae25a2925458436#diff-964a59d491880661889b0e908c47a1e0) references.

It should just need removing from the schema.

**Comment by sarveshwar-gavhane** [comment]
thanks for the links.

**Comment by NayanKhedkar** [comment]
[#PR](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/171)
