### ISSUE TITLE
Trickle works 900 in width but not at 1024

### ISSUE THREAD

**Issue by jupedega** [adaptlearning/adapt_framework#2411]
### Subject of the issue/enhancement/features
When the screen is 900px wide the trickle works perfectly, when I change the width to 1024 it is lost
### Your environment
* version (2.2.1/2.2)
* Explorer 11, chrome 73.0.3683.103
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by moloko** [comment]
please could you include steps to reproduce. without knowing how you have configured trickle it's going to be very hard to replicate this issue.

**Comment by moloko** [comment]
closing due to lack of detail/response
