### ISSUE TITLE
trickle

### ISSUE THREAD

**Issue by jupedega** [adaptlearning/adapt_framework#2412]
### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by oliverfoster** [comment]
no issue specified - closing
