### ISSUE TITLE
Inheritance bug breaks ItemComponentModel chain.

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2415]
### Subject of the issue
`ItemsComponentModel` ends up inheriting from `QuestionModel` due to the poor creation of `ItemsQuestionModel`. The `ItemsComponentModel` `constructor` function is extended in error.

**Comment by moloko** [comment]
done in b6988c335cd9f8b077c7d9f52fc379a5ddc6721b
