### ISSUE TITLE
adapt-contrib-media: adding component without media ends up in infinite loop

### ISSUE THREAD

**Issue by canstudios-simonasd** [adaptlearning/adapt_framework#2418]
### Steps to reproduce
- Add media component to block.
- Open media component settings and click `Save`.
- Click `Preview course`.
- Open page in which media component was added.

### Expected behaviour
Course page should fully load even when media component has no media in it.

**Comment by tomgreenfield** [comment]
I can't seem to replicate this one, especially after following the second step:
> * Open media component settings and click `Save`.

**Comment by canstudios-simonasd** [comment]
I can see two issues, one is:
> Otherwise, it reminds me of [adaptlearning/adapt_authoring#1158](https://github.com/adaptlearning/adapt_authoring/issues/1158).

And other is this one. When there is no media selected `setReadyStatus` is never called.

**Comment by tomgreenfield** [comment]
Update: confirmed that this issue has been caused by the removal of the `finally` statement in https://github.com/adaptlearning/adapt-contrib-media/pull/186.

Replicable in authoring tools running framework 4 (which targets Media 4+).
