### ISSUE TITLE
Assessment results does not reset on revisit if passed

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#2430]
### Subject of the issue/enhancement/features
When passing an assessment and returning to the menu and re-entering the assessment, the assessment results will be present with the feedback on the original attempt even though the assessment has reset.

### Your environment
- Assessment v3.1.0
- Assessment results v2.4.0
- Framework v3.5.3

- all browsers
- all devices

### Steps to reproduce
Create an article with a series of questions
Configure it for an assessment and ensure the following settings are enabled:

- Reset on Revisit
- Allow retry once passed

Add and configure assessment results

Preview and fail the assessment
Return to the menu and then re-enter the page with the assessment
The assessment and assessment results will be reset
Now pass the assessment, return to the menu, then re-enter the page

### Expected behaviour
Assessment and assessment results will be reset

### Actual behaviour
Assessment is reset but assessment results is not

**Comment by chetan-hajare** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/52
