### ISSUE TITLE
adapt-contrib-hotgraphic: pin classes missing from template

### ISSUE THREAD

**Issue by SteveX** [adaptlearning/adapt_framework#2432]
### Subject of the issue/enhancement/features
When uploading graphics for pins (https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/166, if classes are entered for individual pins they don't appear in the html as they aren't allowed for in the template.

### Your environment
* 0.7.1 / 4.0.1
* adapt-contrib-hotgraphic 4.2.0

### Steps to reproduce
Upload a pin image, add classes, check html.

**Comment by moloko** [comment]
hi @SteveX, according to the README, for the `_items[n]._classes` property:
> CSS class name to be applied to the hot spot popup item. The class must be predefined in one of the Less files. Separate multiple classes with a space.

Appreciate it might be useful to be able to specify classes for the pin when using images as pins but I think it might be better to specify that as `_items[n]._pin._classes`...?

**Comment by SteveX** [comment]
Yes, it's more of a mess than it first looked.

In the authoring tool it is labelled as Pin Classes and appears above Pin Position - Left (_items[n]._left) and Pin Position - Top (_items[n]._top).

There is also Graphic Classes which are never applied, and no field for the popup classes.

**Comment by moloko** [comment]
Yep, we [just recently addressed](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/170) this confusion. so recently it hasn't yet been released hence why you'll see the old, confusing, info in the authoring tool.

**Comment by SteveX** [comment]
Oh, ok.

Looking at that readme, it says about positioning pins in pixels which is incorrect, they use percentages.
