### ISSUE TITLE
PLP looks for JSON that doesn't exist in default Adapt-cli setup

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2433]
### Subject of the issue/enhancement/features

When you create a new course with the latest version of the FW and try to run it there is some JSON missing. Either the JSON needs to be added in the correct place or the PLP extension needs to be updated to be defensive.

PLP - https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/8202e3c291c15edb5e1905f14566c1f4d12c1a6c/js/PageLevelProgressNavigationView.js#L44
course.json - https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/course.json#L34

With Grunt this isn't a problem and the course compiles but Rub prevents the course loading.

### Your environment
* version (AT/Framework) fw v4.2.0 
* Node v8.11.4

**Comment by moloko** [comment]
This is really an issue for [rub-cli](https://github.com/cgkineo/rub-cli) not for Adapt Open Source
