### ISSUE TITLE
Error during registering a plug-in

### ISSUE THREAD

**Issue by kunjsharma** [adaptlearning/adapt_framework#2434]
### Subject of the issue/enhancement/features
While registering Adapt plug-in, an error coming.

### Your environment
* version 4.0.1
* Firefox 66.0.5
* Desktop PC + Windows 8

### Steps to reproduce
when register a plug-in

### Expected behaviour
It should register plug-in as I did it with other plugins.

### Actual behaviour
Error occurred: TypeReeor: <source || "">.trim is not a function

### Screenshots (if you can)
![ari](https://user-images.githubusercontent.com/6715520/57904396-2ef5df80-7890-11e9-8cfb-db2f15fb54c0.png)

**Comment by NayanKhedkar** [comment]
@kunjsharma I'm sure, in your bower.json 
``"repository": {
        "type": "git",
        "url": "git://github.com/<user>/<repo_name>.git"
    }
``
something like this.

can please try with 
`` "repository":" git://github.com/<user>/<repo_name>.git" ``

@chris-steele  I think we need to handle this case.

**Comment by tomgreenfield** [comment]
@kunjsharma, please can you move your issue to the [Adapt CLI repo](https://github.com/adaptlearning/adapt-cli/issues/new) and clearly state your Node and CLI versions:
```console
node -v && adapt -v
```

@NayanKhedkar, your issue is [here](https://github.com/adaptlearning/adapt-cli/issues/110) and I believe the CLI just needs a fresh release.

**Comment by kunjsharma** [comment]
Hi @NayanKhedkar  and @tomgreenfield for reply. Issue moved to https://github.com/adaptlearning/adapt-cli/issues/117 as suggested.

**Comment by NayanKhedkar** [comment]
> @kunjsharma, please can you move your issue to the [Adapt CLI repo](https://github.com/adaptlearning/adapt-cli/issues/new) and clearly state your Node and CLI versions:
> 
> ```
> node -v && adapt -v
> ```
> 
> @NayanKhedkar, your issue is [here](https://github.com/adaptlearning/adapt-cli/issues/110) and I believe the CLI just needs a fresh release.

👍

**Comment by NayanKhedkar** [comment]
Refer : adaptlearning/adapt-cli#117
