### ISSUE TITLE
Adapt.wait should implement a timeout in order to prevent blocking of rendering

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2439]
### Subject of the enhancement
The `Adapt.wait` API has `begin()` and `end()` calls but in cases where calls to `begin()` do not have a corresponding call to `end()` (for whatever reason) it can result in a course failing to load and difficult to diagnose errors.

### Your environment
Adapt Framework v3.5.3

### Steps to reproduce
Inside a plugin call `Adapt.wait.begin()` and do not call `Adapt.wait.end()`.

### Expected behaviour
After a given timeout, the queue should be flushed together with a debug message logged to the console to indicate as such.

### Actual behaviour
The Adapt content appears to get stuck in an intermediate state between loading and rendering.

**Comment by brian-learningpool** [comment]
Just discussed this with @oliverfoster on Gitter chat.   `Adapt.wait.for(callback)` (and correctly handling the error callback) would have prevented this, but it does make sense to add a timeout.

A 7-second timeout (as used by RequireJS) would be sufficient.  This should be reset on every call to `begin()`.  Also, calls to `this.end` should be wrapped in a `_.once()`.

**Comment by oliverfoster** [comment]
@brian-learningpool are we ok to remove the 7 seconds now that the xpi begin/wait queue is sorted? or was this for something else?
