### ISSUE TITLE
Hot Graphic scrolling background

### ISSUE THREAD

**Issue by leahyjulian** [adaptlearning/adapt_framework#2440]
### Bug adapt-contrib-hotgraphic
Scrolling background when pop up is showing

### Your environment
* Adapt Framework  4.1.1
* Latest Chrome Version 74.0.3729.157 (Official Build) (64-bit)
* Microsoft Windows 10

### Steps to reproduce
Within the popup body of a Hot Graphic Component add a lot of text so when viewed in the browser the text goes below the view port

### Expected behaviour
Should be able to scroll within the box to read all text (default behaviour in firefox)

### Actual behaviour
Instead of the box background scrolling the main background scrolls

### Screenshots (if you can)
Note background position - before scroll
![image](https://user-images.githubusercontent.com/48165156/58064510-7d7be480-7bd6-11e9-9c58-1edb876f72da.png)
After scroll
![image](https://user-images.githubusercontent.com/48165156/58064556-b0be7380-7bd6-11e9-871e-54c8f8137743.png)

**Comment by brian-learningpool** [comment]
The console log gives the following error:
`jquery.min.js:formatted:2117 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

**Comment by moloko** [comment]
Tried updating to the latest version of JQuery just on the off-chance that might solve it - but sadly not.

Looks to be originating from `a11y_setupScrollListeners` in jquery.a11y.js

**Comment by brian-learningpool** [comment]
Yes, the error message is being thrown by this line:
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L76

**Comment by oliverfoster** [comment]
This concept of specifying the passive property needs applying to the other scroll events
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L556

**Comment by moloko** [comment]
> 
> 
> This concept of specifying the passive property needs applying to the other scroll events
> https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L556

They may have to be changed to vanillajs first as it doesn't look like JQuery supports passive event listeners yet https://github.com/jquery/jquery/issues/2871

**Comment by oliverfoster** [comment]
That's what's needed. jQuery doesn't support event attachment options, as you said.

**Comment by moloko** [comment]
@leahyjulian hopefully updating to the current master branch of the framework should fix this issue for you...
