### ISSUE TITLE
Grunt, build & changes to libraries.

### ISSUE THREAD

**Issue by jamesrea83** [adaptlearning/adapt_framework#2441]
### Subject of the issue/enhancement/features
Start `grunt dev`, then make a change to a file in core/js/libraries. Grunt will detect the change and start a build process, but the corresponding core/js/libraries file in the build folder will be unchanged.

In order to get the change into the build folder, you must manually stop then restart `grunt dev`.

Is this by design, or should libraries get updated on change like other files in src/?

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt_framework/pull/2444

**Comment by NayanKhedkar** [comment]
@jamesrea83 could you please test it out.
