### ISSUE TITLE
v5: BEM naming and SMACSS Less formatting

### ISSUE THREAD

**Issue by nilslp** [adaptlearning/adapt_framework#2447]
### Subject of the issue/enhancement/features

First step - https://github.com/adaptlearning/adapt_framework/issues/2381

The second step for the v5 refactor work is to convert to the BEM naming convention for each repository. The LESS SMACSS formatting is also required for this step.
All the v5 PR's will be merged into the v5 branches in each repository.

Hopefully we can get them approved ASAP so the other work can be submitted for PR's.
Credit to @guywillis who has done the work in the refactor.

==================================================

### Core - BEM naming and SMACSS Less formatting PR's
- [x] adapt_framework - https://github.com/adaptlearning/adapt_framework/pull/2516

### Components - BEM naming and SMACSS Less formatting PR's
- [x] accordion - https://github.com/adaptlearning/adapt-contrib-accordion/pull/95
- [x] assessmentResults - https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/54
- [x] blank - https://github.com/adaptlearning/adapt-contrib-blank/pull/33
- [x] gmcq - https://github.com/adaptlearning/adapt-contrib-gmcq/pull/121
- [x] graphic - https://github.com/adaptlearning/adapt-contrib-graphic/pull/74
- [x] hotgraphic - https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/180
- [x] matching - https://github.com/adaptlearning/adapt-contrib-matching/pull/120
- [x] mcq - https://github.com/adaptlearning/adapt-contrib-mcq/pull/150
- [x] media - https://github.com/adaptlearning/adapt-contrib-media/pull/203
- [x] narrative - https://github.com/adaptlearning/adapt-contrib-narrative/pull/196
- [x] slider - https://github.com/adaptlearning/adapt-contrib-slider/pull/141
- [x] text - https://github.com/adaptlearning/adapt-contrib-text/pull/55
- [x] textInput - https://github.com/adaptlearning/adapt-contrib-textInput/pull/99
- [x] confidenceSlider - https://github.com/adaptlearning/adapt-contrib-confidenceSlider/pull/45
- [ ] ~~pointGMCQ~~

### Extensions - BEM naming and SMACSS Less formatting PR's
- [x] assessment - https://github.com/adaptlearning/adapt-contrib-assessment/pull/121
- [x] bookmarking - https://github.com/adaptlearning/adapt-contrib-bookmarking/pull/37
- [x] languagePicker - https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/38
- [x] pageLevelProgress - https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/116
- [x] resources - https://github.com/adaptlearning/adapt-contrib-resources/pull/62
- [x] spoor - https://github.com/adaptlearning/adapt-contrib-spoor/pull/185
- [x] trickle - https://github.com/adaptlearning/adapt-contrib-trickle/pull/99
- [x] glossary - https://github.com/adaptlearning/adapt-contrib-glossary/pull/43
- [ ] ~~triggered~~

### Menu - BEM naming and SMACSS Less formatting PR's
- [x] box - https://github.com/adaptlearning/adapt-contrib-boxmenu/pull/91

### Theme - BEM naming and SMACSS Less formatting PR's
- [x] vanilla - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/238

**Comment by guywillis** [comment]
v5 refactor is largely done and now merged with master.

Closing issue.
