### ISSUE TITLE
adapt-contrib-assessmentResults : Review assessment button feature

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#2455]
currently we have retry assessment feature for **adapt-contrib-assessmentResults**, but as of now we don't have facility to review the assessment. 
It would be nice if learner can review their selection of answers after his last attempts. We get numerous requests of this feature from various clients.

Suggestion:
To accomodate this feature we can have "Review assessment" button similar to retry assessment button by click on which learner will be able to review his selections. This button should be only made available if the attempt is final/last attempt. when learner click on "Review assessment" button, he will be able to see all the attempted questions.

we can introduce a new attribute which will decide when to show "Review assessment" button e.g.for passed/failed attempt.

**Comment by moloko** [comment]
hi @sarveshwar-gavhane I don't understand what would happen when the 'review assessment' button is clicked.

What do you mean by 'he will be able to see all the attempted questions'? Surely the learner can just scroll up to see these?

If necessary the `_suppressMarking` feature can also be enabled to show ticks and crosses once the assessment is passed or all attempts have been used up.

**Comment by chetan-hajare** [comment]
Indeed @moloko , but the main use of this button will be ease of use to the learner. 

We have came across the situations where the courses are having 10 to 25 number of questions. When the learner has to review the assessment, they have to scroll up right at the 1st question and review the attempts which is bit annoying for the learners specifically when the number of questions are too large. Yes, we do already have the feature of `_suppressMarking` but this enables/works when we are at last question of the last attempt, then all the suppressed markings and model answers button suddenly get enabled making the changes surprising to the learners. Also this option looks best for the developers but when it comes to end user/learner they don't see any option as such to review the questions. 

So we are thinking of having this `_suppressMarking` feature in assessmentResult component as 'Review assessment' button such that on clicking this button, the learner will be scrolled up to 1st question and at the same time all the suppressed markings and model answer button get enabled if the attempt is the last/final similar to `_suppressMarking` feature.

**Comment by moloko** [comment]
hi both and thanks for taking the time to clarify the requirements

my initial thought is that it does sound like the kind of functionality that could be added in via an extension or a component that 'extends' this one (or perhaps even just by overriding the template in the theme)

Just aware that the core plugins are getting quite heavy in terms of functionality and features - which is making them harder to test and keep bug-free. But if people disagree and think this would be important functionality to have in the core plugin then please say!

**Comment by sarveshwar-gavhane** [comment]
yes i wholeheartedly agree that core plugins are getting heavy, just discuss this with all other members if they feel this feature isn't important/useful to the learner, then i will be happy to close this issue :).
