### ISSUE TITLE
iOS The scroll loses the menu navigation

### ISSUE THREAD

**Issue by jupedega** [adaptlearning/adapt_framework#2456]
### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
* version (0.8.1/4.0.1)
* iOS 12.2
* Iphone 6s + Safari(s)

### Steps to reproduce

To reproduce this bug in iOS I publish the course, before I put _scroollingContainer enabled. 

### Expected behaviour
What should happen is that the scroll will reach the end of the block, not the middle of the block where the video is.
### Actual behaviour
When I try to scroll up to the limit of the trickle, it stays in the middle of the content. for example in the video, which is the first block with trickle. 

When I try to force several times to slide, the menu is lost.

**Comment by oliverfoster** [comment]
There are some quirks with iOS screen size and iframes.
1. screen size:
[Viewport height bug](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html)
[Comment from apple](https://bugs.webkit.org/show_bug.cgi?id=141832#c5)
2. iframes:
[height](https://blog.codepen.io/2017/12/01/stupid-iframes-stupid-ios/)
[scroll](https://davidwalsh.name/scroll-iframes-ios)

You are launching the course inside an iframe on iOS Safari, did you read [this wiki page](https://github.com/adaptlearning/adapt_framework/wiki/Accessibility-v3-%E2%86%92-v4#scrolling) on the `_scrollingContainer` property?

![image](https://user-images.githubusercontent.com/7974663/59417322-ef52e280-8dbe-11e9-91f3-7781f9526d0f.png)


Can I have a copy of your [_scrollingContainer](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/config.json#L47-L50) json? The ticket isn't clear.

**Comment by jupedega** [comment]
Thank you so much for the quick anwser. I pass you an image with the configuration.
![14](https://user-images.githubusercontent.com/23155419/59419974-51feab00-8dcc-11e9-950a-d5456ec2052f.png)

`"_scrollingContainer": {
    "_isEnabled": true,
    "_limitToSelector": ".os-ios"
  },`


Actually, it's the same thing that I've seen in the image

**Comment by oliverfoster** [comment]
Can I have a copy of your course?

**Comment by jupedega** [comment]
Thanks. How can I pass the export course?

**Comment by oliverfoster** [comment]
https://gitter.im/adaptlearning/adapt_framework You can drop the exported zip into a private chat with me in gitter.

**Comment by jupedega** [comment]
Do it...

**Comment by oliverfoster** [comment]
Fixed by back injecting styling into moodle container document.
```js
var lmsDocument = window.top.document;
var $newStyling = $("<style>#scorm_layout { height: 100vh !important; }</style>", lmsDocument);
$('head', lmsDocument).append($newStyling);
```
Moodle sets the `#scorm_layout` (iframe container) height to the size of the screen on ios, rather than the available window space.
