### ISSUE TITLE
adapt-contrib-spoor: SCORM 1.2 courses only ever set exit value to an empty string

### ISSUE THREAD

**Issue by canstudios-matth** [adaptlearning/adapt_framework#2458]
### Subject of the issue/enhancement/features
When creating a SCORM 1.2 course, the `cmi.core.exit` value is only ever set to an empty string. This causes problems in some LMSs when trying to resume and/or restart a course, as an exit value of 'suspend' is expected to enable resuming a course.

### Your environment
* AT 0.8.1 / Framework 4 
* All browsers and devices

### Steps to reproduce
1. Launch course with Spoor extension
2. Close course window

### Expected behaviour
It should be possible to control what `cmi.core.exit` is set to for situations when the default behaviour is not desirable

### Actual behaviour
The value of `cmi.core.exit` is always set to an empty string.

**Comment by moloko** [comment]
> This causes problems in some LMSs when trying to resume and/or restart a course, as an exit value of 'suspend' is expected to enable resuming a course.

Just to clarify that this is actually only known to be occurring on SCORM Cloud when this compatibility setting is applied:
![image](https://user-images.githubusercontent.com/1249597/59674018-4b03de00-91ba-11e9-8407-01bcf293613c.png)
