### ISSUE TITLE
matching v3/FW v2/iOS issue

### ISSUE THREAD

**Issue by Raffaele-pastura** [adaptlearning/adapt_framework#2459]
### Subject of the issue/enhancement/features
matching question does not work on IOS, the options are not selectable. The menu of each option disappears immediately after appearing.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by moloko** [comment]
@Raffaele-pastura please could you give details of your environment as requested in the issue template?

FYI I just tested matching v3.0.0 (with FW v4.2.0) on iOS v12.3.1 (iPhone and iPad) - works fine for me.

**Comment by Raffaele-pastura** [comment]
I’am working on autoring tools in this domain https://mercuri-international.adaptauthoringtool.com/ and I’am testing on on iOS v12.3.1.


[cid:image001.png@01D45647.8A20A910]
Raffaele Pastura  |  Digital Learning - Developer
T. +39 02 54100002        M. +39 331 8634566
raffaele.pastura@mercuri.it<mailto:raffaele.pastura@mercuri.it>

Mercuri International Srl
Via Santa Rita da Cascia, 33 - Milano, Italia
www.mercuri.it<http://www.mercuri.it>
[cid:image002.png@01D45647.8A20A910]<https://www.facebook.com/MercuriItalia/>
[cid:image003.png@01D45647.8A20A910]<https://twitter.com/mercuri_intern>
[cid:image004.png@01D45647.8A20A910]<https://www.linkedin.com/company/mercuri-international-italia/>
Every year Mercuri International empowers companies in over 50 countries to achieve sales excellence. We serve our clients both locally and globally with customized solutions and industry expertise. We grow profit through people, providing the tools and processes to tackle any sales challenge.
[cid:image005.png@01D45647.8A20A910]
Mercuri International is featured on both Training industry<https://www.mynewsdesk.com/mercuri-international-group/pressreleases/mercuri-international-awarded-top-20-sales-training-company-2018-globally-2459143> and Selling Power<https://www.mynewsdesk.com/mercuri-international-group/pressreleases/selling-power-features-mercuri-international-on-2018-top-20-sales-training-companies-list-2503852> ‘Top 20 Sales Training Companies’ lists.

This message is of a confidential nature and information contained herein may not be disclosed to third parties or disseminated in any way. If you are not the intended recipient, please immediately notify to mercuri@pec.mercuri.it<mailto:mercuri@pec.mercuri.it>. Data and information contained in this email will be treated in accordance with and for the purposes of the European Regulation "GDPR" 2016/679 and subsequent amendments




Da: Matt Leathes <notifications@github.com>
Inviato: venerdì 21 giugno 2019 13:55
A: adaptlearning/adapt_framework <adapt_framework@noreply.github.com>
Cc: Raffaele Pastura <raffaele.pastura@mercuri.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [adaptlearning/adapt_framework] matching question does not work on IOS (#2459)


@Raffaele-pastura<https://github.com/Raffaele-pastura> please could you give details of your environment as requested in the issue template?

FYI I just tested matching v3.0.0 (with FW v4.2.0) on iOS v12.3.1 (iPhone and iPad) - works fine for me.

**Comment by moloko** [comment]
@Raffaele-pastura I can't access that authoring tool instance, I think this is something you need to raise with Can Studios. Perhaps @canstudios-nicolaw or @canstudios-paulh can help?

**Comment by canstudios-paulh** [comment]
Hi @Raffaele-pastura our offering includes v3 of the Matching component - its source (bower.json) says it is compatible with the framework we're running, but I guess you hit a bug.
We will be updating the framework on our authoring tools once there is content migration process. (We are actively working on this). The best solution is probably to use the newer framework rather then try to fix the issue in a legacy version.

**Comment by moloko** [comment]
Confirmed I can replicate with Matching v3.0.0 and FW v2.3.3

**Comment by Raffaele-pastura** [comment]
Ok thanks a lot for the reply.
If I understand correctly, should I use the new version of the framework? How can I do this?

[cid:image001.png@01D45647.8A20A910]
Raffaele Pastura  |  Digital Learning - Developer
T. +39 02 54100002        M. +39 331 8634566
raffaele.pastura@mercuri.it<mailto:raffaele.pastura@mercuri.it>

Mercuri International Srl
Via Santa Rita da Cascia, 33 - Milano, Italia
www.mercuri.it<http://www.mercuri.it>
[cid:image002.png@01D45647.8A20A910]<https://www.facebook.com/MercuriItalia/>
[cid:image003.png@01D45647.8A20A910]<https://twitter.com/mercuri_intern>
[cid:image004.png@01D45647.8A20A910]<https://www.linkedin.com/company/mercuri-international-italia/>
Every year Mercuri International empowers companies in over 50 countries to achieve sales excellence. We serve our clients both locally and globally with customized solutions and industry expertise. We grow profit through people, providing the tools and processes to tackle any sales challenge.
[cid:image005.png@01D45647.8A20A910]
Mercuri International is featured on both Training industry<https://www.mynewsdesk.com/mercuri-international-group/pressreleases/mercuri-international-awarded-top-20-sales-training-company-2018-globally-2459143> and Selling Power<https://www.mynewsdesk.com/mercuri-international-group/pressreleases/selling-power-features-mercuri-international-on-2018-top-20-sales-training-companies-list-2503852> ‘Top 20 Sales Training Companies’ lists.

This message is of a confidential nature and information contained herein may not be disclosed to third parties or disseminated in any way. If you are not the intended recipient, please immediately notify to mercuri@pec.mercuri.it<mailto:mercuri@pec.mercuri.it>. Data and information contained in this email will be treated in accordance with and for the purposes of the European Regulation "GDPR" 2016/679 and subsequent amendments




Da: canstudios-paulh <notifications@github.com>
Inviato: venerdì 21 giugno 2019 16:17
A: adaptlearning/adapt_framework <adapt_framework@noreply.github.com>
Cc: Raffaele Pastura <raffaele.pastura@mercuri.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [adaptlearning/adapt_framework] matching question does not work on IOS (#2459)


Hi @Raffaele-pastura<https://github.com/Raffaele-pastura> our offering includes v3 of the Matching component - its source (bower.json) says it is compatible with the framework we're running, but I guess you hit a bug.
We will be updating the framework on our authoring tools once there is content migration process. (We are actively working on this). The best solution is probably to use the newer framework rather then try to fix the issue in a legacy version.

**Comment by oliverfoster** [comment]
please check with the above PR if possible ^

**Comment by moloko** [comment]
can this be closed now?

**Comment by oliverfoster** [comment]
yes
