### ISSUE TITLE
adapt-contrib-trickle: Page auto scrolling to trickle element

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#2460]
### Subject of the issue/enhancement/features
This has been raised by our content team.
- Sometimes if trickle is on a page then the page will scroll to trickle as soon as it is opened
- There doesn't seem to be clear behaviour as to why it is scrolling on some pages and not others
- When the page scrolls to the trickle element, screen reader focus also jumps to the trickle element (probably not an issue in itself)

### Your environment
* version (AT/Framework) 0.8.1 AT & 4.2.0 FW
* which browser and its version IE11 - not been seen on other browsers

### Steps to reproduce
I'm afraid that we don't have a solid way to reproduce this, but it does seem to be happening fairly frequently. 

### Expected behaviour
The page shouldn't jump to the trickle component when it is first opened.

**Comment by moloko** [comment]
possibly related to #2405

**Comment by canstudios-nicolaw** [comment]
I have sent it to the content team to see if it rings any bells

**Comment by moloko** [comment]
@canstudios-nicolaw any update on this or can I close?
