### ISSUE TITLE
Update JSON for when course is created to include language picker

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2461]
The course that comes when you run `adapt create course` should be updated to include all the plugins that come with it. Language picker is currently missing. Even if it was disabled the JSON should be included.

**Comment by moloko** [comment]
This was a deliberate choice. Personally I think it's fine as it is, you only have to copy the relevant snippet of .json from languagePicker's example.json to enable it (as well as add the relevant languages, naturally). But I'm happy to change it if people feel it should be changed?
