### ISSUE TITLE
"soft" _isResetOnRevisit breaks questions

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2474]
Questions set to use `"_isResetOnRevisit": "soft"` within the components.json, cannot be answered. The `_buttonState` is undefined and causes an error, and the question doesn't think its interactive, so items can't be selected.

**Comment by moloko** [comment]
this is the error btw
![issue-2474-error](https://user-images.githubusercontent.com/1249597/61896613-42b36700-af0d-11e9-8921-badb50de2c64.png)
