### ISSUE TITLE
adapt-contrib-media: iOS controls

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2477]
On iOS, when returning from fullscreen, both the iOS native controls and mediaelement controls are visible. This is most evident when closed captions have been enabled.

**Comment by danielghost** [comment]
This can be worked around by either preventing fullscreen, or using native controls for iOS via the following settings, although this isn't fixing the actual issue:
```
"_playerOptions": {
    "iPadUseNativeControls": true,
    "iPhoneUseNativeControls": true
}
```

Previously this option didn't work and threw an error due to the `mediaElement.player` being undefined, but looks like this must have been resolved in a recent update.

**Comment by moloko** [comment]
Maybe the answer is to force `iPadUseNativeControls` and `iPhoneUseNativeControls` to `true` whenever the OS is iOS? I wouldn't have a problem with that.

**Comment by danielghost** [comment]
Found the issue which was previously present when using these native controls and added a PR to fix.

**Comment by moloko** [comment]
I think this should be all OK now @danielghost ?
