### ISSUE TITLE
Hot Graphic/Narrative on landscape iPhone XR keeps tablet/desktop view

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#2492]
### Subject of the issue
When viewing a hot graphic component in landscape view the screen size exceeds the standard mobile breakpoints and displays the component in the desktop/tablet view with pins rather than switching out to the narrative view.

### Your environment
* f/w - 3.5.3 Hot graphic - 4.2.0 Narrative - 3.0.2
* Viewing Safari on iOS 12
* iPhone XR

### Steps to reproduce
create a course with a hot graphic and a narrative
publish
View on iPhone XR with orientation set to landscape

### Expected behaviour
View should on both components should be the narrative mobile view

### Actual behaviour
Hot Graphic renders main image and pins, Narrative displays image and text side by side

**Comment by moloko** [comment]
@kevindoherty30 is this not just a case of setting the breakpoints correctly for this particular device?

**Comment by kevindoherty30** [comment]
@moloko yeah I think that's exactly what it is and as soon as I read your comment it made sense, I could kick myself!
