### ISSUE TITLE
PageLevelProgress - Release request

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#2500]
Please can this plugin be released to include the latest 2 commits, without [@aa4a717](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/aa4a71797163bc759c3522f9392af642120f2c20) i'm finding a course will not load after triggering "pageLevelProgress:update".

Many thanks!

**Comment by moloko** [comment]
yes no problem, thanks for the prompt!

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/releases/tag/v4.1.2
