### ISSUE TITLE
adapt-contrib-narrative: scroll bar appears in graphic area when Text area navigation is disabled and an item has attribution text

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_framework#2509]
### Subject of the issue/enhancement/features
When a Narrative component has text area navigation enabled and attribution text within at least one item, the graphic area of a Narrative item gains a scroll bar. This does not occur when all items within the Narrative component lack attribution text or when text area navigation is disabled.

### Your environment
  * Authoring Tool Version: 0.9.0
  * Framework Version: 4.2.0

### Steps to reproduce
1. In a course, add a Narrative component. 
1. Navigate into the Narrative component's properties.
1. Enable "Move navigation to text area". 
1. Add a few items with attribution text. 
1. Click Save. Click Preview. 
1. Navigate to the Narration component. Notice that the graphic of the item has a scroll bar.

### Expected behaviour
There shouldn't be a scroll bar within any item of a Narrative component.

### Actual behaviour
A scroll bar appears in the graphic area.

### Screenshots (if you can)
![Scroll bar appears when navigation is in text area](https://user-images.githubusercontent.com/48051681/63338951-bcd3e180-c33b-11e9-831e-bc8eade61c44.jpg)

**Comment by guywillis** [comment]
I could not replicate this in the latest version of Adapt. Can I close?
