### ISSUE TITLE
Handlebars v4.3.0/1 prevents Adapt from running

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2524]
A recent (24th Sept) update to the 'compiler' (node) version of handlebars is breaking Adapt.

If you do `$ adapt create course`, build it and run it, Adapt does not render and the following error is shown in the console:
> Error: Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0).

There is a ticket about this issue on the handlebars repo here: https://github.com/wycats/handlebars.js/issues/1561

In the meantime, Framework users should be able to work around this by updating src/core/libraries/handlebars.min.js to the latest version (note: I haven't tested that doing so won't break anything else!)

**Comment by oliverfoster** [comment]
The `src/core/libraries/handlebars.min.js` (runtime) and the grunt compiler (package.json dependency) should match to the extent that they are compatible with each other. 

How are these two copies out of sync? Is the package.json dependency too loose or does the runtime need updating?

**Comment by moloko** [comment]
>  Is the package.json dependency too loose

No, it's more that the author of handlebars should, strictly speaking, have done a major version release. But, for reasons I can understand (and which he explains in the ticket I linked to), he didn't.

**Comment by moloko** [comment]
If we think updating to the latest hbs runtime is a good/safe move then let's just go with that - but I we'll need to do a release of every single major version of Adapt to get it out there

**Comment by moloko** [comment]
>  we'll need to do a release of every single major version of Adapt to get it out there

I've checked both FW v2.4.1 and v3.5.4 - neither is affected by this issue - so we don't need to patch and release these older versions.
