### ISSUE TITLE
pre-release a11y amends

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2530]
### Subject of the issue
* Turn on _isFocusOutlineKeyboardOnlyEnabled  by default
* Make sure it isn't activated over an input or textarea

**Comment by moloko** [comment]
just spotted... `_isFocusOutlineKeyboardOnlyEnabled` is still set to `false` in config.json:

https://github.com/adaptlearning/adapt_framework/blob/c24cd5264a129ad4a22c4c7bf8feb3b9a170f5a1/src/course/config.json#L23-L37

If we really want the default to be `true` then it needs to be changed there also.
