### ISSUE TITLE
notify: make a hard API

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2532]
### Subject of the issue
Currently a notify instance is created by triggering a backbone event. It should be a hard API as there is only ever one end point.

Current:
```js
Adapt.trigger('notify:alert', notifyObject);
```
Suggested:
```js
Adapt.notify.alert(notifyObject);
```

**Comment by moloko** [comment]
related - see #2540 for documentation changes

https://github.com/adaptlearning/adapt_framework/wiki/Core-modules#notify has been updated as well
