### ISSUE TITLE
adapt-contrib-trickle: issue with textInput components on iOS (phone only)

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2536]
### Subject of the issue/enhancement/features
If you have one or more text input components in a block that's trickled and you have set `_autoHide: true` on the trickle button, the trickle button does not appear on component completion. You have to 'pull down' on the screen to force it to 'overscroll' before it will appear... and it worsens on the 2nd (and following) text input components in that you have to scroll up then back down

### Your environment
* Framework v4.4.0/trickle v3.0.1
* Safari for iOS
* iPhone, iPad iOS v10 > v13

### Steps to reproduce
Create a couple of blocks each containing a full-width text component. Apply trickle to the containing article using the following settings:
```json
"_trickle": {
    "_isEnabled": true,
    "_button": {
        "_isEnabled": true,
        "_autoHide": true,
        "text": "Continue",
        "startText": "Continue",
        "finalText": "Continue"
    }
}
```
### Expected behaviour
The trickle button should appear immediately as you are already at the bottom of the viewport

### Actual behaviour
You have to scroll down  - or up and then down to get it to appear

### Screenshots (if you can)
![ios-textinput-trickle-bug gif](https://user-images.githubusercontent.com/1249597/66065861-3e747d00-e540-11e9-9783-267ee67f0542.gif)

**Comment by moloko** [comment]
in case the above animated gif doesn't play automatically, click it and it will open and play!

**Comment by eleanor-heath** [comment]
@oliverfoster Is this still an issue, I can't seem to replicate it when using FW 5.13.0 and trickle 5.0.0

**Comment by oliverfoster** [comment]
I think inview has been fixed since. Thanks for checking.
