### ISSUE TITLE
startController: add 'return to start location' feature

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2541]
Most of the courses that we build which include an 'intro page' (or pages) have some kind of 'back to intro' button contained in them.

It would be handy if the `startController` module offered some way of handling much of the logic for you, something like:
```js
Adapt.startController.returnToStartLocation(alwaysForce:Boolean, dontSkipCompleted:Boolean);
```

**Comment by moloko** [comment]
Just thinking: perhaps the arguments even necessary? I'm struggling to think of an example of when you might want `alwaysForce` and `dontSkipComplete` to be false? So maybe it should just be:
```js
Adapt.startController.returnToStartLocation();
```

Thoughts welcome!

**Comment by oliverfoster** [comment]
Agree
