### ISSUE TITLE
iFrame and Screen Reader scrolling support causing issues on iOS device rotation

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#2545]
### Subject of the issue/enhancement/features
I made a course with "iFrame and Screen Reader scrolling support" enabled. I then opened this course inside an LMS iFrame on an iPad running iOS 12.

All of the scrolling functionality works as I would expect but I encounter problems when I rotate the device.

### Your environment
* FW 4.3.0
* Safari
* iPad (5th Generation) iOS 12.2

### Steps to reproduce
Create a course and view on an iOS device inside an iframe. My course contained three blocks and used the vanilla theme.

### Expected behaviour
I should be able to rotate the device and the course should resize to fit the screen.

### Actual behaviour
When the course is first opened (in portrait) it is sized correctly. If I rotate to landscape and back to portrait then the course is slightly zoomed in. I can't pinch to zoom out. When I rotate to landscape the course is still slightly zoomed in but I can pinch to zoom out.

This means that after rotation, I can't view the full course in portrait mode.

If I disable the "iFrame and Screen Reader scrolling support" setting, then the rotation issue is fixed.

**Comment by oliverfoster** [comment]
Could you give a screenshot of the DOM structure of the parent document > adapt #wrapper please?

**Comment by canstudios-nicolaw** [comment]
This issue was found on courses that were running in Cornerstone LMS (which I've since learned doesn't use iFrames!) - apologies I should have been more explicit about that originally.

I am unable to provide screenshots as I no longer have access to Cornerstone. The issue was consistent across all courses which were opened in the browser on iOS 12. The issue was not present on the cornerstone mobile app.

**Comment by moloko** [comment]
there's a good chance this might be related to #2774

**Comment by oliverfoster** [comment]
closed as assuming lms issue and cannot replicate
