### ISSUE TITLE
QuestionModel needs an _items default

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt_framework#2546]
### Subject of the issue/enhancement/features
Error thrown when a question component that expects items does not have any set

### Steps to reproduce
Create a course with a Matching Question Component that does not have any items

### Expected behaviour
The empty component should render and the course creator should recognise their mistake

### Actual behaviour
Depending on extensions configuration, the course can fall over on page load

**Comment by moloko** [comment]
fixed in v4 by https://github.com/adaptlearning/adapt_framework/commit/b9c5816fef685231fd62aed76bd405896e79d79f and v3 by https://github.com/adaptlearning/adapt_framework/commit/87820aeb06b5babc2846a7cc9ba02fa85889dc86
