### ISSUE TITLE
adapt-contrib-trickle: Trickle disabled on Narrative components containing only 1 item

### ISSUE THREAD

**Issue by canstudios-kent** [adaptlearning/adapt_framework#2560]
### Subject of the issue/enhancement/features
Trickle does not work for Narrative components containing only 1 item.

### Your environment
* Authoring version 4.3.0
* contrib-adapt-trickle version 3.0.0
* contrib-adapt-narrative version 5.0.1

### Steps to reproduce
1. Create a new course. Add Trickle extension.
1. In a page, add a Narrative component. Navigate into the Narrative's property page.
1. Ensure "Set complete on" is set to "allitems".
1. Add only 1 Narrative item. Click Save.
1. Add a few more Narrative components that contain more than 1 Narrative item.
1. Ensure Trickle is enabled on the blocks.
1. Click Preview. Navigate to the page with the Narrative component. Notice that when you reach the Narrative with only 1 Narrative item, the next component is already unlocked.

### Expected behaviour
Trickle should prevent user accessing the next component until the user has completed the current component.

### Actual behaviour
The next component is unlocked as though the Trickle button was already clicked.

**Comment by moloko** [comment]
I wonder if this is similar to #2405 in that completion is triggering so quickly that trickle isn't picking up on it

**Comment by oliverfoster** [comment]
fixed with above pr
