### ISSUE TITLE
typo in boxMenu README

### ISSUE THREAD

**Issue by gorhgorh** [adaptlearning/adapt_framework#2568]
### Subject of the issue
in the readme of the box menu contrib plugin there is a typo for the [cli install line](https://github.com/adaptlearning/adapt-contrib-boxmenu/blob/v3.0.0/README.md#L17)

the plugin name is lower cased where it should be camel cased
so instead of ```adapt install adapt-contrib-boxmenu``` it should be ```adapt install adapt-contrib-boxMenu``` (at least i could install it that way)

the install via adapt.json 
### Your environment
* version (AT/Framework) NA
* which browser and its version NA 
* device(s) + operating system(s) NA

### Steps to reproduce
```adapt install adapt-contrib-boxmenu```

### Expected behaviour
it should install adapt box menu plugin

### Actual behaviour
it does not find it

**Comment by gorhgorh** [comment]
PS there is also the line 29 to edit as i guess uninstall need the right plugin name ?

**Comment by moloko** [comment]
I think the mistake is actually in bower.json [here](https://github.com/adaptlearning/adapt-contrib-boxmenu/blob/fb71aff69edc872973c36c8b4861146cab40e43d/bower.json#L2) - based on the fact that absolutely everywhere else it's referenced it's lowercase.

I guess it all depends how feasible it will be to change the reference in the bower repository... if we can't we'll have to change all the other references to boxMenu to make it match what's in bower.

**Comment by moloko** [comment]
have agreed on call this morning to use boxMenu rather than boxmenu. 

GH repo will need renaming, homepage link in bower.json will need updating and README will need amending

**Comment by moloko** [comment]
right, should be fixed now! but if you have a moment to have a look and double-check I haven't missed anything that would be great.

**Comment by gorhgorh** [comment]
I could install using boxMenu with the readme info and naming seems consistant
