### ISSUE TITLE
IE doesn't support method syntax

### ISSUE THREAD

**Issue by chetan-hajare** [adaptlearning/adapt_framework#2570]
### Subject of the issue/enhancement/features
The below object definition is not supported in IE [Here](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/a11y.js#L743)
```js
{
    url: "http://example.com/example.txt",
    test(data) // <==== here
    {
        // ...
    }
}
```

### Your environment
Framework: 4.4.0
Browser: IE11

### Steps to reproduce
Build and run the latest framework

### Expected behaviour
The course should run properly on IE11

### Actual behaviour
Throws console error on IE11

**Comment by moloko** [comment]
is that line reference correct? it currently points to the function definition for `setPopupCloseTo`

**Comment by moloko** [comment]
ah OK I see what you mean - accidental use of ES6 function definition!

**Comment by moloko** [comment]
@chetan-hajare is this something you're fixing? if not I can pick this up quickly as it's a pretty serious problem! No idea how this didn't get picked up in testing...
