### ISSUE TITLE
adapt-contrib-assessment: assessmentWeighting logic

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2572]
Looks like `assessmentWeighting` works on a reverse logic:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/assessment.js#L365-L366

I would expect an assessment with more weight to add more significantly to the overall assessment score, rather than have less impact.

**Comment by danielghost** [comment]
Looking at the schema, it is supposed to work with the reverse type logic:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/properties.schema#L112

Should this be amended to work in the same way as `_questionWeight`, and as explained above?

**Comment by oliverfoster** [comment]
duplicate of #1974
