### ISSUE TITLE
adapt-contrib-trickle: [JAWS+Chrome] trickle skips reading headers after selection

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2576]
### Subject of the issue/enhancement/features
Upon selecting an unlocked trickle state, focus moves to the following component body text when selecting the down arrow. This skips all article, block & component headers. I can, however, have those headers read out by arrowing back upwards through the page.

### Your environment
* Framework v4.4.1; Trickle v3.0.1
* Chrome v78.0.3904.97
* JAWS 2019 W10

**Comment by moloko** [comment]
sure it’s not just your trickle config settings? if you want the learner to be sent to the next article then “@article +1” might be the right setting for _scrollTo

**Comment by chris-steele** [comment]
Looking into this (when I get chance!), but have noticed in clean clone of v4.4.1 framework this problem occurs: focus lands on the component description (which isn't actually read out anyway) so you miss the component title.

**Comment by moloko** [comment]
> Update: it's a JAWS with Chrome issue it would seem - works as expected with IE11.

Beat me to it - was just about to say working fine in Jaws 2019/IE11 for me. 

Can replicate issue in Jaws 2019/Chrome.
