### ISSUE TITLE
Hot graphic popup not re-centering vertically when 'paging' between items

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2580]
### Subject of the issue/enhancement/features

When moving between items using the back/next buttons the notify popup will not re-center itself vertically to accommodate items with differing amounts of content.

### Your environment

- version v4.4.x, release/v5
- all browsers
- all platforms

**Comment by oliverfoster** [comment]
We probably need a jquery.resize enabled listener on the subview container [here-ish](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/notifyView.js#L194)
to trigger [resetNotifySize](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/notifyView.js#L112) which is then removed [here-ish](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/notifyView.js#L252)

```js
    
    // bind in initialize
    _.bindAll(this, 'resetNotifySize');

    // attach in opened when adding a subview
    this.subView.$el.on("resize", this.resetNotifySize);

    // then remove before removing subview
    this.subView.$el.off("resize", this.resetNotifySize);
```

**Comment by chris-steele** [comment]
That looks good and seems to work just fine. Have put it into a project and will report back.

**Comment by oliverfoster** [comment]
Does it solve the other ticket?

**Comment by chris-steele** [comment]
Sadly not :(

**Comment by oliverfoster** [comment]
Needs v4 pr
