### ISSUE TITLE
[Mac VoiceOver+Chrome] Opening notify popups moves screenreader focus

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2585]
Whenever a popup is opened, the focus for VoiceOver moves to the top of the page, specifically the first component on the page. This has been seen in both MCQ Feedback and Hotgrid Popups.

Framework: v4.4.1; Tutor v2.1.2
Chrome: v78.0.3904.97
Mac OS: 10.13.6
VoiceOver: v8

**Comment by oliverfoster** [comment]
closing as stale
