### ISSUE TITLE
adapt-contrib-spoor - add commit of score and session time after assessment complete

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#2590]
Currently after completing an assessment, the lesson status is set and then committed. The score may or may not be committed depending on the execution order of events. Therefore this opens up a vulnerability enabling a course to terminate with a lesson status of passed or failed but no score or session time. This can result in odd looking results on the LMS.

I would like to suggest adding a commit call into the setScore function.

Ideally I would also like the session time to be set when an assessment is complete too to prevent a zero session time in the event the session is not closed properly. If the user closes the session properly then it will set the session time again and ensure the correct session time is recorded.

**Comment by moloko** [comment]
@paul-mediakitchen I know we talked yesterday in the gitter chat about how this _could_ be the source of the tracking issues you had encountered, did you manage to confirm for sure that this was the source of the problem?

As I mentioned you could also try changing the value of `_timedCommitFrequency` so that `LMSCommit` calls take place more frequently than every 10 mins. That should have the added benefit of helping to prevent the course from 'timing out'.

> Ideally I would also like the session time to be set when an assessment is complete too to prevent a zero session time in the event the session times out.

Unfortunately doing this would not make any difference as value set in session time is only used by the LMS when LMSFinish/Terminate is successfully executed. There is, therefore, no point at all setting the session time more than once per session as only the last value set prior to the LMSFinish call is used. As you can see from the code [here](https://github.com/adaptlearning/adapt-contrib-spoor/blob/f3b9387705d0f78fc916feee8a2d28055e82cece/js/scorm/wrapper.js#L310-L316) the session time is already being set as part of the 'finish' routine.

**Comment by paul-mediakitchen** [comment]
@moloko - the issues we are getting with a user getting a passes or failed lesson status and a score of zero and a session time of zero most certainly appear to be caused by the course setting the lesson status at the end of an assessment and then not going on to call the LMS Finish for whatever reason.

I am not keen to call the timed commits more frequently as adding a commit of the score after the assessment is finished is all I need so it seems like a lot of redundancy calling commit say every minute.

The reasoning for setting the cmi.session_time at the end of an assessment was to prevent the possibility of a session timing out and having no session time at all.

**Comment by moloko** [comment]
> At least if the session time was set at the end of an assessment and the course times out, there would be a record on the LMS that the user has spent some time on the course.

That isn't how it works though. If the `LMSFinish` call does not take place, the 'session time' is not actually stored. At least I have never seen an example of it being stored - except when it gets added to `cmi.core.total_time`.

I really think that you have a higher-level issue at play here that needs addressing - that is that the course is 'timing out'. Increasing `_timedCommitFrequency` to something more appropriate - I would suggest something in the 2 - 5 minute range - may well help to 'keep-alive' the connection between the course and the LMS. I don't agree that it is redundant to run a commit call more frequently. If anything, I think my initial choice of the default value for this being set to 10 mins was probably waaay too high and have often considered changing the default to something more sensible.

**Comment by paul-mediakitchen** [comment]
Thanks @moloko for your reply.
The issue we are experiencing isn't necessarily caused by a time out and could occur if a user closed down their PC without closing the session properly or perhaps if the moved to another tab. I doubt on a tablet that an automatic commit would have any effect if the tab doesn't have focus.

Anyway this was only a suggested enhancement that I felt was a simple enhancement that could prevent others getting incomplete tracking info in the scenario where the course wasn't closed properly

I appreciate your view on this and happy for you to take no action.

**Comment by moloko** [comment]
if they moved to another tab that would trigger the `visibilitychange` event listener which triggers a commit (assuming you haven't set `_commitOnVisibilityChangeHidden` to `false`)

I do see what you're saying about all this, it's an unfortunate side effect of moving the 'has the user completed the course' logic into core that means there are now two events that spoor has to listen out for, which of course means there's no guarantee of the order in which they'll fire.

I'll keep this open for the benefit of others and have a think about possible ways of getting this to work in a way that means that both the score and status change take effect before the commit call.

**Comment by oliverfoster** [comment]
closed as stale
