### ISSUE TITLE
adapt-contrib-media: remove flashmediaelement.swf & silverlightmediaelement.xap

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2598]
I am proposing that we remove these files from the v5 version of this plugin.

Firstly, we no longer support any browser that lacks support for HTML5 video, so these files should no longer be required - their primary purpose was as a 'fallback' for browsers that didn't support HTML5 video.

Secondly, with Flash nearing EOL, some clients' networks/firewalls are having issues taking delivery of/uploading SCORM zips containing these files as they are flagged as containing 'unsafe' files. Some Learning Management Systems also by default now refuse to allow a zip containing .swf files to be uploaded. And typically any error shown in this situation is suitably cryptic, leading to a fair amount of time trying to figure out what exactly the problem is!

If anyone using the Framework to create courses finds they still need these files they can always add them back in manually - but there's no easy workaround for AAT users.

**Comment by tomgreenfield** [comment]
> If anyone using the Framework to create courses finds they still need these files they can always add them back in manually - but there's no easy workaround for AAT users.

Could also just add these lines somewhere in `setupPlayer()` so there'd be no headache for users if they ever needed the Flash plugin:
```js
_.extend(modelOptions, {
  pluginPath: 'https://cdnjs.cloudflare.com/ajax/libs/mediaelement/2.21.2/',
  flashName: 'flashmediaelement-cdn.swf',
  flashScriptAccess: 'always'
});
```

**Comment by moloko** [comment]
I'm also wondering if we really need to continue to include the Adobe Fireworks source files (the ones with extension `.fw.png` that in are in the `assets` folder) - does anyone ever actually use these to modify the look & feel of the controls?

**Comment by tomgreenfield** [comment]
I'd like to port this to Media 2.x because we have a client who requires the fix in the legacy framework.

**Comment by tomgreenfield** [comment]
I now need this ported to Media 4.x following a framework upgrade.
