### ISSUE TITLE
Hello I just started using adapt authoring tool a few days back. I have difficulty using the adapt new window launcher as i'm using localhost for now. Any details on how it works ? 

### ISSUE THREAD

**Issue by judgement96** [adaptlearning/adapt_framework#2603]
### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by moloko** [comment]
@judgement96 if you have questions please could you ask them in the [forums](https://community.adaptlearning.org/course/view.php?id=2) or the [chat rooms](https://gitter.im/adaptlearning)?
