### ISSUE TITLE
adapt-contrib-spoor sends status before score which is a problem for Cornerstone

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2604]
### Subject of the issue
A completed/passed status will be sent to the LMS before a score is sent in courses with an assessment. When this occurs it has been found to be a problem for Cornerstone reporting: the correct score is captured in the user's transcript, but not included in general reporting (the score remains 0 in the reports). When the submission of status and score are reversed this problem is resolved.

N.B. in older versions of Adapt score was sent before status, but for quite some time now (certainly the Adapt v3 and v4 era) the score is sent after.

### Your environment
- more recent versions of the framework (v3, v4, v5, possibly earlier)
- all browsers
- all devices + operating systems

**Comment by chris-steele** [comment]
https://github.com/adaptlearning/adapt_framework/issues/2590 looks to be related

**Comment by moloko** [comment]
I suppose there's no possibility of logging this as a bug with Cornerstone since it's quite clearly something wrong at their end?

#2590 is related but the LMS in question isn't Cornerstone

If (as is likely) Cornerstone refuse to address this then I guess one option might be to put a `_.defer` or a `_.delay` in [here](https://github.com/adaptlearning/adapt_framework/blob/9d35df26196fdc03fe875236625ea9b10679bdb9/src/core/js/tracking.js#L63)

**Comment by moloko** [comment]
I think a fairly simple solution to this and #2590 could be to move responsibility for setting the score away from spoor and into tracking.js... I don't really see why spoor needs to handle setting it. lesson status is a slightly different matter since what that gets set **to** is quite specific to SCORM, so it's more appropriate that it takes place in the spoor extension.

**Comment by moloko** [comment]
Something like this, maybe?

```js
onAssessmentComplete: function(assessmentState) {
  this._assessmentState = assessmentState;
  this.submitScore();
  this.checkCompletion();
},

submitScore: function() {
  if (!this._config._shouldSubmitScore) return;

  if (this._assessmentState.isPercentageBased) {
    Adapt.offlineStorage.set('score', this._assessmentState.scoreAsPercent, 0, 100);
    return;
  }

  Adapt.offlineStorage.set('score', this._assessmentState.score, 0, this._assessmentState.maxScore);
}
```

**Comment by oliverfoster** [comment]
@chris-steele is this still an issue?

**Comment by chris-steele** [comment]
I would say most likely so; I haven't been aware of Cornerstone fixing this - and even if they have some clients may use older unpatched versions.

**Comment by oliverfoster** [comment]
Any ideas of how to fix?

**Comment by moloko** [comment]
> Any ideas of how to fix?

https://github.com/adaptlearning/adapt_framework/issues/2604#issuecomment-632065605 ?

**Comment by oliverfoster** [comment]
[this](https://github.com/adaptlearning/adapt-contrib-spoor/blob/d7eebe2ba31c7cc43dc27ba4fde40e7bdcdb9b31/js/adapt-stateful-session.js#L219-L227) in [here](https://github.com/adaptlearning/adapt_framework/blob/cb967de4d06bb31759b5849e295d73687e0ee29d/src/core/js/tracking.js#L59)?

**Comment by moloko** [comment]
As I recall I was thinking more [here](https://github.com/adaptlearning/adapt_framework/blob/cb967de4d06bb31759b5849e295d73687e0ee29d/src/core/js/tracking.js#L38) but yeah, essentially... 

might need to move the check for `_shouldSubmitScore` to somewhere like [here](https://github.com/adaptlearning/adapt-contrib-spoor/blob/d7eebe2ba31c7cc43dc27ba4fde40e7bdcdb9b31/js/adapt-offlineStorage-scorm.js#L135-L136)

**Comment by oliverfoster** [comment]
superb, ta

**Comment by danielghost** [comment]
Can confirm this approach works. Is needed for a client with custom error messages which include the score and lesson_status if an error occurs when saving this data.

**Comment by chris-steele** [comment]
PRs: https://github.com/adaptlearning/adapt-contrib-spoor/pull/222 and https://github.com/adaptlearning/adapt-contrib-core/pull/30 (merge together of course)
