### ISSUE TITLE
Page Level Progress : Anomalous behavoir

### ISSUE THREAD

**Issue by canstudios-scottd** [adaptlearning/adapt_framework#2608]
### Subject of the issue/enhancement/features
The Page level progress extension is affecting other components operating properly. Two main bugs noticed by users is the accordion items are not collapsing, and feedback is only showing once the submit button on various question components is clicked twice.

Currently, it is unclear how to fully replicate these issues or what other components may be affected. The following console log adapt.min.js:6 Uncaught TypeError: Cannot read property '_excludeAssessments' of undefined is logged when:
1. A component is set to complete on view, and is viewed
2. The last item of a component is viewed/completed

### Work around
Either re-adding the extension to a course or toggling the 'Exclude assessments' in the Page level progress settings.

### Your environment
* version 4.3.0 (AT/Framework)
* Page Level Progress version 4.1.1

**Comment by akshay-bhavsar** [comment]
@canstudios-scottd 
We have tried replicating this issue but we did not observe this case.

It will be helpful if you provide video/gif of reproducing issue.

**Comment by tomgreenfield** [comment]
From the console log it looks like it's just missing defensive coding [here](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/107794445dd62baddaf419e25186a8207c9717a0/js/completionCalculations.js#L48) for when config hasn't been added to the content object for whatever reason. See [line 54](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/107794445dd62baddaf419e25186a8207c9717a0/js/completionCalculations.js#L54) for an example.

**Comment by moloko** [comment]
is this still something that needs addressing?
