### ISSUE TITLE
adapt-contrib-vanilla - remove vanilla schema color variable defaults

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2609]
These are needlessly duplicated when exported from the AAT.

**Comment by guywillis** [comment]
Removing the schema defaults removes the duplication of variables in the Adapt Authoring Tool course export. 

An unfortunate consequence of removing these defaults is that the Theme Picker interface in the AAT no longer pre-populates itself with the standard vanilla theme colours. See screenshots below.

Before:
<img width="281" alt="screen-1" src="https://user-images.githubusercontent.com/11569678/75798911-2f079300-5d6f-11ea-89c1-b1e8b4cd8e4d.png">

After:
<img width="248" alt="screen-2" src="https://user-images.githubusercontent.com/11569678/75798920-33cc4700-5d6f-11ea-87dd-baff9ed9447d.png">

**Comment by kirsty-hames** [comment]
I think it's fine not to have pre-populated colours. We have the 'help' text per property to inform how/where the colour is applied. 
We could add/review the current instruction text if issues are raised regarding how intuitive it is to use?
