### ISSUE TITLE
adapt-contrib-vanilla v5: enable/disable img-zoom

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2615]
Vanilla v5 contains a default hover effect called [img-zoom](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/9b333a06b2263db7f22d5623280a8dfaad699727/less/_defaults/_animations.less#L10-L29). Thanks go to the developers for adding such extras. It is a fun effect for menus and for images that are interactive (e.g., buttons). But it can be distracting in some scenarios, such as Graphic components that use inconsequential images. I think we need the ability to toggle this off, especially with themes used in the authoring tool. 

In the framework, removing the img-zoom() mixin/function from _animations.less causes a compile error. This seems to imply that I would need to remove the call from each component Less file that uses it; or to modify img-zoom so that the effect is rendered meaningless. Unlike standard CSS styles, there's no way to 'unset' or 'none' img-zoom. Currently, this is not the most friendly way to disable a standard feature. Personally, I think that the effect should be disabled by default.

### environment
AAT v0.10.2; FW v5.1.0

### Steps to reproduce
Hover over an image in any core component. The image zooms in (gets bigger). Exit hover and the image zooms out to its original size.

### Expected behaviour
I'd expect that this effect could be toggled on and off from within the AAT. 

Ideas:
- Add a toggle to the theme picker to disable img-zoom course-wide
- Have img-zoom default to disabled. To enable, allow author to add an "img-zoom" class to the component's Classes.

**Comment by guywillis** [comment]
PRs for [Vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/241) and [Hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/185) which disable img-zoom feature by default. img-zoom can be enabled on a component by component basis by adding the `has-img-zoom` class to the component (or contentObject in `boxMenuItems` case)

**Comment by guywillis** [comment]
PRs merged, closing issue.
