### ISSUE TITLE
adapt-contrib-narrative: display issue on Chrome/IE11 when there are three items

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2620]
### Subject of the issue/enhancement/features
If you have three narrative items, a thin line of the next narrative image is shown alongside the current one at certain screen sizes.

I'm guessing this is because the width of `.narrative__slider-image-container` is getting set to 33.333333333333336%

### Your environment
* FW (replicated in v4.2.0 and v5.1.0), Narrative (replicated in v5.0.1 and v6.0)
* IE11 & Chrome
* Windows 10

### Steps to reproduce
Create a narrative containing three images, ideally photographic. Setting the block background colour to a dark colour can make it more obvious. You'll have to experiment with different viewport widths. Unsurprisingly it's easier to replicate in IE11 ;-)

### Expected behaviour
None of the next image should be shown

### Actual behaviour
This is what you see in IE11:
![narrative-ie11](https://user-images.githubusercontent.com/1249597/72070367-572fc400-32e1-11ea-8bf0-a9c34e45cb28.png)

And this is the same thing in Chrome:
![narrative-chrome](https://user-images.githubusercontent.com/1249597/72070378-5dbe3b80-32e1-11ea-8678-2655432d369d.png)

**Comment by oliverfoster** [comment]
closing comment with potential solution https://github.com/adaptlearning/adapt-contrib-narrative/pull/209#issuecomment-826797537
