### ISSUE TITLE
adapt-contrib-trickle: "_isAvailable": false on an article causes error

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#2623]
If an article is set to "_isAvailable": false, trickle breaks and you cannot trickle through a page.

### Environment
Framework v4.3.0
Latest Chrome
Windows 10

### Steps to reproduce
Set up a page with 3 articles, each with trickle configured on the article with "_scrollTo": "@article +1"

Set the second article to "_isAvailable": false

Run course and view the page.

### Expected behaviour
Trickle should move through the 2 'available' articles.

### Actual behaviour
Clicking Trickle on the 1st article does nothing and the console error is shown

![image](https://user-images.githubusercontent.com/7251995/72151341-df749e80-339f-11ea-9f02-0787178b8c45.png)

**Comment by jamesrea83** [comment]
The quick fix for this one is to make sure the child blocks are also set to `_isAvailable: false`.

Would it be worth having a feature that, upon finding an `_isAvailable: false` flag, automatically sets all applicable child elements as well? Is there a scenario where you would want an available block contained in an unavailable article?

**Comment by moloko** [comment]
> Is there a scenario where you would want an available block contained in an unavailable article?

@jamesrea83 we have found previously that cascading changes from parent to children can be problematic in unexpected ways. I think @oliverfoster has an alternative technique for addressing this particular issue from within trickle.

**Comment by oliverfoster** [comment]
Add something like this to `adaptModel.js`:
```js
  /**
   * Derives isAvailable from parent stack
   */
  getIsAvailable: function() {
    var isAvailable = this.get('_isAvailable');
    if (!isAvailable) {
      return false;
    }
    var parent = this;
    while (parent = parent.getParent()) {
      isAvailable = parent.get('_isAvailable');
      if (!isAvailable) {
        return false;
      }
    }
    return true;
  }
```
Then use in trickle.

**Comment by akshay-bhavsar** [comment]
Please neglect above comment and refer PR: https://github.com/adaptlearning/adapt_framework/pull/2665 for this issue

**Comment by moloko** [comment]
this will need fixing in Adapt v5.x/Trickle v4.x as well I think?

**Comment by moloko** [comment]
> 
> 
> Add something like this to `adaptModel.js`:
> 
> ```js
>   /**
>    * Derives isAvailable from parent stack
>    */
>   getIsAvailable: function() {
>     var isAvailable = this.get('_isAvailable');
>     if (!isAvailable) {
>       return false;
>     }
>     var parent = this;
>     while (parent = parent.getParent()) {
>       isAvailable = parent.get('_isAvailable');
>       if (!isAvailable) {
>         return false;
>       }
>     }
>     return true;
>   }
> ```
> 
> Then use in trickle.

I think this can be done in one line (at least when using ES6):
```js
this.getAncestorModels(true).every(model => model.get('_isAvailable'));
```
Which makes me wonder if it's worth adding to the core code?

**Comment by oliverfoster** [comment]
isAvailableInPage is already in isn't it?

**Comment by moloko** [comment]
> isAvailableInPage is already in isn't it?

I think it's only here? https://github.com/adaptlearning/adapt_framework/tree/v4-patches

**Comment by moloko** [comment]
I don't mind particularly, it just seemed to me that if it can be done with one line of code then there's no need to do two separate FW releases as well as two trickle releases

**Comment by oliverfoster** [comment]
```js
this.getAncestorModels(true).filter(model => !['page', 'menu'].includes(model.get('_type'))).every(model => model.get('_isAvailable'));
```

**Comment by moloko** [comment]
> or in v5:
> 
> ```js
> this.getAncestorModels(true).every(model => !model.isTypeGroup('contentobject') && model.get('_isAvailable'));
> ```
I think this will return `false` for anything that's a child of a content object?

> There's no point checking the availability beyond the contentObject as availability is a contentObject relative property.

That's true - but it's generally only going to mean checking one more thing (the course) so doesn't seem like too much of an overhead

**Comment by oliverfoster** [comment]
> That's true - but it's generally only going to mean checking one more thing (the course) so doesn't seem like too much of an overhead

It's not because it's expensive that you should check them, it's because any of the ancestor contentObjects could be `_isAvailable: false` to hide them from a menu for use only as a container of notify components or a multitude of other reasons.

> I think these will both return false for anything that's a child of a content object?

That's true, they should be a filter / similar.

```js
this.getAncestorModels(true).filter(model => !['page', 'menu'].includes(model.get('_type')).every(model => model.get('_isAvailable'));
```

or in v5:

```js
this.getAncestorModels(true).filter(model => !model.isTypeGroup('contentobject')).every(model => model.get('_isAvailable'));
```

**Comment by moloko** [comment]
> It's not because it's expensive that you should not check them, it's because any of the ancestor contentObjects could be `_isAvailable: false` to hide them from a menu or for use only as a container of notify components or a multitude of other reasons.

Ahhh OK I think we're coming at this from two different directions, hence slight confusion. My use-case is to ensure that adapt-search doesn't show results that are included in any contentObject (or article or block) so it's vital that it **does** check to see if the parent contentObject `_isAvailable` or not.

So if you have a different requirement for trickle I think it's an even stronger argument for not including something like `isAvailableInPage` in Adapt itself and instead having trickle/search do their own check. I'll close the v5 PR.

**Comment by oliverfoster** [comment]
Or the alternative, that both are useful in the core?

**Comment by moloko** [comment]
> Or the alternative, that both are useful in the core?

From my perspective, it's such a small bit of code that unless it's going to get used by lots of different plugins, it's probably not worth including in core
