### ISSUE TITLE
adapt-contrib-xapi - add additional context information to statements that makes it clear the statement is from adapt content

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#2637]
### Subject of the issue/enhancement/features
We have been launching adapt content in a platform that also includes statements based on what the user is doing on the platform however we are having an issue with separating the data generated by the platform and the data coming from the content.

In order to improve the statements and make it easier to determine where the statement is coming from we are suggesting that we add a platform key within the context of an xAPI statement. For example:

"context": {
      "contextActivities": {
        "grouping": [
          {
            "objectType": "Activity",
            "id": "https://acitvityid.com",
            "definition": {
              "type": "http://lxp.com/define/type/organisation",
              "name": {
                "en-GB": "LXP"
              }
            }
          }
        ]
      },
      **"platform": "Adapt"**
    },"

### Your environment
* version  - fw - 3.5.4
* all browsers
* all devices and operating systems

**Comment by oliverfoster** [comment]
Is this still relevant? @kevindoherty30

**Comment by oliverfoster** [comment]
closing as stale
