### ISSUE TITLE
the setting _requireCompletionOf is not exposed to the authoring tool

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2639]
original implementation of this is here: https://github.com/adaptlearning/adapt_framework/pull/549 (useful for the original discussion around why this was added)

actual implementation was in https://github.com/adaptlearning/adapt_framework/pull/951

Ideally support should be backported to v4 - and possibly v3?

**Comment by moloko** [comment]
If anyone wants to pick this up it would be great to sort out #1912 at the same time...

**Comment by moloko** [comment]
#1657 also!

**Comment by olivermartinfoster** [comment]
is this done now?

**Comment by moloko** [comment]
Yes I think so?
