### ISSUE TITLE
tslib not found

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2642]
### Subject of the issue
Current framework isn't compiling LESS properly due to upstream bug with less 3.11.0

https://github.com/less/less.js/issues/3469

![image](https://user-images.githubusercontent.com/7974663/74155797-0e836780-4c0d-11ea-8da3-bbe9f654020c.png)

Confirmed working with 3.10.3

**Comment by brian-learningpool** [comment]
In the meantime should the `less` version in `package.json` be set to 3.10.3 exactly?  We should probably consider using package.lock going forward

**Comment by oliverfoster** [comment]
Seems like a sensible suggestion.

References: 
* https://docs.npmjs.com/configuring-npm/package-locks.html
* https://docs.npmjs.com/configuring/npm/package-lock-json

**Comment by oliverfoster** [comment]
The above PR is only going to work with master atm and the package-lock will need to be remade after every version number change just before release.

**Comment by moloko** [comment]
@oliverfoster that second link should be https://docs.npmjs.com/configuring-npm/package-lock-json.html I think

**Comment by moloko** [comment]
> the package-lock will need to be remade after every version number change just before release

How's that done?

**Comment by oliverfoster** [comment]
`$ npm install --package-lock-only` will ensure the lock file reflects the `package.json`
