### ISSUE TITLE
adapt-contrib-vanilla: hyperlink styling missing for component item display text

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2646]
Hyperlink styling is missing for Accordion, Narrative and Media transcript in Vanilla Adapt.

Suggest we use the .link-text mixin as per other hyperlink styles in Vanilla.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/bf30f8bcd2d17590632986bb62c73ba73355e54a
