### ISSUE TITLE
adapt-contrib-bookmarking: location not restored if using page level locations

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2659]
### Subject of the issue/enhancement/features
Due to the changes made to the `className` in 62d75442ef7000bc800999b93b533bb83c6068ed, if bookmarking is enabled to `"_level": "page"`, the lesson location is not restored. The id to restore is found on the menu item, so the extension already thinks it is on screen and returns out of the `restoreLocation` method.

**Comment by moloko** [comment]
is it [this line](https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/af6fdbe4e15c15b3dee2a9edc2f2e4c835512d0e/js/adapt-contrib-bookmarking.js#L53) you're referring to?

**Comment by danielghost** [comment]
Yep. The menu item is found via that selector so thinks it can just ignore the rest of the method. Is possible to wrap that logic in a condition like this:

```javascript
var modelToRestore = Adapt.findById(this.restoredLocationID);

if (this.getBookmarkLevel(modelToRestore) !== 'page') {
  var locationOnscreen = $('.' + this.restoredLocationID).onscreen();
  var isLocationOnscreen = locationOnscreen && (locationOnscreen.percentInview > 0);
  var isLocationFullyInview = locationOnscreen && (locationOnscreen.percentInview === 100);
  if (isLocationOnscreen && isLocationFullyInview) {
    return;
  }
}
```
Or add a prefix to the id being added to the MenuView className, as before.

Not sure what is preferred.

**Comment by moloko** [comment]
Simplest solution might actually be to use a `:not()` selector to change this:
```js
var locationOnscreen = $('.' + this.restoredLocationID).onscreen();
```
to this:
```js
var locationOnscreen = $('.' + this.restoredLocationID + ':not(.menu-item)').onscreen();
```

**Comment by moloko** [comment]
actually thinking about it maybe checking to see if the `restoredLocationID` is a page is better seeing as the rest of the checks are pretty much pointless in that instance

**Comment by olivermartinfoster** [comment]
I think we can probably do a `pageView instanceof MenuView` return early here https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/js/adapt-contrib-bookmarking.js#L165

**Comment by moloko** [comment]
Side note: if, as discussed in #2739, we're going to stop using IDs as css classes, the bookmarking extension will need amending to cope with that change so we could deal with this issue then
