### ISSUE TITLE
Question: Grunt task create-json-config

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2660]
### Question
Can I delete the grunt task [create-json-config](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/create-json-config.js) ?

### Details
The grunt task [create-json-config](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/create-json-config.js) collects the following files and tries to merge them into the `build/course/config.json`:
```js
 'src/components/*/components.json',
 'src/extensions/*/extensions.json',
 'src/menu/*/menu.json',
 'src/theme/*/theme.json',
 'src/*/*/config.json'
```

This is not a feature the [Authoring Tool uses](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/server-build.js) and only works with hand-built courses.

The last reference to its use I can find is [vanilla@4.1.0/theme.json](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/v4.1.0/theme.json).
It has since been removed from v5 vanilla. The vanilla `config.json:screenSize` variable is now configured in [`src/core/schema/config.model.schema`](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/schema/config.model.schema#L179).

**Comment by brian-learningpool** [comment]
I have no objections to it going.

**Comment by moloko** [comment]
None from me either
