### ISSUE TITLE
navigationView should be catching DOM events and calling the relevant APIs

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2669]
a mentioned [here](https://github.com/adaptlearning/adapt_framework/pull/2624#pullrequestreview-359934723), these sorts of events from the DOM should be handled by navigationView which then calls the relevant API

**Comment by moloko** [comment]
going to park this for the moment as currently there's no public API for some of the key functions that navigationView would need to call (`navigateToHomeRoute`, `navigateToPreviousRoute` etc)

**Comment by oliverfoster** [comment]
This should be ready to go now @moloko
