### ISSUE TITLE
adapt-contrib-assessmentResults - _routeToAssessment drops learner on the top of the page, not the assessment article

### ISSUE THREAD

**Issue by kineopete** [adaptlearning/adapt_framework#2673]
### Subject of the issue/enhancement/features
The _routeToAssessment setting should send the user back to the assessment article - in both of my tests it has returned the user to the top of the page.

### Your environment
* Framework versions 5.1.0 (with Assessment Results 4.0.0) and Framework 4.2.0 (with Assessment Results 3.3.1)
* Firefox + Chrome 
* Win10

### Steps to reproduce
Create a page with 3 articles - an assessment in article 2 and assessment results in article 3. Set 'routeToAssessment' to 'true'

### Expected behaviour
When the 'reset' button is clicked, the user should be returned to the article containing the assessment (please see https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/8699da8c414d25ea4cfb5bdfd634bfd7c37c19d5/js/assessmentResultsView.js#L40-L42)

### Actual behaviour
User is routed to the top of the page

**Comment by akshay-bhavsar** [comment]
I have checked with this issue, causes due to delay at line:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/a5609c230a77b21a3efb695f41edd9ea4a348444/js/adapt-assessmentArticleModel.js#L504-L506


To resolve this, we need to add delay at line: 
https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/8699da8c414d25ea4cfb5bdfd634bfd7c37c19d5/js/assessmentResultsView.js#L41

**Comment by akshay-bhavsar** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/57

**Comment by tomgreenfield** [comment]
@akshay-bhavsar, please in the future can you link to the issue from the PR, not the other way around. This will allow us to see from the issue whether the PR has been merged.

**Comment by moloko** [comment]
@akshay-bhavsar easiest is just to do this:
![image](https://user-images.githubusercontent.com/1249597/76509662-4bc75900-6448-11ea-9118-520adc8f0545.png)

https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by akshay-bhavsar** [comment]
Sure,
I'll follow the same.

**Comment by moloko** [comment]
fixed in Assessment v4.1.0 & Assessment Results v4.1.0
