### ISSUE TITLE
Framework - Refresh icon font set

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2688]
### Subject of the issue
The current icon font set doesn't look like it has been updated in a while. It would be nice to have a little refresh of the current icon suite so they look a little fresher and more modern. 

### Your environment
* v5 Framework

**Comment by guywillis** [comment]
Old:
<img width="1453" alt="screen-01" src="https://user-images.githubusercontent.com/11569678/76624326-fb75f700-652c-11ea-8a9c-7eddfadf24e7.png">

New:
<img width="1441" alt="screen-02" src="https://user-images.githubusercontent.com/11569678/76624329-fd3fba80-652c-11ea-89f3-ed5f9fb7032f.png">

Additional:
![screen-03](https://user-images.githubusercontent.com/11569678/76632765-9e357200-653b-11ea-80d9-a30e967af272.png)

* accessibility-2
* alert
* arrow-down-2
* arrow-down-3
* arrow-left-2
* arrow-left-3
* arrow-right-2
* arrow-right-3
* arrow-up-2
* arrow-up-3
* attachment
* block
* camera-off
* camera-on
* cloud
* compass
* copy-file
* copyright
* crop
* devices
* down-up
* ellipsis-vertical
* exclamation
* expand_1
* extension
* favourite
* google-translate
* hand
* lightning
* list-2
* microphone-off
* move
* mute
* ordered-list
* question-circle
* quote-close
* quote-open
* refresh
* send
* sound-down
* sync
* tablet
* thumb-down
* thumb-up
* timer-empty
* timer-full
* video-captions-off-2
* video-captions-off
* video-captions
* video-exit-fullscreen
* video-fast-forward
* video-fullscreen
* video-loop
* video-pause-circle
* video-pause
* video-play-circle
* video-play
* video-replay
* video-rewind
* video-skip-back
* video-skip-forward
* video-stop

**Comment by guywillis** [comment]
Further additions to the font set based on PR comments:
<img width="1441" alt="screen-04" src="https://user-images.githubusercontent.com/11569678/76978508-b2f47a00-692e-11ea-9500-ef5c63419e6c.png">

* quote-close-2
* quote-open-2
* emotion-happy
* emotion-not-ok
* emotion-ok
* emotion-sad
* emotion-very-happy
* emotion-very-unhappy
* blogger-2
* blogger
* deviantart-2
* deviantart
* doc-excel
* doc-pdf
* doc-word
* facebook-2
* facebook
* flickr-2
* flickr
* github
* instagram-2
* instagram
* lanyrd
* linkedin-2
* linkedin
* paypal
* picasa-2
* picasa
* pintrest-2
* pintrest
* qq-2
* qq
* reddit-2
* reddit
* rss-2
* rss
* sina-weibo-2
* sina-weibo
* soundcloud-2
* soundcloud
* steam-2
* steam
* trello-2
* trello
* tumbler-2
* tumbler
* twitch
* twitter-2
* twitter
* vimeo-2
* vimeo
* wechat-2
* wechat
* weibo-2
* weibo
* xing-2
* xing
* youku-2
* youku
* youtube-2
* youtube

**Comment by chucklorenz** [comment]
Excellent! thank you

**Comment by guywillis** [comment]
Removed Lanyrd and Picasa
