### ISSUE TITLE
adapt-contrib-vanilla - Update media player control to use rems + customisable icons

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2689]
### Subject of the issue
The MediaElement.js control bar is unresponsive to user defined font sizes and is difficult to customise the icons. 

Proposed solution: Override the MediaElement.js control bar so that it uses rems to allow for browser zooming and user defined font size variants as well as updating the icon definitions to match v5's implementation so they can be easily customised.

### Your environment
* v5 Framework

**Comment by oliverfoster** [comment]
All agreed not to upgrade mejs.

**Comment by guywillis** [comment]
Screenshot of updated player bar:
<img width="913" alt="screen" src="https://user-images.githubusercontent.com/11569678/77053224-ec2bf900-69c5-11ea-9fad-46b7f2bc54cc.png">
