### ISSUE TITLE
Comments.../*comments*/...//comments

### ISSUE THREAD

**Issue by darylhedley** [adaptlearning/adapt_framework#269]
Once thing we're missing compared to other open source products are comments in our code. It's time to put some back in

**Comment by taylortom** [comment]
I think we need to revisit this, as there are still lots of files with no comments at all, and others with superfluous comments e.g.

[AdaptModel](https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/models/adaptModel.js#L43-L44):
```javascript
// Wait until data is ready before setting up model
Adapt.once('app:dataReady', this.setupModel, this);
```

[QuestionView](https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/views/questionView.js#L58-L65):
```javascript
// Used by the question to disable the question during submit and complete stages
disableQuestion: function() {},

// Used by the question to enable the question during interactions
enableQuestion: function() {},

// Used to check if the question should reset on revisit
checkIfResetOnRevisit: function() {
```

**Comment by taylortom** [comment]
Also see: https://github.com/taylortom/adapt_framework/blob/feature/%23430/src/core/js/views/questionView.js#L32-L37

**Comment by moloko** [comment]
I agree, these sorts of comments are no help at all.

Code should be written clearly enough that you should rarely need comments. [This](https://github.com/taylortom/adapt_framework/blob/feature/%23430/src/core/js/views/questionView.js#L147) is a good example of where a comment is helpful. It doesn't need the repetition on line 38 (when that method is actually called) though.

**Comment by taylortom** [comment]
This should really be done for 2.0.0, as we want to leave the core as is for future releases.

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-458
