### ISSUE TITLE
adapt-contrib-vanilla - Expand on custom classes in theme-extras

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2690]
### Subject of the issue
Introduce additional custom classes that can be used to further customise Adapt courses in both the Framework and Authoring Tool. 

Suggestions:
* Hide page header
* Align block content to the bottom of the container
* Reduce block padding top / bottom
* Increase block padding top / bottom

### Your environment
* v5 Framework

**Comment by joe-replin** [comment]
Classes or JSON configuration to enable labeling on navigational buttons.

**Comment by guywillis** [comment]
@joe-replin Agreed, it would be a useful feature as it does get requested by clients.

Navigation text labels have been mentioned in these issues:
* https://github.com/adaptlearning/adapt_framework/issues/1418
* https://github.com/adaptlearning/adapt_framework/issues/1555
