### ISSUE TITLE
few attributes needs to add in component files

### ISSUE THREAD

**Issue by sarveshwar-gavhane** [adaptlearning/adapt_framework#2692]
### few attributes needs to add in component files
there are few attributes which are introduced lately or already there but not present in components file needs to add to JSON.

### adapt-media

1. `_pauseWhenOffScreen`
2. `_playsinline`
3. `_preventForwardScrubbing`
4. `_showVolumeControl`

### adapt-matching

1. `_shouldResetAllAnswers`

### adapt-assessmentResult

1.  `_retry._routeToAssessment`

### adapt-accordion

1. `_shouldCollapseItems`
2. `_items._graphic.attribution`
3. `_classes` & `_setCompletionOn & comment` (optional)

### adapt-hotgraphic

1. `_isRound`
2. `_graphic.attribution`
3.  `_items._graphic.attribution`

### adapt-narrrative

1. `_items._graphic.attribution`

there can be more attributes which are new/unknown that we can add, suggest any if i missed.

**Comment by moloko** [comment]
these are present in example.json for each component and documented in the README - do we really need to add them to the default course's components.json as well?

**Comment by moloko** [comment]
Personally I think the .json files that come with the framework should just contain the settings necessary to create that particular course - plus additionally any that are likely to be used the majority of the time. the correct place to list all possible settings and include comments should be example.json

**Comment by sarveshwar-gavhane** [comment]
we can skip some of them which are not necessary but attributes likes e.g `_preventForwardScrubbing`,`_pauseWhenOffScreen`,`_shouldResetAllAnswers` etc
i am not sure how of frequently designers see example.json and newly additions.

its better to add if we have!

**Comment by moloko** [comment]
I don't think designers in general necessarily look at components.json either. I really don't think that the right way to be educating people about new settings. We should be directing people to release notes/README/example.json - otherwise we're just wasting our time maintaining these.

**Comment by oliverfoster** [comment]
Can we do both if it's useful?

**Comment by oliverfoster** [comment]
closed as no follow-up
