### ISSUE TITLE
Formalise plugin schemas

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2704]
### Subject of the issue
Document available for comments, [Schema Processing Outline and
Future Direction](https://drive.google.com/file/d/1cjM51g6XUVTc5jdQc5jLXPqwb1DMaNsP/view?usp=sharing)

**Comment by oliverfoster** [comment]
We just need documentation for how the new schemas work and this sorted innit? @taylortom

**Comment by taylortom** [comment]
Yep, lemme know what I need to do here :smile:

**Comment by oliverfoster** [comment]
I think we neeeed... (update if you think of anything else)

* Header definition
* Property definitions
* Spec conformity
* Additions
* Inheritance/extension rules
* Differences to old schemas / how to migrate

**Comment by oliverfoster** [comment]
Implemented in AAT v1
