### ISSUE TITLE
adapt-contrib-assessment - assessment having 1 attempt does not get complete when failed.

### ISSUE THREAD

**Issue by akshay-bhavsar** [adaptlearning/adapt_framework#2706]
### Your environment
* version (AT/Framework) : 5.2.0
* adapt-contrib-assessment v 4.0.0
* all browser 
* device(s) + operating system(s) : all
*  SCROM 1.2

### Steps to reproduce
Add assessment in article set attempt to 1 and attempt assessment to get failed.

### Expected behaviour
Completion status should update.

### Actual behaviour
Completion status shows unknown.

**Comment by moloko** [comment]
what have you got `_onAssessmentFailure` set to in your spoor config?

**Comment by akshay-bhavsar** [comment]
I have set something like "_onAssessmentFailure": "incomplete",

**Comment by moloko** [comment]
Then the behaviour you describe above is exactly as expected...

**Comment by oliverfoster** [comment]
The status `"incomplete"` means the course is `"incomplete"` on the LMS. You need to used "complete" or "failed".

https://github.com/adaptlearning/adapt_framework/blob/master/src/course/config.json#L57

**Comment by moloko** [comment]
@akshay-bhavsar from the README for spoor:
>**\_onAssessmentFailure** (string): Specifies the status that is reported to the LMS when the assessment is failed. Acceptable values are `"failed"` and `"incomplete"`. Some Learning Management Systems will prevent the user from making further attempts at the course after status has been set to `"failed"`. Therefore, it is common to set this to `"incomplete"` to allow the user more attempts to pass an assessment.
