### ISSUE TITLE
adapt-contrib-media: transcript button should include 'btn-text' class

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2720]
### Subject of the issue/enhancement/features
Transcript button doesn't inherit button text styling by default.

### Expected behaviour
'btn-text' class to be applied to transcript button as per other Adapt text buttons for consistency.

**Comment by olivermartinfoster** [comment]
It should probably get a visited state when the component is completed also.

**Comment by guywillis** [comment]
I would actually disagree. The transcript button is specifically related to the media component and not functional like a submit button or navigational like a menu item button. In that sense, it behaves more akin to an accordion or MCQ item.
