### ISSUE TITLE
Missing text when export language files are created

### ISSUE THREAD

**Issue by clementpr** [adaptlearning/adapt_framework#2721]
### Subject of the issue/enhancement/features
It seems some texts are missing when we use command "grunt translate:export --masterLang=en --format=csv --csvDelimiter=;" 

### Environment
* Framework 5.3.0
* all browsers
* Macos

### Steps to reproduce
1. Go to "my-adapt-course" or an other course
2. Export language files for example with "grunt translate:export --masterLang=en --format=csv --csvDelimiter=;" 
3. Go to "languagefiles" folder
4. Open .csv files or json files created. 
5. Some texts are missing. For example : Accordion + Hot graphic : no text for accordion item or hotgraphic content. Or Multiple Choice Question : no text for "mcq item"  or "feedback"

### Expected behaviour
We should have all text  with "true translation" in ""Properties Schema".

### Actual behaviour
Some text are missing. 

### Screenshots (if you can)
<img width="826" alt="Capture d’écran 2020-04-15 à 10 54 43" src="https://user-images.githubusercontent.com/8448884/79318821-caac2780-7f07-11ea-98cd-c2fece0df0ae.png">

**Comment by olivermartinfoster** [comment]
This is probably my fault. Will have a look today.

**Comment by olivermartinfoster** [comment]
Please test with code from above pr or branch [issue/2721](https://github.com/adaptlearning/adapt_framework/tree/issue/2721)
