### ISSUE TITLE
adapt-contrib-trickle: trickle on article that is only article in page causes error

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2728]
### Subject of the issue/enhancement/features
If trickle is enabled on an article and that article is the only one in the page then when the article completes an a11y runtime error can occur as trickle attempts to scroll the user to the next logical article. This prevents the content object model from completing and has the usual kind of knock-on problems such as the next button in quicknav not enabling etc.

### Your environment
Adapt v5
IE11

### Steps to reproduce
Infer from description

### Expected behaviour
Trickle should not try to scroll the user to an article element that does not exist. Call to `findRelativeModel` could use `limitParentId` option; setting its value to the _id of the parent page. This would solve the problem.

Alternatively, patch a11y.js `isReadable` so that if `$element` is undefined it doesn't upset IE11.

### Actual behaviour
See description

**Comment by oliverfoster** [comment]
added _showEndOfPage and allowed trickle to go to other pages
