### ISSUE TITLE
Adapt.wait flush

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#2743]
Is the behaviour implemented via https://github.com/adaptlearning/adapt_framework/issues/2439 a good idea? Isn't it the responsibility of the plugin to ensure they call an `Adapt.wait.end()` if using an `Adapt.wait.begin()`.

Flushing any open waits after 7 seconds means you can't intentionally block Adapt from loading, if required. For example, you may want to not call an `end()` and display an uncancellable notification to indicate an issue which should prevent a user from continuing. Currently the flush will end this, continue with the loading and eventually close any notifications regardless of the plugin functionality.

**Comment by olivermartinfoster** [comment]
Yes, I agree.
