### ISSUE TITLE
adapt-contrib-spoor: question responses code very unreadable

### ISSUE THREAD

**Issue by olivermartinfoster** [adaptlearning/adapt_framework#2744]
### Subject of the issue
This file is extremely unreadable and could do with a rewrite + documentation

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/serializers/scormSuspendDataSerializer.js

**Comment by moloko** [comment]
done & released in [spoor v3.4.0](https://github.com/adaptlearning/adapt-contrib-spoor/releases/tag/v3.4.0)
