### ISSUE TITLE
release/v5.5.0 Release progress

### ISSUE THREAD

**Issue by olivermartinfoster** [adaptlearning/adapt_framework#2753]
### Subject of the issue
In Adapt Framework v.5.5.0 the ContentObjectView destroys its sub views rather than all descendant views being destroyed on the global Adapt:remove event. Multiple contentObjects can now be rendered simultaneously (for [transitions](https://github.com/olivermartinfoster/adapt-contentObjectTransition) etc).
Reference code: [Adapt.remove](https://github.com/adaptlearning/adapt_framework/blob/issue/2709-1/src/core/js/adapt.js#L408), [ContentObjectView.destroy](https://github.com/adaptlearning/adapt_framework/blob/issue/2709-1/src/core/js/views/contentObjectView.js#L93-L126)

Some extensions which produce content inside menus and pages still listen to the global remove event and so remove their views before the page is destroyed. 

This issue is to rectify that.
These four plugins need a release/v5.5.0 branch to move to the ContentObjectView destruction model:

- [x] assessmentResults
- [x] matching
- [x] pageLevelProgress
- [x] trickle

**Comment by oliverfoster** [comment]
Need to do releases for:

https://github.com/adaptlearning/adapt-contrib-assessmentResults
https://github.com/adaptlearning/adapt-contrib-matching
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress
https://github.com/adaptlearning/adapt-contrib-trickle
