### ISSUE TITLE
Adapt v5.7.0 Proposal

### ISSUE THREAD

**Issue by olivermartinfoster** [adaptlearning/adapt_framework#2766]
### Subject of the issue
[Document to read](https://drive.google.com/file/d/1xIYTFNofe_AVgCBjii24fWZ4UMdJwPB5/view?usp=sharing) with a rational for v5.7.0, please add comments on the document or below this ticket.

Example course: 
https://olivermartinfoster.github.io/v5_6_0/build/scorm_test_harness.html

Example source code: https://github.com/olivermartinfoster/olivermartinfoster.github.io/tree/master/v5_6_0

Download:
https://github.com/olivermartinfoster/olivermartinfoster.github.io/tree/master/v5_6_0/v5_6_0.zip

**Comment by moloko** [comment]
@oliverfoster I think the title needs changing again ;-)

**Comment by oliverfoster** [comment]
I don't think so, all of this is in now I just have to get that trickle rewrite approved and rewrite assessment.

**Comment by oliverfoster** [comment]
Assessment rewrite is in progress.
