### ISSUE TITLE
Question: contentObject transitions extension

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2768]
### Subject of the issue
v5.5.0 contentObject transitions are possible.
Should we move a basic contentObject transition extension into the adaptlearning repository?

Proposed prototype: https://github.com/cgkineo/adapt-contentObjectTransition
Running example: https://olivermartinfoster.github.io/pageTransitions/build/

**Comment by moloko** [comment]
I think it would be a nifty thing to include with Adapt 'out of the box'

**Comment by moloko** [comment]
it would look even nicer with a subtler loading animation

**Comment by oliverfoster** [comment]
Definitely going to need a frond-end developer to take a look before it's ootb. The prototype will need some love from the LESS side.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-contentObjectTransition

Finished and registered. Just needs scrutiny then a first release.
