### ISSUE TITLE
Update underscore to v1.10.2?

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2773]
We're currently running v1.9.1 (released 2018)

Changes are listed [here](http://underscorejs.org/#changelog)

**Comment by olivermartinfoster** [comment]
Definitely, does backbone need doing also?

**Comment by moloko** [comment]
nope, they haven't released an update since Feb last year - v1.4.0 (which is what we're using)

**Comment by oliverfoster** [comment]
Cool.
