### ISSUE TITLE
Framework - Adapt does not trigger device resize on iOS orientation change

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2774]
### Subject of the issue
This issue is noticeably present in the Slider plugin if the user views the Slider in portrait mode and then switches to landscape, the numbers bunch up on the left hand side. This doesn't occur if the component is initially viewed in landscape; it appears to be triggered by switching orientation.

### Your environment
* v5.3.0 FW, v0.10.3 AT

### Expected behaviour
Adapt triggered device resize on iOS orientation change which, in turn, causes the slider numbers and notches to expand to fill the space when the user rotates their device.

![IMG_0794](https://user-images.githubusercontent.com/11569678/82038238-239fe480-969b-11ea-8bf3-eee865f9c19d.png)

**Comment by oliverfoster** [comment]
Adapt reports normalised widths and heights on iOS, removing the orientation, such that the screen portrait width and height are always reported.

https://github.com/adaptlearning/adapt_framework/blob/be865ed6c6dbd319bf004fa174950ef6f65a30e7/src/core/js/device.js#L163-L169

I'm not sure, but I think that code was meant to do the opposite, in that iOS used to report a static width and height that had to be corrected width the orientation?

**Comment by moloko** [comment]
Just got here via discovering what (I'm assuming is) the same issue but with the [adapt-hide extension](https://github.com/cgkineo/adapt-hide/)

@oliverfoster happy to help with debugging this on iPad - if I can actually persuade my Mac to let me do so...! 

Would help to get some pointers as to what to look for (or can screen share Mac via Teams)

**Comment by oliverfoster** [comment]
You'll just need to make a small standalone html5 site with our viewport metatag, which reports the values of `screen.height`, `screen.width`, `window.innerHeight`, `window.innerWidth` and `window.orientation`, then screen print the results as you rotate the device.

**Comment by moloko** [comment]
@oliverfoster here you go...

Portrait:
![ipad_portrait](https://user-images.githubusercontent.com/1249597/97029494-6a044400-1555-11eb-8ee7-93586103d06b.JPG)

Landscape:
![ipad_landscape](https://user-images.githubusercontent.com/1249597/97029518-7092bb80-1555-11eb-9c9e-df3512714620.JPG)

**Comment by oliverfoster** [comment]
Damn. So that says that the status quo still stands. We need the results of Adapt.device.screenHeight and Adapt.device.screenWidth now. So that code will need to be run inside Adapt.

**Comment by moloko** [comment]
Yeah no problem!

In landscape orientation I get:
screenHeight: 768
screenWidth: 1024

In portrait, it's:
screenHeight: 1024
screenWidth: 768

**Comment by oliverfoster** [comment]
I can only think this:
https://stackoverflow.com/a/25322717

Might be worth trying the new mediaMatch function?

**Comment by moloko** [comment]
I dunno, I have to confess I'm not entirely clear on the specifics of the problem - I can see that `screen.height` and `screen.width` are clearly not much use but all the others I've tried appear to be showing changes based on orientation? Maybe one to pick up on the Monday call?

**Comment by oliverfoster** [comment]
Yup. The code all looks good. So I'm thinking that window.orientation isn't changing fast enough as suggested in that thread and so it's misreporting.

**Comment by oliverfoster** [comment]
need ios device for this

**Comment by eleanor-heath** [comment]
@oliverfoster we have brought this into our Sprint, I will start working on this soon.

**Comment by oliverfoster** [comment]
Just in case you need them, there are many different ways to calculate and listen for orientation changes.
[`window.mediaMatch`](https://hacks.mozilla.org/2012/06/using-window-matchmedia-to-do-media-queries-in-javascript/)
[`screen.orientation`](https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation)
[`window.addEventListener('deviceorientation')`](https://developer.mozilla.org/en-US/docs/Web/Events/Detecting_device_orientation)

I'm not sure which is more relevant for iOS these days.

**Comment by eleanor-heath** [comment]
This cannot be replicated.
