### ISSUE TITLE
adapt-contrib-assessment: '_isAvailable: false' is ignored

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#2777]
If a question component is set to '_isAvailable: false' and also its containing block, the assessment:complete trigger is never fired.

Tested in latest AT and Assessment v3.1.0

Reproduce by setting up an assessment article with 3 blocks, each with a question in. Set 1 block and it's component to '_isAvailable: false'.

The assessment-results component after the quiz should show the results.

Actual behaviour is the assessment hasn't registered as complete so the results do not show.

Perhaphs these 2 lines should check for '_isAvailable: true' ?

[https://github.com/adaptlearning/adapt-contrib-assessment/blob/a5609c230a77b21a3efb695f41edd9ea4a348444/js/adapt-assessmentArticleModel.js#L74](url)

[https://github.com/adaptlearning/adapt-contrib-assessment/blob/a5609c230a77b21a3efb695f41edd9ea4a348444/js/adapt-assessmentArticleModel.js#L145](url)

**Comment by moloko** [comment]
Should be fixed in Assessment [v4.1.0](https://github.com/adaptlearning/adapt-contrib-assessment/releases/tag/v4.1.0)
