### ISSUE TITLE
website stuck at "Loading your interactive resources - please wait"

### ISSUE THREAD

**Issue by Guyver1wales** [adaptlearning/adapt_framework#2778]
Hi, server admin here not a developer. We have a member of staff reporting the following issue.
![adapt_error](https://user-images.githubusercontent.com/22168798/82546097-84259a80-9b4f-11ea-9caa-462593c2120c.png)

We are running IIS on Server 2012 R2, If you can tell me how to find the version of adapt framework I can provide it.

Are there any things I can check to start troubleshooting this issue?
iisreset /noforce has not resolve. We are going to reboot the web server this evening.

**Comment by moloko** [comment]
@Guyver1wales you need to get in touch with the person or organisation who created this piece of training for you...
