### ISSUE TITLE
adapt-contrib-media : tab order alert on js-skip-to-transcript button

### ISSUE THREAD

**Issue by kunjsharma** [adaptlearning/adapt_framework#2784]
### Subject of the issue
When run ANDI test on v5 demo ( https://adaptlearning.github.io/v5demo/#/id/co-05 ), got 2 alerts, one of them is for on js-skip-to-transcript button of adapt-contrib-media .

### Your environment
* Framework v5.3.0 ( https://adaptlearning.github.io/v5demo/#/id/co-05 )
* Firefox 76.0.1
* HP G-42 laptop Windows 7

### Steps to reproduce
Click url: https://adaptlearning.github.io/v5demo/#/id/co-05
Run ANDI test and it shows 2 alerts

### Screenshots
![adapt-contrib-media__issue](https://user-images.githubusercontent.com/6715520/83059646-dac33500-a077-11ea-9b7b-1b833fec62d9.png)

**Comment by olivermartinfoster** [comment]
This is as expected. That button is for screen readers only and therefore should not be tabbable in the normal flow as it isn't visible. If it were tabbable for a normal keyboard user the tab would seem to disappear with no indication. With a screen reader cursor, that button reads additionally to allow skipping straight to the transcript.

**Comment by moloko** [comment]
@kunjsharma the test tool is not actually saying there is an issue, it is asking you a question: 'should this button be tabbable?'. In this case, the answer is 'no'.

Automated accessibility testing tools are all well and good but no substitute for going through the course properly using JAWS or NVDA.
