### ISSUE TITLE
languagePicker: 'change language' popup needs a lang attribute

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2785]
Because the text of the popup is in the language the learner is trying to switch **to**, it is therefore different to the language declared via the `lang` attribute of the `html` element.

It should be possible to add  `lang` attribute to Notify that specifies the language used in the popup correctly. This would be beneficial both for assistive technology and for language-specific styling as well (for example, you may want to use a different font for non-Latin languages)

**Comment by guywillis** [comment]
Ideally alongside the `lang` attribute there should be a language class `is-en` / `is-de` to amend styling / font is required.

**Comment by moloko** [comment]
> Ideally alongside the `lang` attribute there should be a language class `is-en` / `is-de` to amend styling / font is required.

small suggestion: something more like `is-lang-de` might be a bit clearer? otherwise someone might look at a class like `is-de` and wonder what on earth it means! Not to mention `is-it` for Italian...

**Comment by NayanKhedkar** [comment]
I think class will be a fine. Is there attribute really need? [PR](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/41)

**Comment by tomgreenfield** [comment]
As @moloko says, the attribute is useful for [assistive technology](https://www.w3.org/TR/WCAG20-TECHS/H58.html).

**Comment by moloko** [comment]
@NayanKhedkar Jaws uses the `lang` attribute to work out what language to use when reading out the text

**Comment by NayanKhedkar** [comment]
Hi, Should I write [here](https://github.com/adaptlearning/adapt_framework/blob/cec104037c3046599e2da61fd17b79cd2e02fa7e/src/core/js/views/notifyView.js#L13)
```
attributes: function () {
      return _.extend({
        'role': 'dialog',
        'aria-labelledby': 'notify-heading',
        'aria-modal': 'true'
      }, this.model.get('_attributes') || {})
 }
```
and [here](https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/85bbd3930fc4a11189413a13d18460e0a2bc5c74/js/languagePickerDrawerView.js#L32)
``` _attributes: { 'lang': newLanguage } ```

**Comment by tomgreenfield** [comment]
A few things to note about the above code:
* `Object.assign()` can be used since we now have a polyfill for IE
* No `|| {}` fallback is needed because `Object.assign()` handles falsies
* `lang` doesn't need quotes

**Comment by NayanKhedkar** [comment]
Dependent [PR](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/41):

**Comment by moloko** [comment]
not actually fixed yet..!

**Comment by guywillis** [comment]
I think this issue can be closed now?

**Comment by moloko** [comment]
yep, done in FW v5.6 and languagePicker v4.1.0
