### ISSUE TITLE
[adapt-contrib-assessmentResults] still invisible when assessment completed

### ISSUE THREAD

**Issue by loudoweb** [adaptlearning/adapt_framework#2791]
### Subject of the issue/enhancement/features
The adapt-contrib-assessmentResults is still invisible when the assessment has been completed.
It seems that commenting this line https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/js/assessmentResultsModel.js#L123 fixes the problem.

### Your environment
Framework: 5.3.0

### Steps to reproduce
Use trickle.

### Expected behaviour
The component should be visible when the assessment has been completed

### Actual behaviour
The component is still invisible when the assessment has been completed

**Comment by olivermartinfoster** [comment]
How is your config different to the standard course?

Is the assessment results component outside of the assessment article?

**Comment by loudoweb** [comment]
Yes it is in a different article.

**Comment by loudoweb** [comment]
It works when I disable trickle. 
I'll try with the demo course.

**Comment by oliverfoster** [comment]
Did you have any luck?

**Comment by moloko** [comment]
closing as heard nothing further on this in > 2 months
