### ISSUE TITLE
adapt-theme-vanilla: assets & templates folder

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2792]
Just adding a small quality of life change here. I would recommend adding an 'assets' & 'templates' folder to the root of the vanilla theme just to show that these things are free to use for storing your repeated assets as well as the ability to affect the HTML templates. I would wager any new developers would try to modify core instead. @guywillis

**Comment by guywillis** [comment]
Agreed Joe. There is a limitation with Git however that stops the implementation of empty folders. There would need to be a hidden file like `.keep` / `.gitignore` or a visible `README` file that's either empty or has a brief explanation as to why there is an empty folder.

**Comment by moloko** [comment]
I like the idea of putting a readme.txt in each folder to explain usage

**Comment by olivermartinfoster** [comment]
A readme.md would be formatted and readable on GitHub.

**Comment by moloko** [comment]
that’s very true but my thinking behind suggesting .txt was to do with whether people would be more likely to read it on GH or locally. A .txt file is more easily readable locally  and, given that it’s probably only going to need a sentence at most to explain the purpose of the folder, would be just as readable via GH too. 

It’s a minor thing, I just feel that in this instance .txt has a slight advantage. but if you want to go with .md, I don’t feel that strongly about it!

**Comment by olivermartinfoster** [comment]
Nah, I like your rational. Nothing like double click to notepad.exe.
