### ISSUE TITLE
Question component - Marking should only be displayed on final question attempt

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt_framework#2796]
### Subject of the enhancement
The Question component could benefit from a 'Display Final Marking Only' type setting

### Your environment
* FW5

### Steps to reproduce
Create a course with Matching Question components with multiple question stems; each question having only 2 possible answers and the user has 2 attempts.

### Expected behaviour
The component could be set to only display marking on the final attempt

### Actual behaviour
After the first attempt, the marking is displayed, making it quite obvious to the user what the correct answers are for each Matching Question

**Comment by moloko** [comment]
I don't seem to be able to replicate this, am I missing something obvious?
![image](https://user-images.githubusercontent.com/1249597/84805465-3855fc00-affc-11ea-9a2e-db4a8d4592c4.png)

Using FW v5.3.0 and Matching v4.0.0 it displays marking only on the final attempt, as expected... is it specific to a more recent FW version perhaps?

**Comment by oliverfoster** [comment]
Weird. From the code it definitely adds the classes each time, which it definitely shouldn't.

QuestionView:onSubmitClicked
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/questionView.js#L189

MatchingView:showMarking
https://github.com/adaptlearning/adapt-contrib-matching/blob/master/js/matchingView.js#L86

**Comment by moloko** [comment]
Ah OK yes IIRC it was adding the classes - but not displaying ticks/crosses. There must be something in the theme preventing ticks/crosses from being displayed until all attempts used up. We should definitely stop the classes from being added in the first place though.

**Comment by oliverfoster** [comment]
I assume something about the styling / version is a reason for it. I do remember a few clients telling us that their users were using the debugger to figure out from the marking classes what the correct / incorrect options are. This will at least help tackle that one at the same time.

**Comment by cahirodoherty-learningpool** [comment]
Yeh I have just confirmed that with FW5 it is behaving as you say @moloko 
Based on the conversation it probably does make sense for the code changes to go in to address any inspection cheating by end users

**Comment by oliverfoster** [comment]
There was one more on found in this vein. 
![image](https://user-images.githubusercontent.com/7974663/85271700-0d8ffb80-b473-11ea-9a7a-3f4cdbd36a1f.png)

**Comment by moloko** [comment]
This change has created couple of issues for MCQs with more than one attempt:

- the `can-show-marking` class now doesn't get added to the component, ever. which is annoying if you were using that to add additional styling ;-)

- the green-circle-with-tick that should be displayed when you answer correctly doesn't get shown if you get it right first time

**Comment by moloko** [comment]
the second issue I think can be fixed by adding `if (this.get('_isCorrect')) return true;` [here](https://github.com/adaptlearning/adapt_framework/blob/d6bab14fd741d771f088abe79197a1449f83bd9a/src/core/js/models/questionModel.js#L328)

**Comment by oliverfoster** [comment]
That makes sense.

**Comment by moloko** [comment]
the first issue I thought I could fix by adding `this.$el.addClass('can-show-marking');` inside of [this if block](https://github.com/adaptlearning/adapt_framework/blob/d6bab14fd741d771f088abe79197a1449f83bd9a/src/core/js/views/questionView.js#L311-L313) BUT I can't see that `questionview.refresh` actually gets called unless the question is in an assessment...

Equally we could change [this line](https://github.com/adaptlearning/adapt_framework/blob/d6bab14fd741d771f088abe79197a1449f83bd9a/src/core/js/views/questionView.js#L26) back to `(this.model.get('_canShowMarking') ? 'can-show-marking' : '')` as - IIRC - the purpose of this class wasn't actually to do with showing marking, it was there mainly to indicate what settings in the model had been enabled (see #2606).

**Comment by oliverfoster** [comment]
Just firing up a framework to have a go at it.

**Comment by moloko** [comment]
> 
> 
> Just firing up a framework to have a go at it.
> 
> ```js
> if (this.get('_isComplete')) return true;
> ```
> 
> Seems a little more robust if you don't mind?

Not at all, presumably that would also mean [these lines](https://github.com/adaptlearning/adapt_framework/blob/d6bab14fd741d771f088abe79197a1449f83bd9a/src/core/js/models/questionModel.js#L329-L333) would then be redundant? And should it be `_isComplete` or would `_isInteractionComplete` be better?
> 
> I'll revert that line in className to this.model.get('_canShowMarking') from this.model.canShowMarking

yep, I think that leaves it consistent with how the `can-show-model-answer` and `can-show-feedback` classes are used i.e. they are added at the start to indicate that those settings are enabled. 

or we update those so that they are only added when 'model answer should now be shown' and 'feedback now can be shown'... either way it should be consistent but I'm not 100% sure which is the best

**Comment by oliverfoster** [comment]
> yep, I think that leaves it consistent with how the can-show-model-answer and can-show-feedback classes are used i.e. they are added at the start to indicate that those settings are enabled.

I agree looking at it again. That was my fault I think.

**Comment by moloko** [comment]
@guywillis @kirsty-hames and any other styling folks, would it be easier from your point of view if these classes were always present - or were only added once marking/model answer/feedback _should_ be shown?
