### ISSUE TITLE
adapt-contrib-spoor: warning shown in Firefox when running from scorm_test_harness.html

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2798]
If you run Adapt using scorm_test_harness.html (or via `grunt server-scorm`), the following warning is displaying in the console in Firefox:
> Cookie “_spoor” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by oliverfoster** [comment]
Problem code: https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/offline_API_wrapper.js#L279-L283

**Comment by moloko** [comment]
I think that we should be able to fix this by updating to [js-cookie](https://github.com/js-cookie/js-cookie/) (replacement for jquery.cookie). I might have an opportunity to look at this over the next couple of months as I've got a client who'd like to have the 'cookie tracking' option available - but currently it's not working properly as the cookie is always created as a 'session cookie', so typically gets deleted too soon. And weirdly I don't seem to be able to set it to anything else in Firefox. Am assuming that it's just an 'old code' problem and hoping that updating to the new version will magically make it all work...
