### ISSUE TITLE
adapt-contrib-spoor: android chrome zoom not working

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2800]
### Subject of the issue

Need to remove the maximum-scale value from the viewport meta-tag throughout:
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/index.html#L11
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/index_lms.html#L7
https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/required/scorm_test_harness.html#L8

Reference: [#2569](https://github.com/adaptlearning/adapt_framework/pull/2569)

**Comment by moloko** [comment]
derp, my bad for forgetting to amend these as well!

**Comment by NayanKhedkar** [comment]
😄 
Pr: https://github.com/adaptlearning/adapt-contrib-spoor/pull/196

**Comment by oliverfoster** [comment]
There's a secondary issue I'll do in a second. Scroll disable blocks zooming on notify and drawer fixed position elements.
