### ISSUE TITLE
adapt_framework: move trackingIds to components from blocks

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2805]
### Subject of the issue
Blocks currently own the trackingIds for session state save and restore. This makes blocks mandatory as part of the course structure. It makes the component state save and restore more complicated than it needs to be.

By moving trackingIds to components we can remove the complexity and demote blocks from a necessary part of the course content to an optional part of the course content.

**Comment by oliverfoster** [comment]
After assessment pr goes in https://github.com/adaptlearning/adapt-contrib-assessment/pull/125 it needs updating to be tracking id location agnostic.

**Comment by moloko** [comment]
> 
> 
> After assessment pr goes in [adaptlearning/adapt-contrib-assessment#125](https://github.com/adaptlearning/adapt-contrib-assessment/pull/125) it needs updating to be tracking id location agnostic.

that PR has been merged now. want me to do a release of assessment before you add anything further?

**Comment by oliverfoster** [comment]
moved to assessment plugin
