### ISSUE TITLE
Graphic + PLP - Amend aria-label to support html characters

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2807]
### Subject of the issue
The aria labels for the Graphic and PLP Item templates don't allow for HTML characters. This is needed to make well pronounced abbreviations for screen readers.

### Your environment
* FW v5+

### Expected behaviour
Aria labels should support html characters.

**Comment by moloko** [comment]
@guywillis could you give me an example of the sort of html chars you're looking to support?

**Comment by guywillis** [comment]
@moloko 

I'm looking to support both HTML tags (e.g. span) and zero width characters.

`<span class='u-zero-width'>A&#8203;B&#8203;C</span>`

Use case example: If a word is required to be pronounced as a series of characters in a screen reader (NVDA) you'd want to put zero width characters between each character of the word. This, in turn, causes the visual display to break over multiple lines when there is not enough space to display the entire word on a single line. To resolve this visual issue the introduction of a span with inline styling or a class is required.

**Comment by moloko** [comment]
ta @guywillis always useful to have an example for testing ;-)
