### ISSUE TITLE
Convert all core components/extensions to ES6 classes/modules add import/export

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2808]
Core plugins (updated 07/09/2021):
- [x] [adapt-contrib-accordion](https://github.com/adaptlearning/adapt-contrib-accordion)
- [x] [adapt-contrib-assessment](https://github.com/adaptlearning/adapt-contrib-assessment)
- [x] [adapt-contrib-assessmentResults](https://github.com/adaptlearning/adapt-contrib-assessmentResults) ES Modules
- [x] [adapt-contrib-blank](https://github.com/adaptlearning/adapt-contrib-blank) ES Modules
- [x] [adapt-contrib-bookmarking](https://github.com/adaptlearning/adapt-contrib-bookmarking)
- [x] [adapt-contrib-boxMenu](https://github.com/adaptlearning/adapt-contrib-boxMenu)
- [x] [adapt-contrib-branching](https://github.com/adaptlearning/adapt-contrib-branching)
- [x] [adapt-contrib-confidenceSlider](https://github.com/adaptlearning/adapt-contrib-confidenceSlider)
- [x] [adapt-contrib-contentObjectTransition](https://github.com/adaptlearning/adapt-contrib-contentObjectTransition) ES Modules
- [x] [adapt-contrib-glossary](https://github.com/adaptlearning/adapt-contrib-glossary)
- [x] [adapt-contrib-gmcq](https://github.com/adaptlearning/adapt-contrib-gmcq)
- [x] [adapt-contrib-graphic](https://github.com/adaptlearning/adapt-contrib-graphic)
- [x] [adapt-contrib-hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic) ES Modules
- [x] [adapt-contrib-instructionError](https://github.com/adaptlearning/adapt-contrib-instructionError) ES Modules
- [x] [adapt-contrib-languagePicker](https://github.com/adaptlearning/adapt-contrib-languagePicker)
- [x] [adapt-contrib-matching](https://github.com/adaptlearning/adapt-contrib-matching)
- [x] [adapt-contrib-mcq](https://github.com/adaptlearning/adapt-contrib-mcq)
- [x] [adapt-contrib-media](https://github.com/adaptlearning/adapt-contrib-media) ES Modules
- [x] [adapt-contrib-narrative](https://github.com/adaptlearning/adapt-contrib-narrative)
- [x] [adapt-contrib-pageLevelProgress](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress)
- [x] [adapt-contrib-pointGmcq](https://github.com/adaptlearning/adapt-contrib-pointGmcq) Deprecated
- [x] [adapt-contrib-resources](https://github.com/adaptlearning/adapt-contrib-resources)
- [x] [adapt-contrib-slider](https://github.com/adaptlearning/adapt-contrib-slider) ES Modules
- [x] [adapt-contrib-spoor](https://github.com/adaptlearning/adapt-contrib-spoor) ES Modules
- [x] [adapt-contrib-text](https://github.com/adaptlearning/adapt-contrib-text)
- [x] [adapt-contrib-textInput](https://github.com/adaptlearning/adapt-contrib-textInput)
- [x] [adapt-contrib-trickle](https://github.com/adaptlearning/adapt-contrib-trickle)
- [x] [adapt-contrib-triggered](https://github.com/adaptlearning/adapt-contrib-triggered)
- [x] [adapt-contrib-tutor](https://github.com/adaptlearning/adapt-contrib-tutor)
- [x] [adapt-contrib-vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla)
- [x] [adapt-contrib-xapi](https://github.com/adaptlearning/adapt-contrib-xapi)
- [x] [adapt-component](https://github.com/adaptlearning/adapt-component)
- [x] [adapt-questionComponent](https://github.com/adaptlearning/adapt-questionComponent)
- [x] [adapt-extension](https://github.com/adaptlearning/adapt-extension)
- [x] [adapt-vimeo](https://github.com/adaptlearning/adapt-vimeo)
- [x] [adapt-youtube](https://github.com/adaptlearning/adapt-youtube)

Bring up to fw version 5.8

**Comment by oliverfoster** [comment]
ollie to update checklist for es modules

**Comment by oliverfoster** [comment]
Done. Tutor can probably be left until https://github.com/adaptlearning/adapt-contrib-tutor/pull/61 this pr is approved.

**Comment by oliverfoster** [comment]
@eleanor-heath media and slider have old module definitions still

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/156017765-329e8e8e-91f1-4e6a-ad25-ad1083dba939.png)

@eleanor-heath it seems as though we have these three left
