### ISSUE TITLE
adapt_framework: babel fast-async causes very slow compilation

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2816]
### Subject of the issue
I introduced fast-async to help debugging promises but it seems to elongate the build process by about 6 seconds, which is not ideal.

Debugging promises is slightly more painful without fast-async, as the call-stack is a bit longer and the errors aren't as clear, but it beats having to wait a minimum of 6 seconds a time for each compilation cycle.

Since I segregated the babel task into a compile and a dev version, debugging promises seems to have improved without needing fast-async.

Suggest removal.

**Comment by moloko** [comment]
worth adding a switch for enabling this when needed?

**Comment by oliverfoster** [comment]
Nah, I've done some more reading into the library and I'm convinced it's not a great idea to keep it as a dependency. The owner has expressed a strong unwillingness to maintain it on the webpack forums.
