### ISSUE TITLE
adapt-contrib-trickle - iOS voiceover goes past page lock

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2823]
### Subject of the issue/enhancement/features

A learner using iOS voice can navigate past the hidden elements on the page without pressing continue to reveal the content.

### Your environment

* FW 5.3.0
* iOS 13.5, Safari 13, VoiceOver

### Steps to reproduce

* Create a course using Trickle with a button to proceed
* Swipe right as if you were continuing normally when you should be prevented

### Expected behaviour

The learner shouldn't be able to continue to navigate and should be prompted to press the Continue button

### Actual behaviour

The learner is able to continue swiping through the course content, the screenreader reads out what is being selected by the screenreader but it is invisible on the screen.

### Screenshots (if you can)

https://s3.amazonaws.com/mydonedone.com/DoneDone_zoonou/cf8192fc-1a69-4508-886f-3962f79e5c5e_/-1-iOS-content-that-is-not-accessible.mp4

**Comment by oliverfoster** [comment]
fixed with the above pr
