### ISSUE TITLE
adapt-contrib-graphic feature request: allow graphic to be a hyperlink

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2832]
just because this is something that has come up once or twice in projects: would be useful if the graphic component allowed for adding a link to the graphic so that, when clicked, it could link to:
* external URL
* course resource (e.g. PDF)
* location within Adapt course

Thoughts?

**Comment by oliverfoster** [comment]
With either visual or textual instructions of some kind. It must look and read clickable.

**Comment by moloko** [comment]
> With either visual or textual instructions of some kind. It must look and read clickable.

Well, as with all component it supports both body and instruction so there's nothing preventing the course author from including this. In terms of 'look clickable', on desktop hyperlinking it will be sufficient to change the cursor to the 'hand' style, for touch devices I'm not sure what more we can do aside from making it clear in the component body/instruction... 

including support for the `title` attribute might be an idea?

**Comment by oliverfoster** [comment]
Yup all good. Role=link I think might be a thing if we use ```window.open```

**Comment by moloko** [comment]
cool, let's get the ES6 version of graphic merged & I can either add it for that release or one after
