### ISSUE TITLE
Authoring Tool schema: Hide block title by default

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2833]
I can't be the only person who thinks it's stupid this is on by default when Block titles are probably used in like >1% of the time.

See - https://github.com/adaptlearning/adapt_authoring/issues/2481

**Comment by moloko** [comment]
@simondate AFAIK the AAT requires that all pages/articles/blocks/components have a `title` set. Certainly if you go to import a Framework course into the AAT it will fail if you have not done so.

The `displayTitle` is, however, optional and is set as such in block.model.schema - are you maybe referring to the `default` [that is set here](https://github.com/adaptlearning/adapt_framework/blob/455d487675a48dc55a685b4988bb4d223b84d70d/src/core/schema/block.model.schema#L26)?

**Comment by moloko** [comment]
also begs the question should the same also apply to the article display title?

**Comment by simondate** [comment]
* Yes, I was referring to `displayTitle`
* Yes, I think it should for the Article title too
