### ISSUE TITLE
Developer build vs final build request

### ISSUE THREAD

**Issue by robertmausser** [adaptlearning/adapt_framework#2836]
### Subject of the issue/enhancement/features

We use both Dev-Tools extension and Shadow-ID's extension to speed up development process of the framework

https://github.com/cgkineo/adapt-devtools

https://github.com/darylhedley/adapt-shadowIds

 

However every so often someone makes the mistake of not turning them off for the final build, which is obviously not a good thing!

Is there a way to have a line of code in JS or something that says "only build this if grunt dev command is used, not grunt build" So when we are working on the framework  with the Grunt Dev command, they show up, but on final build with Grunt Build they dont?

Any other similar method or solution is greatly appreciated, this is just how I would forsee it working. If you have a different idea that works too, im all ears

Thank you!!!

### Your environment
Adapt framework 4.4.0 and 5.0. 

Browsers etc irrelevant 

### Steps to reproduce
Not an issue, feature request.

### Expected behaviour
When the developer user Grunt Dev, devtools is available. When using Grunt Build, devtools is removed for final build. 

### Actual behaviour
Devtools is enabled even at build, causing learners to complete the course by using the devtools.

**Comment by olivermartinfoster** [comment]
With the latest framework master you can now do this:

#### config.json
```json
    "build": {
        "productionExcludes": [
            "adapt-devtools"
        ]
    },
```
