### ISSUE TITLE
default FW -> AT import issues - PLP settings

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2841]
### Subject of the issue/enhancement/features

When you create the framework using `adapt create course` the JSON for Page Level Progress isn't complete and breaks what should be a direct import into the Authoring Tool.

I propose updating the JSON so that a direct import is possible.

This could also be fixed by changing the PLP extension code to be more defensive (accommodating of incomplete JSON).

### Your environment
* version (Framework) v5.6.1

### Steps to reproduce
Tell us how to reproduce this issue.

1) create a course using `adapt create course`
2) Import the course into the Authoring Tool
3) Try to run the course

**Comment by moloko** [comment]
> This could also be fixed by changing the PLP extension code to be more defensive (accommodating of incomplete JSON).

I agree and I think we should do this as well

**Comment by olivermartinfoster** [comment]
Could we just do the PLP defensive code and not remove the indicators from the default course?

**Comment by moloko** [comment]
> Could we just do the PLP defensive code and not remove the indicators from the default course?

We should definitely do the defensive code but @simondate has not actually removed the indicators from [the default course](https://adaptlearning.github.io/v5demo/#/id/co-05)

**Comment by simondate** [comment]
As Matt said I made the JSON reflect what is currently in the pre-installed course.

I've never used this PLP functionality myself. I like having it half on and half off to show that there is a choice.

**Comment by oliverfoster** [comment]
Sweat, I misunderstood then. Ta :+1:

**Comment by oliverfoster** [comment]
do the defensive code bit

**Comment by oliverfoster** [comment]
@simondate what was the original error / problem / point of failure?

**Comment by simondate** [comment]
The course wouldn't run when you imported it. There was an error in the developer console that mentioned `_isCompletionIndicatorEnabled`

**Comment by oliverfoster** [comment]
As you can see from this search https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/search?q=_isCompletionIndicatorEnabled&unscoped_q=_isCompletionIndicatorEnabled

https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/blob/master/js/adapt-contrib-pageLevelProgress.js#L76 This is the only place `_isCompletionIndicatorEnabled` is referenced which would never cause and error. I cannot proceed without more info.

**Comment by simondate** [comment]
<img width="1117" alt="explorer_0rgrL1kXW2" src="https://user-images.githubusercontent.com/1676635/88933560-7be88a80-d277-11ea-9be1-c6e7ef1da112.png">
<img width="1280" alt="chrome_cil1nAXnJi" src="https://user-images.githubusercontent.com/1676635/88933577-8145d500-d277-11ea-9049-1c9fbee3a5e2.png">
<img width="1280" alt="chrome_23JrjZmjF5" src="https://user-images.githubusercontent.com/1676635/88933586-83a82f00-d277-11ea-9c63-fbb5d38b0ef8.png">
<img width="1036" alt="chrome_QPCa9ABEpQ" src="https://user-images.githubusercontent.com/1676635/88933589-84d95c00-d277-11ea-96e1-e8c67e248876.png">
Menu loads but error shows
<img width="1036" alt="chrome_6ZymSp1A67" src="https://user-images.githubusercontent.com/1676635/88933590-860a8900-d277-11ea-8c42-e6e6ae3dd2ff.png">

Any page with a component with the missing attribute doesn't load.
