### ISSUE TITLE
adapt_framework: grunt add image compression command

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2866]
### Subject of the issue
Sometimes it's nice to be able to web compress without having to open another tool.

**Comment by moloko** [comment]
Should also help with https://github.com/adaptlearning/adapt_authoring/issues/2435

**Comment by moloko** [comment]
Could we have an option to run this on the src folder's graphics as well? That way you don't have to remember to keep running it every time you do grunt dev/build!

**Comment by moloko** [comment]
note to self: remember to document this command in [GRUNT.md](https://github.com/adaptlearning/adapt_framework/blob/master/GRUNT.md)

**Comment by oliverfoster** [comment]
As agreed on the call:

`grunt compress` should work on `course` folder
`grunt compress --outputdir=` should work on specified folder
