### ISSUE TITLE
adapt-devTools: Question Banks checkbox no longer works

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt_framework#2871]
### Subject of the issue/enhancement/features
In Adapt v5 using Dev Tools v3.0.3, clicking on the Question Banks checkbox throws an error:

`Uncaught (in promise) TypeError: e.ownerDocument is undefined`

### Your environment
* Adapt Framework v5.6.1
* Tested in Mac High Sierra: Firefox 79, Chrome 84

### Steps to reproduce
Set up an assessment with question banks.  Open Dev Tools and uncheck "Question banks".

### Expected behaviour
Page should reload with question banks disabled.

### Actual behaviour
Javascript error

**Comment by swashbuck** [comment]
The assessment code we're using in articles.json:

        "_assessment": {
            "_isEnabled": true,
            "_id": "assessment-1",
            "_isPercentageBased": true,
            "_scoreToPass": 75,
            "_includeInTotalScore": true,
            "_assessmentWeight": 1,
            "_suppressMarking": false,
            "_allowResetIfPassed": false,
            "_banks": {
                "_isEnabled": true,
                "_split": "2,2,1,1,1,1",
                "_randomisation": false
            },
            "_questions": {
                "_resetType": "hard",
                "_canShowFeedback": false,
                "_canShowMarking": false,
                "_canShowModelAnswer": false
            },
            "_isResetOnRevisit": true,
            "_attempts": "infinite"
        },

**Comment by moloko** [comment]
sounds similar to #2870 - as with that, would you mind testing against the current master branch? thx ;-)

**Comment by swashbuck** [comment]
Thanks, @moloko .  Updating the framework to the latest from master fixed the issue.
