### ISSUE TITLE
In Adapt 5.6.1, turning _scrollingContainer":{"_isEnabled":true breaks inview

### ISSUE THREAD

**Issue by robertmausser** [adaptlearning/adapt_framework#2872]
### Subject of the issue/enhancement/features
In Adapt 5.6.1, turning _scrollingContainer":{"_isEnabled":true breaks inview. Inview completion no longer works and the bookmarking/progress menu buttons etc all bring you to the wrong part in the course.

### Your environment
* version 5.6.1
* chrome 84
* Windows 10

### Steps to reproduce
Enable  _scrollingContainer":{"_isEnabled":true 
### Expected behaviour
Simply the top menu nav bar is above the iframe content.

### Actual behaviour
inview completion and anchor tag to components breaks. (you dont get sent to where you are supposed to)

**Comment by oliverfoster** [comment]
Hi Robert, can you confirm, was this master or v5.6.1?

**Comment by robmausser** [comment]
I did "adapt create course" which gave me adapt v5.6.1 as in the package.json file indicates.

So you tell me, I dont know what "adapt create course" does.

**Comment by moloko** [comment]
thanks for the info @robmausser we’ll look into this. might need a bit more info if we can’t replicate 

(btw unless you specify a branch/tag, `adapt create course` defaults to giving you the master branch)

**Comment by oliverfoster** [comment]
@tomgreenfield did you check your amends with _scrollingContainer on?
