### ISSUE TITLE
adapt-contrib-hotgraphic - component does not render on small screens

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#2873]
### Subject of the issue
The hotgraphic component does not render on small screens. I believe this is due to this [PR](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/193) as the latest release of the Hotgraphic component works correctly. 

### Your environment
* FW master, Hotgraphic master
* Chrome 
* MacOSX

### Steps to reproduce
Install the latest release of the FW and use the master branch of the Hotgraphic component. Shrink browser size to below 760px and refresh, Hotgraphic will not render.

**Comment by moloko** [comment]
that's very odd cause I remember checking this before committing the changes in that PR.

I've just tested again (in Firefox and Chrome, Windows) and it works fine for me.

Seeing as it switches out for Narrative on small screens, could it be perhaps that you're not using the latest version of Narrative?

**Comment by moloko** [comment]
Also, are you seeing any errors in the Console?

**Comment by guywillis** [comment]
Error still appears after using the master version of Narrative. 

I used `adapt create course` to download a fresh master version of Adapt and then updated both the Hotgraphic and Narrative to master and retested. Similarly, I have also used the same command to download the v5.6.1 release version of the Framework and tested this with master versions of both components with the same outcome.

This is the error I get in the console:
![Screenshot 2020-08-12 at 09 18 15](https://user-images.githubusercontent.com/11569678/89992675-81819f80-dc7d-11ea-97f8-2a55d94c5ef8.png)

This is the visual output on the page (you'll notice the narrative before and media after where the Hotgraphic (turned Narrative) should display:
![Screenshot 2020-08-12 at 09 18 21](https://user-images.githubusercontent.com/11569678/89992717-965e3300-dc7d-11ea-9256-12e7267b99c4.png)

DOM representation with missing component:
![Screenshot 2020-08-12 at 09 18 32](https://user-images.githubusercontent.com/11569678/89993074-184e5c00-dc7e-11ea-8453-17f4dd0f1468.png)

**Comment by moloko** [comment]
@guywillis I'm a bit stumped TBH as it's still working fine for me:
![image](https://user-images.githubusercontent.com/1249597/90027296-4b114800-dcb0-11ea-901e-98220006d7de.png)

(I'm using the 'devinstall' version of Adapt with everything just updated to the latest master branch and have even deleted and recreated `node_modules` just to be sure.)

**Comment by moloko** [comment]
If it is that PR that's at fault my guess is it's something in the `replaceWithNarrative` function of hotgraphicView.js

Some changes I made to that which might be worth checking:
* amended the lookup for `component__container` so that JQuery doesn't need to search the entire DOM for it
* removed the calls to `newNarrative.reRender()` and `newNarrative.setupNarrative()` as they were already being triggered elsewhere
* instead of triggering `"device:resize"` event then deferring `this.remove` I switched the order so that `this.remove` is called immediately and the `"device:resize"` event trigger is deferred (at the recommendation of @oliverfoster)

**Comment by moloko** [comment]
FYI Unfortunately the console error is of no use, it's just the bookmarking extension erroring because there's a component missing

**Comment by moloko** [comment]
@guywillis apologies, missed the bit in the 'steps to reproduce' where it says '... and refresh'. can replicate now.
