### ISSUE TITLE
Grunt build fails when we provide languages param.

### ISSUE THREAD

**Issue by muthuselvan86** [adaptlearning/adapt_framework#2875]
### Subject of the issue/enhancement/features
grunt build fails when we run with param --languages=en

### Your environment
* Framework. 5.6.1
* Tested on Mac OS

### Steps to reproduce
Build the course using `grunt build --languages=en`

### Expected behaviour
Should build the course with English language package.

### Actual behaviour
It breaks at grunt (schema-defaults) step where it look for course/config.json that isn't copied into build folder yet. I compared it with older version of the framework 4.2 this isn't a problem there. 

### Screenshots (if you can) 
![bug](https://user-images.githubusercontent.com/13156998/89969967-af3afa00-dc25-11ea-8d5a-2c7616dcf8f1.png)

**Comment by oliverfoster** [comment]
This was my fault, apologies. I was unaware of the `languages` flag when I rewrote this code.
