### ISSUE TITLE
Navigation back button - hide on single page course

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2882]
The back button should not be visible on a single page course with no menu.

Perhaps we could add some kind of check [here](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/navigationView.js#L37) that gets passed into the template?

`if( Adapt.startController.get('_isMenuDisabled') && codetochecksinglepage)`

**Comment by oliverfoster** [comment]
Please don't add anything for specific content structures. It should all be structurally agnostic. So either logic to determine if the parent exists and if it has a menu to render otherwise hide the back button, or just a class for hiding the back button etc would be fine.

**Comment by guywillis** [comment]
There is a custom class built into the Vanilla theme that will hide the back button in the navigation bar.

`"_htmlClasses": "hide-nav-back-btn",`

This class can be used in both the Framework and Authoring Tool.
