### ISSUE TITLE
Resource Plugin Accessibility focus issue

### ISSUE THREAD

**Issue by RichKnop** [adaptlearning/adapt_framework#2883]
### Subject of the issue/enhancement/features
Resources plugin tab focus does not stay within the menu when using the keyboard tab - Accessibility issue

### Your environment
v5 Framework
Chrome Version 84.0.4147.125
Windows 10

### Steps to reproduce
Create a new course in Framework
Add the resource extension
Add a item to the resource plugin
Launch the course
Using the tab key, the first tab for the course should be the skip nav link, the 2nd tab should be the resources menu
Click the enter key on the keyboard to open the menu
Tab once again and the next tab should stay within the menu and any further keyboard tabs should stay in the menu until the menu has been closed. 

### Expected behaviour
In the adapt v5 demo course with the resources menu extension, when you open the resource menu you can tab through the options and the tab order stays within the menu. Once open the next tab options is the first option in the menu itself. 

### Actual behaviour
When you add the resource extension to a new course you can tab to the menu, select the icon to open the resource menu and the menu opens. However, the focus or next tab in the order is not within the menu but the next tab on the course page menu itself.

**Comment by oliverfoster** [comment]
I can't replicate.
Have you tried with the latest framework? Which specific subversion are you using?

![resources](https://user-images.githubusercontent.com/7974663/90522430-9a99bd00-e163-11ea-8f1c-b96c06667887.gif)

**Comment by RichKnop** [comment]
In the V5 demo it works perfectly fine.

The issue that I am seeing is when creating a brand new course in Framework, adding the resources extension, adding a link or document to the extension and launching the course, the tab does not stay in the menu.

We are using resources extension version 4.0.0 and the latest version of the the adapt framework.

**Comment by oliverfoster** [comment]
Can you upload a zip of the course folder please?

**Comment by RichKnop** [comment]
[resource-issue-demo-course-export.zip](https://github.com/adaptlearning/adapt_framework/files/5091011/resource-issue-demo-course-export.zip)

Attached is a source export of a new course I just created to replicate the issue.

**Comment by oliverfoster** [comment]
The version of your framework is 5.2.0 the latest is 5.6.1.

Did you turn accessibility on in the config?

**Comment by RichKnop** [comment]
The config accessibility setting fixed the issue. Sorry I overlooked that

Thanks for the help,
Rich
