### ISSUE TITLE
Firefox - Triggering a Notify popup causes sudden page jump

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2886]
Using a fresh v5.6.1 Adapt install, triggering a notify panel causes a sudden jump to the top of the page. This happens with both presentation & question components.

### Your environment
* Adapt Framework - v5.6.1
* **Only present in Mozilla Firefox v79**
* Dell Inspiron + Windows 10

![Screen Shot 2020-08-19 at 15 47 30](https://user-images.githubusercontent.com/7740674/90688016-6b528100-e233-11ea-9ec8-4016a764db09.png)

**Comment by oliverfoster** [comment]
@joe-replin could you try out the above pr please?

**Comment by joe-replin** [comment]
Thank you, @oliverfoster for pushing this as well as for the reference links. I have tested in 2 separate projects and Firefox is not misinterpreting that focus change anymore.

**Comment by oliverfoster** [comment]
Could you accept the changes in the pr? @joe-replin 
Or add a +1 if you don't have access to the "review changes" button on the "files changed" tab.
https://github.com/adaptlearning/adapt_framework/pull/2889/files

**Comment by oliverfoster** [comment]
Will get closed when the pr goes through.
