### ISSUE TITLE
adapt-contrib-matching & adapt-conrib-textInput - unable to submit questions

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt_framework#2887]
Using a fresh v5.6.1 Adapt install, the Text Input and Matching component submit buttons remain in a disabled state even after selecting or inputting answers.

### Your environment
* Adapt Framework - v5.6.1
* All of the following: Mozilla Firefox v79, Chrome v84, Edge & IE
* Dell Inspiron + Windows 10

### Steps to reproduce
Installed Adapt with the 'adapt create course' command. Navigated to co-10 and noticed I was unable to submit answers for both Text Input & Matching components.

![Screen Shot 2020-08-19 at 15 53 34](https://user-images.githubusercontent.com/7740674/90688645-5cb89980-e234-11ea-87d5-333d723ce335.png)

![Screen Shot 2020-08-19 at 15 55 43](https://user-images.githubusercontent.com/7740674/90688712-7528b400-e234-11ea-89b0-5a64e17fcb10.png)

**Comment by joe-replin** [comment]
Just noticed this was already submitted!

**Comment by oliverfoster** [comment]
`adapt create course` irritatingly does fw master and component latest version. So we have it in mind to change it to fw latest and component latest with `adapt devinstall` doing master and master respectively. Sorry for the confusion.
