### ISSUE TITLE
adapt-contrib-languagePicker: triggers error if _restoreStateOnLanguageChange enabled

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2905]
If you have a multilanguage course and are using the option `_restoreStateOnLanguageChange`, when you switch language you either get an error (v5.6.1) - or no error but you end up on the wrong page (v5.7.0)

In Adapt v5.6.1, this is the error that's being triggered:
![image](https://user-images.githubusercontent.com/1249597/92406112-19fd2980-f12f-11ea-817b-5a43364fe722.png)

In v5.7.0, (using the OOTB content) if you change language from the menu, question components or assessment pages, you end up being sent back to the presentation components page - which is presumably why the above error is being triggered: because languagePickerModel expects `'menuView:ready'` to be triggered, but it never is - `'pageView:ready'` gets triggered instead.

**Comment by moloko** [comment]
To fix the v5.6.1 error it looks like [this line](https://github.com/adaptlearning/adapt-contrib-languagePicker/blob/b6866a8a020c8eb346b3209656758872b41c921d/js/languagePickerModel.js#L58) in languagePickerModel needs to be changed to:
```js
if (!Adapt.findById(this.locationId)) return;
```

**Comment by oliverfoster** [comment]
Can change the event listener to `contentObjectView:ready` in v5.7+

**Comment by moloko** [comment]
> Can change the event listener to `contentObjectView:ready` in v5.7+

I'm not sure it's the event that's the problem, it's more why is it trying to send you to the course's first page?

**Comment by moloko** [comment]
For example, in v5.7.0 if i disable the setting `_restoreStateOnLanguageChange` and then change languages I get sent back to presentation components instead of the menu, changing the event listener wouldn't help with that

**Comment by moloko** [comment]
I think it's something to do with the `_start` configuration. even though it's not enabled in the JSON it somehow seems to be getting enabled if I change languages.

**Comment by moloko** [comment]
> In v5.7.0, (using the OOTB content) if you change language from the menu, question components or assessment pages, you end up being sent back to the presentation components page - which is presumably why the above error is being triggered: because languagePickerModel expects `'menuView:ready'` to be triggered, but it never is - `'pageView:ready'` gets triggered instead.

This is a different issue altogether which has only surfaced in v5.7.0 because of [this change](https://github.com/adaptlearning/adapt_framework/pull/2881). It's still possible to replicate this in earlier v5.x releases

Have moved this over to #2907
