### ISSUE TITLE
adapt-contrib-spoor: scorm tracking of course state not working if _shouldStoreResponses: false

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2910]
### Subject of the issue/enhancement/features
The tracking of which blocks are complete/incomplete doesn't appear to be working as it should

### Your environment
* Framework master branch (but also occurs with v5.6.1)/spoor v3.5.0 (also checked master, still has issue)
* Checked in IE11, FF, Chrome
* Not checked devices but don't expect it to be any different

### Steps to reproduce
Use `adapt create course` to set up a fresh install of Adapt. In config.json, set `_spoor._tracking._shouldSubmitScore` to `false`. run `grunt dev` then `grunt server-scorm`. Go into Presentation Components and complete a couple of interactive components. Reload the course.

### Expected behaviour
The components completed prior to the reload should show as completed still

### Actual behaviour
No components show as completed.

### Additional info
The 'completion string' that is output to the console is correct BUT the value of `"c"` in the suspend_data never changes from its initial value of `"hAA"`, which doesn't seem anything close to being correct:
![image](https://user-images.githubusercontent.com/1249597/92953774-344e4480-f45a-11ea-8734-89f8ce05bfc8.png)

**Comment by oliverfoster** [comment]
I forgot to mention. I removed that behaviour.

**Comment by moloko** [comment]
errr... really?

**Comment by oliverfoster** [comment]
Yeas.... Slight oversight. Pretty easy to add back in. I was concentrating on the component stuff. 

As a side note and so I don't do this again. Do we use block only completion regularly? Or are we using shouldStoreResponses almost always now? I'm not sure I understand the use-case.

**Comment by moloko** [comment]
From my point of view I do tend to enable `_shouldStoreResponses` only when I think it's actually needed, typically where the course contains an assessment esp. when there's a need to limit the number of attempts at that assessment. I might be being over-cautious here, but it's generally on the principle of avoiding 'something that could potentially go wrong & cause bugs'.

Another use-case for turning this setting off would be if one needed to free up space in suspend_data for some other reason, say, creating a VERY lengthy course or having other data to store in there which takes up a lot of space.

I'm not against dropping support for it but that would of course be a breaking change.

I'm curious about the value of `c` in the suspend_data, it doesn't seem to get updated...

**Comment by oliverfoster** [comment]
Cool. I'll get a pr sorted for just component completion when responses is off. I want to move away from having completion restored in any layer but the component level.

c is now just course and assessment completion booleans. C for completion.
