### ISSUE TITLE
adapt-contrib-trickle - error in IE11 when course rendered in iframe

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#2918]
### Subject of the issue/enhancement/features
Trickle breaks in IE11 when course is rendered within an iframe

### Your environment
* v5
* IE11 within an iframe

### Steps to reproduce
Create a couse that uses trickle buttons on each block
View course within an iframe in IE11

### Actual behaviour
First button displays fine and works
Second button appears but console displays the error as shown below and clicking the button does nothing

### Screenshots
![Screenshot 2020-09-21 120412](https://user-images.githubusercontent.com/19267399/93759715-a5cc8680-fc02-11ea-9179-8336c4d2ea20.png)

**Comment by moloko** [comment]
Just to note I've seen this too on a course running in Saba (which uses an `<iframe>`). 

As it didn't require accessibility support (and needed fixing quickly), I just commented out the code in question.

**Comment by danielstorey** [comment]
👍 and thanks for changing the title to something a bit more helpful!
