### ISSUE TITLE
MCQ - correct answer button not enabled on page revisit

### ISSUE THREAD

**Issue by zarek3333** [adaptlearning/adapt_framework#2920]
### Subject of the issue/enhancement/features
When I choose my answer in a MCQ component, Submit it and then get it incorrect. I can click the "Correct answer" button. When I leave the page or go to the menu and come back. The "Correct answer" button is disabled. I am thinking this has something to do with the new change on Submit buttons being disabled before sumbitting.

### Your environment
Authoring Tool 0.10.4 / Framework 5.7.0
Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Windows 10

### Steps to reproduce
On MCQ get submit with an incorrect final, leave the page and come back the "Correct answer" button will be disabled?

### Expected behaviour
Button shouldn't be disabled for users as they may still want to see there answer on returning back to the page.

### Actual behaviour
"Correct answer" button is disabled when returning to page.

### Screenshots (if you can)
![Mcq-issue](https://user-images.githubusercontent.com/53020396/93819390-a4fb1b00-fc29-11ea-9745-72b8ffb83726.png)

**Comment by tomgreenfield** [comment]
In my tests it appears more broken – I return to an enabled submit button (and clicking it just removes the red circle):

![submit](https://user-images.githubusercontent.com/922987/93859500-98bc9f80-fcb5-11ea-9e06-1ea8237faf4d.png)

Authoring tool 0.10.4
Framework 5.7
MCQ 4

**Comment by moloko** [comment]
Weirdly, this is working fine for me using the FW directly. Initially I thought it might be because I was using the FW 'master' branch but I've just checked again using the v5.7.0 release and it's still working fine. Tested in FF (80.0.1), Chrome (85.0.4183.102 and 85.0.4183.121) and IE11.

**Comment by zarek3333** [comment]
Thanks guys for looking into this one...
Works fine for me too in the FW. Just not behaving as it should in the authoring tool?

**Comment by tomgreenfield** [comment]
@zarek3333, after investigation it seems the issue was caused by a cached preview; performing a force rebuild resolved it for me.
