### ISSUE TITLE
adapt-contrib-matching: correct answer button disabled in 'resumed' SCORM

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2922]
### Subject of the issue/enhancement/features
Similar to the problem reported in #2920 the 'correct answer' button in matching components is disabled when the course is 'resumed' from the LMS (and `_shouldStoreResponses` is enabled)

### Your environment
* FW master branch/matching v4.1.0/spoor issue/2910 branch
* Checked in Chrome and FF, assume is common to all browsers
* Win 10

### Steps to reproduce
* run `adapt create course issue-2922` then `cd issue-2922 && grunt build && grunt server-scorm`.
* go into question components page and answer all questions incorrectly
* return to main then back into page, note how all 'correct answer' buttons are enabled
* reload page, select 'yes' in bookmark prompt.

### Expected behaviour
The correct answer button for all question components on the page should be enabled - _except_ for textInput (which doesn't support storing user answer between sessions) 

### Actual behaviour
The correct answer button on the matching component isn't enabled

### Screenshots (if you can)
![image](https://user-images.githubusercontent.com/1249597/94027187-7ceaf380-fdb2-11ea-91e2-3a8a74d9b25a.png)

**Comment by moloko** [comment]
I believe this is something to do with when the `checkCanSubmit` function is being called by MatchingModel - in that it's being called too early. If I manually run it after the page has rendered, the Correct Answer button switches to being enabled and works perfectly when selected.

Will investigate more tomorrow.

**Comment by zarek3333** [comment]
Hi I was just testing out the text input component and it has the same issue as MCQ and Matching with the "Correct Answer" button being disabled on re-entry of the page. 

Interesting though I tested the slider component too with this issue and it works as it should. On re-entry of the page I can click the "Correct Answer" button as it is active. Not sure if that helps though towards this issue and sounds like you may of cracked it.
