### ISSUE TITLE
adapt-contrib-trickle: "scroll" is unused value for "_styleAfterClick"

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2924]
### Subject of the issue
In README, properties.schema, and example.json, "scroll" appears as an option for "_styleAfterClick". However, I can't find any code that references the "scroll" value of "_styleAfterClick". [handlers/buttonView.js ln 271](https://github.com/adaptlearning/adapt-contrib-trickle/blob/fe0540834c61b15d5ba934c8977a7bc636381b49/js/handlers/buttonView.js#L271) has a switch that tests "hidden" and "disabled" but not "scroll".

Seems references to "scroll" in these three files should be deleted (unless plans are in the works for new behaviour?)

### Your environment
* FW 2+
* Trickle v2+

**Comment by oliverfoster** [comment]
new trickle has disabled, visible and hidden
