### ISSUE TITLE
adapt-contrib-trickle: replace "disabled" with "visible" for "_styleAfterClick"

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#2925]
### Subject of the issue/enhancement/features
(Trickle code/documentation originally specified three values for "_styleAfterClick": "hidden", "disabled", and "scroll". In #2924 I'm proposing that "scroll" be deleted since it is not referenced by code.)

To reduce confusion, I am proposing that the option "disabled" be replaced/renamed "visible".

The word "disabled" is misleading. It does not describe the behaviour. "_styleAfterClick": "disabled" causes the Trickle button to remain visible after it has been clicked. CSS classes for disabled elements are not applied to it. If the button has "_autoScroll" enabled, it retains the scroll functionality; it is not disabled.

[properties.schema](https://github.com/chucklorenz/adapt-contrib-trickle/blob/fe0540834c61b15d5ba934c8977a7bc636381b49/properties.schema#L119) interprets "_styleAfterClick" to be all about visibility, as it does "_styleBeforeCompletion". By changing "disabled" to "visible", the same two options--"hidden" and "visible"--will be used for both "_styleBeforeCompletion" and "_styleAfterClick". 

### Your environment
FW v2+
Trickle v2+

**Comment by oliverfoster** [comment]
superseded by #2890
