### ISSUE TITLE
Global to Adapt plugins: Placeholder image alt text

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2939]
### Subject of the issue
Do we need to include placeholder alt text in _example.json_ files? I often find this doesn't get removed from courses unless it's being replaced. 

```
              "_graphic": {
                  "src": "course/en/images/example.jpg",
                  "alt": "Placeholder graphic",
                  "attribution": "Copyright © 2019"
              }
```

When an alt attribute is left empty the image is ignored and I think this would be a more suitable default. It's more of a nuisance to include alt text when not needed never mind placeholder text. In most use cases, an image is decorative or content is already covered by the display text.

I would suggest a __comment_ attribute in the _example.json_ or improve the description in the _README_ (e.g. What alt text is and when to use it.)

Plus, we wouldn't need to include 'graphic' in image alt text so we're setting a bad example.

### Plugins this relates to
Accordion https://github.com/adaptlearning/adapt-contrib-accordion/blob/master/example.json
GMCQ https://github.com/adaptlearning/adapt-contrib-gmcq/blob/master/example.json
Graphic https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/example.json
Hotgraphic https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/example.json
Narrative https://github.com/adaptlearning/adapt-contrib-narrative/blob/master/example.json
Boxmenu https://github.com/adaptlearning/adapt-contrib-boxmenu/blob/master/example.json

**Comment by oliverfoster** [comment]
Yes

**Comment by kirsty-hames** [comment]
Graphic PR https://github.com/adaptlearning/adapt-contrib-graphic/pull/78
