### ISSUE TITLE
adapt-contrib-boxMenu: do not release

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2940]
### Subject of the issue
After [this commit](https://github.com/adaptlearning/adapt_framework/commit/c36300cb486e68ae727886488f7a03f3821e3761) boxMenu master won't work due to a change in the `childViews` property.
[This line](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/master/js/adapt-contrib-boxMenu.js#L27) will throw an error that the property is read only.

**Comment by moloko** [comment]
@oliverfoster just to check it is now OK to release boxMenu?

**Comment by oliverfoster** [comment]
Yup it is indeed.
