### ISSUE TITLE
adapt-contrib-spoor: the new error system throws a JavaScript error

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2945]
Using Adapt v5.7.1 and the master branch of spoor, build and run the course using index_lms.html so that it triggers a 'could not connect to LMS error'.

The error handler (the irony!) throws the following error:
![image](https://user-images.githubusercontent.com/1249597/96167918-f3919180-0f17-11eb-8294-cadde8d0720f.png)

There's a few other issues/changes need as well but since this hasn't been released yet I won't bother listing them all here, I'll just fix them in the PR to fix the above (which I'll put together tomorrow).

**Comment by oliverfoster** [comment]
Thanks
