### ISSUE TITLE
Narrative component not working on iOS when Accessibility is enabled

### ISSUE THREAD

**Issue by onclick-mark** [adaptlearning/adapt_framework#2956]
### Subject of the issue/enhancement/features
On mobile devices using Chrome browser, the Narrative tool doesnt work properly. After clicking the first arrow, the 2nd label/button label skips straight to the third and is not clickable until you reach the last label and then scroll back. After extenside testing, I've worked out this only happens when the Accessibility tickbox is enabled via the course Configuration page.

### Your environment
* version FW 5.7.1 / AT 0.10.4
* Google Chrome 86.0.4240.93
* iPhone 11 pro . software 14.0.1

### Steps to reproduce
When Accessibility is enabled and a narrative component is produce, the narrayive tool on Mobile devices using the Chrome browser skips from the 1st slide to the 3rd button but the image below doesnt skip. The button is then not selectable until you skip forward to the last item on the narrative.

###Example for testing
[Test Preview](https://www.onclick.co.uk/preview/wast/test11/#/id/5f8ee5b1cebb546452753884)

**Comment by oliverfoster** [comment]
> When Accessibility is enabled and a narrative component is produce, the narrayive tool on Mobile devices using the Chrome browser skips from the 1st slide to the 3rd button but the image below doesnt skip. The button is then not selectable until you skip forward to the last item on the narrative.

Does this happen when you click the right button?

**Comment by oliverfoster** [comment]
Can you try rebuilding the course with:
```js
this. onNavigationClicked = _.debounce(this.onNavigationClicked.bind(this), 100);
```

At line 19, here https://github.com/adaptlearning/adapt-contrib-narrative/blob/master/js/narrativeView.js#L19

There is a similar issue, here https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/js/hotgraphicPopupView.js#L21

**Comment by onclick-mark** [comment]
Thanks. Have tried the above and it doesn't seem to have fixed the issue. I may have be premature with stting it as only a Chrome issue, just exported another course and the issue is appearing in other browsers such as Safari also.

[Narrative example](https://www.onclick.co.uk/preview/brook/tlt_elearning_03/#/id/5f7f365dfb2ae3035ec55d50)

**Comment by moloko** [comment]
Just to mention that I can replicate this using the link provided by @onclick-mark, in Safari for iOS v14.0.1 - but not in the 'OOTB' v5.7.1 course. It's a bit of a mystery.

There's some further detail on [the original forum post for this](https://community.adaptlearning.org/mod/forum/discuss.php?d=3946).

@onclick-mark Chrome for iOS is actually really just Safari with a different interface. Apple still doesn't allow any browser rendering engine other than Webkit.

**Comment by oliverfoster** [comment]
The only really intrusive bits of behaviour that would get turned off when with accessibility that I can think might have impact are `_isFocusNextOnDisabled` and `_isFocusOnClickEnabled`. Might be worth turning both of those off and trying again?

**Comment by onclick-mark** [comment]
Just to clarify, I'm using the AT to build the course - how do I go about doing the above?

**Comment by moloko** [comment]
@onclick-mark in the configuration settings for your course, under Accessibility:
![image](https://user-images.githubusercontent.com/1249597/97575679-065e9880-19e5-11eb-9b6d-c21eb263d3fe.png)

**Comment by moloko** [comment]
@onclick-mark if you get a chance could you check to see if Narrative v6.2.1. resolves this issue for you?
