### ISSUE TITLE
can we remove the 'old CSS location' stuff from scriptLoader.js?

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2957]
I think we might be able to drop this stuff in the next version?

https://github.com/adaptlearning/adapt_framework/blob/bb5e71e1c5a7c0e0770e0c3b2738445a10d99b6e/src/core/required/adapt/js/scriptLoader.js#L4-L40

**Comment by oliverfoster** [comment]
Absolutely.
