### ISSUE TITLE
adapt-contrib-hotgraphic: popup images without 'alt' aren't being hidden 

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2968]
When inspecting the popup images I've found that `aria-hidden="true"` is applied initially but then stripped out when that item is the current item in view.

To replicate, inspect an item graphic and then cycle through the item pagination to see the attribute being added and removed.

Issue reported running JAWS in Chrome as without `aria-hidden="true"`, the image filename is read. The issue is global however and I think it's related to the recent a11y api updates ​https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/f1787079c4fa796df0ab8ba58544e479b5926c5a

**Comment by moloko** [comment]
looks to me like it may be the selector hotgraphicPopupView's [handleTabs function](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/f8ad7a35b32ca011802fa6d4a9fc9e44b78313f5/js/hotgraphicPopupView.js#L61-L64) being a bit _too_ wide in scope

**Comment by moloko** [comment]
Possibly as simple as just changing it to:
```js
handleTabs() {
  Adapt.a11y.toggleHidden(this.$('.hotgraphic-popup__item:not(.is-active)'), true);
  Adapt.a11y.toggleHidden(this.$('.hotgraphic-popup__item.is-active'), false);
}
```
??

**Comment by kirsty-hames** [comment]
I can confirm @moloko's suggestion resolves the issue thanks.
