### ISSUE TITLE
adapt-contrib-assessment v4.2.0 - throwing error when trying to reset multiple assessments

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2971]
### Subject of the issue
I'm updating a 'role selector' feature for v5 compatibility and, whilst re-testing to make sure it still works, I noticed that when it tries to reset the assessments in a course with more than one assessment, the reset code triggers a JavaScript error (see screenshot below). 

After some investigation I have figured out that this is only occurring if v4.2.0 of the assessment extension is used - it works fine with previous versions.

### Your environment
* FW v5.7.1, adapt-contrib-assessment v4.2.0
* seems to be any browser, certainly occurs in IE11, FF & Chrome

### Steps to reproduce
Use `adapt create course` to set up a new, OOTB Adapt course. Create a 4th content object and set up an assessment in it. Build and run. From the console, execute the following code:
```js
require('core/js/adapt').assessment._assessments.forEach(assessmentArticle => {
  assessmentArticle.reset(true);
});
```

### Expected behaviour
Using earlier versions of the assessment extension, both assessments would reset.

### Actual behaviour
The error shown below is thrown. Error is occurring on [this line](https://github.com/adaptlearning/adapt-contrib-assessment/blob/659f0e9f827e4e3b31df37947601588776297e70/js/adapt-assessmentArticleModel.js#L669)

### Screenshots (if you can)
![assessment-error](https://user-images.githubusercontent.com/1249597/98841836-94546d80-2440-11eb-8584-b92dcae72f4c.png)

**Comment by moloko** [comment]
Additional note - the error only seems to occur when BOTH assessments have 'question banks' enabled...

**Comment by oliverfoster** [comment]
This problem should exist in the previous versions as the changes between versions don't touch the relevant code https://github.com/adaptlearning/adapt-contrib-assessment/compare/v4.0.0...v4.1.0

It seems that resetting an assessment causes a [global "save state" for all assessments](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L171) and that saving the state relies on the [`_questions` attribute](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L669). An assessment configures its `_questions` attribute [on reset](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L169), [on question complete](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L301) and [on assessment complete](https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L335) meaning that the first assessment is trying to save the state of an as yet not reset second assessment.
The solution is to setup the `_questions` attribute early in order for the save state to be possible on an assessment not yet reset.

Solution: 
Add `this._updateQuestionsState();` to https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L80 .

**Comment by moloko** [comment]
> This problem should exist in the previous versions as the changes between versions don't touch the relevant code [adaptlearning/adapt-contrib-assessment@v4.0.0...v4.1.0](https://github.com/adaptlearning/adapt-contrib-assessment/compare/v4.0.0...v4.1.0)

My bad - put the wrong assessment version in the ticket title. Bug actually occurs with v4.2.0, not v4.1.0. Will amend.

**Comment by danielghost** [comment]
Can confirm this fixes the issue. If there is more than 1 assessment in a course and the assessment not currently being loaded contains banking, the issue occurs.

**Comment by moloko** [comment]
@danielghost thanks for confirming. would you mind adding a +1 comment to [the PR](https://github.com/adaptlearning/adapt-contrib-assessment/pull/126)?
