### ISSUE TITLE
adapt-contrib-spoor: offlineStorage handler doesn't actually 'save' when save() is called

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2972]
If you look at the implementation ([here](https://github.com/adaptlearning/adapt-contrib-spoor/blob/f586d1d12afa00e85193c5d3a917a0a9aba0978b/js/adapt-offlineStorage-scorm.js#L22-L24)  and [here](https://github.com/adaptlearning/adapt-contrib-spoor/blob/f586d1d12afa00e85193c5d3a917a0a9aba0978b/js/adapt-stateful-session.js#L138-L150)) you'll notice it really only serializes the data and writes it to the SCORM API - the data won't be saved to the LMS until something else triggers `LMSCommit`

To my mind, calling `Adapt.offlineStorage.save()` should also trigger an `LMSCommit` call so that it does save the data back to the LMS.

Suggest modifying the `save` method of adapt-offlineStorage-scorm.js to include `this.scorm.commit()`, like this:
```js
save() {
  this.statefulSession.saveSessionState();
  this.scorm.commit();
}
```

What do people think?

**Comment by oliverfoster** [comment]
Agree.
