### ISSUE TITLE
Narrative IPhone 8 strapline button issue

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3013]
### Subject of the issue/enhancement/features
Description of issue:
Customer has reported that When testing two modules) on an Iphone 8. She is having issues with the narrative and hot graphic components - when trying to tap the + to expand the text it is greyed out and on some of them the + to expand disappears completely.

This only happens after the first narrative/graphic and is only happening when I do the modules on an Iphone 8, XS, 11 and 12. It's happening on all of them. I've tried on a number of Android and It's not happening. It's an iPhone specific problem.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)
iPhone 8 IOS
### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen
You should be able to see the narrative strapline button.

### Actual behaviour
Tell us what happens instead
On an Iphone 8, I am having issues with the narrative and hot graphic components - when trying to tap the + to expand the text it is greyed out and on some of them the + to expand disappears completely.
This only happens after the first narrative/graphic and is only happening when I do the modules on an Iphone 8. 
### Screenshots (if you can)
[Narrative and Hot Graphic component issues Iphone 8.pptx](https://github.com/adaptlearning/adapt_framework/files/5797001/Narrative.and.Hot.Graphic.component.issues.Iphone.8.pptx)

**Comment by eleanor-heath** [comment]
<img width="413" alt="ADAPT-7825 - narrative strapline issue on mobile" src="https://user-images.githubusercontent.com/61159216/104214058-e90b6900-542e-11eb-85e1-c37eb64b9e47.png">

**Comment by moloko** [comment]
similar to #2956 ?

**Comment by eleanor-heath** [comment]
@moloko  yes that is the exact issue.

**Comment by eleanor-heath** [comment]
@moloko I have a PR linked to this ticket if you could have a look please.
