### ISSUE TITLE
Cannot add videos as resources

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#3020]
### Subject of the issue/enhancement/features
You cannot add a video as a resource in the authoring tool.

Problem commit: https://github.com/adaptlearning/adapt-contrib-resources/commit/5194c74c163b6585a95eebb61cdaf49b6fd2e4a3.

### Your environment
* Framework 4.5
* Resources 3.0.2
* Authoring tool 0.10.5

### Steps to reproduce
Attempt to set an MP4 asset as the link in a resource item.

### Expected behaviour
All available assets should be selectable.

### Actual behaviour
Assets are filtered to only show 'documents'.

**Comment by moloko** [comment]
reopening as still needs a v5 FW compatible release
