### ISSUE TITLE
Sort out plugin assets and how they compile into the build

### ISSUE THREAD

**Issue by darylhedley** [adaptlearning/adapt_framework#304]
- Plugins like spoor and media have assets and sometime might need grunt files run.
- Needs some research on best approach

**Comment by taylortom** [comment]
@hrajotia I'm not really sure what this was addressing; has this now been fixed?

**Comment by oliverfoster** [comment]
not really. sounds like we need to the main gruntfile.js to run sub gruntfiles on extensions etc if they exist.

**Comment by hrajotia** [comment]
Current build structure is like this -
- Component's , Extension's, Menu's assets goes into `build/assets/`
- Theme's assets goes into `build/adapt/css/assets/`

but there are special case for extension as in general there may be situations, like [adapt-contrib-spoor/required/](http://github.com/adaptlearning/adapt-contrib-spoor/tree/master/required), when extension may contain some file which they wants to position by there folder structure.

So according to @oliverfoster comment http://github.com/adaptlearning/adapt_framework/pull/496#issuecomment-69165804 , we should amend a folder, may be named as `required`, which should present on each extension folder and whose content goes into build folder by there folder structure.

**Comment by oliverfoster** [comment]
i feel that this should be almost identical to the new proposal for 'assets' but in the root of the build folder instead. something similar to https://github.com/adaptlearning/adapt_framework/pull/497#issuecomment-69908871

**Comment by taylortom** [comment]
This has been fixed.
