### ISSUE TITLE
adapt-contrib-assessment: Scroll to assessment on reset

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3054]
### Subject of the issue
The current assessment reset behaviour leaves user at the top of the assessment page. It would be useful to be able to scroll to the assessment automatically.

**Comment by moloko** [comment]
I think that was (partly) the intention of the `_routeToAssessment` setting in the assessment results component (see [v2.4.0](https://github.com/adaptlearning/adapt-contrib-assessmentResults/releases/tag/v2.4.0)) - might be worth bearing that in mind

**Comment by oliverfoster** [comment]
I knew I knew we did this before...

**Comment by moloko** [comment]
yes i think it probably makes more sense for it to be handled on the assessment
