### ISSUE TITLE
Media component tabbing issue

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3055]
### Subject of the issue/enhancement/features
When using the tab key to navigate to a media component containing an audio file, and then continue past it, the media controls disappear.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)
All

### Steps to reproduce
Create a course with an mp3 link and a poster link. Tab through the elements on the screen and tab past the media controls.

### Expected behaviour
The media controls should not disappear when you tab away from the controls.

### Actual behaviour
When using the tab key to navigate to a media component containing an audio file, and then continue past it, the media controls disappear.

### Screenshots (if you can)
Media controls appearing when tabbing:

![ADAPT-7912 - media controls before tabbing](https://user-images.githubusercontent.com/61159216/110356952-ad59dd80-8032-11eb-9010-b5e76a99cbc4.png)

Media controls missing and gap below the media element appearing after tabbing past the controls:
![ADAPT-7912 - media controls missing](https://user-images.githubusercontent.com/61159216/110357079-d11d2380-8032-11eb-91af-2fa4bd00c190.png)

**Comment by moloko** [comment]
does this happen in a specific browser?

**Comment by tomgreenfield** [comment]
Have you tried setting `"_playerOptions": { "alwaysShowControls": true }`?

**Comment by moloko** [comment]
Works for me if `alwaysShowControls` is enabled. I think we need to force that setting on whenever the media component is being used as an audio player.

**Comment by eleanor-heath** [comment]
Yes it works for me too, ok I will amend the PR to force this setting.
