### ISSUE TITLE
Screen readers reads out blank issue

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3057]
### Subject of the issue/enhancement/features
Description
When using a screen reader to navigate through adapt content, there is an area in the top left hand corner that a user can reach by going to the end of the page or by going to the end of the menu. However, once this area is focused it just read out blank with no clear indication of that it is. Pressing down should bring us back through the menu page but it just gets stuck on this button.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)
All

### Steps to reproduce
Tell us how to reproduce this issue.

1. Create a course
2. Add a page
3. Add a text component
4. Save and Preview
5. Enable a screen reader
6. Once screen reader is active, press down to navigate through the page
7. Once you reach the menu item, keep pressing down and you will see focus going to the top left and it will read out blank.
8. Pressing down keeps the focus on this area continually.

### Expected behaviour
Tell us what should happen

Area that is focused should have some aria text that gets read out and pressing down should allow us to continue navigating the page/menu

### Actual behaviour
Reads out blank and will not progress further

**Comment by moloko** [comment]
could you use `document.activeElement` to identify which element this is?

**Comment by eleanor-heath** [comment]
it is caused by the _addFocuserDiv that is a part of the a11y.js on line 110 I believe

**Comment by moloko** [comment]
and just to check - what FW version?
