### ISSUE TITLE
Buttons labels: where possible the label should explain what action will be taken on click

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#3059]
For example, the button in question components that shows the correct answer is, by default, set to 'Correct answer' - it would be clearer if this were labelled 'Show correct answer'.

There may be other instances, I'll have a check

**Comment by oliverfoster** [comment]
`Resume` `Got to Menu`

**Comment by moloko** [comment]
I'm probably making the whole thing a bigger issue than it really is

**Comment by oliverfoster** [comment]
If there's an issue with `Resume` then we need to change the whole dialog text.

`Go to start`

**Comment by moloko** [comment]
Yeah, originally it said 'Bookmarking' but translators kept translating that as being equivalent to 'add to favourites'...!

Honestly I think I'm worrying about a non-existent problem here, let's just leave it as is

**Comment by moloko** [comment]
oops forgot to update course.model.schema to match....
