### ISSUE TITLE
'exception thrown but not caught' error in IE11 whenever clicking on the page

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#3064]
### Subject of the issue/enhancement/features
Whenever I click (anywhere) on the page in Adapt, IE11logs an 'Except thrown and not caught' error in the console:
![image](https://user-images.githubusercontent.com/1249597/110655916-647f6180-81b7-11eb-809b-d5f4bd02c2a6.png)

### Your environment
* FW (v5.11.0)
* IE11
* Windows 10

It doesn't appear to be causing any obvious problem. But I can't see anything obvious in wait.js that might be causing this.

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/110658995-11f37480-81ba-11eb-94f8-0de9e1e3ff51.png)
![image](https://user-images.githubusercontent.com/7974663/110659016-17e95580-81ba-11eb-8344-5797c5f713b7.png)
