### ISSUE TITLE
Narrative mobile instruction highlighting

### ISSUE THREAD

**Issue by 5amm** [adaptlearning/adapt_framework#3070]
### Subject of the enhancement
Inspired by the instruction highlighting in previous versions of the MCQ component. I've experienced users sometimes being unsure how to complete mobile Narrative / Hot Graphic items. It's not always clear to users they need to click on an item's strapline before the arrow in order to complete that item

I've implemented what I believe to be suitable changes [here](https://github.com/5amm/adapt-contrib-narrative/commit/ad939e05aa3a53ac1196b724f5e9504722e4cd78) and can open a PR if others are in agreement.

The changes I've made also assume the class and variable `.interaction-error` and `@interaction-error` are available in the theme so they can be added to `.narrative__instruction-inner`. These changes have also been made [here](https://github.com/5amm/adapt-contrib-vanilla/commit/4f2900fba52a7e83cf973530ca53b25c796e2b61).

### Versions
* FW v5.11.0
* Narrative v6.2.2

### Screenshots
![Narrative mobile instruction highlighting](https://user-images.githubusercontent.com/72963894/110841873-57896d80-829e-11eb-9e6f-a37e1ee6c007.png)

**Comment by moloko** [comment]
Yeah I really like this. I've added a couple of suggestion to your commit.

(I won't comment on the .less changes as that's not my area of expertise)
