### ISSUE TITLE
Correct order of interaction in Narrative mobile instruction

### ISSUE THREAD

**Issue by 5amm** [adaptlearning/adapt_framework#3077]
### Subject of the issue
The Narrative / Hot Graphic mobile instruction in the example FW course doesn't seem quite right in terms of the order of interaction required to progress as expected through the component's items (i.e. strapline > arrow > strapline > arrow). 

My proposed change can be found [here](https://github.com/5amm/adapt_framework/commit/346c7309f4ede109dd675d135c3f6e4fdc06becd) and below:
```
 "mobileInstruction": "Select the plus icons followed by the next and back arrows to find out more."
```

**Comment by moloko** [comment]
Yes, now you mention it, it's not brilliant. I also notice that the 'out of the box' course doesn't have mobile instruction for the hot graphic component. I think it could be simplified to "Select the plus icon followed by the next arrow to find out more".
