### ISSUE TITLE
all core plugins: default instruction text (properties.schema and example.json)

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#3078]
Currently it seems few - if any - of the core plugins have default instruction text set in properties.schema. 

This means that course authors have to create this manually every time they set up a component.

It would be far better if we could provide a sensible default for each (based on the default component configuration). Esp. given that course authors may not necessarily be familiar with the way the component works or be experienced in writing instruction text.

It would also be a good opportunity to review the instruction text set in example.json which is often:
- missing completely
- wildly inaccurate (the narrative instruction says to swipe the images on mobile!)
- poorly written

In some cases - e.g. MCQ - it'll be a little challenging to write generic instruction text but should be possible - and I still feel would be better than nothing at all.

**Comment by moloko** [comment]
## Presentation components

### Accordion
#### default course
Select the headings to find out more.
#### example.json
Select the headings below to reveal the text.
#### schema
Not set

### Narrative (desktop) 
#### default course
Select the next and back arrows to find out more.
#### example.json
Select the forward arrows to move through the narrative on a desktop, or swipe the images and select the plus icons to do so on mobile.
#### schema
Not set

### Narrative (mobile) 
#### default course
Select the plus icon followed by the next arrow to find out more.
#### example.json
This is optional instruction text that will be shown when viewed on mobile.
#### schema
Not set

### Hot Graphic (desktop) 
#### default course
Select the icons to find out more.
#### example.json
Select the hotspots on the image to reveal the text. This component will scale down to a narrative when viewed on mobile.
#### schema
Not set

### Hot Graphic (mobile) 
#### default course
Select the plus icon followed by the next arrow to find out more.
#### example.json
This is optional instruction text that will be shown when viewed on mobile.
#### schema
Not set

### Media
#### default course
Select the play button to start the video.
#### example.json
Select the play button to start the video.
#### schema
Not set

**Comment by moloko** [comment]
## Question components

### MCQ
#### default course
Choose one option and select Submit. / Choose one or more options and select Submit.
#### example.json
not set
#### schema
not set

### GMCQ
#### default course
Choose option 2 and select Submit.
#### example.json
not set
#### schema
not set

### Matching
#### default course
Choose an option from each dropdown list and select Submit.
#### example.json
not set
#### schema
not set

### Slider
#### default course
Drag the slider to make your choice and select Submit.
#### example.json
not set
#### schema
not set

### Text Input
#### default course
Input your answer and select Submit.
#### example.json
not set
#### schema
not set

**Comment by tomgreenfield** [comment]
Can we hold fire on the schema part of this request for the moment? We're in the midst of schema changes for the authoring tool and also quite possibly https://github.com/adaptlearning/adapt_framework/issues/1743. It might be easier just to add it to the new JSON schema once live and confirmed.

**Comment by moloko** [comment]
For sure! I think first we need to sort out what the right default instruction text should be anyway. Be easier to do that here than in several different PRs

**Comment by 5amm** [comment]
Happy to pitch some ideas for default instruction text. For MCQ we usually use:
> Click or touch[/tap] to make your selection, then submit your answer.

**Comment by moloko** [comment]
> > Click or touch[/tap] to make your selection, then submit your answer.

We normally favour 'select' as the best alternative to click/touch... but obviously 'Select to make your selection' doesn't really work!

We might be able to do something clever with handlebars conditions to change the instruction text dynamically, e.g.
```hbs
Choose {{#if _isRadio}}one option{{else}}one or more options{{/if}} and select Submit.
```

**Comment by chris-steele** [comment]
Default instructions have been provided and PRs raised for the listed plugins.
