### ISSUE TITLE
adapt_framework: v5.12.0 references node_modules directly

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3080]
### Subject of the issue
Creating a separate inclusion pathway for react libraries from the standard `core/libraries` one, was a mistake. It has had some tooling issues across the community, from the AAT rewrite to clients to rub-cli.

Should revert to loading the react libraries through the standard libraries folder.

**Comment by moloko** [comment]
also causes https://github.com/cgkineo/adapt-devtools/issues/53
