### ISSUE TITLE
adapt-contrib-graphic: Add scrollable option

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#3091]
It would be a useful addition to the graphic component to include a setting to enable displaying wide images with a scrollbar  (such as an electrocardiogram). This is especially useful for medical related e-Learning but could also prove useful for other uses  e.g timelines.

I envisage this as the addition of a setting to enable/disable horizontal scrolling. (vertical and horizontal scrolling may be useful in some circumstances)

![image](https://user-images.githubusercontent.com/10856676/111776190-9bd1ca80-88a9-11eb-99a4-f8862b92a9de.png)

Currently using custom CSS to achieve this:

.graphic__image-container {
    height: 100%;
    overflow: auto;
    overflow-y: hidden;
    white-space: nowrap;    
}

.graphic__image-container img {
    width: unset;
}
.graphic__image-container img, object, embed {
    max-width: unset;
}

.graphic__image-container img:not([width]) {
    width: unset;
}

**Comment by paul-mediakitchen** [comment]
I have realised with my CSS solution, I am not able to scroll the image with my keyboard as the graphic component is not accessible. Hmm that puts a spanner in the works....

**Comment by oliverfoster** [comment]
bump @guywillis

**Comment by paul-mediakitchen** [comment]
@guywillis - I can take this off your hands if you want? I created a component a few months ago for this so just needs a bit of spit and polish by me. No worries if you have already started this - I am sure your solution will be better :)

**Comment by oliverfoster** [comment]
@paul-mediakitchen Guy is pretty busy up and through Christmas, but he made significant progress in the discovery phase on this one. I believe the final hurdle is finding and implementing well supported keyboard accessibility for the horizontal scrolling.

**Comment by guywillis** [comment]
Couldn't have said it better myself, @oliverfoster
