### ISSUE TITLE
adapt-contrib-trickle

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#3093]
### Subject of the issue/enhancement/features
If more than one notify popup is open at the same time, trickle does not unlock the hidden content. The button is unlocked (if enabled) but the content is not revealed.

Currently `Adapt.trigger("trickle:overlay");` and ` Adapt.trigger("trickle:wait");` fire each time a notify is open and `this.isStepLocking === true`, but they are only removed once when a notify is closed due to:
https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/notify.js#L42

This means trickle is still waiting for additional overlays and waits to be removed when the additional notify popups are closed.

### Proposed solution
Either remove the `isNotifyOpen` logic completely so the trickle events above are added and removed for each notify, or replace this with a counter so the events are triggered once when a notify is opened, and wait until they are all closed before removing. I would assume the latter is preferred:
https://gist.github.com/danielghost/9cc8f37070dfb7fb932ab9d340b93d14

**Comment by oliverfoster** [comment]
Could you try with the rewrite? @danielghost https://github.com/adaptlearning/adapt-contrib-trickle/pull/113
You'd need a fw version >=5.8
