### ISSUE TITLE
delete 2 sections of adaptlearning/documentation repo

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#3107]
1. I recommend deleting two sections of the [adaptlearning/documentation repo](https://github.com/adaptlearning/documentation):
05_wiki_changelog
06_wiki_style_guide
These are vestiges of the documentation prep for the release of v3.  I don't believe there is value in retaining them.

2. Does this repo warrant being pinned on the main github page? There must be many people who come along looking for help/documentation, see this repo and jump in, only to leave confused. Yes, I'm totally aware of the description below the repo title--but we know how people are: act first; read later. I don't know how frequently core developers are referencing the repo, but it appears that the contents don't change often. And core developers should be sharp enough to find the repo quickly if not pinned. Anyway, just a suggestion to nix a potential source of confusion for visitors to the github page.

**Comment by moloko** [comment]
I think the style guide should be kept as it is linked to from some other pages (I think??) but certainly needs updating

06_wiki_style_guide yes definitely delete

and yes agree completely this should not be pinned

**Comment by chucklorenz** [comment]
Personally not aware of anything linking to the style guide. I proposed it as an incomplete draft to Sven back when we prepping v3. I never heard back. Great if someone is linking to it. Great if someone thinks it might have future value as a foundation for a new and improved guide. Just stumbled through the repo yesterday and thought about tidying up--being Spring and all.  😉

**Comment by moloko** [comment]
@chucklorenz I've unpinned the documentation repo from the main page and pinned adapt-cli instead

**Comment by oliverfoster** [comment]
deleted section
