### ISSUE TITLE
Drawer animation duration can't be set to 0

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#3108]
### Subject of the issue/enhancement/features

If you set `Adapt.config._drawer._duration` to `0` it reverts back to using 400. I'm not sure if it's intentional but it's caused by this conditional assignment [here](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/drawerView.js#L29).

### Your environment
* version (AT/Framework) Latest FW

**Comment by moloko** [comment]
should be able to fix this via use of nullish coalescing operator I think?
