### ISSUE TITLE
Glossary - The search bar disappears when viewed on an iOS device

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3117]
### Subject of the issue/enhancement/features
Glossary - The search bar disappears when viewed on an iOS device

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

all iOS devices and chrome/safari browsers.

### Steps to reproduce
Enable the glossary extension.

Add a few items along with their descriptions to the glossary extension.

Test on a variety of iOS devices including iPhones and iPads.

### Expected behaviour
Glossary should have a search bar

### Actual behaviour
No search bar available

### Screenshots (if you can)

![Image from iOS](https://user-images.githubusercontent.com/61159216/114066167-5181af00-9893-11eb-947c-c60d051aa95c.png)

**Comment by tomgreenfield** [comment]
I can't replicate this one on my flatmate's iPhone 8 running iOS 14.

Please can you provide all version information, including that of the framework?

**Comment by moloko** [comment]
side note - orientation change causes the search bar to appear
