### ISSUE TITLE
First element in drawer not being focussed

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3119]
### Subject of the issue/enhancement/features
First element in drawer not being focussed. I noticed that when working on https://github.com/adaptlearning/adapt_framework/issues/3117 `this.$el`  was undefined inside the complete function, therefore no focus was being supplied.

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

I tested on an iOS device with Chome/Safari but this issue could be happening on all browsers/devices.

### Steps to reproduce
Create a course with a page and a text component and add the glossary extension. Debug through to the complete function in core drawer.js to see what this.$el evaluates to.

### Expected behaviour
The first element in the drawer should be focussed.

### Actual behaviour
The first element in the drawer is not focussed.

**Comment by tomgreenfield** [comment]
> but this issue could be happening on all browsers/devices

I don't have access to an Apple device but I can't replicate this on desktop. I'm not entirely sure why there would be any difference in the `this` context between devices...

**Comment by eleanor-heath** [comment]
Closing this, please see discussion here https://github.com/adaptlearning/adapt_framework/pull/3118
