### ISSUE TITLE
Localisation/translation import issue with json

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt_framework#3125]
### Subject of the issue/enhancement/features
Trying to import json file for translation instead of csv, but getting error on import

### Your environment
Framework, v5.3.0
Windows 10

### Steps to reproduce
Export content to json
Duplicated the en folder in a course within builds folder, and renamed it de (this has the json and images folder in it, but in English)

added a de folder to the languagefiles folder (top level of dev folder) and added in the translated export.json

ran 
`rub translate:import –targetLang=de –format=json`
get error saying that “sorry, the imported file is not valid”

### Expected behaviour
Should import the json

### Actual behaviour
Get above error

### Screenshots (if you can)
attached. (i've blanked out part of the file path
![Screenshot 2021-04-13 171128](https://user-images.githubusercontent.com/7137955/114585394-7f903600-9c7b-11eb-9003-9f68f212f1f8.jpg)
)

**Comment by oliverfoster** [comment]
moved to rub-cli
