### ISSUE TITLE
Page level progress not completing when trickle is enabled on the block of assessment results

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt_framework#3130]
### Subject of the issue/enhancement/features
Describe your issue here.
Page level progress not completing when trickle is enabled on the block of assessment results

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)
All

### Steps to reproduce
Tell us how to reproduce this issue.

- Create a course
- Add page level progress
- Create an assessment with submission per question
- Edit the assessment settings and enable Allow retry once passed?
- Add the trickle extension and configure it on the blocks
- Save and preview
- Pass the Assessment

### Expected behaviour
Tell us what should happen
Page level progress should complete

### Actual behaviour
Tell us what happens instead
Page level progress does not complete an a console error can be viewed when inspecting the course.

**Comment by moloko** [comment]
@eleanor-heath what's the console error?

**Comment by eleanor-heath** [comment]
@moloko 
<img width="612" alt="ADAPT-7899" src="https://user-images.githubusercontent.com/61159216/115019071-92d81700-9eb0-11eb-8324-b831196a4587.png">

**Comment by moloko** [comment]
is it not just a case of changing `const` to `let` then? I'd have thought the property locking system in Adapt would handle preventing visibility from being changed should trickle want it to remain hidden.

**Comment by eleanor-heath** [comment]
is does not display the assessment results component and the page level progress wont complete without the trickle enabled condition I added

**Comment by moloko** [comment]
out of interest, what have you got `_isVisibleBeforeCompletion` set to?

**Comment by eleanor-heath** [comment]
I have _isVisibleBeforeCompletion enabled

**Comment by oliverfoster** [comment]
fixed in https://github.com/adaptlearning/adapt-contrib-assessmentResults/pull/63
