### ISSUE TITLE
adapt-contrib-spoor autotranslation problem

### ISSUE THREAD

**Issue by johanlavenius** [adaptlearning/adapt_framework#3136]
### Subject
Building courses mainly in Swedish. index.html/index_lms.html in adapt-contrib-spoor defines lang="en" which makes certain browsers trying to autotranslate the course.

### Suggestions
- Ability to toogle translate="no/yes" in the html-tag
- Ability to change lang in settings

**Comment by tomgreenfield** [comment]
https://github.com/adaptlearning/adapt_framework/blob/dd94d83d9e0a76ad05971cd06b709195dc71bd23/src/core/js/data.js#L91

https://github.com/adaptlearning/adapt_framework/blob/e948280cb34118bd74794e11febb97465a9b0942/src/course/config.json#L2

Hi @johanlavenius, if you change the default language in config.json does the current code run too late to stop the browser offering a translation? Please could also you provide browser names and versions.

**Comment by oliverfoster** [comment]
Is this solved?

**Comment by johanlavenius** [comment]
I think so as I am not able to reproduce the problem after changeing default language. I have also asked my client if the can reproduce it and waiting for confirmation.

Med vänliga hälsningar
Johan Lavenius

**Comment by oliverfoster** [comment]
Cool. Please reopen if your client has issues.
