### ISSUE TITLE
adapt-contrib-languagePicker: progress can be lost when switching languages

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#3139]
### Subject of the issue/enhancement/features
If the notify prompt to confirm a language change is cancelled rather than using the prompts, when the language is ultimately changed, the progress is reset as it attempts to set and restore the data multiple times due to the drawer view not being removed.

### Your environment
* framework: 5.13.0, languagePicker 4.3.1 but not specific to these versions
* not browser or device specific

### Steps to reproduce
1. Setup a course with a languagePicker enabled and `"_restoreStateOnLanguageChange": true`.
2. Complete some content in a language then choose a new language from the drawer. Cancel the notify by clicking on the background rather than using the button prompts.
3. Choose a new language from the drawer again, but this time accept the change via the yes prompt.
4. When the page reloads, the progress is reset. This doesn't occur if using the prompts in step 2.

### Proposed change
`languagePickerDrawerView` should remove itself on cancelling the notify. This will prevent multiple instances of the view from remaining and remove the event listeners causing the issues with the models `trackedData` being cleared as the content is reloaded and then set again for each view isntance.

**Comment by oliverfoster** [comment]
@danielghost any progress on this?
