### ISSUE TITLE
Post Install Issues

### ISSUE THREAD

**Issue by christianswanepoel** [adaptlearning/adapt_framework#3145]
I have installed the framework and can login - but all pages are blank besides plugin management 
Any advice?

<img width="1676" alt="Screenshot 2021-05-11 at 16 11 33" src="https://user-images.githubusercontent.com/7249713/117830156-a5f1c300-b273-11eb-84c3-c877e3858e62.png">

Startup log:
info [11 May 21 14:05:17 +00:00] configuration loaded from /home/adapt_authoring/conf/confi
g.json
info [11 May 21 14:05:17 +00:00] Supporting the following authentication types:
info [11 May 21 14:05:17 +00:00] - local
info [11 May 21 14:05:17 +00:00] Connection established: adapt-tenant-master
info [11 May 21 14:05:17 +00:00] Adapt authoring tool 0.10.5.
info [11 May 21 14:05:17 +00:00] Adapt framework 5.13.0.
info [11 May 21 14:05:18 +00:00] Server started listening on port 5000

**Comment by oliverfoster** [comment]
Moved to https://github.com/adaptlearning/adapt_authoring/issues/2560
Matching forum post https://community.adaptlearning.org/mod/forum/discuss.php?d=4032#p14804
