### ISSUE TITLE
general: Some title/body combinations are not compiling handlebars

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3150]
### Subject of the issue
- [x] [Narrative](https://github.com/adaptlearning/adapt-contrib-narrative/blob/e74158de5414507777235c049f8c4e17341aca87/templates/narrative.hbs#L16)
- [x] [Hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/a888ec4d47c79bb2a96bdfed8182e9d0688414bd/templates/hotgraphicPopup.hbs#L12)
- [x] [Resources](https://github.com/adaptlearning/adapt-contrib-resources/blob/f67758945b8d285b25ca4d63cdd2dc475605e43f/templates/resources.hbs#L53), [Resources2](https://github.com/adaptlearning/adapt-contrib-resources/blob/master/templates/resources.hbs#L61)
- [x] [Accordion](https://github.com/adaptlearning/adapt-contrib-accordion/blob/master/templates/accordion.hbs#L19)

Should all be `{{compile title}}` or `{{compile description}}` etc

**Comment by vaish567** [comment]
Howdy @oliverfoster Can I step up on this issue? if you're not working still?
