### ISSUE TITLE
adapt_framework: scoring

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3163]
### Subject of the issue
[Original forum comment](https://community.adaptlearning.org/mod/forum/discuss.php?d=4036#p14820)

There is no option specific scoring in Adapt at present. 

Currently, with an assessment, questions are scored 0 / `_questionWeight` according to their correctness, not an option specific score. Effectively, `_questionWeight` behaves as `_questionMaxScore` or `_questionCorrectScore` (for weird legacy reasons) so that we can calculate a percentage score from a collection of questions.

* [mcq/gmcq model](https://github.com/adaptlearning/adapt_framework/blob/deea638ca36553b03ba4c13fc719d9854364341d/src/core/js/models/itemsQuestionModel.js#L108-L113)
* [matching model](https://github.com/adaptlearning/adapt-contrib-matching/blob/949a7e2ae0765a9c69871d3d37b26d2f89e87457/js/matchingModel.js#L124-L138)
* [assessment scoring](https://github.com/adaptlearning/adapt-contrib-assessment/blob/8b37309e2dff5d9129e306b0d97dc7ef6fcb58e6/js/adapt-assessmentArticleModel.js#L440-L463)

You can see that the assessment ignores the `_score` value on the questions in favour of `_questionWeight` as questions have no `_maxScore` which is essential for proportionality (out of 100%).

@danielghost Suggests separating the `correctness` from the `score` calculation and handing that decision to the designer.

Proposal:
* QuestionModel
  * Add `score`, defaulted to `0` for incorrect/partly correct, `maxScore` for correct
  * Add `maxScore`, defaulted to `_questionWeight`
  * Add `minScore`, defaulted to `0`
* ItemsQuestionModel
  * Add `_hasItemScoring`, defaulted to `false`
  * With `_hasItemScoring === true`
    * Add `_items._score`, defaulted to `0`
    * Add `score` as the sum of the `_items._isActive`,  `_items._score`
    * Add `maxScore` as the sum of the `_selectable` highest positive `_items._score` items or 0
    * Add `minScore` as the sum of the `_selectable` lowest negative `_items._score` items or 0
  * Keep correctness as incorrect/partiallyCorrect/correct based on `_selectable`, `_items._shouldBeSelected`
  * Keep `_score` as a ratio of `score` to `maxScore` in a range of 0-1
* Assessment  
  * Change to scoring by `score` instead of [`_questionWeight` and `_isCorrect`] 
    * Moved `_isCorrect` check into `score` property with `_hasItemScoring === false`
    * Using `_hasItemScoring === true` on questions will allow partially correct and incorrect scoring
  * Add a correctness threshold for passed state `_correctToPass`, defaulted to `60` and contingent on `_isPercentageBased`
  * Keep `_scoreToPass ` and `_isPercentageBased`

This would be:
* Backward compatible
* Provide option specific scoring
* Allow partial correctness scoring
* Allow incorrect scoring (penalisation)
* Allow for proportional option specific scoring (out of 100% etc) 

Notes:
* `_correctToPass` is effectively `_scoreToPass` except when `_hasItemScoring` is enabled and it is possible to get a score greater than one. This is as without `_hasItemScoring`, score is equal to the number of correct questions.
* `_correctToPass` is contingent on `_isPercentageBased` because percentages are used with variable question amounts, such as with branching, or because questions may be added later and the boundary of a pass should move proportionally with the question amounts.

**Comment by oliverfoster** [comment]
need reviews on the idea, will attempt a prototype

**Comment by danielghost** [comment]
If I am understanding this correctly, wouldn't this mean a user would always be best off selecting all responses regardless of correctness? Unless this was limited to questions where only one option can be selected, or negative points could be added to incorrect items, you wouldn't get penalised for answering incorrectly.

**Comment by oliverfoster** [comment]
> [..] rawScore as the sum of the _items._score of the _items._isActive, _items._shouldBeSelected responses

`_isActive` is limited by `_selectable` so you can only choose `_selectable` * `_items._isActive` and `_items._shouldBeSelected` means to only count the score from correct active items. I wasn't suggesting to add the ability to penalise by adding incorrect item scores, but it's an interesting idea.

**Comment by oliverfoster** [comment]
@danielghost Suggests separating the `correctness` from the `score` calculation and handing that decision to the designer.

Proposal:
* QuestionModel
  * Add `rawScore`, defaulted to `0` for incorrect/partly correct, `1` for correct
  * Add `maxScore`, defaulted to `1`
  * Add `minScore`, defaulted to `0`
* ItemsQuestionModel
  * Add `_items._score`, defaulted to `1`
  * Add `rawScore` as the sum of the `_items._isActive`,  `_items._score`
  * Add `maxScore` as the sum of the highest `_items._score * _selectable` items
  * Add `minScore` as the sum of the lowest `_items._score * _selectable` items
  * Keep correctness as incorrect/partiallyCorrect/correct based on `_selectable`, `_items._shouldBeSelected`
  * Keep `_score` as a ratio of `rawScore` to `maxScore` in a range of 0-1
* Assessment  
  * Add option to score by [`_questionWeight` and `_isCorrect`] (as is) 
  * Add option to score by [`maxScore`], add correctness threshold for passed state, as [`requiredScore`, `minimumOverallCorrectness`]

This would be backward compatible, provide option specific scoring, provide partial correctness scoring and allow for proportional option specific scoring (out of 100% etc)
