### ISSUE TITLE
Better error reporting on translation import

### ISSUE THREAD

**Issue by jayseventwo** [adaptlearning/adapt_framework#3165]
### Subject of the issue/enhancement/features
When importing translated csv files into Adapt Author Tool (v 0.10.5.), using the following command:

grunt translate:import --targetLang=th-th --format=csv --replace

 I get errors, but the only message I see is:

$ grunt translate:import --targetLang=th-th --format=csv --replace
Running "translate:import" (translate) task
>> Using src/ folder for course data...
>> Encoding detected as UTF-8 languagefiles/th-th/articles.csv
>> Delimiter detected as , in languagefiles/th-th/articles.csv
>> Encoding detected as UTF-8 languagefiles/th-th/blocks.csv
>> Delimiter detected as , in languagefiles/th-th/blocks.csv
>> Encoding detected as UTF-8 languagefiles/th-th/components.csv
>> Delimiter detected as , in languagefiles/th-th/components.csv
>> Encoding detected as UTF-8 languagefiles/th-th/contentObjects.csv
>> Delimiter detected as , in languagefiles/th-th/contentObjects.csv
>> Encoding detected as UTF-8 languagefiles/th-th/course.csv
>> Delimiter detected as , in languagefiles/th-th/course.csv
>> TypeError: Cannot read property 'length' of undefined

The last line does not tell me what line or character etc. the issue is, which makes it very hard to fix.

As an aside, I managed to fix the issue by copy-pasting the translated portion of the file into a copy of the original ENG version of the file.

### Your environment
Adapt Author Tool (v 0.10.5.)
Adapt Framework 5.13.0

* Which browser and its version
* Chrome (Version 91.0.4472.77)
* Windows 10 (20H2)

### Steps to reproduce
Exported course, translated course into Thai and Simplified Chinese, tried importing both,  have the same errors for both.

I am happy to provide the course files but as these are not meant for public viewing, please message/email me for access.

### Expected behaviour
The error message should display at least the line number where the issue is located.

### Actual behaviour
As above, I get the following message only:

$ grunt translate:import --targetLang=th-th --format=csv --replace
Running "translate:import" (translate) task
>> Using src/ folder for course data...
>> Encoding detected as UTF-8 languagefiles/th-th/articles.csv
>> Delimiter detected as , in languagefiles/th-th/articles.csv
>> Encoding detected as UTF-8 languagefiles/th-th/blocks.csv
>> Delimiter detected as , in languagefiles/th-th/blocks.csv
>> Encoding detected as UTF-8 languagefiles/th-th/components.csv
>> Delimiter detected as , in languagefiles/th-th/components.csv
>> Encoding detected as UTF-8 languagefiles/th-th/contentObjects.csv
>> Delimiter detected as , in languagefiles/th-th/contentObjects.csv
>> Encoding detected as UTF-8 languagefiles/th-th/course.csv
>> Delimiter detected as , in languagefiles/th-th/course.csv
>> TypeError: Cannot read property 'length' of undefined

**Comment by oliverfoster** [comment]
closing as stale
