### ISSUE TITLE
adapt-contrib-trickle - Not revealing all content on a page

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#3168]
### Subject of the issue
When using the latest version of trickle (5.0.0) it isn't revealing all of the content on a page when working through it. It will take you to an item that has trickle enabled on it and will show the continue button and you are taken to the next block/component but then there is nothing else scrollable on the page, even though there are other components below this.

If you go to menu and back in to the page again or if you open the page level progress and select a component that isn't visible then it will then show the content.

### Your environment
* f/w version: 5.13.0
* Trickle version: 5.0.0
* Vanilla version: 5.4.0
* Box menu version: 5.1.0
* all browsers
* all devices

### Steps to reproduce
Create a course
Add a page
Add a few components to the page
Add the trickle extension
Add page level progress
Go to the block settings for a component near the top of the page
Enable trickle - can do this with or without buttons and with or without scroll automatically
Step Locking Attributes set to Enabled and Completion Required
Save and preview the course

### Expected behaviour
Component will be locked by trickle, completing it will unlock the next article and you can continue on through the page

### Actual behaviour
Component is locked, completing it will unlock the next component but anything else on the page is not available to scroll to unless you open page level progress and select the next component or return to the menu and then go back into the page

### Screenshots (if you can)
Here's a screen recording where trickle is set on the initial narrative but nothing else on the page - https://www.loom.com/share/ff01d4694df64004a4d44cf0c4a3524e

I've also attached an example file
[course-title-trickle-issue.zip](https://github.com/adaptlearning/adapt_framework/files/6615329/course-title-trickle-issue.zip)

**Comment by oliverfoster** [comment]
Hi Kevin. Trickle wasn't meant to be release yet in its new implementation, apologies. I am currently working on a fix for the aforementioned issue.

**Comment by kevindoherty30** [comment]
Hi Oliver, no problem, thanks for the update.

**Comment by oliverfoster** [comment]
@kevindoherty30  could you try this pr for me? https://github.com/adaptlearning/adapt-contrib-trickle/pull/119
