### ISSUE TITLE
"Get link" button required for uploaded documents and assets

### ISSUE THREAD

**Issue by jayseventwo** [adaptlearning/adapt_framework#3170]
### Subject of the issue/enhancement/features
When uploading documents in the "Asset Management" area, there should be a button or similar called "Get link". When you click this, the document link is copied, so you can use it elsewhere in the course.

This should also be in the Resources plugin area.

There definitely also needs to be a checkbox or similar, where you can specify that you want the original file name kept.

### Your environment
Adapt author Tool - any version

### Steps to reproduce
N/A

### Expected behaviour
After clicking "Get link" you should have a copied link to your asset, that you can then use elsewhere in the course (EG: from a link in the Rich Text Editor).

File name stays the same as the uploaded file.

### Actual behaviour
N/A

**Comment by oliverfoster** [comment]
Hi @jamieshepherd,

The authoring tool has its own issues page https://github.com/adaptlearning/adapt_authoring/issues could you please re-post this issue there?

**Comment by jayseventwo** [comment]
Thanks Oliver - done!
