### ISSUE TITLE
adapt-contrib-media: option to display controls underneath the video 

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#3191]
The control bar is aligned to the bottom of the video element which means the bottom 32px of the video is obscured when the control bar is displayed. For videos with subtitles or text at the bottom of the video this can be problematic.

I suggest adding a class or attribute to position the control bar underneath the video instead.

**Comment by guywillis** [comment]
Hi Kirsty,

I recently added some custom CSS in a project that could form a useful start point for the issue at hand. 

```
.media.offset-media-controls {
  .mejs-video:not(.mejs-container-fullscreen) {
    .mejs-controls {
      bottom: -2rem;
    }
  }

  .media__widget {
    padding-bottom: 2rem;
  }
}
```

**Comment by kirsty-hames** [comment]
> Hi Kirsty,
> 
> I recently added some custom CSS in a project that could form a useful start point for the issue at hand.
> 
> ```
> .media.offset-media-controls {
>   .mejs-video:not(.mejs-container-fullscreen) {
>     .mejs-controls {
>       bottom: -2rem;
>     }
>   }
> 
>   .media__widget {
>     padding-bottom: 2rem;
>   }
> }
> ```

Perfect, thanks @guywillis. Let's go with this and replace `2rem` with `@mejs-controls-height`.
