### ISSUE TITLE
adapt-contrib-boxmenu: no space between header and items

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#3192]
When a header background image/colour is applied the header appears to sit on top of the menu items. Spacing can be a design preference and something we can easily amend in the LESS but I find this is something I regularly apply. I think for AAT authors who aren't using a custom theme it would make sense to set a default margin value for `boxmenu__item-container`?

**Boxmenu currently (no margin)**
<img width="1014" alt="without_margin" src="https://user-images.githubusercontent.com/7045330/124622679-3f53e480-de73-11eb-875c-672bd810e01b.png">

**Boxmenu with 1.5rem margin applied to  `boxmenu__item-container`**
<img width="1004" alt="with_margin" src="https://user-images.githubusercontent.com/7045330/124622860-601c3a00-de73-11eb-8a43-49d2dbafcf3f.png">

**Comment by oliverfoster** [comment]
Agree
