### ISSUE TITLE
fw4 adapt-contrib-gmcq: 'aria-hidden="true"' prevents image alt text from being read out

### ISSUE THREAD

**Issue by sh-ln** [adaptlearning/adapt_framework#3200]
### Subject of the issue
The `aria-hidden="true"` on the parent label for GMCQ items prevents item image alt text from being read out.

### Environment
* FW v4.5.0 / AT v0.10.5
* adapt-contrib-gmcq v4.0.0 (and potentially later versions)
* Firefox 89
* Windows PC

### Steps to reproduce
Add alt text to GMCQ item images and test course with screen reader (NVDA was used when discovering issue).

### Expected behaviour
Screen reader reads out image alt text when reached with arrow keys.

### Actual behaviour
Alt text is in DOM (verified with browser dev tools and adapt-devtools extension), but alt text is not read out.

### Screenshots
![gmcq-issue](https://user-images.githubusercontent.com/67964426/124916908-19e9e680-dfeb-11eb-91b7-d08a67d652e0.PNG)

**Comment by tomgreenfield** [comment]
Pending a port to GMCQ 4.x.

**Comment by oliverfoster** [comment]
closing as a stale, known issue, fixed in v5
