### ISSUE TITLE
adapt-contrib-spoor and adapt-contrib-trickle: tracking broken

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3204]
### Subject of the issue
Original report https://community.adaptlearning.org/mod/forum/discuss.php?d=4059

The new version of trickle injects trickle components, spoor is trying to save and restore these injected components, but they are missing in the restoration phase on a new session and cause spoor to crash.

![image](https://user-images.githubusercontent.com/7974663/126458039-deb1b0ad-9ddb-4099-8f52-87308758a93b.png)

**Comment by danielghost** [comment]
These changes fix the error, but there still seems to be an issue with unlocking content objects, e.g. sequential locking. The content object can be reached via the trickle button on the last component within a page, but if you return to the menu, that page is still locked. Content object unlocking works as expected if the page just completed isn't trickle, so it would suggest the injected trickle components are still being added to the completion criteria.

**Comment by oliverfoster** [comment]
That is intended @danielghost you can turn off the final trickle button with `"_showEndOfPage": false` if you don't want the final trickle button to show. Or I can have tht final trickle button be optional if that would be better?

**Comment by danielghost** [comment]
New issue with locking moved to https://github.com/adaptlearning/adapt_framework/issues/3205.
