### ISSUE TITLE
adapt-contrib-trickle: Locking and final button in conflict

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3205]
### Subject of the issue
The content object can be reached via the trickle button on the last component within a page, but if you return to the menu, that page is still locked. Content object unlocking works as expected if the page just completed isn't trickled, so it would suggest the injected trickle components are still being added to the completion criteria.

**Comment by oliverfoster** [comment]
That is intended you can turn off the final trickle button with `"_showEndOfPage": false` if you don't want the final trickle button to show. Or I can make an amend to have that final trickle button be optional if that would be better?

Reply:
> _showEndOfPage doesn't work

**Comment by danielghost** [comment]
`"_showEndOfPage": false` seems to be ignored as the button is seemingly always shown regardless. Ideally the default would be false so any upgraded courses don't change their original behaviour. I assume there would also be a conflict with the button being shown when using custom navigation components such as https://github.com/cgkineo/adapt-pageNav at teh end of a page.

**Comment by oliverfoster** [comment]
`"_showEndOfPage": true` is the default as courses have always shown their final button, it has just been broken for a while.

**Comment by oliverfoster** [comment]
This is as one part of the code wasn't assuming `_onChildren` should be true when it's missing.
