### ISSUE TITLE
adapt-contrib-trickle: multiple buttons on browser refresh

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#3206]
### Subject of the issue/enhancement/features
If the browser is refreshed, previously trickled models display the button again. This doesn't seem to happen when revisiting the page via normal Adapt navigation, such as via the menu.

### Your environment
* 5.15.2
* Chrome (not tested others yet)
* Using trickle https://github.com/adaptlearning/adapt-contrib-trickle/tree/issue/3204

**Comment by oliverfoster** [comment]
Are multiple buttons appearing or are the original buttons reappearing?
Is the course saving and restoring?

**Comment by oliverfoster** [comment]
stale
