### ISSUE TITLE
adapt-contrib-media: hide closed captions by default with the option to display?

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#3207]
Is it possible to add a config option to hide closed captions by default? There may be good reason to why we wouldn't want to do this re accessibility. Closed captions, when not in use however can be distracting from the video. I've had this request come up on a project.....thoughts?

**Comment by oliverfoster** [comment]
Should be possible

**Comment by moloko** [comment]
`_startLanguage: "none"` IIRC...

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-media/blob/7a5563b9819dab23e3fbd98303891a99484fb117/js/mediaView.js#L283-L295
