### ISSUE TITLE
adapt-contrib-trickle has issues with PLP

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#3213]
### Subject of the issue/enhancement/features
PLP can't find element from trickle buttons to check isInViewport.

[trickle-broken-course.zip](https://github.com/adaptlearning/adapt_framework/files/6903810/trickle-broken-course.zip)

**Comment by oliverfoster** [comment]
Can I have an unminified output?

**Comment by simondate** [comment]
@oliverfoster 
[3213-output.zip](https://github.com/adaptlearning/adapt_framework/files/6908457/3213-output.zip)

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/127832695-292617ad-3a85-4606-a048-1a1c430bc5de.png)

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/127999383-1a078e74-90b8-4f98-900d-32efdfbbda16.png)
You have a custom plp which is causing it.

Closing issue.

**Comment by simondate** [comment]
My bad 😨 I should have remembered the changes to this plugin

**Comment by oliverfoster** [comment]
It should just fail silently rather than throwing an error. Make sure to check errors with sourcemapping turned in that way they're much more informative about the origin of the bug.
