### ISSUE TITLE
Course will not load unless Language extension is enabled

### ISSUE THREAD

**Issue by css3ninja** [adaptlearning/adapt_framework#3224]
### Subject of the issue/enhancement/features
Course will not load unless Language extension is enabled. If I enable the Language extension and create a language dialogue ex. (en) then course loads fine. When I remove the language extension entirely it breaks my course.

### Your environment
Authoring Tool: 0.10.5
Framework: 5.15.4
Browser: Chrome Version 92.0.4515.131 (Official Build) (64-bit)
Windows 10

### Steps to reproduce
Take any course and remove language extension

### Expected behaviour
Course should work fine without language extension

### Actual behaviour
Course gets stuck at theme loading page

**Comment by oliverfoster** [comment]
Yea, the last few commits on the framework have broken it.

This is the current working ticket: https://github.com/adaptlearning/adapt_framework/issues/3222 and the associated prs at the bottom

**Comment by cahirodoherty-learningpool** [comment]
Fixed with framework release 5.15.5
