### ISSUE TITLE
Changing language with search extension is breaking the course

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt_framework#3229]
### Subject of the issue/enhancement/features
A multi-lang course with search extension will work when first loaded, but changing language will fail.

This is due to the onDataReady() -> setupConfig() being run as expected first time round, therefore SEARCH_DEFAULTS are applied to the model defaults.
However, changing language does not apply these defaults and thus 'isSearchable' will break due to attempting hideTypes.includes(type) when hideTypes is null

### Your environment
* FW5.15.5

### Steps to reproduce
Create a multi-lang course with search extension
Load the course in any of the languages
Use drawer language picker to try to change language

### Expected behaviour
Language will be changed

### Actual behaviour
Course will break due to JS error

**Comment by oliverfoster** [comment]
I've added you as a contributor to adapt-search whilst I'm on holiday.

**Comment by cahirodoherty-learningpool** [comment]
Resolved with most recent release of Search (https://github.com/cgkineo/adapt-search/releases/tag/v4.2.1)
