### ISSUE TITLE
ItemsComponentModel doesn't update items of its children

### ISSUE THREAD

**Issue by jonas-jelinski** [adaptlearning/adapt_framework#3242]
### Subject of the issue/enhancement/features

ItemsComponentModel doesn't update items of its children of type ItemModel if  ``` ItemsComponentModel.set('_items',newitems)```
is called.

Example: 
```
if (newitems.length > 0) {
      Adapt.findById(id).set('_items', newitems) <--- updates the items but not the children
      var model = Adapt.findById(id);
      if (model.setUpItems) {
        model.setUpItems(); <---need to call setUpItems to update children too
      }
    }
```

Reason: Children are only set on ```init``` in ```setUpItems```
```
export default class ItemsComponentModel extends ComponentModel {

  toJSON() {
    const json = super.toJSON();
    // Make sure _items is updated from child collection
    json._items = this.getChildren().toJSON();
    return json;
  }

  init() {
    this.setUpItems(); <---- called on init
...
...
...

setUpItems() {
    // see https://github.com/adaptlearning/adapt_framework/issues/2480
    const items = this.get('_items') || [];
    items.forEach((item, index) => (item._index = index));
    this.setChildren(new Backbone.Collection(items, { model: ItemModel })); <---- sets Childs as ItemModel
  }
```

### Your environment
*  "name": "adapt_framework", "version": "5.16.0",
* Firefox Version 92.0
* Notebook, W10

### Steps to reproduce
Try to overwrite the items by calling ```Adapt.findById(id).set('_items', newitems) ```
of an adapt-contrib-hotgraphic component in an extension. After that create the course
with  ```grunt build; grunt server ``` and open the hot-graphic-notify-popup by clicking 
on the pin.  
 
### Expected behaviour
Children should be updated too if someone updates '_items'

### Actual behaviour
The changes won't be visible in the popup as ```this.model.toJSON() ``` of the 
HotgraphicPopupView will return the old values of  ```items ```.

**Comment by oliverfoster** [comment]
```js
Adapt.findById(id).getChildren().set(newitems);
```;

**Comment by jonas-jelinski** [comment]
Thank you for the answer!

Wouldn't it be smarter in the long run to include this in ItemsComponentModel as updating the items trough `model.set(attributes, [options])` is the common way by backbone?

**Comment by oliverfoster** [comment]
Yea, kind of. Except that `_items` in the `ItemsComponentModel` is actually turned into a `Backbone.Collection` of `ItemModel` accessed by `getChildren()`. So `_items` in this case isn't the value you should be interacting with. It is instead:

```js
const itemsModelCollection = itemsComponentModelInstance.getChildren();
const firstItemModel = itemsModelCollection.at(0);
firstItemModel.set(newItemJSON);
```

**Comment by oliverfoster** [comment]
> Thank you for the answer!

> Wouldn't it be smarter in the long run to include this in ItemsComponentModel as updating the items trough model.set(attributes, [options]) is the common way by backbone?

Does that make sense? Can I close this as you have a viable solution.
