### ISSUE TITLE
grunt build fails

### ISSUE THREAD

**Issue by MihailMiller** [adaptlearning/adapt_framework#3246]
### Subject of the issue/enhancement/features
When running `grunt build` from course folder, the build fails running "schema-defaults" task:
`Running "schema-defaults" task
Warning: Cannot read property 'json' of undefined Use --force to continue.

Aborted due to warnings.`

### Your environment
* v5.17.0
* OS: alpine v3.11
* node v14.18.0

### Expected behaviour
* no issues in v5.16.0 when running `grunt build`

**Comment by oliverfoster** [comment]
It's probably that you're running the npm install as the root user. The preinstall scripts run without root which causes them to fail.
If you follow [these instructions](https://github.com/adaptlearning/adapt_authoring/issues/2566) you should be able to get them to run as root.
