### ISSUE TITLE
confusing warning message re language-data-manifests

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#3247]
FW v5.17.1

When I run build while having duplicate component ids in component.json, I get a correct and meaningful error message. It is followed by a warning about missing "language-data-manifests". I'm wondering if this warning might send someone off in the wrong direction and wondering if it could be suppressed when there's only one language folder.

Anyway, this is only meant as a heads-up. Feel free to close this issue without discussion. 

![image](https://user-images.githubusercontent.com/9489014/137213085-41bcb828-a6df-4931-a294-c2ff798a7b7e.png)

**Comment by oliverfoster** [comment]
This was a transitional warning re switching to dynamic file loading. Closing as should not be an issue moving forward.
