### ISSUE TITLE
`_classes` not assigned to course

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#3248]
Since framework 5.17.1, the `_classes` for the course model don't seem to be applied to the page view.

**Comment by danielghost** [comment]
Looks like the cause is actually due to the ES6 update to `adapt-contrib-boxMenu`:
https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/master/js/BoxMenuView.js#L9.

The `className` method is overriding the one in `AdaptView` rather than extending it. I can pick this up and amend.

**Comment by oliverfoster** [comment]
Cool, ta.
