### ISSUE TITLE
Question button accessibility - Show my / correct answer

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt_framework#3258]
### Subject of the issue/enhancement/features
The "Show correct answer" / "Show my answer" button can be interacted with via keyboard and screenreader.  However, the button provides no value to the user as it simply toggles between the two button states.

### Your environment
* Framework v5.13

### Expected behaviour
I think one of the following should happen:

1. The button is hidden from screenreaders altogether.
2. (preferred) The button provides information about the correct answer and the user's answer.  For instance, activating "Show my answer" could read out "My answer - Option 1" and activating "Show correct answer" could read out "Correct answer - Option 2."

**Comment by oliverfoster** [comment]
Hi brad. Matt did this already.

https://github.com/adaptlearning/adapt_framework/pull/3051/files
https://github.com/adaptlearning/adapt-contrib-gmcq/pull/127/files
https://github.com/adaptlearning/adapt-contrib-mcq/pull/156/files

You should be able to add add these properties in the course globals https://github.com/adaptlearning/adapt-contrib-mcq/blob/147248c62375accf5a182faafd79820c20f20908/properties.schema#L6-L51 if they aren't there already.

![image](https://user-images.githubusercontent.com/7974663/141165958-64355e97-3c2e-4ce2-90e0-c90b141d9c9d.png)


![image](https://user-images.githubusercontent.com/7974663/141165830-1f8d4af8-b55a-49db-80c4-5fffd86f3fa8.png)

**Comment by swashbuck** [comment]
Thanks, Ollie.  Looks like we were overriding the buttons.hbs template, and it was missing the .js-answer-live-region element.  All good now :)
