### ISSUE TITLE
Adapt Accessibility tests: Jaws stops mid sentence

### ISSUE THREAD

**Issue by gareehilsdon** [adaptlearning/adapt_framework#326]
Location:
Go to: https://community.adaptlearning.org/course/view.php?id=4
navigate with keybaord, using tab and pressing enter/space to select ['Adapt V1.1.0 - Accessibility']
Takes user to: https://community.adaptlearning.org/mod/scorm/view.php?id=43
navigate with keybaord, using tab and pressing enter/space to select [Enter]
Takes user here: https://community.adaptlearning.org/mod/scorm/player.php
navigate with keyboard, using tab and pressing enter/space to select [Adapt v1.0.1 - testing]
HOME:Welcome to Adapt Learning - v1.0.0 
https://community.adaptlearning.org/pluginfile.php/1287/mod_scorm/content/3/index.html

Go to first link - Welcome to Adapt Learning https://community.adaptlearning.org/pluginfile.php/1287/mod_scorm/content/3/index.html#/id/co-05

Jaws stops mid sentence when reading the text under the headings on this page, eg.
'Welcome to the Adapt Learning demo page. This page contains a sample of the functionality that will be available in the upcoming releases of the open [STOPS HERE] source  code in January 2014. The content itself will explain some of the thinking that’s gone into the design and development of the framework, as well [STOPS HERE] as highlighting what’s on the roadmap for release later in the year.' - investigate why..

**Comment by apasternack** [comment]
I am getting this same bug when Insert + Down Arrow, no discernable reason.  All other pages in the app JAWS reads fine
