### ISSUE TITLE
course import error

### ISSUE THREAD

**Issue by eclass4learning** [adaptlearning/adapt_framework#3262]
### Subject of the issue/enhancement/features
WHen trying to import a particular course, adapt will throw an UnhandledPromiseRejectionWarning.

### Your environment
* version 0.10.5
* chrome 96
* PC, linux/windows

### Steps to reproduce
export course from another server, then import course into another server.

### Expected behaviour
for teh course to be properly imported

### Actual behaviour
adapt throws an UnhandledPromiseRejectionWarning
[adapt.log](https://github.com/adaptlearning/adapt_framework/files/7629210/adapt.log)

**Comment by oliverfoster** [comment]
this is an authoring tool issue, could you please repost on the https://github.com/adaptlearning/adapt_authoring/issues page please?

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_authoring/issues/2580
