### ISSUE TITLE
_canShowModelAnswer breaks MCQ on assessment reset

### ISSUE THREAD

**Issue by deltanetdan** [adaptlearning/adapt_framework#3279]
### Subject of the issue
If _canShowModelAnswer is set to true on the assessment article and MCQ component selecting "Show correct answer" and reseting the assessment breaks the question display.

### Your environment
FW v5.18.4
MCQ v6.0.0
Assessment v4.5.4 (issue/149 branch does not fix the issue)
Node v14.18.2
Chrome 97
macOS 11.6.3

### Steps to reproduce
1 - Create a course using the CLI
2 - Change _canShowModelAnswer on the "Adapt assessment" article to true
3 - Change _canShowModelAnswer in all of the questions in "Adapt assessment" to true
4 - Answer the questions incorrectly and select "Show correct answer"
5 - complete the assessment and reset

### Expected behaviour
Reseting the assessment should restore the questions so they can be attempted again.

### Actual behaviour
After resting the assessment the questions have the correct answers selected as shown below and visual state of checkbox/radio items cannot be altered:
![Screenshot 2022-02-01 at 09 57 32](https://user-images.githubusercontent.com/4161219/151956943-07a2e1fb-9bef-4c21-947a-b7be75dce318.png)

**Comment by deltanetdan** [comment]
Adding _isCorrectAnswerShown: false [here](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L313) seems to fix this issue. 

However it does not fix [Lars Halkjaer's issue](https://community.adaptlearning.org/mod/forum/discuss.php?d=4124) on the forum.

**Comment by oliverfoster** [comment]
That is the solution @chris-steele 
I'm actually surprised that it's missing from the template.
