### ISSUE TITLE
Question About Dev Environment Doc

### ISSUE THREAD

**Issue by TheFutonEng** [adaptlearning/adapt_framework#3333]
### Question
Is [this page](https://github.com/adaptlearning/adapt_framework/wiki/Setting-up-your-development-environment) still valid?  It seems like the web based authoring tool is the preferred method to author a course but the docs still point to the CLI.

Context: I'm a developer and exploring using adapt in order to produce some training material.  I have Adapt installed and I'm just looking for the best place to get a good understanding of what is possible with the authoring tool.

**Comment by oliverfoster** [comment]
That's not an authoring tool page, that's a framework page. The AAT uses to framework to produce courses.

https://github.com/adaptlearning/adapt_authoring/wiki
