### ISSUE TITLE
Define accessibility best practice guide for Adapt

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#3379]
Adapt accessibility has been implemented in conformance with [WCAG](https://www.w3.org/WAI/WCAG2AA-Conformance) however there is often multiple solutions or conflicting opinions to meeting criteria. In addition, we have  interactions/functionality in Adapt that isn't part of standard web leaving it to us as developers to determine the appropriate implementation.

In order to ensure consistency in Adapt and provide support for developers it would be good to document a best practice guide. 

I see this having the following uses:
- A resource guide for developing/maintaining Adapt functionality. Including examples of implementation and reasoning for why we've chosen a particular implementation if applicable (e.g. ARIA heading levels vs H tags).
- A resource guide for authoring content in Adapt (e.g how content should read and knowing how to mark it up #2553).
- A measure for reviewing where Adapt is now and addressing any inconsistencies (e.g. review use of ARIA holistically rather looking at plugins in isolation).

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/229451975-f883dab1-ee31-4933-9e85-6c8097832cf3.png)

**Comment by oliverfoster** [comment]
[https://github.com/adaptlearning/adapt_framework/issues/3357 Slider ](https://github.com/adaptlearning/adapt-contrib-confidenceSlider/issues/82#issuecomment-1479512564) Slider forms mode

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/issues/2553#issuecomment-1488788556 Zero width spacing

**Comment by kirsty-hames** [comment]
Closing as this will be covered by https://github.com/adaptlearning/adapt_framework/issues/3586
