### ISSUE TITLE
'server-build' grunt task fails since 5.31.3

### ISSUE THREAD

**Issue by Pzenarch** [adaptlearning/adapt_framework#3415]
### Subject of the issue/enhancement/features
When performing an Adapt authoring tool build of a course using the new 'adapt_framework' v5.31.3, the build fails (error given below in 'actual behaviour').  This appears to be because the change that was applied in v5.31.3 was applied to the 'build' grunt task, but not the 'server-build' grunt task, the latter of which assumes the screen config steps are still performed as part of the 'less' build task.

### Your environment
* version (AT/Framework) : 5.31.3
* which browser and its version: Chrome, 113.0.5672.93
* device(s) + operating system(s): Windows desktop PC

### Steps to reproduce
Install the adapt authoring tool (0.11.1), and link it to the adapt_framework v5.31.3.  Create a new course, and immediately attempt to publish/build.  After a short delay, the error mentioned above will be presented.

### Expected behaviour
The course should build! - or rather the server-build process should complete in the same manner that the build process does.

### Actual behaviour
The course fails to build, with the following error:

error [16 May 23 08:11:46 +01:00] Command failed: npx grunt server-build:prod --outputdir=courses\6463226d1cf94b72306f8679\6463230edd525d608017feed\build --theme=646322c31cf94b72306f870d --menu=adapt-contrib-boxMenu
Error: No screenSize defined in config.json

**Comment by oliverfoster** [comment]
I'll have a look today. Apologies. I had hoped the AAT would produce the screenSize data from the config.json schema.

**Comment by oliverfoster** [comment]
Yes, server-build assumes that the AAT supplies all of the correct json from the schemas. 
Which I can confirm it doesn't.
Good find.

**Comment by oliverfoster** [comment]
@Pzenarch Could you go to the `Files Changed` tab on the following pull-request, and click, `Review Changes` and `Approve` if you can. Or just add a comment with the phrase `+1`.

https://github.com/adaptlearning/adapt_framework/pull/3416

![image](https://github.com/adaptlearning/adapt_framework/assets/7974663/4cad1525-ce9c-49d7-ae92-3b43123816ec)

**Comment by oliverfoster** [comment]
Thanks for persisting in your explanation. :+1:
