### ISSUE TITLE
Broken accessibility link in readme

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt_framework#3446]
https://github.com/adaptlearning/adapt_framework/blob/44ea80132b2f37dac2aa9dcf59d9fa4a9079bb86/README.md?plain=1#L20

The link https://github.com/adaptlearning/adapt_framework/wiki/Accessibility does not exist yet.

Should this link to the new guide that will presumably be created in #3379 @kirsty-hames @oliverfoster ?

**Comment by kirsty-hames** [comment]
Looks like that link was added 6 years ago and not populated. Whilst we do need to put some guidance together as per #3379 I hadn't thought what form this would take.

Perhaps as a starter, we could create that Accessibility page and populate with some headings for areas we want to cover? We could focus on any v5 changes to build on from the [Accessibility v3 to v4 wiki](https://github.com/adaptlearning/adapt_framework/wiki/Accessibility-v3-%E2%86%92-v4)? This page gives a good overview to accessibility in Adapt but some config/syntax will be outdated now.
