### ISSUE TITLE
How can we ensure plugin updates have not broken e2e tests?

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt_framework#3499]
With the new FW-level testing additions, we will be running all e2e tests via a GitHub Action (GHA) every time a FW PR is created. However, with the testing code of plugins now living on the individual plugins repository, we don't really have any automation in our e2e testing.
When we add unit tests to plugins, I believe they will be able to be run as GHA on PR per plugin, but the e2e requires the context of the overall FW and always will.

I wanted to raise this issue to gather the thoughts of the community in case anyone has any solutions to this. One thing that could help us catch issues early (and prevent the blocking of a FW PR) would be to trigger the testing action on a schedule (daily?) as well as it's action on PR creation.
I would be happy to submit the PR that achieves this if we decide that is the best approach for now.

**Comment by oliverfoster** [comment]
Ideally:
* We'd be able to use the fw as a testing environment for the components
* We'd be able to supply a series of component/course configurations against which to test the component
* We'd be able to execute using gh automation

Running the main one daily seems fair for the moment.

**Comment by cahirodoherty-learningpool** [comment]
Thanks for your input Oliver. I will create a linked PR now that puts the test runner on a schedule and also allows for manual triggering from the Actions tab. This will give us flexible use in the interim and as much coverage as is possible at this point
