### ISSUE TITLE
E2E code coverage reports would be good to have

### ISSUE THREAD

**Issue by lemmyadams** [adaptlearning/adapt_framework#3520]
### Subject of the issue/enhancement/features
With the recent push forward and potential to create e2e tests on the various components of the framework, it would be a good idea to use coverage reports to understand how much is covered and what still needs addresses. 

Personally I've only used [istanbul/nyc](https://istanbul.js.org/) to do this, which does the job quite well but introduces some complexity when applying it to the framework. Simply installing nyc creates coverage reports of the grunt folder, both unit and e2e, but will need a lot more investigation on how to impact the src folder.

**Comment by oliverfoster** [comment]
I don't think it is a good idea to do this for e2e tests until we have a mechanism of providing test data/courses for specific use-cases.

To do that we need a way of having the running course reload with the correct course data. We probably need an API and a strategy in Adapt that can help achieve this.

**Comment by lemmyadams** [comment]
@cahirodoherty-learningpool ^ thoughts?

**Comment by cahirodoherty-learningpool** [comment]
Fair points, thanks Ollie. Definitely worth considering as we move forward with testing. @lemmyadams I will close off this issue now until the testing has evolved more
