### ISSUE TITLE
Cypress helper function for stripping html

### ISSUE THREAD

**Issue by lemmyadams** [adaptlearning/adapt_framework#3532]
### Subject of the issue/enhancement/features
With more tests in place, there's some reused code that would be best placed in a custom cypress command to reduce the risk of errors. Such as:
```
function stripHtml(text) {
  const textWithoutHtml = text.replace(/<[^>]*>/g, '');
  cy.wrap(textWithoutHtml).as('text');
}
```

**Comment by oliverfoster** [comment]
```js
function testQuestionButtons(buttonsObject = {btn__action: 'Submit', btn__feedback: 'Show feedback'}) {
  Object.keys(buttonsObject).forEach((key) => {
    cy.get(`.${key}`).should('contain', buttonsObject[key])
  })
}
```
This is much more generic than it looks:
```js
function hashContains(hash) { // the name needs changing
  Object.entries(hash).forEach(([key, value]) => {
    cy.get(`.${key}`).should('contain', value)
  })
}
```
 The default values should not be hardcoded in English but instead be passed from the loaded JSON.

**Comment by oliverfoster** [comment]
There are 1001 ways of doing the stripHtml function:
```js
function stripHtml(text) {
  const textWithoutHtml = text.replace(/<[^>]*>/g, '');
  cy.wrap(textWithoutHtml).as('text');
}
```
As you can see here: https://stackoverflow.com/questions/822452/strip-html-tags-from-text-using-plain-javascript

What are you going to use this for?

**Comment by lemmyadams** [comment]
> There are 1001 ways of doing the stripHtml function:
> 
> ```js
> function stripHtml(text) {
>   const textWithoutHtml = text.replace(/<[^>]*>/g, '');
>   cy.wrap(textWithoutHtml).as('text');
> }
> ```
> 
> As you can see here: https://stackoverflow.com/questions/822452/strip-html-tags-from-text-using-plain-javascript
> 
> What are you going to use this for?

I'm going to use it for stripping the html. On that link currently its the 2nd bit of code, it was just the simplest design which I chose. I can pick the first one though if thats preferred or any other option.

**Comment by lemmyadams** [comment]
> ```js
> function testQuestionButtons(buttonsObject = {btn__action: 'Submit', btn__feedback: 'Show feedback'}) {
>   Object.keys(buttonsObject).forEach((key) => {
>     cy.get(`.${key}`).should('contain', buttonsObject[key])
>   })
> }
> ```
> 
> This is much more generic than it looks:
> 
> ```js
> function hashContains(hash) { // the name needs changing
>   Object.entries(hash).forEach(([key, value]) => {
>     cy.get(`.${key}`).should('contain', value)
>   })
> }
> ```
> 
> The default values should not be hardcoded in English but instead be passed from the loaded JSON.
> 
> Reference:
> 
> * [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)
> * [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

My initial thought was to reduce duplicated code here, and so I was going to have a default param for the submit and feedback buttons. I can get the text values from the course I presume so I'll update that there. Whilst I suppose this is a very generic function, what would stop it from becoming a general testElementContains function? Which I feel like would add a lot of complexity to something that doesn't need to be complex.
Just trying to think of readability here which I think is overlooked a lot in the aim of getting overly technical, and I want to avoid setting the object manually in every single test if that object is going to be the exact same for all the question components at least

**Comment by oliverfoster** [comment]
It's not really a helper at all it's a very specific externalised feature test. 

Helpers are more like stripHtml above, they're generic repeatable utilities or standardised logic and usually not full tests on a specific feature.

> what would stop it from becoming a general testElementContains function

That's exactly what it should be really, to become a helper.

**Comment by lemmyadams** [comment]
> It's not really a helper at all it's a very specific externalised feature test.
> 
> Helpers are more like stripHtml above, they're generic repeatable utilities or standardised logic and usually not full tests on a specific feature.
> 
> > what would stop it from becoming a general testElementContains function
> 
> That's exactly what it should be really, to become a helper.

Okay then lets pretend its not a helper function per se, where should that live in the code structure?

**Comment by oliverfoster** [comment]
If you want to externalise a test and reuse it across plugins, we don't have a mechanism for doing that, you'd have to repeat the 5 lines of code in each plugin, either in an imported file (if that's possible) or at the top of each test file.

You've put a common test into core, which is used only by question components, I'd assume?

**Comment by lemmyadams** [comment]
> I don't think you should avoid setting the object manually. It makes it very clear what's being tested. Or just don't test the buttons here, test them in the core where the code lives? (obviously that's slightly difficult as there are not components in the core to test against) Note: Buttons are also overridable from the [component config](https://github.com/adaptlearning/adapt-contrib-textInput/blob/ab95d5434b05aa80826c8201f7668ffb2614acf3/example.json#L68-L88)

I find it confusing that sometimes we're in favour of making what is to be tested clear, like hardcoding an object, but not other times. It seems as though the button situation is far more complicated than I understood so its best to just remove it for now

**Comment by oliverfoster** [comment]
> I find it confusing that sometimes we're in favour of making what is to be tested clear... but not other times.

Can you give the line references and examples of where we've chosen to not make things clear? We can set about correcting them.

> like hardcoding an object,

I don't understand, do you mean the English default function parameters?

I'm always available to chat on Google meet, element/gitter or teams if you want? I think we've only spoken through text so far.

**Comment by lemmyadams** [comment]
> Can you give the line references and examples of where we've chosen to not make things clear? We can set about correcting them.

> I don't understand, do you mean the English default function parameters?

Creating the same object for at least 5 different tests doesn't make any sense to me as we should want to reduce repeated code as much as possible. It's no different from a testContainsOrNotExists, so I don't understand why one is fine but the other is a terrible idea. Changing it to a very vague function is good for usability, but that extra use cases don't exist right now and it makes things much more confusing. Changing it to a hashContains would really confuse me

**Comment by oliverfoster** [comment]
> Creating the same object for at least 5 different tests doesn't make any sense to me as we should want to reduce repeated code as much as possible.

I agree. However, tests should live in the same repo as the code they're testing. You've put a test for the core question buttons views in the compilation suite. We segregate the code into responsibilities and therefore separate repos so that it's easy to find and so that each section is as loosely coupled and replaceable as possible. I'm afraid code colocation trumps reducing repetition, always. Otherwise we end up with things in places that are hard to find.

> It's no different from a testContainsOrNotExists, so I don't understand why one is fine but the other is a terrible idea.

One is a test, with a specific purpose, name and defaults that lives in the wrong place. The other is a generic utility function that lives in the right place, which is utilised by a test defined and located appropriately.
