### ISSUE TITLE
Update Node.js prerequisite to specify LTS version requirement 

### ISSUE THREAD

**Issue by henrietta-k** [adaptlearning/adapt_framework#3537]
### Subject of the issue/enhancement/features
The adapt-learning-wiki GitHub page doesn't currently specify the updated Node.js version. It states Node.js LTS version, but it may be helpful to users if there is a specific version that they can look out for. 

### Steps to reproduce
Go to the adapt-learning-wiki page and scroll down to the "Prerequisites" section to the part where it says "you will need to install Node.js" 

### Expected behaviour
Can specify a specific version (currently v20). Users may not know that the Node.js LTS version needs to be an even-numbered release, or else this error message will show up if the version is incorrect/ incompatible: 
`$ adapt create course
? type: (Use arrow keys)
❯ course 
  component 
  question (node:11670) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
`
### Screenshots (if you can)
![image](https://github.com/adaptlearning/adapt_framework/assets/111554249/2c60b705-8977-4285-a1a8-a70840502e8c)

**Comment by henrietta-k** [comment]
Since GitHub doesn't support PRs for the wiki repository, I made a new GitHub repository to show the proposed changes to this Wiki page: https://github.com/henrietta-k/adapt-learning-wiki/blob/master/Setting-up-your-development-environment.md 

The proposed changes is under the **Prerequisites** section (as shown in the screenshot below): 
![image](https://github.com/adaptlearning/adapt_framework/assets/111554249/36c5ee73-e554-4a35-92b0-09d38ce4ba3e)

This change specifies that Node.js must be an even-numbered release. This may clarify what version is needed to help future users avoid getting an error when using the wrong version of Node.js.

**Comment by oliverfoster** [comment]
remove `currently v20` as we'd need to update that frequently

**Comment by henrietta-k** [comment]
Updated the example to remove `currently v20`
<img width="1042" alt="image" src="https://github.com/adaptlearning/adapt_framework/assets/111554249/fc57104d-20c2-47c6-ac2a-70fe5eef949b">
Side note: this wiki page also states `currently v__` so it should be removed too. 
https://github.com/adaptlearning/adapt_framework/wiki/Manual-installation-of-the-Adapt-framework

**Comment by oliverfoster** [comment]
Have merged in your changes. :+1: Thank you.
