### ISSUE TITLE
The testing script always transforms testfiles globs to lowercase at the Cypress level

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt_framework#3588]
### Subject of the issue/enhancement/features
Running tests but attempting to limit to a specific plugin glob that includes a capital letter as part of the component (e.g. npm test --testfiles=**/components/adapt-contrib-textInput/**), the test will not find anything to run as Cypress seems to force lowercase and no such file exists `testMatch: **/components/adapt-contrib-textinput/** - 0 matches`

### Your environment
* FW v5.40.6

### Screenshots (if you can)
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/0f0d49aa-eaed-442b-a5e1-9bc9be2fe4a5">

**Comment by lemmyadams** [comment]
I think this is caused by the `.toLowerCase()` in https://github.com/adaptlearning/adapt_framework/blob/70e13288035b464bdaa9d47d73fc70d7c99d3f5f/test.js#L209
Unsure of the effects of removing this

**Comment by cahirodoherty-learningpool** [comment]
> I think this is caused by the `.toLowerCase()` in
> 
> https://github.com/adaptlearning/adapt_framework/blob/70e13288035b464bdaa9d47d73fc70d7c99d3f5f/test.js#L209
> 
> 
> Unsure of the effects of removing this

That's exactly it
