### ISSUE TITLE
Responsive Layout Issues

### ISSUE THREAD

**Issue by salali** [adaptlearning/adapt_framework#392]
Currently there are widths being set for various elements based on screen size in responsive.less

Adding padding or margin (depending element) can cause overflow on the horizontal axis.
My solution would be to switch over to max-widths instead of setting the width explicitly, this seems to work better in general and makes the intent clearer.

**Comment by oliverfoster** [comment]
fixed https://github.com/adaptlearning/adapt-contrib-vanilla/pull/72

**Comment by oliverfoster** [comment]
Please close
