### ISSUE TITLE
Adapt Accessibility tests: co-05 component descriptions repeated in erroneous locations

### ISSUE THREAD

**Issue by shauncg** [adaptlearning/adapt_framework#403]
Once JAWS reaches the media component on co-05 it issues a helpful description of the component and the transcript link. It then reads "Region Document Link Transcript Document End" (which is a little clumsy, although I can see why JAWS reads it like this) and repeats the entire description of the media component and transcript, before issuing the description of the hotspot image component that is a little further down the page (this latter description also occurs just after the hotspot image). 

Similar issues occur with other component types throughout co-05: 

1. A description of the accordion component occurs at the end of the paragraph under the heading "Below the fold, ahead of the curve", before the lower-level heading and text preceding the accordion. This is a somewhat confusing place for this description to occur, as it does not directly precede an accordion. The description is later repeated, after the accordion link/headings have been read out. This actually seems like a more appropriate location for the description, despite being after the accordion, as it helpfully contextualises what the user has just heard. 

2. The description of the MCQ component occurs immediately after the accordion description, prior to the 'Key benefits...' sub-heading and text. It then appears again after all elements of the MCQ have been read out by JAWS. 

3. The narrative component description appears at the end of the MCQ, following its description, before the heading 'What's coming next?' 

Ideally these useful component descriptions should appear only once each, directly before the component in question (or possibly directly after as with the accordion).

**Comment by oliverfoster** [comment]
Fixed. Please close.
