### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#451]
These points may have been raised elsewhere but on having a quick 10 minute review of the functionality, there seems to be some inconsistencies in how this works and also some genuine issues:

* The use of the dashed line when items are focussed seems to be inconsistently applied. Some components seem to use this only (e.g. accordian items), others also include the rollover state (e.g. mcq options), some just show rollover state (e.g. matching)  and some don't seem to show any sort of focus indicator (e.g. submit buttons).
* You can overlay multiple tutor feedbacks if you tab to the submit button and hit enter multiple times.
* Hidden/disabled items can still be tabbed to in places, e.g. first and last arrows on hotgraphic popups.
* Items are sometimes selectable via different keys, e.g. mcq options seem to need SPACE keypress whereas most others use ENTER. Some work with either. Hitting SPACE on some will actually scroll you on the page instead.
* Think you can still tab to certain elements whilst a tutor popup is open. Obviously can't use the mouse but think you can still use keypresses.
* With trickle the next tab index isn't always the next thing the user should click, e.g. the continue button. Sometimes it can switch to the back button in navigation for example, so it isn't entirely obvious what you are on due to not everything containing a focus indicator of some sort.

As I say this is only from a really quick run through to see how it worked so this isn't an extensive list. Tested in Chrome.

**Comment by oliverfoster** [comment]
Needs closing as resolved.
