### ISSUE TITLE
(Accessiblity) Changing links to role="button" should allow use of spacebar to mimic button behaviour

### ISSUE THREAD

**Issue by kris-savoia** [adaptlearning/adapt_framework#481]
Stumbled across this today and thought that it applies to accordion, narrative, hotgraphic, drawer, and various other UI within Adapt.

>Warning: Be careful when marking up links with the button role. Buttons are expected to be triggered using the Space key, while links are expected to be triggered through the Enter key. In other words, when links are used to behave like buttons, adding role="button" alone is not sufficient. It will also be necessary to add a key event handler that listens for the Space key in order to be consistent with native buttons.

[Source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role)

**Comment by oliverfoster** [comment]
Needs closing, implemented in develop.
