### ISSUE TITLE
implement _isOptional

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#490]
Currently this property exists in adaptModel.js, but there is no code that uses it.

My understanding of this is that it's purpose is to allow an author to mark a ContentObject/Article/Block/Component as 'optional' i.e. the user is not required to complete it and, as such, it should be ignored by anything that calculates overall progress/completion (the progress of the item should still be stored, but just for reference).

When speak to @darylhedley about this yesterday he thought it should be the responsibility of a plugin to use _isOptional - but given that the overall course completion is currently calculated by AdaptModel.checkCompletionStatus - which generates the 'change:_isComplete' event that a plugin like contrib-spoor listens for to find out when the overall course is completed - I would have thought it would be best implemented in checkCompletionStatus.

I guess you could do it within contrib-spoor, but you'd essentially be replicating the functionality of AdaptModel.checkCompletionStatus - which seems like wasted effort to me.

Any thoughts on this?

**Comment by taylortom** [comment]
I'm of the opinion that if it's in the core code, it should be implemented. This goes with what @darylhedley was saying about keeping the core as light as possible.

Plugins could just as easily set _isOptional for themselves without it needing to be defined in AdaptModel, this is just confusing for devs that aren't well-versed in Adapt; I know I've been caught trying to use _isOptional assuming it was set somewhere, only to find it wasn't.

**Comment by darylhedley** [comment]
``_isOptional`` is a locked attribute:
https://github.com/adaptlearning/adapt_framework/wiki/Adapt-API#--set--locked-attributes
Removing this from the adaptModel.js will mean it becomes a standard attribute on a model and not use the built in mediator pattern.

**Comment by taylortom** [comment]
Is it reasonable to be able to define new locked attributes from a plugin? I imagine this is something that could be useful in the future. 

I guess if there's no other sensible way to deal with it, we'll just need to make sure it's documented clearly in the code.

**Comment by olivermartinfoster** [comment]
Firstly, do we currently have any community plugins that provide the _isOptional behaviour or any community plugins which use the _isOptional attribute? Is the _is optional attribute behaviour a large enough community requirement that it should be core? Will it break anything else? Have we put the idea to tender on the forum? Do we have a proposed implementation that can be reviewed?

**Comment by darylhedley** [comment]
@taylortom - yes any model extending from Backbone.Model will have the ability to lock the attribute
@olivermartinfoster - this should stay in core as many plugins would need access to this

**Comment by oliverfoster** [comment]
So, now we need a core implementation of _isOptional, plus a forum page and some community input. And a discussion around whether this will break anything. Who's taking it?

**Comment by brian-learningpool** [comment]
+1 for an actual implementation of _isOptional as part of core, although to avoid breaking anything we could introduce _isCompletionRequired (or something meaningful).  

I think it makes sense to indicate which components, etc. should count towards completion.  There will obviously be a knock-on effect on some of our core plugins, PageLevel Progress, Spoor, etc.

**Comment by oliverfoster** [comment]
Need to do PLP stuff to reflect mandatory + optional components...

**Comment by oliverfoster** [comment]
Done
