### ISSUE TITLE
router assumes a menu is always required

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#491]
The `handleCourse` method assumes a menu will always be displayed first. Whilst this may be true the majority of the time, it may not always be the case. The most obvious reason being a course which only has one contentObject and therefore one page.

Obviously this can be overcome in different ways as we have done in courses already but I would have thought the default approach should at least make some effort to look at the structure of the course rather than assuming it will always be a menu.

**Comment by moloko** [comment]
is this still relevant?

**Comment by chris-steele** [comment]
+1 for no longer relevant
