### ISSUE TITLE
Accessibility: Symantic header vs Aria headers

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#494]
Should we use h1, h2, h3, h4, h5, h6 tags or <span role="heading" aria-level="1" etc?

menu = level 1,
page = level 2,
article = level 3,
block = level 4,
component = level 5

h tags do not read consistently on screen readers due to nested header levels and inconsistent use of header tags.
h tags are easy for programmers but bad for users
h tags are the preferred industry standard

span+role+level tags read consistently across screen readers as they override the nested header level behaviour.
span tags are good for users and a small pain for programmers
span tags are also industry standard but are not preferred

###Reference Material
http://www.w3.org/WAI/GL/wiki/Using_role%3Dheading  < see example 2
http://www.w3.org/TR/wai-aria/roles#heading
http://www.w3.org/TR/wai-aria-practices/#kbd_layout_nesting_vs_level

**Comment by taylortom** [comment]
I personally prefer the additional flexibility that using `<span>` tags gives you.

Given the non-linearity of a lot of Adapt courses in terms of DOM structure (when compared to regular web pages), it will likely prove very useful to be able to have fine-grained control over the order in which text is read out by screen readers.

*(aside) it may be worth mentioning that using the 'h1...6' semantic notation also limits the developer to 6 levels of headers.*

**Comment by oliverfoster** [comment]
this issue is from PR: https://github.com/adaptlearning/adapt_framework/pull/489
