### ISSUE TITLE
checkIfResetOnRevisit does not give user notification.

### ISSUE THREAD

**Issue by olivermartinfoster** [adaptlearning/adapt_framework#495]
[questionView.checkIfResetOnRevisit function](https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/views/questionView.js#L65-L109)

Does not give user notification on reset and returns the user to a blank and incomplete component on a page revisit as per [forum comment](https://community.adaptlearning.org/mod/forum/discuss.php?d=475#p2378)

This needs to be fixed.

**Comment by darylhedley** [comment]
This should be handle by plugins wanting to reset questions on revisit as this is by default set to not reset

**Comment by oliverfoster** [comment]
I agree, this function should be part of a plugin. Perhaps called, adapt-resetOnRevisit ?

**Comment by taylortom** [comment]
Is the suggestion then to refactor 'checkIfResetOnRevisit' into a separate plugin?

**Comment by olivermartinfoster** [comment]
Only plugins should reset components and give appropriate notification. checkIfResetOnRevisit is a specific reset behaviour actioned on a page revisit. This type of reset behaviour is only one use-case for resetting and should indeed be a separate extensions. This would allow people to choose which reset behaviour they would like. The extension could listen to pageView:prerender, select all children components which have _isResetOnRevisit: true, ask the user via a prompt and proceed to reset or not based upon their feedback and using the model based behaviour. The the component/question view wouldn't need its own reset behaviour except for instances of UI resetting whereby the component is reset whilst on the page. For this each component can listen to _isInteractionComplete: true>false and implement UI resetting accordingly.

**Comment by oliverfoster** [comment]
#493

**Comment by oliverfoster** [comment]
#498
