### ISSUE TITLE
#449 Presentation components should be able to be reset

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#498]
All presentation components extend ComponentView which has no isResetOnRevisit behaviour. Only QuestionView components implement the isResetOnRevisit behaviour. 

All identical reimplementions of reset behvaiour in each ComponentViews/presentation component is very heavy.

See PR #493 about bringing the reset functionality into the AdaptModel and create an implementation of the isResetOnRevisit behaviour in the Component View.

**Comment by oliverfoster** [comment]
from #449

**Comment by taylortom** [comment]
+1 for moving this reset functionality into AdaptModel or a similar ancestor. The ability to be able to reset a component feels like something that spans all components, not just questions.

**Comment by oliverfoster** [comment]
Done
