### ISSUE TITLE
Can't open test course build with Adapt

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#501]
Hi,

today I have tried to setup adapt framework on my friends machine so she can experiment with it and we've found following issue:

After installing nodejs, git then adapt-cli and grunt-cli, creating new course and building it preview just showed big empty page (there was no errors during creating or building). We were not able to see a demo course, not even the loading animation.

The console was starting with:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/opensans/v10/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff. This can be fixed by moving the resource to the same domain or enabling CORS.

followed by

TypeError: t.call is not a function adapt.min.js:121

Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. adapt.min.js:119

TypeError: i.config is undefined adapt.min.js:121

I thought it was a Windows 8 issue, but when I came home to my Windows 7 PC, and created new course it has exactly the same results. Old courses (created yesterday runs fine) but test course created today is not working.

**Comment by LukaszGrela** [comment]
there is a vast number of changes when I use WinMerge to compare adapt test course created on 09-Jan and 13-Jan e.g. underscore lib was downgraded from 1.7.0 to 1.6.0

**Comment by oliverfoster** [comment]
Could you verify if you are trying to run the index.html file straight from your harddrive or are you hosting it on a development server?

**Comment by hrajotia** [comment]
- if you've used `grunt build` command to build the course then you should run the `grunt server` to run a local dev server which allows you to run the course on [http://localhost:9001](http://localhost:9001) so that there will be no issue of `Cross-Origin Request`. <b>(Recommanded)</b>

- Or if you're trying to open it using `index.html`, as Oliver has pointed out, also if you using chrome then you could use [disable-same-origin-policy-in-chrome](http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) link to fix that at your end

**Comment by LukaszGrela** [comment]
I have tried to open it through `index.html` or `main.html` run from harddrive directly and through `localhost` server at port `9001` as it is done automatically after invoking `grunt server` command. The problem is that it was working the day before and yesterday stopped working without any changes. I had impression that it is due to Windows 8 but I got the same results on my Windows 7 machine that (and I repeat) was working before. Also it only affects new courses created, all courses created before yesterday runs fine.

Also I think the other errors are real problem and not cross origin request blocked to font:
FireFox

    TypeError: t.call is not a function adapt.min.js:121
    Use of getPreventDefault() is deprecated. Use defaultPrevented instead. adapt.min.js:119
    TypeError: i.config is undefined adapt.min.js:121

Chrome

    Uncaught TypeError: undefined is not a function adapt.min.js:121
    Uncaught TypeError: Cannot read property 'get' of undefined adapt.min.js:121

[Here(create_course_log.txt)](http://greladesign.com/temp/create_course_log.txt) you can find the log of the commands (and output) when creating course.

**Comment by LukaszGrela** [comment]
Is there a way to get adapt framework from point before Commits on Jan 12, 2015? As this is the only commit made after the 9-Jan (when it was working) and after which it stopped working.

**Comment by hrajotia** [comment]
@LukaszGrela - we have an on going disscussion on this issue adaptlearning/adapt_framework/pull/502 and i think if you change this line http://github.com/adaptlearning/adapt_framework/blob/master/package.json#L26 to `"grunt-contrib-handlebars": "~0.8.0"` in your `package.json` and do a `npm install` then it should be fixed.

**Comment by LukaszGrela** [comment]
Hi Himanshu, yes it works - thanks.

**Comment by hrajotia** [comment]
Thanks @LukaszGrela for notifying this issue, Now Fixed adaptlearning/adapt_framework/pull/502

**Comment by taylortom** [comment]
This has now been fixed in master.
