### ISSUE TITLE
Prevent overwrite of similarly named plugin assets

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#503]
If any plugin assets have the same name, they replace any existing assets. We need some way to stop this. Possible suggestions so far:
- Fail the build process if duplicates found
- Introduce a nested assets folder in `build`
- Add a prefix to the asset filename

Both of the latter could be accomplished automatically, or could just be the responsibility of the individual. Any thoughts?

**Comment by hrajotia** [comment]
I would like to with @darylhedley's comment on this - http://github.com/adaptlearning/adapt_framework/pull/497#issuecomment-69167726

i.e.: so in this case number 3.

**Comment by oliverfoster** [comment]
i think 3 is the simplest in terms of build tools etc, it just needs to be documented so that we can all point people in the right direction. allowing people to prefix files or supply unique sub-folders would be ideal for me.

**Comment by oliverfoster** [comment]
I think well intentioned overwrite behaviour can sometimes be fruitful, like the theme.less vs. all-else.less. The graphic component would be a good one for a placeholder.

**Comment by taylortom** [comment]
I'm thinking that we just add in a check/log output for this during build. As @oliverfoster says, this can be intentional

**Comment by oliverfoster** [comment]
agreed this can be intentional, closing.
