### ISSUE TITLE
Look into reducing the size of the repo

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#504]
On slow connections, it can take quite a while to pull down the repo.

One issue is the `course` folder, which is ~12mb, and another is the `test` folder, which contains the selenium server, and is ~35mb.

Seeing as we have to do an `adapt install` (or manual install) of the components/extensions, I'd like to see us implement some similar way of dealing with the course folder; creating a new course can be a bit of a hassle, as you're required to remove/amend the content that's already there. Maybe the answer is to have a very bare-bones course (I'm thinking 1xCO, 1xpage, 1xarticle, 1xblock, 1xcomponent), and then having a separate repo with an example course using the core bundle components.

Not sure if there's any solution to the nightwatch/selenium issue, perhaps linking to a hosted jar, rather than including it in the DL?

**Comment by taylortom** [comment]
`test` has already been removed from the `develop` branch, will do the same for master when I get some time.

**Comment by zenduo** [comment]
Could the video thats included in the course folder be hosted somewhere else? Or put a shorter version in the framework?

This is MP4 is 5.5mb and OGV is 4.7mb making most of the package size.

**Comment by taylortom** [comment]
We're looking into separating the entire sample course into a separate repo, hopefully for v2.0

**Comment by moloko** [comment]
this is done now, isn't it?

**Comment by moloko** [comment]
test suite has been removed, video changed to one with a smaller file size. will also look to remove the .ogv file from the course as all major browsers on all major operating systems now support mp4 (see [ABU-1073](https://adaptlearning.atlassian.net/browse/ABU-1073)).

not much we can do about the repo size without trying to hack the history, but I think this of secondary concern. the main thing is that `$ adapt create course` doesn't have as much to download
