### ISSUE TITLE
Add wiki page for contributing to Adapt

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#505]
Maybe something like: https://developer.mozilla.org/en/docs/Introduction

**Comment by oliverfoster** [comment]
Absolutely necessary.

**Comment by moloko** [comment]
great suggestion, page created: https://github.com/adaptlearning/adapt_framework/wiki/Contributing-to-the-Adapt-Framework

**Comment by taylortom** [comment]
See https://github.com/adaptlearning/adapt_framework/issues/548
