### ISSUE TITLE
_onQuizFailure is incorrect in config.json, should be _onAssessmentFailure

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#506]
Master branch of adapt-contrib-spoor uses _onAssessmentFailure instead of _onQuizFailure

LN 18 or config.json should be:

            "_onAssessmentFailure": "incomplete"

See https://github.com/adaptlearning/adapt_framework/pull/468

**Comment by zenduo** [comment]
This one looks like its been added to the develop branch now.
