### ISSUE TITLE
Performance related fixes

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#507]
Over use of underscore helpers in the core. This leads to an exponential growth of resource requirements when used with course material arrays. I.e. the problem gets more apparent the more course material exists. We need to look at the most used Adapt functions and remove as many utility function calls (such as uneccesary _.each calls) where possible. The core should ideally be as small and fast as possible giving more resources to components and extensions as they are likely to be changed more frequently.

**Comment by oliverfoster** [comment]
Examples:

https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/models/backboneModel.js#L27-L34
https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/models/backboneModel.js#L49-L66

**Comment by oliverfoster** [comment]
Reference:

https://github.com/jashkenas/underscore/blob/1.5.2/underscore.js#L76-L90

**Comment by oliverfoster** [comment]
What this demonstrates is that a function closure has to be created for each item in the for loop and that the this context has to be carried through.

Simply using native for syntax solves this resource hoging operation speedying up processing and reducing memory consumption. 

_.each should not be used in frequently used function calls on large arrays.

**Comment by oliverfoster** [comment]
http://jsperf.com/jquery-each-vs-underscore-each-vs-for-loops/11  < example from @moloko

**Comment by moloko** [comment]
That's just someone else's I found. here's a slightly tidier one: http://jsperf.com/underscore-each-versus-for-loop

**Comment by taylortom** [comment]
Also worth watching out for any code doing the length calculation like this:
```
for(var i = 0; i < arr.length; i++) {
}
```

**Comment by oliverfoster** [comment]
Yuup, I am also one who fondly writes iterative length calculations... learn something new everyday!

From now on:

```
for (var i = 0, length = arr.length; i < length; i++) {

}
```

**Comment by oliverfoster** [comment]
Backbone collections:

```
for (var i = 0, length = collection.models.length; i < length; i++) {
   var model = collection.models[I];

}
```

**Comment by zenduo** [comment]
Is this one still an issue?
