### ISSUE TITLE
Remove backboneModel.js

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#513]
#507 

There are few use cases where extensions will conflict over variable settings and therefor where the backboneModel code is used. It seems sensible to remove this code.

The removal would improve the large quantity of set operations that occur in Adapt.

Allowing the inverse behaviour seems a more sensible way of achieving an attribute lock, by allowing a plugin to force an attribute lock rather than having the framework check for complex locks on each set operation.

Suggestion for similar behaviour:  
     1. _isLocked { attributeName: true } on the model with a simpler validator (still checking on every set but using a much smaller mechanism)

Suggestions for inverse behaviour:  
   1. trigger "prechange:_attributeName" event and allow for cancellation (allows plugins to take control over the change handling)
   2. change "change:_attributeName" event to allow for cancellation (cannot guarantee event order)

**Comment by zenduo** [comment]
Is this still an issue?

**Comment by oliverfoster** [comment]
Yea. I just need some support on it.

**Comment by taylortom** [comment]
(just updated PR to reference this)

**Comment by zenduo** [comment]
Moved to  https://adaptlearning.atlassian.net/browse/ABU-474
