### ISSUE TITLE
Hard-coded dependencies on 'adapt-contrib-vanilla' and 'adapt-contrib-boxMenu'

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#520]
The current Gruntfile.js seems to reference hard-coded plugins.  Although these are core plugins installed in a default `adapt install` call, they probably shouldn't be hard-coded here.

@hrajotia, this seems to have been introduced with your change to persist the structure  21b0c0c66f7a2e68e99b39cb77c26573733669b9

**Comment by taylortom** [comment]
+1 for this. I'd suggest using a wild card to build all if no theme/menu is specified

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-473
