### ISSUE TITLE
Allow multiple/no menus - Requirements Collection

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#521]
https://github.com/adaptlearning/adapt_framework/issues/230 < no menu also permissable
https://github.com/adaptlearning/adapt_framework/issues/516 < agreed on need, breaking pr
https://github.com/adaptlearning/adapt_framework/issues/491 < inception

Initial requirements:
- Menu chosen on device size
- Menu dynamically changes with device size
- Specify sub and course menu types
- Easy + simple config
- Single menu as the default
- Route to single page (no menu)
- Conforms to current architectural abstractions - i.e. no dynamic menu loading and (view+model)+router styling

**Comment by moloko** [comment]
Pretty sure all this now handled by the _start configuration; if not please raise new ticket
