### ISSUE TITLE
Extending view methods

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#525]
All views just seem to override methods rather than extending them from the superclass. Why aren't components etc. setup so any methods which also exist higher in the hierachy work this way?

If you want to add something to one of these parent classes so all subclasses inherit the same behaviour you can't currently do this without changing the subclasses. Unless you actually want to explicitly override the superclass functionality I would have thought this would be the default approach seeing as Backbone handles inheritance for multiple levels.

**Comment by moloko** [comment]
does it though? I thought it didn't have any built-in support for extending functionality from the superclass, just overriding it.
Quite a nice workaround for it here: http://stackoverflow.com/a/9170976/1646700

**Comment by danielghost** [comment]
There isn't a super method to call but as you pointed out in your link, you can do something such as:
AdaptView.prototype.remove.apply(this, arguments);

This is what we have generally used. Unless there are reasons not to use this, although it seems to work ok in our code, then wouldn't it make sense to implement this where required as default?

**Comment by moloko** [comment]
no I suppose not, other than it being a little graceless! *sigh* when can we start using ES6?!

I suppose we could do a PR to add that workaround into the core code.

**Comment by oliverfoster** [comment]
```
this.constructor.__super__.remove.apply(this, arguments);
```
also works with backbone views.

**Comment by taylortom** [comment]
I quite like that SO solution Matt, pretty neat

**Comment by chris-steele** [comment]
Generally the SO approach gets used. I think we can close this now unless anyone knows a reason why my mouse and the close button should not unite?

**Comment by oliverfoster** [comment]
yea, make cute little mose buttuns chris

**Comment by chris-steele** [comment]
xD
