### ISSUE TITLE
[Windows 7] Copying the node_modules folder causes path too long error

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#526]
I've created a course with `adapt create course` then I wanted to copy it somewhere else but windows copy process has failed with an error that paths (from the node_modules) are too long. Has anyone encountered similar/the same problem? Is there a solution for that?

**Comment by oliverfoster** [comment]
don't copy the node_modules folder
run 'npm install' on the destination after you've copied

**Comment by LukaszGrela** [comment]
:) I knew I was doing something silly:D

**Comment by oliverfoster** [comment]
nah, just one of those things.
