### ISSUE TITLE
IE8 Left over opacity filter after animation

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#535]
https://github.com/adaptlearning/adapt_framework/blob/develop/src/core/js/views/pageView.js#L33

Suggest using .css({opacity:1}) to clear for ie8.

Causes styling issues and problems with flash video + filter clashing.

**Comment by moloko** [comment]
also text appearing in wrong colour with horrible anti-aliasing. images occasionally disappearing. generally just a pretty nasty issue in IE8.
here's another possible solution: http://www.bennadel.com/blog/2459-removing-inline-opacity-filters-after-fade-in-fade-out-transitions-in-ie8.htm

**Comment by moloko** [comment]
https://adaptlearning.atlassian.net/browse/ABU-408

**Comment by zenduo** [comment]
Think this one has been solved here: https://github.com/adaptlearning/adapt_framework/commit/36a0f1b54123c00d135b0d038d2e98edc003b9f5
