### ISSUE TITLE
add to grunt the fonts folder of components/extensions/menus

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#538]
Recently extensions and menu assets were added to the Grunt file to fix #304. Can the same be done with the fonts folder for components, extensions, and menus? I'm working on an extension (a Drawer item) that uses an icomoon font file to supplement the icons in vanilla.woff. Seems reasonable that other components and menus might need to deliver fonts, too.

**Comment by hrajotia** [comment]
@chucklorenz  thanks for the PR.
