### ISSUE TITLE
accessibility : validation submit error

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#552]
Currently when submitting an unselected question component the instruction text turns red to alert a validation error (set in theme). However this only alerts non-visually impaired users - I think an alternative needs to be provided, perhaps the submit button aria-label could be updated for selected/unselected?

**Comment by moloko** [comment]
I'm not sure it would cope for all visually impaired users (not all use a screenreader) but definitely worth doing anyway - we may just have to come up with something else, I am not sure what though. I'm sure we'll get there - we can't be expected to make it perfect first time!

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-467
