### ISSUE TITLE
@focus-outline is missing in develop branch

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#554]
I've created a "develop" branch course and during build got this error:

    Running "less:dist" (less) task
    >> NameError: variable @focus-outline is undefined in src/less/adapt.less on line 29, column 18:
    >> 28     .focused, *:focus, input:focus + label {
    >> 29         outline: @focus-outline;
    >> 30     }
    Warning: Error compiling src/less/adapt.less Use --force to continue.
    
    Aborted due to warnings.

in the `base.less` this CSS rule is set but there is no `@focus-outline` variable.

**Comment by oliverfoster** [comment]
Have you got the develop adapt-contrib-vanilla theme?

**Comment by LukaszGrela** [comment]
I've run `adapt create course` and choose develop branch

**Comment by hrajotia** [comment]
@LukaszGrela - i think you may also have to update the [adapt.json](http://github.com/adaptlearning/adapt_framework/blob/develop/adapt.json#L3-L21) as below
```
{
    "dependencies": {
        "adapt-contrib-vanilla": "develop",
        "adapt-contrib-text": "develop",
        "adapt-contrib-narrative": "develop",
                :
        "adapt-contrib-resources": "develop",
        "adapt-contrib-slider": "develop"
    }
}
```

after this you could install plugins using `adapt install` command.

**Comment by LukaszGrela** [comment]
Shouldn't the `adapt create course` command do any necessary steps needed for "develop" branch?

**Comment by hrajotia** [comment]
I won't think its available for now but there is an [issue](http://github.com/adaptlearning/adapt-cli/issues/16) been created on respective repository. I also think this the demanding feature which should be available.
