### ISSUE TITLE
Math helpers for handlebars

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#556]
Could the math helper be added to the helpers.js?
http://jsfiddle.net/mpetrovich/wMmHS/

	math: function(lvalue, operator, rvalue, options) {
		lvalue = parseFloat(lvalue);
		rvalue = parseFloat(rvalue);
		return {
			"+": lvalue + rvalue,
			"-": lvalue - rvalue,
			"*": lvalue * rvalue,
			"/": lvalue / rvalue,
			"%": lvalue % rvalue
		}[operator];
	}

**Comment by taylortom** [comment]
This looks like it could be useful, although it's something you could easily set up as an extension. I'd like to maybe see the existing helpers move into such an extension - I think the core should be modularised much more that in it currently, but that's for another time ;)

**Comment by oliverfoster** [comment]
I like the idea but i don't like that the implementation has to do 5 mathematical calculations every time it's run.

**Comment by moloko** [comment]
The original version is a very odd (though admittedly interesting) way of going about doing this. @oliverfoster's method seems the more straightforward.

**Comment by zenduo** [comment]
Added to develop, closing
