### ISSUE TITLE
Notify and tutor too similar to have separate instances?

### ISSUE THREAD

**Issue by nilslp** [adaptlearning/adapt_framework#561]
Wanted to ask if anyone else thought the same;

The hotgraphic on a small device opens up a notify popup instance, whereas a matching component opens up a tutor instance when pressing the submit button.

Is there any reason the notify popups can't be the tutor (as it brings through the feedback stuff from questions) and maybe just do away with the notify?

**Comment by oliverfoster** [comment]
Notify is a part of core whereas tutor is an extension which re-implements the notify-style popup.

In my mind tutor should be using the notify API, and notify should be extended to accommodate the requirements of tutor, being that they are quite minimal.

**Comment by moloko** [comment]
@oliverfoster agreed

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-tutor/pull/47

**Comment by oliverfoster** [comment]
done
