### ISSUE TITLE
jquery.v2.js

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#568]
We use jquery v1.x throughout adapt. The jquery.v2.js file is never used (as far as I can see) and my gut reaction is just to remove it. However....

We only use v1.x for ie8 compatibility and should really use version 2 for performance increases and forward compatibility in all other cases.

The ideal situation for me would be to swap out v1 and v2 dynamically depending on ie8 or not. To do this it would be necessary to identify ie8 in the scriptLoader.js, either with a custom code piece or by shifting bowser backwards in the loading chain.

Any thoughts?

**Comment by moloko** [comment]
sounds good to me
