### ISSUE TITLE
Bug in router navigateToParent() function when using nested pages

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#573]
There seems to be an issue routing back when the page is nested inside one or more menus.  This can be replicated on a simple course structure as follows:
- Page 1
- Menu 1
    - Page 2

Using the Vanilla theme, hit the < (back) button when on Page 2.  The screen gets stuck as Loading.... due to what I think is a problem with this line:
https://github.com/adaptlearning/adapt_framework/blob/293eb9fdba452053f1bf67e5737511d5e7c05d92/src/core/js/router.js#L117

**Comment by oliverfoster** [comment]
no parentid?

**Comment by oliverfoster** [comment]
For this one we've got:

```
                        var parentId = Adapt.findById(Adapt.location._currentId).get("_parentId");
                        var route = (parentId === Adapt.course.get("_id")) ? "#/" : "#/id/" + parentId;
                        Backbone.history.navigate(route, { trigger: true });
```
