### ISSUE TITLE
Sometimes jquery doesn't load fast enough for adapt.min.js

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#579]
Need to reevaluate script loader to wait for jquery.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/580

**Comment by zenduo** [comment]
Closing this as its now fixed in dev branch

**Comment by hrajotia** [comment]
on slow connection Modernizr.load completes before script get loaded.
