### ISSUE TITLE
Issue with router _canNavigate implementation

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#587]
There are some issues with the implementation of `_canNavigate` property.

This can be set to `false` by any component, at any time, and break routing to home or the back button  if it is not unset.  Furthermore, unless I'm mistaken it's essentially global, and one component "tidying up" after itself could disable the planned for behavior of another plugin.

Maybe we could open up some discussion on this?

**Comment by oliverfoster** [comment]
i'm going for an Adapt.trigger("router:lock") && Adapt.trigger("router:unlock") scenario. Whereby each lock is a +1 and each unlock is a -1. When the lock is at 0 the router is allowed to navigate. Could make this named much like the old lockedAttributes, whereby Adapt.trigger('router:lock', 'nameOfPlugin') will +1 to the total, but Adapt.trigger('router:unlock', 'nameOfPlugin') would only unlock the instance created by its name. Mean that each extension using router:lock is forced to manage its lock.

**Comment by oliverfoster** [comment]
https://adaptlearning.atlassian.net/browse/ABU-674 < fixed detailed here

**Comment by oliverfoster** [comment]
This is in already.
