### ISSUE TITLE
Issue with findDecendants()/getChildren() on component model

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#592]
There's a slight issue around `findDecendants()` and `getChildren()` in that the `_children` property does not exist in components, but sometimes a call to `findDecendants()` can end up recursively calling `getChildren()`.  

We require a check for undefined here to avoid the "Cannot read property 'where' of undefined error".

**Comment by aniketdharia** [comment]
:+1:
