### ISSUE TITLE
Feedback popup / modal window

### ISSUE THREAD

**Issue by Sethdickens** [adaptlearning/adapt_framework#601]
Hello!

When using the feedback option (Tutor?) the popup window can’t be closed by clicking outside of it. As an end user I think I would expect this. 

When you click outside the "Drawer" popup, you can close the window.

I suggest these two popups / modals should behave the same.

Thank you.

Seth.

**Comment by moloko** [comment]
Agreed, now logged in https://adaptlearning.atlassian.net/browse/ABU-641
