### ISSUE TITLE
Grunt improvments

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#623]
Couple of improvements needed:

**Tracking IDs**
We currently have `tracking-insert` running during the `dev` and `build` tasks. It's been requested to remove this from `dev`, and to also include a check to see if spoor's installed.

**Hard-coded course**
if the `_id` in `course.json` is anything other than `course`, the build processes fail. This needs to be more flexible.

**Comment by taylortom** [comment]
See also: https://github.com/adaptlearning/adapt_framework/issues/210, https://github.com/adaptlearning/adapt_framework/issues/369, https://github.com/adaptlearning/adapt_framework/issues/208 (particularly: https://github.com/adaptlearning/adapt_framework/issues/208#issuecomment-36640815)

**Comment by tomgreenfield** [comment]
New package 'columnify' awkwardly double line-breaks its output on Windows. As discussed, may be worth seeing if this can be cleaned up?
