### ISSUE TITLE
Missing dependencies - grunt build

### ISSUE THREAD

**Issue by Thoughtfulmonkey** [adaptlearning/adapt_framework#639]
Hi,  I was following the instructions on "Setting up your development environment" (https://github.com/adaptlearning/adapt_framework/wiki/Setting-up-your-development-environment), and ran into problems at:  $ grunt build

Unlesss I missed a step there were some missing modules that needed to be installed separately before it would work:

globule
findup-sync
resolve
stack-trace
file-utils
requirejs
object-assign
chalk
slash

**Comment by moloko** [comment]
hi @Thoughtfulmonkey - could I ask you to post this over at the [Technical discussion forum](https://community.adaptlearning.org/mod/forum/view.php?id=4) on the Adapt Community site? There's a lot more traffic on there so you will get more eyes on the problem you're having.

**Comment by brian-learningpool** [comment]
Is the documentation missing an npm install step?

**Comment by moloko** [comment]
nope, ```$ adapt create course``` does that for you in the background (I assume). certainly for me the node_modules folder is present after this command has run - I just tried it. I can immediately run ```$ grunt build ``` with no errors.

**Comment by taylortom** [comment]
No movement for a while, so closing.
