### ISSUE TITLE
Issue with tight coupling on course.json _globals property 

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#662]
There is quite tight coupling between the `_globals` section of `course.json` in version 2 and the plugins themselves.  This issue is a placeholder for conversations on how to make this work.

One option is for the Grunt build process to pull the properties and their default values into `course.json` -- if the attributes do not exist already.

In terms of the adapt_authoring project, when a plugin is added to a course, the code could append its defaults to the JSON, and allow the user to edit.

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
https://www.npmjs.com/package/underscore-deep-extend < will help

**Comment by taylortom** [comment]
Sounds good to me

**Comment by brian-learningpool** [comment]
So do we need some kind of a file included with the plugins themselves to indicate what the globals are and their default values?

**Comment by brian-learningpool** [comment]
Also, there seem to be case inconsistencies in the current sample course.json.

**Comment by brian-learningpool** [comment]
@taylortom, @oliverfoster, as it stands unless the relevant globals section is manually inserted into the course.json the framework won't work as expected.

@chucklorenz do you have any thoughts on this? I've tagged you in this issue as unless we come up with a way of automating the insertion of the globals it's going to require quite a big documentation effort across all the core plugins to let people know that they must insert the expected JSON.

**Comment by oliverfoster** [comment]
I suggest adding them to the schemas for the moment. Tom or I will sort out a grunt later. I'm back on Monday so I can take a look then.

**Comment by oliverfoster** [comment]
Done
