### ISSUE TITLE
Notify popup doesn't scroll on touch devices @bug

### ISSUE THREAD

**Issue by belal-almassri-spongeuk** [adaptlearning/adapt_framework#668]
If the notify feedback is larger than the screen hight then the user won't be able to scroll the rest of the content, it is fine on other devices.

The following code is the criminal suspect :-) in the core -> js -> views -> notifyView.js , any suggestion?

       resizeNotify: function() {
            var windowHeight = $(window).height();
            var notifyHeight = this.$('.notify-popup').height();

            if (notifyHeight > windowHeight) {
                this.$('.notify-popup').css({
                    'height':'100%', 
                    'top':0, 
                    'overflow-y': 'scroll', 
                    '-webkit-overflow-scrolling': 'touch'
                });
            } else {
                this.$('.notify-popup').css({
                    'margin-top': -(notifyHeight/2)
                });
            }
        },

**Comment by moloko** [comment]
master or develop? just wondering if related to this https://adaptlearning.atlassian.net/browse/ABU-972

**Comment by moloko** [comment]
this too maybe https://adaptlearning.atlassian.net/browse/ABU-983

**Comment by belal-almassri-spongeuk** [comment]
Hi @moloko, the issue I am having is on the develop branch.It seems like it is the same issue as this one https://adaptlearning.atlassian.net/browse/ABU-983. 

I will test the fix now. Thanks.

**Comment by oliverfoster** [comment]
Done
