### ISSUE TITLE
Unable to register for site

### ISSUE THREAD

**Issue by FrankBohac** [adaptlearning/adapt_framework#671]
Hi,

Someone closed the ticket that I had opened for this without verifying that the problem was fixed, which it isn't. I still am unable to log in to the site. I am also unable to register for the site, because I have run out of email addresses.

Please:
-  delete the attempted loginid registrations for frankbohac1 and frankbohac11. 
-  complete the registration process for loginid frankbohac using the email address bohac@bconserv.com
-  test the login process with my new credentials to make sure that they are actually working. If you need to change my password, that's fine.
-  send me the working and tested credentials so I can log in.

FYI: you should be careful to have your support staff not close a ticket until the person that opened the problem can verify that the problem has actually been fixed, which in this case it was not.

Frank

**Comment by FrankBohac** [comment]
still waiting for help on this one....

**Comment by moloko** [comment]
Really sorry about this, unfortunately admin access to the community site seems to be restricted to just a couple of users who are away at the moment. 
I believe we have logged a ticket with the support team who look after this server but I will double-check for you on Monday.

**Comment by moloko** [comment]
Support team have got back to me with updated credentials for you. 

I have tested them and they work for me, so have emailed them to the address bohac@bconserv.com

Please could you give these a try and let me know the outcome here?

**Comment by FrankBohac** [comment]
That works. I have closed problem #671
