### ISSUE TITLE
Unable to complete install process

### ISSUE THREAD

**Issue by FrankBohac** [adaptlearning/adapt_framework#672]
Hi,

I am trying to install the Adapt tool. I am following the instructions at: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin

and am stopped at the step:
To install:
 npm install -g grunt-cli 
 npm install -g adapt-cli 

When I run the second command, I am getting the errors as shown in the attached screenshot. How do I fix this?
![installproblem](https://cloud.githubusercontent.com/assets/13388123/8910757/612b7154-343d-11e5-8ca4-1030897587f9.jpg)

**Comment by moloko** [comment]
hi there

either you don't have Git installed at all or you do but the path to it is not set as an 'environment variable'
Did you install Git and did you reboot after doing so? (unfortunately some Git installs don't prompt you to do this but it's necessary for the changes in environment variables to kick in)

**Comment by FrankBohac** [comment]
Hi,

 

Yes, I have git installed and I have rebooted. Same problem. I tried uninstalling and reinstalling git, but still get the same error.

 

Frank

**Comment by FrankBohac** [comment]
Hi,

 

I figured out this one: when git is installed, you have to select an option to allow it to run from a command line. Once I re-installed and selected this option I made it past this problem.

 

Now I am getting the error in the attachment. How do I fix this one?

 

Frank

**Comment by FrankBohac** [comment]
Also: I am assuming that I can run the MOngDB remotely on a database server rather than on my desktop. Is this correct? If not: MongoDB installation options don’t have a Windows Desktop alternative (they only specify Windows Servers versions), so what version of MongoDB should I install?

**Comment by FrankBohac** [comment]
Can someone help me with this?

**Comment by taylortom** [comment]
Hi Frank, 

Yep, you should be able connect to a remote mongodb server (you provide the DB server settings during the install process).

I've successfully installed mongodb on a windows machine before - there's an installer on their website somewhere which should automate everything for you.

As far as I'm aware, it doesn't matter what version of mongodb you install; the latest should do fine.

**Comment by moloko** [comment]
@FrankBohac could you post these sorts of questions on https://community.adaptlearning.org/course/view.php?id=2 ? You'll not only get more of a response (because more people follow that) but others will also be able to see and search for your solution more easily

**Comment by moloko** [comment]
of course what I'm forgetting here is that you can't actually use the community site on account of #671

Apologies, please ignore previous message!!

**Comment by FrankBohac** [comment]
Still waiting 
![installproblem2](https://cloud.githubusercontent.com/assets/13388123/9009594/2b17bf1a-3757-11e5-9476-4670bb3f5521.jpg)
for help on this one

**Comment by moloko** [comment]
very odd, that. Just tried this myself, no problem:
![2015-07-31 19_42_15-cmder](https://cloud.githubusercontent.com/assets/1249597/9014759/58a80916-37bc-11e5-9152-c78171f81215.png)
Strange that it's asking for your username and password... do you have a proxy server in place where you are maybe? I've seen someone else posting about such a setup requiring a username/password...

**Comment by moloko** [comment]
FYI despite the unusual looking terminal (which is the rather lovely [cmder](http://gooseberrycreative.com/cmder/)) I am also running Win7

**Comment by FrankBohac** [comment]
No proxy server…

**Comment by oliverfoster** [comment]
You've misspelt adaptlearnng in your URL. Github will assume it's a private repo if it can't find a public one.

**Comment by FrankBohac** [comment]
Excellent! Thanks much.
