### ISSUE TITLE
Unable to install Adapt

### ISSUE THREAD

**Issue by FrankBohac** [adaptlearning/adapt_framework#679]
Hi,

Here is my next problem. I am still trying to install adapt and am getting the errors shown in the screenshot when I execute the nmp install.

Please let me know what to do to fix this.

Thanks
![installproblem3](https://cloud.githubusercontent.com/assets/13388123/9016177/bfcf1e4c-3783-11e5-9921-6e6c01951537.jpg)

**Comment by oliverfoster** [comment]
Out of interest why are you using the command prompt and not got bash? Everyone here uses got bash and it'd make it a lot easier for use to debug as we can assume environment concistancy.

**Comment by FrankBohac** [comment]
I am following the installation instructions as published: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin

**Comment by oliverfoster** [comment]
Fair enough. For reference at Kineo we use https://msysgit.github.io/ in the git prerequisites section. Gives you an application called git bash. It's a Linux/Unix/Mac style version of the command line which is the native home of node, npm, git etc.

Can you try running those commands in gitbash unless someone else can help you with the windows command prompt, I'm a bit stumped. Sorry.

**Comment by oliverfoster** [comment]
If you do end up installing git bash, make sure you select to install git in both terminal and command line when it asks, and go for 'shell integration' so that you get the right-click to 'open gitbash here' in windows explorer.

**Comment by oliverfoster** [comment]
I'm gonna check if anyone from the authoring tool team uses the command prompt on windows and if it's required for the authoring tool. I could be digging you a bigger hole.

**Comment by chucklorenz** [comment]
Hi Frank, sorry about your troubles, but glad you're getting good attention from Ollie. I have a suggestion that you might try in addition to Ollie's about using git bash. You can try this with or without git bash.

In the screen shot, installation fails with phantomjs. This is a module that is often used by developers for testing. It is not required for the normal activities of building courses. Here's a recent post with a bullet point that snuck past most of us that already have the authoring tool installed: https://community.adaptlearning.org/mod/forum/discuss.php?d=814 

So if you have no plans to join in hacking the authoring tool, why not try installing with  
`npm install --production` 

If you do try the --production option, please report the results here--good or bad. Cheers.

**Comment by chucklorenz** [comment]
Frank, I updated the [install instructions](https://github.com/adaptlearning/adapt_authoring/wiki/Installing-Adapt-Origin#3-run-the-install-script) to include that '--production' option.

**Comment by oliverfoster** [comment]
Thanks for stepping in chuck. --production mode is a good step. Can you let us know if you receive and further errors Frank?

**Comment by FrankBohac** [comment]
Hi,

 I reran the install using the --production switch and received the output as shown in the screen shot. It doesn't appear that anything happened. In the install instructions it says:

"Be patient; it can take a few minutes to complete. If any error occurs, read the output. Determine if you forgot to install one of the prerequisites or if one failed to install properly. If you need assistance troubleshooting, consult the Adapt community's Technical Discussion Forum. If this script completes successfully, you get to run the install script. 

The final script will help you configure the authoring tool. Most configuration questions will appear with a default answer already in place. And most times you can just accept the default values by pressing the Enter key. The only input you are required to provide are an email address and password for the super user account. (The questions about the super user account is not the same as the SMTP service or the master tenant.) The super user's email address and password will be used to login to the authoring tool. "

however, I didn't received any prompts for configuration options. I also don't understand the sentence: 

"If this script completes successfully, you get to run the install script.". What does this mean?

![installproblem4](https://cloud.githubusercontent.com/assets/13388123/9024368/6fbbd71c-3880-11e5-85f7-b0952dbd54eb.jpg)

**Comment by taylortom** [comment]
The install script referred to here is referencing `install.js` in the root directory of the authoring tool. This is run using `node install`, as explained a bit further on (below the 'note' blocks).

**Comment by FrankBohac** [comment]
Hi,

 

I didn’t understand your response. What do I do to fix this problem?

 

Frank

**Comment by taylortom** [comment]
Run `node install` in the root directory for the authoring tool.

**Comment by FrankBohac** [comment]
Didn’t work. I have attached the error that I get.

**Comment by moloko** [comment]
@FrankBohac attachment's missing...

**Comment by FrankBohac** [comment]
here it is again.

![installproblem5](https://cloud.githubusercontent.com/assets/13388123/9095356/b6c42cd4-3b6b-11e5-9bd9-715f7e986aad.jpg)

**Comment by taylortom** [comment]
It doesn't look as if `npm install` worked correctly. You should have a couple of listings for bson when you run: `npm list bson`

**Comment by FrankBohac** [comment]
Here is what I get when I execute npm list bson:

![installproblem6](https://cloud.githubusercontent.com/assets/13388123/9116644/49a4ee2c-3c1a-11e5-8c4d-52023dc434ba.jpg)

**Comment by taylortom** [comment]
You'll need to install the node dependencies again. If nothing much happens when you try `npm install --production`, you can try one of the following: 
- Delete the `node_modules` folder in the authoring tool root directory, then run `npm install --production` again.
- Manually install the bson package, and see what happens after that (if you choose this option, it's likely you'll need to manually install other packages).

**Comment by FrankBohac** [comment]
Hi,

 

What are ‘the node dependencies’ and how do I install them?

 

If I get that far: what is ‘the bson package’ and how do I manually install it? What other packages would I need to manually install and what is the procedure for this?

 

Frank

**Comment by taylortom** [comment]
The node dependencies are third-party packages which are required for the authoring tool to run. Npm handles these, so you just need to do either of the suggestions in my comment above.

**Comment by FrankBohac** [comment]
I deleted the node_modules folder and re-ran the npm install --production, which seemed to complete.

Then I ran the next step in the installation procedure which is 'node install', with the following result:

![installproblem7](https://cloud.githubusercontent.com/assets/13388123/9139387/d4b086b0-3cde-11e5-9335-d1b84c27f1da.jpg)

**Comment by FrankBohac** [comment]
still unable to proceed...

**Comment by jscampos** [comment]
Have you thought about installing in a VM running ubuntu? Also try running cmd as admin and restart the installation process in a new folder.

**Comment by FrankBohac** [comment]
I haven’t particularly thought about any approach: I am just looking for help to get the product installed so I can try using it.

 

I tried running as admin which didn’t work. I didn’t understand the ‘restart the installation in a new folder’ idea. You will need to describe how to do things rather than describe what things to do.

 

Thanks,

 

Frank

**Comment by taylortom** [comment]
Discussion has been moved here: https://github.com/adaptlearning/adapt_framework/issues/762
