### ISSUE TITLE
update jquery.a11y and jquery.onscreen to latest fixes

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#696]
* jquery.a11y issue/16: trigger window.scroll on popup scroll https://github.com/adaptlearning/jquery.a11y/commit/00c2db06ce22ecdd6ffbc1b38470fe7f9cac5c06
* jquery.onscreen issue/2: debounce scroll check
https://github.com/adaptlearning/jquery.onscreen/commit/166ba30feb7fa0c43c76db61e95e0f68b45cc13f

**Comment by moloko** [comment]
can this be closed now?

**Comment by oliverfoster** [comment]
yup
