### ISSUE TITLE
Conditionally bundle only plugins used as part of the build process

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#723]
As part of the build process it would be great if only the extensions and components used within a course were bundled as part of the build.  I think with the upcoming release of the authoring tool we might be able to facilitate this.

In the authoring tool now, the `config.json` file contains `_enabledComponents` and `_enabledExtensions`.  The Gruntfile could read from these keys (if available) and then affect the glob pattern with regards to bundling the associated JavaScript.  Possible advantages of this would be:
* shorter build time
* less compiled code / less possibility for errors, e.g. by excluding code that isn't used yet and might adversely affect the course
* faster page loads / better performance, i.e. less time for the SPA to bootstrap
* smaller build packages

**Comment by moloko** [comment]
+1 for this

**Comment by taylortom** [comment]
+1

How do you propose we configure this on the framework side? We'd need to have an additional config file somewhere.

Is this needed in the immediate future, or can we put off until we discuss the state of the gruntfile/possibility for swapping grunt for something different?

**Comment by brian-learningpool** [comment]
From the framework side, for consistency I think it makes sense to add the attributes to `config.json`.  Another file isn't really necessary here.

This isn't something that's required immediately, but I would like us to discuss this as part of either a performance tune-up of the Gruntfile or whatever is going to replace it.  I'd be curious how much faster the Gruntfile performs when only the essential JavaScript is compiled.

**Comment by taylortom** [comment]
I created a test for this that we tried internally last year, I'll see if I can dig it out and repurpose.

**Comment by brian-learningpool** [comment]
@taylortom, did you get anywhere with this?

**Comment by taylortom** [comment]
Ongoing work happening here: https://github.com/taylortom/adapt_framework/tree/issue/ABU-680

**Comment by taylortom** [comment]
Also going to pull in a fix for https://github.com/adaptlearning/adapt_authoring/issues/887
