### ISSUE TITLE
Adapt content does not scroll in iOS iFrames

### ISSUE THREAD

**Issue by darloboy101** [adaptlearning/adapt_framework#751]
Adapt 2.0 content (using the Vanilla theme) does not scroll or behave responsively within an iFrame on an iOS device.

It is well-established that iOS is fussy in its handling of scrolling content within iFrames. The standard advice is to apply something like the following to the html and body elements which are to appear within the iFrame (e.g. http://davidwalsh.name/scroll-iframes-ios)

`html {`
`height: 100% !important;`
`-webkit-overflow-scrolling: touch !important;`
`overflow-y: scroll !important;`
`}`
`body {`
`overflow-y: scroll !important;`
`height: 100% !important;`
`}`

As currently set-up, applying these styles to Adapt (with or without the height:100%) breaks more than it fixes (e.g. large amounts of scrollable white space are introduced across all devices).  Testing with and without trickle, the effect is the same.

**Comment by LukaszGrela** [comment]
This is similar to this issue: https://github.com/adaptlearning/adapt_framework/issues/585

**Comment by moloko** [comment]
this should be resolved with the new `_scrollingContainer` configuration in Adapt v4
