### ISSUE TITLE
Changing screen sizes in `theme.json` not persisted when running `watch`

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#752]
When you change the breakpoints in the theme's `theme.json` and run `grunt dev`, some actions that cause the build will also not load the custom breakpoints and will fall back to the defaults set in `src\core\js\models\configModel.js`.

The only way to resolve this is to cancel the `grunt dev` and either re-run it or run `grunt build`.

**Comment by richsearlesponge** [comment]
adding create-json-config to the end of the courseJson watch config `grunt\config\watch.js` seems to fix this issue.
```
courseJson: {
        files: ['<%= sourcedir %>course/**/*.json'],
        tasks : ['jsonlint', 'check-json', 'copy:courseJson', 'create-json-config']
    },
```

**Comment by andrewhosgood** [comment]
Can we add this in?

**Comment by oliverfoster** [comment]
yup, i'll +1 if you can pr
