### ISSUE TITLE
Validating progress on single component content object

### ISSUE THREAD

**Issue by gorhgorh** [adaptlearning/adapt_framework#755]
I have a really simple CO containing a single article/block/component, it is not really tall, so on desktop with a big screen it is not "completed" when just shown. 

if i reduce the window size and reload everything validate correctly.

**Comment by gorhgorh** [comment]
@oliverfoster found the cause, so I'll leave him close this issue when the fix is pushed

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/757 https://github.com/adaptlearning/adapt_framework/pull/758

I think Alan did it already.
