### ISSUE TITLE
Cleaning the build folder on new build

### ISSUE THREAD

**Issue by gorhgorh** [adaptlearning/adapt_framework#761]
I just remarqued that the build process does NOT clear the build folder in the clean task, to avoid possible leftovers of previous builds (i'm playing with generating a zip out of the content and it ended up inside the next batch of zip) or caching problem, I would favor cleaning it as well, since all of the assets/files will be overwritten anyway.

If nobody have a specific need for this behavior, I'll submit a pr to reflect this.

feel free to comment on this non existential issue :)

**Comment by zenduo** [comment]
I have no issue with this and would see it as an improvement. More often than not I have to clear my build files to remove spoor generated files which weren't needed. 

However, I have a feeling there was a reason why we never did this. Possibly to do with people customising files in the build folder. I'll let others comment on that. 

If you fancy making a "grunt publish" which emptied the build folder and generated a zip of the project this would be cool... Just an idea though :)

**Comment by gorhgorh** [comment]
sound more reasonable than my initial option ! more flexibility is better :)

**Comment by taylortom** [comment]
I implemented @gorhgorh's suggestion in https://github.com/adaptlearning/adapt_framework/commit/283c8bd2818aaef3d8ee2a793b30e4ec9cf4b8a2#diff-27b412a2892c303280cac630c6acee84. I don't particularly have a problem with enforcing users to keep edits in src.
