### ISSUE TITLE
still unable to complete the install

### ISSUE THREAD

**Issue by FrankBohac** [adaptlearning/adapt_framework#762]
Hi,

I haven't heard back from anyone on my earlier issue for about a month. Can someone help me finish the installation?

Frank

**Comment by jscampos** [comment]
What is your problem? OS? and what version are you trying to install?

**Comment by FrankBohac** [comment]
I am running Windows 7. I am trying to install the latest version of adapt (what I get when I download from your site).

**Comment by taylortom** [comment]
Hi Frank, 

Welcome back. Can you first confirm that you have the required command line utilities installed. Please post back the results from running the following in a bash window (these all simply give you the currently installed version, if any aren't installed, bash will tell you):
- `npm --version`
- `node --version`
- `git --version`
- `mongo --version`
- `adapt --version`

**Comment by FrankBohac** [comment]
Hi,

 

Not sure what bash is. I assume you mean ‘dos window’. Here is the screen shot with the results:

 

Frank

**Comment by moloko** [comment]
bash - if you've installed Git for Windows you should have a program called 'git bash' installed as well, it looks like [this](https://git-for-windows.github.io/img/gw1.png)

it's better to use this or something similar (e.g. [cmder](http://cmder.net/)) for command line operations as the Windows command line is somewhat lacking...

**Comment by moloko** [comment]
oh, and there was no screenshot included

are you trying to install the framework or the authoring tool?

**Comment by FrankBohac** [comment]
Here is the screen shot again. When I reply to your emails and attach it to the reply, it gets lost for some reason.

I am trying to install the authoring tool (what is the framework?).

![screenshot](https://cloud.githubusercontent.com/assets/13388123/10430992/490e693a-70b7-11e5-9f2b-2de90f9dfbb4.jpg)

**Comment by andrewhosgood** [comment]
Looks like you need to install MongoDB. The instructions I used can be found here: http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/#install-mongodb-for-windows

**Comment by jscampos** [comment]
The command is mongod, not mongo.

**Comment by moloko** [comment]
There's a good explanation of the difference between the framework and the authoring tool [here](https://community.adaptlearning.org/mod/forum/discuss.php?d=958#p4588)

**Comment by taylortom** [comment]
@jscampos the mongo command runs the mongo shell; we were merely trying to establish that @FrankBohac had installed all of the dependencies for Adapt.

**Comment by jscampos** [comment]
Sounds good.

**Comment by FrankBohac** [comment]
Hi,

 

I installed the mongo db on a DB server rather than on my laptop: I was told I could point to the location of the db server at some point during the install process. Is this not correct?

 

Frank

**Comment by FrankBohac** [comment]
Thanks. I was hoping to get started with the authoring tool, evaluate whether Adapt looked useful and if so, perhaps proceed with the framework. Is this reasonable?

**Comment by taylortom** [comment]
@FrankBohac I'd suggest that maybe getting involved in the technical stuff a perhaps a bit premature then. 

Instead, you can have a look at our [v2.0 test package](https://rawgit.com/adaptlearning/adapt-test-package/master/standard/build/index.html). We can also probably sort out getting you login details to try a pre-installed demo version of the tool.

**Comment by FrankBohac** [comment]
Hi,

 

The v2.0 test package looks nice, but I was hoping to try out the authoring tool…

 

Frank

**Comment by taylortom** [comment]
Also to note that you should be posting issues related to the authoring tool here: https://github.com/adaptlearning/adapt_authoring/issues

This repository is for the framework.
