### ISSUE TITLE
adapt.js - missing underscore from currentLocation

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#792]
I think in the line https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/adapt.js#L22 there should be an underscore for `currentLocation`, it should read `Adapt.location._currentLocation` as it is used e.g. in router https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/router.js#L147

**Comment by LukaszGrela** [comment]
Same in Develop and Master branch

**Comment by LukaszGrela** [comment]
reopening as not yet in master

**Comment by moloko** [comment]
should be in master now?

**Comment by LukaszGrela** [comment]
I meant to keep it open until this fix from dev will be merged into master

**Comment by moloko** [comment]
I merged dev into master earlier today...
