### ISSUE TITLE
Unbuild course

### ISSUE THREAD

**Issue by oghmios** [adaptlearning/adapt_framework#795]
Hi, I have a build course, but I lost the initial files, and I did some plugins than i want recover. Have I any solution to unbuild my project or anything to recover the extensions?

**Comment by taylortom** [comment]
Unfortunately, the published zip doesn't come with source files, only the concatenated (and minified) JS.

Do you still have the authoring tool with your course running?

**Comment by oghmios** [comment]
No, i'm not using authoring tool because many of the extensions I use didn't work on it. Thank you for all
