### ISSUE TITLE
Blank space in assessment

### ISSUE THREAD

**Issue by anujgtm** [adaptlearning/adapt_framework#799]
![white-space-bug](https://cloud.githubusercontent.com/assets/6188996/10898992/0ccbb9b6-8235-11e5-8ef1-891e85db82f2.jpg)
I have cloned the latest version of Adapt framework. After building it using either rub or grunt,  when I navigate to assessment page it's showing a blank space below the first question. In terms of functionality trickle works as expected.

**Comment by oliverfoster** [comment]
which browser are you in? and which os?

**Comment by andrewhosgood** [comment]
Duplicate: https://github.com/adaptlearning/adapt-contrib-trickle/issues/60
I am on Windows, Chrome and get the same issue with a completely new demo course.

**Comment by moloko** [comment]
#797 should fix this, could you give it a try and +1 it if it does?

**Comment by samumist** [comment]
I had a similar problem with trickle with the latest framework. I can scroll a page (which should stopped by trickle) with quite a lot blank space.

I'm on Mac with chrome.

**Comment by andrewhosgood** [comment]
Can confirm https://github.com/adaptlearning/adapt_framework/pull/797 fixed it for me!
+1

**Comment by oliverfoster** [comment]
Could you +1 797 in that case? @andrewhosgood

**Comment by samumist** [comment]
#797 fixed it for me too.
+1

**Comment by anujgtm** [comment]
Awesome #797 fixed the issue :)

:+1:
