### ISSUE TITLE
Reference error: text not defined

### ISSUE THREAD

**Issue by anujgtm** [adaptlearning/adapt_framework#800]
After building a fresh version of the framework when navigating to presentation componetnts, console shows ReferenceError: text not defined error. 

![missing-text](https://cloud.githubusercontent.com/assets/6188996/10899029/6ed9457e-8235-11e5-87fa-1e0867a5170e.jpg)

**Comment by oliverfoster** [comment]
this is fixed in pr > https://github.com/adaptlearning/adapt_framework/pull/797

**Comment by moloko** [comment]
just tried that PR, definitely makes this error disappear

**Comment by anujgtm** [comment]
Great fixed in #797 

:+1:
