### ISSUE TITLE
"page", article, block, component - missing _classes adds 'undefined' to the class list

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#804]
I've noticed if I skip the `_classes` property then `undefined` class is added, could we add to the models that support `_classes` default empty value so we could then skip unused property?

**Comment by oliverfoster** [comment]
Here are two examples:
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/componentView.js#L12
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/articleView.js#L11


You'll need to go through each view to check them:

https://github.com/adaptlearning/adapt_framework/tree/master/src/core/js/views

**Comment by LukaszGrela** [comment]
wouldn't work modification of the models? e.g. for ArticleModel:

```
define(function(require) {

	var AdaptModel = require('coreModels/adaptModel');
	var Adapt = require('coreJS/adapt');

    var ArticleModel = AdaptModel.extend({
        _parent:'contentObjects',
    	_siblings:'articles',
        _children: 'blocks',
        _classes: ''
    });

    return ArticleModel;

});

```

**Comment by oliverfoster** [comment]
you could try adding it here > https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L18

**Comment by LukaszGrela** [comment]
that's fine, I will do this on each "view" class
