### ISSUE TITLE
Tight coupling between some components

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#805]
There are some components which either inherit from another component, e.g. GMCQ and MCQ, or are dependent on another component, e.g. Hot Graphic and Narrative.  Should we plan on de-coupling these, so each component is standalone?

**Comment by oliverfoster** [comment]
was thinking about trying to kill two birds with one stone. https://adaptlearning.atlassian.net/browse/ABU-699 < size switcher?

**Comment by moloko** [comment]
@brian-learningpool https://adaptlearning.atlassian.net/browse/ABU-691

**Comment by moloko** [comment]
we discussed these at the start of the current sprint and the thinking was that maybe this should be part of Framework v3

**Comment by brian-learningpool** [comment]
@moloko I think that it would be great to tidy this up as part of v3.  The new superclass approach mentioned in the JIRA ticket sounds like a potential solution.

**Comment by moloko** [comment]
@brian-learningpool there's lots of things like this that I'd like to sort out as part of v3. Want to give the whole framework's structure a really good re-think and tidy-up - so if you spot anything else like this please do log a ticket in Jira.

**Comment by chris-steele** [comment]
@moloko looks like this can be closed, would you say?

**Comment by moloko** [comment]
yes, I think best dealt with under https://github.com/adaptlearning/adapt_framework/issues/835
