### ISSUE TITLE
More than two components

### ISSUE THREAD

**Issue by oghmios** [adaptlearning/adapt_framework#809]
Hi,
In my project, I put 3 or 4 components for block, writting in "_layout" left or right more than 1 time in the same block. I use html classes to order my components in css, but in some cases this creates visual errors in blocks. 
Is obligated to use only two components for block or I can change any variable to say that I will put more than two? 
Visual errors are provided for errors in css or for another question relationed with the number of components?

Thank you for all

**Comment by brian-learningpool** [comment]
Hi @oghmios, you should only have a maximum of two components in a block.  It's not enforced by the framework, but if you were using the adapt_authoring tool this would enforce it for you.
