### ISSUE TITLE
Editing the source code of the header and footer of the framework.

### ISSUE THREAD

**Issue by jscampos** [adaptlearning/adapt_framework#815]
Is there a way to edit the header and footer sections of the courses? I want to enable pinch and zoom, and add a course wide footer. Any tips help.

**Comment by harrygfox** [comment]
@jscampos +1

I'd be really keen to implement a footer that allows navigation between articles - simply: `next` `previous`

**Comment by brian-learningpool** [comment]
@harrygfox, you could develop this as an extension which attaches routes to Next and Previous buttons.

**Comment by belal-almassri-spongeuk** [comment]
The easiest way you can use a text component as the last component in the content object and in the text component body add the following HTML.
<a href='#/id/co-05' class='button'>Go to this page</a>

**Comment by moloko** [comment]
The [quicknav extension](https://github.com/cgkineo/adapt-quicknav) allows navigation between pages

**Comment by jscampos** [comment]
I will check out that extension. Thanks for the link.

**Comment by jscampos** [comment]
After a couple of updates I got it to do what I wanted, thanks!
