### ISSUE TITLE
How is created the js for adapt?

### ISSUE THREAD

**Issue by oghmios** [adaptlearning/adapt_framework#821]
Hi, I am modifying your extensions and components to use like I need but i will know how you call all methods and classes. How is estructured your javascript?

Thank you for all

**Comment by moloko** [comment]
Hi @oghmios if you have any specific questions around this, could you ask them on the [forums](https://community.adaptlearning.org/mod/forum/view.php?id=4) or [gitter chat](https://gitter.im/adaptlearning/adapt_framework)?
