### ISSUE TITLE
how to add adapt tool

### ISSUE THREAD

**Issue by maz1989** [adaptlearning/adapt_framework#824]
how can i add adapt tool to my asp.net project 
to allow the use to create courses from my web site using adapt e learning tool

**Comment by moloko** [comment]
You should look at the [Adapt Authoring Tool](https://github.com/adaptlearning/adapt_authoring) since that already does what you're talking about... even if you don't want to use it you can look at how it's structured since you'll be wanting to do the same thing/something very similar

**Comment by maz1989** [comment]
thanks

but i not understand why i need gif and nodejs can i add html and js files only

**Comment by moloko** [comment]
if you don't need the ability to add/remove any of the plugins then you could do it solely using .json plus any assets you might need like jpg/gif/png/mp4

I would suggest you [get comfortable using the framework](https://github.com/adaptlearning/adapt_framework/wiki) first, this will help you to understand what you can and can't do.
