### ISSUE TITLE
Technical TODO list

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#835]
This is a placeholder ticket for items which could be considered technical debt.  @oliverfoster and @moloko have some ideas for re-work.  Please add the details below, guys.

**Comment by oliverfoster** [comment]
add es6 support - using a transpiler (?) https://babeljs.io/

**Comment by oliverfoster** [comment]
remove core require mappings "coreJS" "coreViews" etc

**Comment by oliverfoster** [comment]
rework event cascades from component to course so that they trigger in order rather than in reverse

**Comment by oliverfoster** [comment]
add questionModel and component models

**Comment by oliverfoster** [comment]
move core theme dependencies from theme to core

**Comment by oliverfoster** [comment]
add global text support to framework

**Comment by oliverfoster** [comment]
move scrolling body from html+body tags to nested psuedo html+body tags (for ios moddle iframe scrolling support). remove scrollto library and replace with velocity scrolling.

**Comment by oliverfoster** [comment]
split libraries folder into "compiled libraries" and "static libraries"

**Comment by oliverfoster** [comment]
backbone alternatives

**Comment by oliverfoster** [comment]
ui component alternatives https://www.polymer-project.org/1.0/

**Comment by moloko** [comment]
[TypeScript](http://www.typescriptlang.org/)??

**Comment by moloko** [comment]
it would certainly be interesting to use something like Polymer to handle UI stuff as many UI elements are shared across different plugins - e.g. the slider UI is used in contrib-slider, confidenceSlider and linkedConfidenceSlider - crazy duplication. Separating these out would allow all three components to take advantage of the same UI component.

(although in this particular instance if we were to drop support for IE8 & 9 we could just use the HTML5 'range' input type)

**Comment by moloko** [comment]
If not TypeScript, support for [Flow](http://flowtype.org/) would be great

**Comment by moloko** [comment]
Possible alternatives for MediaElement:
* [PayPal accessible player](https://paypal.github.io/accessible-html5-video-player/)
* [AblePlayer](https://github.com/ableplayer/ableplayer)
* [Plyr](https://plyr.io/) [more](http://www.noupe.com/design/html5-plyr-is-a-responsive-and-accessible-video-player-94389.html)
Need to do a feature-comparison table to work out which is best.

**Comment by davidpesce** [comment]
+1 for es6 modules and typescript!

**Comment by gorhgorh** [comment]
+1 for es6 + flow :)

**Comment by moloko** [comment]
if we do drop support for IE8 in a future version, we should consider starting to use some of the new HTML semantic elements like `<header>` and `<nav>` where appropriate

**Comment by corymayfield** [comment]
@moloko There's no reason why we can't use semantic elements like `<header>` and `<nav>` now. For IE8 support which a lot of people (especially corporates in AUS) just upgraded too from IE6, you can use a polyfill such as html5shiv (https://github.com/aFarkas/html5shiv) - which Bootstrap 3.3.6 uses to support IE8 compatibility.

**Comment by moloko** [comment]
Look at using webpack (from #1364)

**Comment by moloko** [comment]
I think point 8 is now done in that libraries with the `.min.js` are assumed to be static i.e. they are not touched by the minification process... or have I misunderstood?

**Comment by oliverfoster** [comment]
Kind of, my description is terrible.

Some modules are part of the boot loader and browser normalization, others are part of the framework.

The framework modules all used to be compiled into adapt.min.js - now they aren't because of compilation speed issues.

It's the distinction between the way they're loaded and their intent which I wanted to make clear, whilst also getting a handle on the compilation process. 

I don't think scriptloader should be in the same folder as backbone because of the architectural distinction between the two.

I think this will be entirely solved when we turn everything into plugins.
