### ISSUE TITLE
documentation for properties.schema files

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#837]
At the moment it can be quite hard work getting these up and running as there's no documentation, so it's a case of having to dig around to find a similar property already defined somewhere.

Some documentation would remove the barrier to getting these implemented for community plugins that don't yet support them.

**Comment by dancgray** [comment]
@chucklorenz started some documentation here: https://github.com/chucklorenz/demo-wiki/wiki/Properties-Schema

**Comment by chucklorenz** [comment]
https://github.com/adaptlearning/adapt_authoring/wiki/Properties-Schema  
Most of it is done, but is still missing an explanation of schemas for extensions, menus, and themes.
