### ISSUE TITLE
Accordion - iPad on Moodle shoots to top of page

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#845]
_From @hmaffin on November 18, 2015 13:4_

When opening an accordion section on iPad2 (ios9.1) in Moodle 2.7 in a new window, you are shot back to the top of the page and have to scroll back down to see the open accordion.

_Copied from original issue: adaptlearning/adapt-contrib-accordion#70_

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 13:8_

Also on iPad 4 (ios7) after clicking a section you get a white page overlay

**Comment by chris-steele** [comment]
@hmaffin I think this was down to an iframe (and that issue we closed earlier?)

**Comment by hmaffin** [comment]
Yes i believe it was! Close away!

**Comment by chris-steele** [comment]
Awesome, thank you!
