### ISSUE TITLE
Assessment Results - _bands only work if _score used in increasing value

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#846]
_From @kevindoherty30 on November 27, 2015 16:52_

I have been using the Assessments results component and noticed an issue with the bands.

If the bands are all entered in increasing score value then it will work correctly within the component.
However, if you enter them in decreasing value then it stops working correctly.

I had set the component up to give a congratulatory message when a user scores above 83% - this was the first band I entered.
I then added another band with 0% as the starting range so that any user that scores between 0-82% will receive a message stating they have not passed.

Upon testing, the feedback appeared correctly if the assessment was failed but if you passed the assessment it would take the feedback from the 0-82% range and state you did not pass despite getting above the correct range for the 83%+ feedback.

I removed the bands and placed them in order of increasing value so the first item was 0%, the second item was 83% - upon doing this we received the correct messages for failing and passing.

Whilst I understand that this would make sense logically, a lot of users could potentially place the feedback messages from highest to lowest, which will not work correctly.

_Copied from original issue: adaptlearning/adapt-contrib-assessmentResults#16_

**Comment by guywillis** [comment]
_From @moloko on November 30, 2015 11:26_

https://adaptlearning.atlassian.net/browse/ABU-1145

**Comment by moloko** [comment]
fixed in [v2.0.2 of assessmentResults](https://github.com/adaptlearning/adapt-contrib-assessmentResults/releases/tag/v2.0.2)
