### ISSUE TITLE
Hotgraphic - completion when changing orientation on mobile device

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#848]
_From @Ariiz91 on May 8, 2015 11:20_

Scenario: There is hot graphic component with 3 items to view.

When using hot graphic component in landscape orientation, and switching to portrait orientation to complete some of the items. Results in items that were viewed in portrait not being marked as complete when switching back to landscape orientation.

Steps to reproduce - use landscape orientation:
1. Click on the first item - close pop up - now item will be marked as complete 
2. Switch orientation (hot graphic component is changed to slider)
3. Now click on '+' for other two items
4. Go back to landscape orientation
5. The other two items you just viewed in portrait orientation are not marked as complete.

_Copied from original issue: adaptlearning/adapt-contrib-hotgraphic#89_

**Comment by moloko** [comment]
fixed in 79b97b8
