### ISSUE TITLE
Hotgraphic - hide pins

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#849]
_From @sandervanzijl on July 10, 2015 9:28_

as a feature request: could someone add the possibility to add a hotspot, without placing a pin on top of it.

this way I could use a maingraphic that already has areas on it and instruct the learners to click the areas, in stead of clicking the pins.

_Copied from original issue: adaptlearning/adapt-contrib-hotgraphic#94_

**Comment by guywillis** [comment]
_From @markl55 on July 15, 2015 16:4_

Hi Sander,

Following on from the conversation in the forum this feature exists using the "Use graphics as pins" should be "false".

If you are happy with that would you mind replying so that we can close this issue?

Thanks,

Mark.

**Comment by guywillis** [comment]
_From @sandervanzijl on September 23, 2015 10:28_

this is not what I mean. I want normal hotspot, but without seeing the pins. or better, with the possibility to change the pins graphic.

**Comment by guywillis** [comment]
_From @ciaranlp on September 23, 2015 14:10_

Hey sander, the pin icon is set in the less,

the pin icon is set by the `.hotgraphic-graphic-pin-icon:before` `content: "\e60f";` this can be changed to any of the other icons included in the vanilla font.

Otherwise to hide the pin completely but still clickable you can set the `.hotgraphic-graphic-pin-icon` to`visibility: hidden;` **NOTE NOT** `display: none;` as the parent div requires this content for its height and width dimensions, then set the `.hotgraphic-graphic-pin` to `background-color: transparent;`

Hope that helps 

Ciaran

**Comment by sandervanzijl** [comment]
Hi guy, I got a status update, because you changed the title.

Nice to see that it is possible to hide the pin. however... To me this is useless because we can not edit in the framework. we only edit in the authoring tool. so hopefully this functionality will find its way there as well.

**Comment by chris-steele** [comment]
Propose we close this as it's another stale issue and this is not a feature that has had repeat requests.
