### ISSUE TITLE
Hotgraphic - _graphic.title is no longer required and is not consistent with other plugins

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#850]
_From @dancgray on July 23, 2015 14:39_

_Copied from original issue: adaptlearning/adapt-contrib-hotgraphic#101_

**Comment by tomgreenfield** [comment]
Fixed in https://github.com/adaptlearning/adapt-contrib-hotgraphic/commit/b89443a8d8265763fa873d65bf76f250a75225cf.
