### ISSUE TITLE
MCQ - Individual feedbacks with multiple attempts

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#852]
_From @danielghost on May 22, 2015 15:31_

Is there a reason why https://github.com/adaptlearning/adapt-contrib-mcq/commit/9764c043842cb21bffc1313cdf7e984b741bb23d doesn't offer different feedbacks for multiple attempts like other feedback types?

_Copied from original issue: adaptlearning/adapt-contrib-mcq#94_

**Comment by guywillis** [comment]
_From @moloko on May 22, 2015 19:38_

To be honest, it's because we were just restoring functionality that is currently available in the master branch (of adapt_framework) but which got removed during a re-write of questionView.js

As this didn't originally have 'not final' option-specific feedback we didn't even think to put it in...

You make a good point though.

I think this should be a question for the design team as to whether this would be useful or they are happy to stick with generic 'not final' feedback.

**Comment by moloko** [comment]
@danielghost I think @chris-steele has done this here: https://github.com/chris-steele/adapt-contrib-mcq/commit/f7c2cf7f2ad0a2ce84ba3a659c7092b82a112fce - please feel free to set up a PR if you think this should be in core

**Comment by chris-steele** [comment]
@moloko @danielghost just thinking, MCQs with individual feedbacks are set up without a correct answer - so would there ever be a point to having multiple attempts at a question you can't get right? And if someone said, "well, it would be good to let the user go through each option", why not use something like more appropriate like hot text?

**Comment by moloko** [comment]
@chris-steele I wouldn't say it's always the case that 'MCQs with individual feedbacks are set up without a correct answer'

**Comment by moloko** [comment]
@chris-steele are you still actively working on this?

**Comment by chris-steele** [comment]
@moloko no, this has gone stale it would seem. I did recently customise this component to allow banded feedback based on the sum of selected option weights (uk-lcel-402408). It's probably at a similar level of usefulness as attempt-based feedback. Customisations like this seem to be done now and again, so we'd have to ask which customisations are frequent enough to warrant merging.
