### ISSUE TITLE
MCQ - odd code placement

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#853]
_From @moloko on October 14, 2015 13:45_

shouldn't lines 126 & 127:
```
this.$('label').removeClass('selected');
this.$('input').prop('checked', false);
```
be part of the function `deselectAlItems`?

_Copied from original issue: adaptlearning/adapt-contrib-mcq#115_

**Comment by moloko** [comment]
can address things like this when we do #921
