### ISSUE TITLE
Media - v1.1.0: Video component, play button issue, in ie8 (XP)

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#855]
_From @kineoluke on May 21, 2014 13:29_

When clicking quickly on, or between, the two play buttons (smaller one in the bottom left, bigger one on the actual video), I can produce either of two bugs:

(1) The bigger play button appears and then won't disappear even as the video continues to play behind it; when this happens the smaller (bottom-left) button doesn't change visual state to a pause icon (although it does pause the video): 

![capture-2](https://cloud.githubusercontent.com/assets/7656268/3040414/9b4427e2-e0eb-11e3-85ce-a22bde10a39a.JPG)

(2) The loading/buffering icon appears and animates perpetually:

![capture](https://cloud.githubusercontent.com/assets/7656268/3040323/b242dbf6-e0ea-11e3-9c95-fbf52b83b2f6.JPG)

_Copied from original issue: adaptlearning/adapt-contrib-media#39_

**Comment by guywillis** [comment]
_From @darylhedley on May 22, 2014 16:8_

I think we should take into consideration the amount of times someone is likely to click the play button in a repetitive motion?

**Comment by guywillis** [comment]
_From @kineoluke on May 23, 2014 10:15_

I think this is a triple-click issue, or double-clicking and dragging slightly by mistake. Sometimes one can see the text behind or around the video component being unintentionally selected. Perhaps it's interrupting the triggers/clicks somehow.

**Comment by moloko** [comment]
closing as relates to v1
