### ISSUE TITLE
Media - The video player has gigantic size

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#856]
_From @LukaszGrela on January 23, 2015 9:33_

I have an issue that I can't tackle, the mediaelement of media component starts with gigantic size, exactly the full width of the browser (See code below - from FF35.0).

IE11.0.9600.17501 this automatically resolves itself (You can see brief large player but then it returns to expected size)
FF35.0 you have to resize browser or click play so the player returns to expected size
Chrome 39.0.2171.99 m same as FF

I have also tried with latest mediaelement

    <div style="width: 1423px; height: 800px;" id="mep_0" class="mejs-container svg mejs-video">
        <div class="mejs-inner">
            <div class="mejs-mediaelement">
                <video src="course/en/video/03_01_015.mp4" preload="none" poster="course/en/video/03_01_015-small.jpg" style="width: 100%; height: 100%;" width="1423" height="800">
                    <source src="course/en/video/03_01_015.mp4" type="video/mp4">
                    <source src="course/en/video/03_01_015.ogv" type="video/ogg">
                    <track kind="subtitles" src="course/en/video/03_01_015_sub.srt" srclang="en">
                    <track kind="subtitles" src="course/pl/video/03_01_015_sub.srt" srclang="pl">
               </video>
            </div>
            <div class="mejs-layers">
                <div style="display: none; width: 100%; height: 100%;" class="mejs-captions-layer mejs-layer">
                    <div class="mejs-captions-position mejs-captions-position-hover"><span class="mejs-captions-text"></span></div>
                </div>
                <div style="display: none; width: 100%; height: 100%;" class="mejs-chapters mejs-layer"></div>
                <div style="background-image: url(&quot;course/en/video/03_01_015-small.jpg&quot;); width: 100%; height: 100%;" class="mejs-poster mejs-layer">
                    <img src="course/en/video/03_01_015-small.jpg" width="100%" height="100%">
                </div>
                <div style="display: none; width: 100%; height: 100%;" class="mejs-overlay mejs-layer">
                    <div class="mejs-overlay-loading"><span></span></div>
                </div>
                <div style="display: none; width: 100%; height: 100%;" class="mejs-overlay mejs-layer">
                    <div class="mejs-overlay-error"></div>
                </div>
                <div style="width: 100%; height: 770px;" class="mejs-overlay mejs-layer mejs-overlay-play">
                    <div style="margin-top: -35px;" class="mejs-overlay-button"></div>
                </div>
            </div>
            <div style="display: block; visibility: hidden;" class="mejs-controls">
                <div class="mejs-button mejs-playpause-button mejs-play">
                    <button type="button" aria-controls="mep_0" title="Play/Pause" aria-label="Play/Pause"></button>
                </div>
                <div style="width: 100px;" class="mejs-time-rail">
                    <span style="width: 90px;" class="mejs-time-total">
                        <span style="display: none;" class="mejs-time-buffering"></span>
                        <span class="mejs-time-loaded"></span>
                        <span class="mejs-time-current"></span>
                        <span class="mejs-time-handle"></span>
                        <span class="mejs-time-float">
                            <span class="mejs-time-float-current">00:00</span><span class="mejs-time-float-corner"></span>
                        </span>
                    </span>
                </div>
                <div class="mejs-time">
                    <span class="mejs-currenttime">00:00</span><span> | </span><span class="mejs-duration">00:00</span>
                </div>
                <div class="mejs-button mejs-captions-button">
                    <button type="button" aria-controls="mep_0" title="Captions/Subtitles" aria-label="Captions/Subtitles"></button>
                        <div style="height: 0px;" class="mejs-captions-selector">
                            <ul><li><input name="mep_0_captions" id="mep_0_captions_none" value="none" checked="checked" type="radio"><label for="mep_0_captions_none">None</label></li><li><input name="mep_0_captions" id="mep_0_captions_en" value="en" type="radio"><label for="mep_0_captions_en">English</label></li><li><input name="mep_0_captions" id="mep_0_captions_pl" value="pl" disabled="disabled" type="radio"><label for="mep_0_captions_pl">Polish (loading)</label></li></ul>
                        </div>
                </div>
            </div>
            <div class="mejs-clear"></div>
        </div>
    </div>

_Copied from original issue: adaptlearning/adapt-contrib-media#77_

**Comment by guywillis** [comment]
_From @LukaszGrela on January 28, 2015 11:32_

I have created sample project and added it to the repository
https://github.com/LukaszGrela/adapt-contrib-media-bug-showcase

**Comment by guywillis** [comment]
_From @LukaszGrela on January 30, 2015 13:42_

on top of that, when tracks feature is used (closed captions) then the menu with languages is trimmed.

**Comment by guywillis** [comment]
_From @LukaszGrela on February 5, 2015 8:39_

**Update** When the media element is created it searches for closest visible container to take size from it. `t.container.parent().closest(':visible')` In this case the closest was article. This alone didn't explain why the issue was happening as the other course was running fine. The answer was clear after comparison, this course was changing the visibility of the elements because it was using trickle plugin. After I've uninstalled it all works well (size of the video AND size of the CC menu).

Is there any Adapt event that will tell me that element has been made visible?

**Comment by moloko** [comment]
I've just tried this using latest framework, media and trickle plugins and all seems fine to me...
