### ISSUE TITLE
Media - IE8 stuck on the loading page when trying to open a page containing a media component

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#857]
_From @nilslp on April 27, 2015 16:6_

There seems to be a pretty severe issue on IE8 with the media component.
If a user on IE8 tries to go into a page that contains a media component (video in this case) the loading page appears and it is then stuck here. Has anyone else encountered this?

I am not sure if this is related to another ticket open here: https://github.com/adaptlearning/adapt-contrib-media/issues/61

It is happening with an OGG and MP4 file. Are there any requirements for IE8 that a user would have to already have on their machine?

_Copied from original issue: adaptlearning/adapt-contrib-media#92_

**Comment by oliverfoster** [comment]
Adobe flash.
