### ISSUE TITLE
Media - Change the default player on Devices to native player

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#858]
_From @aniketdharia on June 5, 2015 8:10_

Change the default player on Devices to native player to resolve the accidental tap while scrolling.

_Copied from original issue: adaptlearning/adapt-contrib-media#104_

**Comment by guywillis** [comment]
_From @moloko on June 5, 2015 8:49_

the accidental tap issue should be fixed in v2



—
Matt Leathes

**Comment by guywillis** [comment]
_From @aniketdharia on June 10, 2015 18:32_

Ok . I checked the code. Will take it up for testing and if it works will close this issue.

Thanks

**Comment by moloko** [comment]
this is definitely fine now - was implemented in v2.0.0 and a bug with it not working when the page contained multiple video components was fixed (and tested as being fixed) in v2.0.1
