### ISSUE TITLE
Media - Cannot Hide Video Controls

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#859]
_From @samumist on September 21, 2015 14:3_

The video controls is blocking the subtitles, especially on small screen devices. I tried to set the player options as following, but no effect.
```
"_playerOptions": {
    "alwaysShowControls": false,
```

_Copied from original issue: adaptlearning/adapt-contrib-media#121_

**Comment by moloko** [comment]
this is actually fixed in the master branch of contrib-media
