### ISSUE TITLE
Text Input - Validation issues for generic _answers in authoring tool schema

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#866]
_From @dancgray on July 1, 2015 11:4_

There should be the same number of items in the generic _answers array as in the _items array. I don't think it is currently possible to validate this in the authoring tool schemas.

It may be better to refactor this functionality, e.g "_answersInAnyOrder": true/false.

_Copied from original issue: adaptlearning/adapt-contrib-textInput#59_

**Comment by guywillis** [comment]
_From @dancgray on July 1, 2015 11:7_

refers to this part of the JSON:

_answers

*Optional *

This allows generic answers, which are not dependant on order to be specified, allowing the learner to give the correct answers in any order, and still be marked correct. This attribute expects a 2-dimensional array:

“_answers”: [
   [“one”,1],
   [“two”,2],
   [“three”,3]   
]

**Comment by chris-steele** [comment]
This has been resolved a long while back.
