### ISSUE TITLE
Bookmarking - is not working on on SCORM cloud, probably other LMS's

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#867]
_From @dancgray on October 15, 2015 16:39_

Bookmarking seems to be failing on this line:

https://github.com/adaptlearning/adapt-contrib-bookmarking/blob/master/js/adapt-contrib-bookmarking.js#L57

Error is 
TypeError: Cannot read property '_byAdaptID' of undefined(…)

this.locationID is null and not being set in checkRestoreLocation

_Copied from original issue: adaptlearning/adapt-contrib-bookmarking#15_

**Comment by guywillis** [comment]
_From @oliverfoster on November 23, 2015 10:7_

@dancgray did we solve this with the alternative branch merge? i'm sure you has said this was ok now..

**Comment by dancgray** [comment]
Fixed in November.
