### ISSUE TITLE
Bookmarking - Unusable on iPad in landscape

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#868]
_From @hmaffin on November 18, 2015 10:1_

On iPad in Landscape mode, Bookmarking banner goes off the bottom of the page and cannot be used unless turned to portait.

![photo](https://cloud.githubusercontent.com/assets/11558341/11238086/36a374e8-8ddb-11e5-9a00-f509a4ddf162.PNG)

_Copied from original issue: adaptlearning/adapt-contrib-bookmarking#18_

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 10:35_

uhoh! that uses notify.... this is not good...

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 10:38_

can you list the iPad model and the iOS version?

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 10:39_

looks like it's in an iframe also

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:5_

Mine is an iPad 2 on iOS9.1 although it happens on another iPad we have in the department.

It is running through Moodle in a popup window.

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:11_

thanks. does the navigation bar go off the top of the screen when you scroll?

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:14_

Yes. Shouldn't it?!

PS you can't scroll the page you see above, it's immovable

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:19_

The other iPad is :  16GB Wifi only iPad 4 
IOS version 7.0.6

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:23_

yea, it's in an iframe still :/ 

the fixed position things (the notify popups and navigation bar) should sit relative to the size of the browser window. 

when they're in an iframe this doesn't happen. the fixed position elements sit relative to the size of the iframe. the iframe height is determined by its content size and not by the size of the browser window (an horrific bug)... so if the iframe content (the adapt course page) is longer than the brower window, the popups will appear like they've done for you, in the middle of the iframe, not in the middle of the window.

you also can't scroll the content inside the iframe. so the navigation bar appears at the top of the iframe, but as you're scrolling the page which contains the iframe, the the content inside the iframe, the navigation bar scrolls off the screen.

you need to find a moodle setting which ditches the iframes... which is where my knowledge dies. perhaps someone else can help?

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:28_

~~https://docs.moodle.org/22/en/File_module_settings < suggests using "New Window" rather than "In Popup"~~ edit, wrong link: https://docs.moodle.org/22/en/SCORM_settings#Display_settings

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:34_

Oh yes of course, the nav bar stays put when i preview in a browser. Hadn't noticed the switch!

Our Moodle course is in a new window.... we don't have a pop-up option. Plus we don't have the option to change how we show it as I'm not an administrator and any changes have to go through a lengthy change request process.

I am having to put some javascript in to my index.html already to force Moodle to get rid of some annoying css formats.

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:36_

PS on PC from moodle in an iframe the bookmarking banner works fine, as does the nav bar.

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:36_

yea, all pc browsers appear to do iframes correctly. it's only ios which has issue.

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:37_

ah ha. Yes just checked and our only options in Moodle are Current Window or New Window.

![image](https://cloud.githubusercontent.com/assets/11558341/11240211/cb5876e4-8de8-11e5-9163-8e3d3f429b3d.png)

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:40_

Pete (my boss) asks which version of Moodle you're using?

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:41_

2.7 :)

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:42_

Two ticks, he's gone to ask the dudes from our LMS team.

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:42_

heh - thanks Oli and Pete!

**Comment by guywillis** [comment]
_From @oliverfoster on November 18, 2015 11:47_

i had the wrong help page btw > https://docs.moodle.org/22/en/SCORM_settings#Display_settings < says exactly what your screen shot does. Pete is gonna hop onto gitter and give you a response.

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 11:47_

awesome

**Comment by guywillis** [comment]
_From @kineopete on November 18, 2015 12:0_

Hi Helen, unfortunately both of those Moodle launch options use an iframe and so will cause these problems in iOS. There is a fix available in Totara (which is built on top of Moodle core code) which offers a third launch option - new window (simple) which doesn't use an iframe. 

These enhancements are often pushed back from Totara to Moodle, but we've just checked Moodle 2.8 and 2.9 and both versions have the same two launch options as 2.7. I will check-in with the Totara team to see if there have been any discussions with Moodle about the fix.

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 12:53_

Fabulous. We are thinking of moving to Totara in a few years perhaps but doesn't help us now I guess.

Can I use css to modify the position of it to fixed for now?

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 12:58_

Accordions and Assessment are also broken on iOS with Moodle.

**Comment by guywillis** [comment]
_From @moloko on November 18, 2015 15:38_

hi @hmaffin why not launch in 'same window' then use the ['launch page' technique](https://community.adaptlearning.org/mod/forum/discuss.php?d=477#p2212) to have the course open itself in a new window?

**Comment by guywillis** [comment]
_From @hmaffin on November 18, 2015 15:41_

Worth a shot I guess!

**Comment by guywillis** [comment]
_From @oliverfoster on November 19, 2015 9:33_

Success?

**Comment by guywillis** [comment]
_From @hmaffin on November 19, 2015 17:33_

OK well, almost. I used the launch.html and the following happens 
1. Navigation drawer and accordions work great now!
2. it never auto pops up my pop up window, I ALWAYS have to click on "click here to try again" even though my pop-up blocker is set to allow.
3. When I close the tab with the adapt course in it it sticks on the "Your course should load in a new window" screen (set in current window for Moodle) -this is more of an annoyance than a big problem but if you launch a SCORM course in a new window and then close that new window Moodle force returns to the course's main page.
4. Bookmarking banner is not showing up to ask me if I want to go back to my last visited page
*EDIT* ah wait bookmarking is now showing up. I think this is linked to 3 above. If I use the "click here to try again" link after i close the course tab, rather than going back to the course's main page, it does not load bookmarking. If we could fix 3 this won't be a problem.

But ultimately yes so much better than it was before! Thanks so much Matt, Pete and Oli.

**Comment by guywillis** [comment]
_From @oliverfoster on November 20, 2015 13:21_

https://github.com/oliverfoster/adapt-moodle could you give this extension a try? if you've got trickle there is a branch with a few fixes in to make it work located at https://github.com/adaptlearning/adapt-contrib-trickle/tree/feature/moodle-iframe

**Comment by guywillis** [comment]
_From @moloko on November 20, 2015 20:35_

hi @hmaffin 
1. great stuff!
2. It does sound slightly like you might have another popup blocker in play... What browser are you using and does it make any difference if you use an alternative?
3. this is standard Moodle behaviour for any course that opens in same window, you have to click 'Exit Activity' (usually in the top right) or use the breadcrumb trail. Not quite sure why Moodle does this, possible something to do with supporting multi-SCO packages? I usually add something to launch.html to explain to the user that they need to click 'Exit Activity' once they have close the course.
4. Sorry I'm not sure why this would be, this should work fine. Bookmarking definitely configured correctly? If you switch on Moodle SCORM debugging (or the contrib-spoor debug window) can you see a bookmark being saved/retrieved? Does it work if you put the same course on another LMS like SCORM Cloud (minus the launch.html page)?

**Comment by chris-steele** [comment]
@guywillis This one seems to have gone stale. I can't identify an actual issue in the framework after reading through the conversation. OK to close this?

**Comment by hmaffin** [comment]
Yes i believe it was an iframe issue - rather than a problem with the extension. Happy to have it closed

**Comment by chris-steele** [comment]
@hmaffin Thanks for coming back to us quickly on this - will close. Cheers :)
