### ISSUE TITLE
Page Level Progress - Article + Blocks should be available in plp

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#869]
_From @oliverfoster on May 22, 2015 13:35_

If an article or block title describes a series of components with not titles, PLP will still take you to the component and the article / block title will be off the screen.

This looks terrible.

Need to allow articles and block in the PLP

_Copied from original issue: adaptlearning/adapt-contrib-pageLevelProgress#44_

**Comment by simondate** [comment]
Has there been any work on this?

**Comment by oliverfoster** [comment]
nope

**Comment by simondate** [comment]
I'm assuming it would require creating an attribute in the Article level of PLP extension called `showInProgressDrawer` . Probably a lot of work?

**Comment by oliverfoster** [comment]
um, please don't invent a new attribute, just follow the pattern of the block config. it's the other bits that'll be more work, defining the property is pretty much already done on the block.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/8202e3c291c15edb5e1905f14566c1f4d12c1a6c
