### ISSUE TITLE
Page Level Progress - OptionalContent property is in the wrong place

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#870]
_From @brian-learningpool on June 29, 2015 9:55_

For consistency this should be next to _altText, not inside globals.

_Copied from original issue: adaptlearning/adapt-contrib-pageLevelProgress#50_

**Comment by guywillis** [comment]
_From @oliverfoster on August 12, 2015 12:4_

This seems to tie into the new globals system a little better. Should we still change it?

**Comment by moloko** [comment]
is this still relevant?

**Comment by oliverfoster** [comment]
yes, we need it to take from globals or from plp config

**Comment by oliverfoster** [comment]
no, i guess not
