### ISSUE TITLE
Page Level Progress - and Accordion component

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#871]
_From @dacashmachine on September 16, 2015 19:26_

Hi,  I have been using the latest version of the Adapt framework and builder, and I am having an issue regarding the page level progress component.  I have noticed that the second time you visit a page with the page level progress, it doesn't seem to log when you complete an accordion component.  I have noticed that it is only the accordion one that is having a hard time and ONLY on the second time through the course.  You will see the other components on the page mark complete as you go through but the accordions no.

_Copied from original issue: adaptlearning/adapt-contrib-pageLevelProgress#70_

**Comment by guywillis** [comment]
_From @moloko on September 17, 2015 8:51_

hi @dacashmachine - I've just been giving this a try in the out-of-the-box course provided with adapt framework v2, I don't seem to be able to replicate.
Could you give us a bit more detail about how you replicate this issue i.e. what browser you are using; is the course hosted on an LMS - and when you say 'second time through the course' what do you mean by that? Do you go to the page with the accordion component on it, then back to the menu then back to the page? Or quit the course altogether then relaunch?

**Comment by guywillis** [comment]
_From @dacashmachine on September 17, 2015 12:42_

It's when I'm in an scorm cloud, on both chrome and safari.  and just not
in an lms either.  There is also the same issue with the hot spot graphic.
 but with the hotspot graphic i found I can trick it to say complete on the
progress bar if i shrink the browser down to phone size and go through the
narrative version of the hot spot graphic.  And this is happening when I
quit the course all together and relaunch in scorm or if I complete the
whole course,(i have a like learning module then a seperate assesment page
so upon completion of both pages.) and then just replaying it after
completion.  I hope that makes since.  I might need to try and download the
developer version of those components and reinstall them im using the
developer authoring tool version.

**Comment by moloko** [comment]
unable to replicate
