### ISSUE TITLE
Page Level Progress - Navigation padding variable, when changed the error is thrown at the page-level-progress-navigation

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#872]
_From @LukaszGrela on November 4, 2015 13:6_

I've been updating the padding for navigation bar from `@navigation-padding: 5px;`, single value to `@navigation-padding: 5px 0px 5px 26px;` multi-value form. With this change during the compiling I've got following error:

```
Running "less:dist" (less) task
>> OperationError: Operation on an invalid type in src/less/adapt.less on line 6
658, column 5:
>> 6657 .page-level-progress-navigation {
>> 6658     padding:(@navigation-padding+6px);
>> 6659     @media all and (max-width:(@device-width-medium - 1px)) {
Warning: Error compiling src/less/adapt.less Use --force to continue.

Aborted due to warnings.
```

Probably theme should give more granular padding variables for this
https://github.com/adaptlearning/adapt-contrib-vanilla/issues/185

_Copied from original issue: adaptlearning/adapt-contrib-pageLevelProgress#81_

**Comment by guywillis** [comment]
Same issue as https://github.com/adaptlearning/adapt_framework/issues/884

**Comment by chris-steele** [comment]
@guywillis I can see this is still an issue - is this one for you or your team?

**Comment by oliverfoster** [comment]
#mindblow#

**Comment by chris-steele** [comment]
@guywillis you mentioned on the tech call yesterday this sort of thing being possible in the new 'themeless' Adapt, is that right?

**Comment by moloko** [comment]
is this still an issue?

**Comment by jamesrea83** [comment]
@guywillis Is this one still relevant?

**Comment by oliverfoster** [comment]
very very old, closing
