### ISSUE TITLE
Spoor - Consider responding to visibilityChange for mobile platforms for LMSCommit()

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#873]
_From @brian-learningpool on November 26, 2015 11:4_

This was mentioned by @moloko on the Gitter room in reference to https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility.

"we should be using a combination of pagehide and visibilityChange in Safari mobile & desktop, unload and visibilityChange in Android and just unload for other desktop browsers"

_Copied from original issue: adaptlearning/adapt-contrib-spoor#115_

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-spoor/commit/bb660119c0cae999271b2c64a2065caf63e52992
