### ISSUE TITLE
Trickle - debounce resize check

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#874]
_From @oliverfoster on August 13, 2015 22:1_

can overwhelm ie8

https://github.com/cgkineo/jquery.resize/issues/1

need to move this library into adaptlearning

_Copied from original issue: adaptlearning/adapt-contrib-trickle#49_

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-trickle/commit/113c4e6705f775fc80d1297802cf731b196a5541
