### ISSUE TITLE
Trickle - Completed components locked in trickle on revisit

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#875]
_From @dancgray on October 21, 2015 14:9_

when you have presentational components loaded from Spoor (you have left the course and come back), some of the components have been locked off by trickle, despite having been completed. Reported by @andrewhosgood 

This is because trickle uses _isInteractionComplete for completion attribute by default. Can set _completionAttribute in config.json : "_trickle": { "_completionAttribute": "_isComplete" }

Needs documenting in readme, exampe.json and properties.schema if this is to be used as a solution.

_Copied from original issue: adaptlearning/adapt-contrib-trickle#57_

**Comment by guywillis** [comment]
_From @belal-almassri-spongeuk on October 21, 2015 15:10_

I suggest making PR for the config page including the following line of code: 
"_trickle": { "_completionAttribute": "_isInteractionComplete " }.

I know it is set by default, but it could be handy to have it in the config page as well.

**Comment by guywillis** [comment]
_From @dancgray on November 10, 2015 13:52_

Issue created in Jira:
https://adaptlearning.atlassian.net/browse/ABU-1127

I think there is a bug with this when _completionAttribute =  _isInteractionComplete. See jira ticket:
https://adaptlearning.atlassian.net/browse/ABU-1126

**Comment by dancgray** [comment]
Fixed in 
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/124 and https://github.com/adaptlearning/adapt-contrib-accordion/pull/73
https://github.com/adaptlearning/adapt-contrib-trickle/pull/64
