### ISSUE TITLE
Trickle - Cannot disable trickle on articles after using a custom _completionAttribute

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#876]
_From @andrewhosgood on October 22, 2015 12:2_

When you set the attribute in `config.json` e.g.

```json
"_trickle": {
    "_completionAttribute": "_isComplete"
}
```

Then disabling trickle in articles with:

```json
"_trickle": {
    "_isEnabled": false
}
```

doesn't appear to work.

Removing the `_completionAttribute` again works.

_Copied from original issue: adaptlearning/adapt-contrib-trickle#58_

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-trickle/commit/113c4e6705f775fc80d1297802cf731b196a5541
