### ISSUE TITLE
Trickle - button appears before notify pop-up

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#878]
_From @chucklorenz on November 2, 2015 5:32_

When Hot Grid has three items and the third item is clicked, the Trickle "Continue" button appears (frequently) before the Notify pop-up. In fact, if one is attuned to the behavior, the Trickle button can actually be clicked before the Notify pops up.

_Copied from original issue: adaptlearning/adapt-contrib-trickle#61_

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/26b7bdd925f4fbfa7056282128bf6c26ff218b5d
