### ISSUE TITLE
Trickle - trickle-buttonPlugin.js#shouldRenderButton - invalid if statement, missing brackets

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#879]
_From @LukaszGrela on November 13, 2015 8:46_

The if statement with 
`            if (!trickleConfig._button._component == "trickle-button") return false;`

will always be false, it should be:
`            if (!(trickleConfig._button._component == "trickle-button")) return false;`

or
`            if (trickleConfig._button._component !== "trickle-button") return false;`

_Copied from original issue: adaptlearning/adapt-contrib-trickle#62_

**Comment by oliverfoster** [comment]
property redundant in trickle refactor
