### ISSUE TITLE
Vanilla Theme - is templates/partials/buttons.hbs still being used?

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#881]
_From @moloko on December 8, 2014 15:49_

Looks it's not and templates/buttons.hbs is being used instead but just wanted to check I'm not missing something...

If it's not being used any more, can it be deleted?

_Copied from original issue: adaptlearning/adapt-contrib-vanilla#60_

**Comment by guywillis** [comment]
_From @oliverfoster on December 8, 2014 15:52_

Is far as I know it can be deleted.

**Comment by guywillis** [comment]
_From @hrajotia on December 9, 2014 5:6_

I also think we can delete it, but before that we should consider merging of these two PRs  adaptlearning/adapt-contrib-gmcq#43, adaptlearning/adapt-contrib-textInput#46. As the develop branch of these two components are still using the `templates/partials/buttons.hbs` partial.

**Comment by guywillis** [comment]
_From @darylhedley on December 9, 2014 13:34_

I think it should be cahnged to button.hbs and have a standard UI component for buttons - this way extensions and components can use it over and over again keeping similar UI. We should look to do this for most of the HTML elements

**Comment by guywillis** [comment]
_From @moloko on December 10, 2014 12:26_

@darylhedley I think what @hrajotia is saying is that this work has been done in in contrib-mcq and contrib-textInput - but is just awaiting someone to do a manual merge of the PR.
Or are you suggesting something over and above of how - for example - the MCQ component is set up?

**Comment by guywillis** [comment]
_From @darylhedley on December 10, 2014 12:40_

@moloko - my reply wasn't to Himanshu - it was to say we should be leaving this in and renaming it to button.hbs.

The contents should be something like this

```
<button class="button {{_classes}}">
{{#if _icon}}
<i class="icon  {{icon}}"></i>
{{/if}}
<span>{{text}}</span>
</button>
```

This way we can use this in plugins to create standard UI buttons by passing in the _classes, text and _icon

**Comment by guywillis** [comment]
_From @moloko on December 10, 2014 12:58_

Aha I see now - thanks for clarifying

**Comment by oliverfoster** [comment]
removing in theme > core #954
