### ISSUE TITLE
Vanilla Theme - Page title variable uses block margin in develop

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#882]
_From @zenduo on June 17, 2015 19:31_

Hey @kirsty-hames 

Just checking out the new theme updates, looking really good.

Had a question regarding the page-title.

It uses the block variable value to set the margin bottom. Should this be the case? All of the others have their own values.

.page-title {
        margin-bottom: @block-body-margin-bottom;
}

_Copied from original issue: adaptlearning/adapt-contrib-vanilla#104_

**Comment by tomgreenfield** [comment]
Done in https://github.com/adaptlearning/adapt-contrib-vanilla/pull/162.
