### ISSUE TITLE
Vanilla Theme - Should selection.json travel alongside fonts?

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#883]
_From @chucklorenz on August 1, 2015 22:42_

*selection.json* is a file that was produced by icomoon to make it easy to reselect icons. It was used to create the vanilla font files found in the *fonts* directory. It currently lives at vanilla root. Would it make more sense to store it in *fonts* with the files it created?

_Copied from original issue: adaptlearning/adapt-contrib-vanilla#159_

**Comment by guywillis** [comment]
From what I can tell, selection.json, is purely there so that you can load the font icon set into the Icomoon App. I have removed it from build, and moved it into different folders with no errors being returned. 

Perhaps renaming it to 'vanilla.json' and moving it to the fonts folder is more appropriate?

**Comment by chucklorenz** [comment]
I recommend that it be moved to the fonts folder with the various vanilla fonts; however, I don't recommend renaming it since that is a name used by icomoon. The selection file can be reimported into icomoon so that new additions/replacements can be easily made.

**Comment by oliverfoster** [comment]
+1

**Comment by lc-thomasberger** [comment]
+1 (for moving and keeping the same name)

**Comment by moloko** [comment]
+1

**Comment by guywillis** [comment]
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/187

**Comment by guywillis** [comment]
PR merged
