### ISSUE TITLE
matching: Disabled State default styling cannot be overridden

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#886]
"Having issues where the select text turns into a light grey when disabled on IE8/9. After some research it looks like it's not possible to change that grey. This is causing issues where the text is very hard to read depending on the background colour of the select. Only way around it atm is for it to be styled with a white background colour on the browsers affected."
https://github.com/adaptlearning/adapt-contrib-matching/issues/46

**Comment by lc-thomasberger** [comment]
created a fork with select2: https://github.com/lc-thomasberger/adapt-contrib-matching/tree/select2
needs some testing and feedback and probably some accessibility work.
Important:
updated to select2 update, required a lot of style changes. might cause breaking changes. recommend to merge this after we decided how to deal with the theme rework.

**Comment by chris-steele** [comment]
Needs a visual state for when select controls have focus, but I like that the select menu is revealed on selection - this is an accessibility improvement certainly.

I don't think there is a way around this (correct me if I'm wrong), but I don't think we can get the +60KB dependency any smaller can we? Seems a bit heavy for something which is specifically addressing an issue in a couple of old browsers.

**Comment by lc-thomasberger** [comment]
Have added a focus style when accessibility is switched on.

Unfortunately not. I have not found a way to create custom builds. Have added the minified version though.

**Comment by lc-thomasberger** [comment]
todo: remove !important from _select2.less

**Comment by moloko** [comment]
@chris-steele there's also [Chosen](https://harvesthq.github.io/chosen/) might be a bit lighter than Select2? Sitepoint do a comparison of the two [here](http://www.sitepoint.com/jquery-select-box-components-chosen-vs-select2/)

**Comment by lc-thomasberger** [comment]
Chosen mentions that it is disabled on iOS and Android. https://github.com/harvesthq/chosen/pull/1388

Will need to test.
