### ISSUE TITLE
slider: rebuild - possibly based on 'range-slider'

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#887]
Quite a lot of issues with this component are arising and are difficult to fix because of the somewhat 'quirky' nature of the code.
Suggest we take the opportunity to rebuild this component based on something like rangeslider.js - need to first check it's going to be RTL compliant though

**Comment by moloko** [comment]
PR: https://github.com/adaptlearning/adapt-contrib-slider/pull/97

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-slider/releases/tag/v2.1.0
