### ISSUE TITLE
Page-level progress progress-bar offset

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#892]
Steps to replicate:

Download and extract latest Adapt Framework zip
Add trickle elements into the article.json file
Build and Run

If you now open the 'presentation components' section and click on the drawer, you'll notice the disabled page link progress-bar are not in-line with the 1st enabled link (offset by about 10px to the right).

Moved from https://adaptlearning.atlassian.net/browse/ABU-1138

**Comment by lc-thomasberger** [comment]
@dancgray possible duplicate to #932 ?

**Comment by dancgray** [comment]
@lc-thomasberger yes, definitely a duplicate. Thanks
