### ISSUE TITLE
Different answers weight rather than just a single question weight

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#893]
I'm to build an assessment which requires a question component I'm not sure how to build with Adapt.
It's a 4-options MCQ of single answer. All 4 options are selectable, but different answer option has different weight point. For example, Option A - 4 points, Option B - 3 points, Option c - 2 points and Option d - 1 point.
Currently, the adapt-contrib-mcq only allow setting up the whole question weight rather than the answer weight.

+1 johnniezen

Moved from https://adaptlearning.atlassian.net/browse/ABU-1043

**Comment by oliverfoster** [comment]
sub issue of #1974
