### ISSUE TITLE
GMCQ Layout issues

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#894]
At present the GMCQ can only display 2 items per line (even when spanned). This needs to be changed (and be configurable) so that:
Component can be single or spanned.
2 to 4 items can be placed within a line and then any more should wrap onto the line below
The items on the second row need to also be configurable so that if there are less items they can be left, centre or right aligned.
For mobile the default should be a single item although I think a single width should allow

Anonymous added a comment - 04/Sep/15 4:29 PM
+1

Anonymous added a comment - 16/Sep/15 1:18 PM
+1 johnniezen

Moved from [ABU-948](https://adaptlearning.atlassian.net/browse/ABU-948)

**Comment by guywillis** [comment]
Hi Dan,

I'm working on implementing a column system to the GMCQ component and I am wondering how useful it would be to align the overflow items to the left / right?

What are the possible use cases for these alignment options?

Thanks in advance.

**Comment by guywillis** [comment]
PR for configurable column layout - https://github.com/adaptlearning/adapt-contrib-gmcq/pull/96

Note: Currently does not contain overflow item alignment.

**Comment by guywillis** [comment]
done in https://github.com/adaptlearning/adapt-contrib-gmcq/commit/bd4e5a2473949793836d260d9a99b6d7f52bddfb

Awaiting outcome of above question before closing.

**Comment by dancgray** [comment]
I guess there might be some use cases where you need a direction for the items, but it would alter on RTL or LTR languages. If someone has a requirement for that then I would suggest they detail it in another issue.

**Comment by guywillis** [comment]
Thanks for replying Dan.

Closing issue.
