### ISSUE TITLE
adapt-cli: rework create component

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt_framework#896]
adapt-cli has "create component" command. It uses adapt-component as a template. Rework command so that it can create a presentation component and a question component. Template repository (adapt-component) would need to be updated as part of this work.

Moved from [ABU-772](https://adaptlearning.atlassian.net/browse/ABU-772)

**Comment by moloko** [comment]
bump - this still needs looking at.

at the very least we should get rid of the 'tests' folder, .travis.yml and karma.conf.js as we stopped using these in Adapt some time ago

**Comment by oliverfoster** [comment]
closed as ancient
