### ISSUE TITLE
Media completes in iPad when transcript button is clicked

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#898]
I updated Media so that it includes "Inline transcript triggers completion". Now in iPad, the component triggers the Trickle button when I click the transcript button.

To replicate in iPad:
- Media component in trickled block.
- component JSON including "_setCompletionOn":"ended" and "_transcript"."_setCompletionOnView": false for good measure.
- navigate to Media and verify it is locked by Trickle.
- click "View Transcript" button and then the Trickle button appears

**Comment by moloko** [comment]
ah - this would be because we set it so that it would always complete when transcript opened if accessibility is active - and accessibility is _always_ active on iOS...

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-media/pull/136

**Comment by oliverfoster** [comment]
done as discussed
