### ISSUE TITLE
IE8 and The "jump to top" scrolling issue

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#900]
This is general to the framework but I could replicate it on the page with the accordion component. I was clicking on the item to reveal it. I've checked this on the 2.0.6 version, page co-05.

**Comment by davewallace** [comment]
I just replicated this on an accordion component and mcq component on an ipad in portrait orientation, too.

**Comment by sarveshwar-gavhane** [comment]
@LukaszGrela i have tested on IE8 and ipad ,this is not happening now, this issue can be closed.....???

**Comment by LukaszGrela** [comment]
Yes it is, IE8 (8.0.6001.18702IC) on Win XP - here you can see the scrollbar moving up and down), on Win 7 IE11 in emulation of IE8 (here you can see the flash of the content from above).
If other can't replicate then maybe it is something peculiar to my machine?

**Comment by chris-steele** [comment]
@LukaszGrela just to note, support for IE8 on XP has been dropped, so this issue is unlikely to resolved any time soon.
