### ISSUE TITLE
need to be able to exclude 'decorative' images from the tabbing order

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#902]
Content frequently contains images which are either merely 'decorative' i.e. they have no bearing on the e-learning (they're just there to make the page look nice) - or any alt text you would associate with them is already displayed somewhere else, leading to pointless repetition.

We need to have some way of excluding these from accessibility to prevent screen-reader users from having to read through image descriptions that have no meaning to the content e.g. 'stock photo image of two business people shaking hands' or that just repeat text that is elsewhere.

So far I've mainly encountered this in contrib-graphic and notify images (where the alt text for the image is a repetition of the notify popup title)

The solution I've used which seems to work well is to do something like this:
```
{{#if alt}}
<img src="{{image}}" alt="{{alt}}" tabindex="0"/>
{{else}}
<img class="a11y-ignore" aria-hidden="true" tabindex="-1" src="{{image}}"/>
{{/if}}
```

**Comment by hrajotia** [comment]
or even a one liner -
```
<img src="{{image}}" {{#if alt}}alt="{{alt}}" tabindex="0"{{else}}class="a11y-ignore" aria-hidden="true" tabindex="-1"{{/if}} />
```

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-graphic/commit/e14fa4830250fc9f915b8200cd5b92f57b31edaa
