### ISSUE TITLE
Player options 'features' cannot be set in the authoring tool

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#903]
The player options cannot be set in the authoring tool as an array of string values is expected by the JS code.  Perhaps in the authoring tool the schema could be updated to render checkboxes or drop down lists, and the media code updated to toggle the arrays depending on which settings are enabled.

**Comment by taylortom** [comment]
Yeah, this is an interesting one. We don't support the majority of the features, so maybe we just add the most useful to the schema, and don't bother with the rest? Can't imagine supporting dynamic objects is something that'll be particularly useful, so probably not worth sinking much time into.

**Comment by brian-learningpool** [comment]
For a first pass I was thinking of just supporting the basics, like 'playpause', 'duration', etc.

**Comment by taylortom** [comment]
Does this refer to the [whole object](https://github.com/adaptlearning/adapt-contrib-media/blob/master/example.json#L40-L76), or just the [features](https://github.com/adaptlearning/adapt-contrib-media/blob/master/example.json#L67)?

**Comment by brian-learningpool** [comment]
I was thinking of `features` specifically, as the authoring tool does not support entering an array of text strings.  I've updated the issue title for clarity.

**Comment by taylortom** [comment]
@tomgreenfield has found a fix for https://github.com/adaptlearning/adapt_authoring/issues/994 to allow for inputting arrays of strings.

**Comment by brian-learningpool** [comment]
I'm closing this ticket as @taylortom and @tomgreenfield have been looking into support in the authoring tool for arrays of strings.  It's an authoring tool issue.
