### ISSUE TITLE
phase out use of 'position: fixed' due to poor cross-platform implementation

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#907]
move position fixed elements (notify, navigation etc) to use position absolute and amend global css to start new position stack on html element

e.g

```
html {
    position: absolute;
    height:100%;
    width: 100%;
    overflow: hidden;
}

body {
    height: 100%;
    overflow: auto;
}
```

**Comment by moloko** [comment]
moved from [ABU-1107](https://adaptlearning.atlassian.net/browse/ABU-1107)

**Comment by oliverfoster** [comment]
implemented in v4 scrolling behaviour
