### ISSUE TITLE
contrib-hotgraphic: Tabbing loses focus in item popup

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#908]
When tabbing through the default adapt build, the focus is lost when tabbing reaches the final text field in a hotgraphic's item popup. The focus returns to the top of the page, then to the instruction text on the narrative component, and then finally on to the close button within the hotgraphic popup.

Moved from [ABU-1142](https://adaptlearning.atlassian.net/browse/ABU-1142)

**Comment by moloko** [comment]
@oliverfoster https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/componentView.js#L33-L44

^ the focus is on this .accessibility-state element, it needs to be updated rather than replaced.

**Comment by moloko** [comment]
PR here: https://github.com/adaptlearning/adapt-contrib-narrative/pull/156

**Comment by chris-steele** [comment]
This should be good to go now.
