### ISSUE TITLE
contrib-slider: RTL layout issue

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#913]
While testing in RTL layout, I noticed 2 issues.

1. The 'slider-scale-marker' was offset from the actual 'slider-scale-numbers'.
2. Starting range is the same as LTR, instead of starting from 10 down to 1.

Moved from [ABU-1136](https://adaptlearning.atlassian.net/browse/ABU-1136)

**Comment by ratnadeeprajput** [comment]
PR raised - https://github.com/adaptlearning/adapt-contrib-slider/pull/98

**Comment by oliverfoster** [comment]
issue 2. as designed (from old slider and kineo israel)

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-vanilla/releases/tag/v2.0.2
