### ISSUE TITLE
Hot graphic enhancement - no images on pop up

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt_framework#914]
Would it be possible to add an enhancement to the hot graphic so that the pop up window (individual items) does not require an image and displays only text?

**Comment by moloko** [comment]
the problem with this is that the images that are associated with each hotspot are used as the main images when the component changes to narrative for smaller screens - so you'd still need to supply these images for it to work in 'narrative mode'

could you maybe work around this in the styling?

**Comment by kevindoherty30** [comment]
That's a very good point and one I hadn't considered, I think styling is the more sensible approach on this one. Thanks!
