### ISSUE TITLE
Bower.json issue links now out of date

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#918]
...as they all reference JIRA

**Comment by moloko** [comment]
I've been amending these with each new release

**Comment by tomgreenfield** [comment]
- [ ] Accordion
- [x] Assessment
- [x] Assessment Results
- [ ] Blank
- [ ] Bookmarking
- [ ] Box Menu
- [ ] GMCQ
- [ ] Graphic
- [ ] Hot Graphic
- [ ] Matching
- [ ] MCQ
- [ ] Media
- [ ] Narrative
- [ ] Page Level Progress
- [ ] Resources
- [ ] Slider
- [ ] Spoor
- [ ] Text
- [ ] Text Input
- [ ] Trickle
- [ ] Vanilla
- [ ] Tutor

**Comment by moloko** [comment]
OK all done
