### ISSUE TITLE
Remove DOM manipulations from views - react style

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#921]
the best part about react's rendering style can be summed up in this video > https://www.youtube.com/watch?v=nYkdrAPrdcw 
it's a bit long, start from about 10:20 with jing chen talking about MVC, then at 26:00 Pete describes the important followup.

:: Rerender, diff with DOM and update DOM changes whenever the view-state or model changes. 
:: The View, Template and the DOM are always identical and manual DOM manipulation code can be removed.
1. View expresses state
2. Template expresses DOM representation
3. View, Template and DOM relationship taken care of in the framework
4. Programmers just need to write a template which renders the view state and a view which renders a state, never will the two cross.
##### 1. Inside the template

```
   <div style="{{_width}}"> </div>
```
##### 2.DOM starts empty

```

```
##### 3. The view changes it's state

```
    this.view.set("_width", "100%");
```
##### 4. DOM Changes to

```
   <div style="100%"> </div>
```
##### 5. The view updates the width

```
    this.view.set("_width", "50%");
```
##### 7. DOM update to ONLY the `style` attribute value

```
   <div style="50%"> </div>
```

Much easier to program and understand. No DOM manipulation code required.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-narrative/tree/enhancement/921 < is how a component can look in this style.

https://github.com/adaptlearning/adapt_framework/tree/enhancement/921 < is a version of the framework with the relevant amends (for just components in this style), the adapt.json is configured to install the above narrative using:

See it in action with:

```
git clone https://github.com/adaptlearning/adapt_framework
cd adapt_framework
adapt install
npm install
grunt build
grunt server
```

**Comment by moloko** [comment]
definitely like the concept, need to have a little bit more of a look at the implementation

**Comment by oliverfoster** [comment]
please do, this could utterly change the way we build components

**Comment by oliverfoster** [comment]
the implementation isn't production ready, but it should give you an idea of how easy this is to get

**Comment by taylortom** [comment]
Yes

**Comment by oliverfoster** [comment]
Lol? Yes?

**Comment by oliverfoster** [comment]
added hotgraphic example https://github.com/adaptlearning/adapt-contrib-hotgraphic/tree/enhancement/921

* split out hotgraphic and popup into separate views
* created a basicViewDifferential class in adapt_framework (it extends from Backbone.View)
* implemented hotgraphic popup as a basicViewDifferential
* hotgraphic popup shares viewstate and model with hotgraphic but lives in a child node of hotgraphic

**Comment by brian-learningpool** [comment]
I've had a quick look and in principle I'm in favour of something like this.  

From a cursory look I think`this.view` should be renamed to something like `this.state` though, as `this.view` containing instances of `Backbone.Model` is a little confusing.

**Comment by oliverfoster** [comment]
Seconded

**Comment by oliverfoster** [comment]
* changed this.view to this.state
* added ie8 skip checking for attributes jquery*, sizzle* and a11y_uid
* added skip checking for attributes data*

**Comment by oliverfoster** [comment]
* Added optional selective redraw on named attributes changing... Like "_isComplete", "_isDesktop", "_currentIndex" etc. That way we can specify that "_isReady" won't trigger a redraw. 
* Added diff + change debug messages and times to help show when redraws are occurring with which view state changes.
* Removed a lot of duplicate code
* Renamed some variables.
* Added some view removal checks and functions.

**Comment by moloko** [comment]
+100 absolutely love it

**Comment by oliverfoster** [comment]
* reworked after remaking and unit testing a faster differ library

**Comment by moloko** [comment]
also need to investigate https://github.com/mateusmaso/handlebars.binding

**Comment by oliverfoster** [comment]
very stagnant, deferring to v6
