### ISSUE TITLE
PLP disabled drawer items style

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#932]
The text of disabled PLP items doesn't match the styling of enabled items.

![after-box-sizing](https://cloud.githubusercontent.com/assets/9489014/12707343/bf767f7e-c858-11e5-8ac7-98b2d0653f7e.gif)

Related to https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/83

**Comment by moloko** [comment]
see https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/84

**Comment by moloko** [comment]
and https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/83
