### ISSUE TITLE
Look into hooking up jscs/jshint to travis

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#933]
Support for jshint/jscs has been added [here](https://github.com/adaptlearning/adapt_framework/pull/891), but compliance is currently at the individual developer's discretion.

Would be nice to get this enforced in someway -- either as a git hook to be called on commit, or at the travis ci level. 

I'm all for the consistency that this should bring, but think we need to be careful that we're not too strict with the rules, as will likely cause many :angry::anger::fist:

**Comment by moloko** [comment]
yeah the danger here is that - because we are adding this _after_ the majority of code has been written - lots of existing stuff will be flagged the first time it's run. so whoever does the first commit/push is going to be hammered with all the existing issues!

**Comment by taylortom** [comment]
Yeah exactly. A solution could be to add a very bare-bones configuration (i.e. stuff we definitely *don't* want to get through like spaces/tabs or whatever), and just let everything else be up to the dev.

**Comment by taylortom** [comment]
Have set up a test. See the following for more details:
- [.travis.yml](https://github.com/taylortom/adapt_framework/blob/master/.travis.yml)
- [v2_test.sh](https://github.com/taylortom/adapt_framework/blob/master/v2_test.sh)

Main test consists of:
  1. `jscs`
  1. `jshint`
  1. `grunt build`
  1. An attempted build of the framework against v2.0.0 core plugins 

My tasks in script will override anything found in `scripts` in package.json, not sure if this is an issue or not.

**Comment by moloko** [comment]
see #2377
