### ISSUE TITLE
update theme to match slider updates

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#937]
due to the changes to slider using a third party library the less files in the theme need to be updated. This changes will make sure that the variables (colors, padding, fonts) are applied correctly and match the whole vanilla theme.

**Comment by lc-thomasberger** [comment]
PR -> https://github.com/adaptlearning/adapt-contrib-vanilla/pull/190

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-vanilla/releases/tag/v2.0.2
