### ISSUE TITLE
Allow ESC key to dismiss modal popups

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#938]
Thinking of things like the tutor, hotgraphic items, etc., it would be useful if the ESC key could dismiss these and return to the course.  It's quite a common behaviour now, e.g. Gitter, Slack, etc.

**Comment by moloko** [comment]
I seem to recall this couldn't be done on account of <esc> being a special key for screen readers... I thought perhaps I saw a PR for enabling it when accessibility wasn't active though, might be wrong

**Comment by moloko** [comment]
ah, it was for closing the drawer see #612

**Comment by oliverfoster** [comment]
this line for drawer https://github.com/adaptlearning/adapt_framework/blame/master/src/core/js/views/drawerView.js#L39 needs to be _isActive rather than _isEnabled, like https://github.com/adaptlearning/adapt_framework/commit/e9b7f9d48227c271ae9818ac632611816615c9ad

**Comment by moloko** [comment]
I think that's everything now?

**Comment by moloko** [comment]
added to hotgraphic in [v2.0.7](https://github.com/adaptlearning/adapt-contrib-hotgraphic/releases/tag/v2.0.7)
