### ISSUE TITLE
Trickle readability refactor

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#940]
https://github.com/adaptlearning/adapt-contrib-trickle/tree/refactor < branch

https://github.com/adaptlearning/adapt-contrib-trickle/pull/66 < pr

fixes #874
fixes #876
fixes #879

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-trickle/commit/113c4e6705f775fc80d1297802cf731b196a5541
