### ISSUE TITLE
Add a 'description' attribute to course.json

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#945]
I've been looking into the upcoming xAPI extension and it might be sensible to allow adding a `description` attribute to `course.json`.  The `body` attribute is carried through into the display of the course.  I'd imagine that the `description` property would not be rendered, but could be used in SCORM or xAPI files.

**Comment by moloko** [comment]
+1 
could also be used to populate 
* a meta description tag in the html
* the description metadata in imsmanifest.xml

**Comment by oliverfoster** [comment]
+1

**Comment by brian-learningpool** [comment]
This is resolved in #971

**Comment by moloko** [comment]
done in 11d87ab
