### ISSUE TITLE
make core resilient to theme

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#953]
Move basic and essential parts of the theme into core to reduce the requirement on the theme and give the theme more "themeing" responsibility.

Makes the core and theme more stable to theme changes.

**Comment by oliverfoster** [comment]
i had a thought that we could use grunt to take theme variables from the json and compile them into the css output through less variables. that way we could leverage the schema from the theme and the authoring tool editor to provide some quite complex customization - with comparably little... the themes would then be really easily to customize and we could have a less editor for the heavy stuffs?

**Comment by lc-thomasberger** [comment]
would make sense for deveice size variables specified in the [json](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/theme.json) and used in [LESS](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/generic.less#L6-L8)

Would be also possible to use assests (Images) uploaded to the AT in the theme? E.g. select a Image and use it as a background/hero-image for a block/page

**Comment by oliverfoster** [comment]
@sagarkachare @aniketdharia 
We're going to have to start again with this theme stuff.
Nobody is reviewing these PRs so we need to change course.
I've set up a new epic with the intention of starting from the beginning. [new epic](https://github.com/adaptlearning/adapt_framework/issues/1901)
Could I close these issue?
Can you let me know if you want to join in with the new attempt to sort out theming?

**Comment by oliverfoster** [comment]
restarting on https://github.com/adaptlearning/adapt_framework/issues/1901

**Comment by aniketdharia** [comment]
@oliverfoster assigned Sagar to the new Epic.. you can drop him an email and then he can get started.

Cheers!

**Comment by oliverfoster** [comment]
cool, thanks 👍
