### ISSUE TITLE
spoor + isoptional

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#957]
spoor will not restore the state of components on a revisit if the block was completed and contains only optional components.

this is as blocks with optional only components are marked as complete when adapt starts. spoor then checks for completion on the block before it restores the component completion. if the block is already complete, it will skip marking the children as complete.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/pull/120

**Comment by moloko** [comment]
+1

**Comment by brian-learningpool** [comment]
Code has been fixed in Spoor.
