### ISSUE TITLE
wrap component.hbs in div

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt_framework#965]
It would be nice to have the contents of _partials/component.hbs_ wrapped in a div. The title, body, and instruction are typically sisters of any widget that follows. This makes it difficult to style the title, body, and instruction as a group. One reason this is an issue is because IE maintains faint but visible space between divs. It cannot be eliminated without introducing a wrapping div and styling it instead.

**Comment by moloko** [comment]
this sounds eminently sensible to me; assuming it has no knock-on issues. would be interested to hear what @lc-thomasberger, @guywillis or @kirsty-hames think

**Comment by guywillis** [comment]
I can't think of there being any immediate knock on affects of surrounding the three elements in a div tag.. the problem arises when adding styling to this div tag and accounting for the varying components.

I've just recently done exactly this on a project and ran into the problem where applying a background colour + padding to the component-header causes components without a displayTitle / body tag to still render the styling. I solved this by simply including a &:not(.graphic-header).

If there were a way within the template file to do something like:

```{{#if displayTitle or body}}
{{_component}}-header component-header
	component-header-inner
{{/if}}
"{{_component}}-title
"{{_component}}-body"
"{{_component}}-instruction"
{{#if displayTitle or body}}
	/div
/div
{{/if}}
```

**Comment by chucklorenz** [comment]
Thinking about your last example, Guy...wondering if it is overkill. If I understand correctly, I'd be more concerned about your scenario if we were proposing a change to Vanilla that applied a style to this div that affected all components. Not so. I'm proposing a div with a class named appropriately for Adapt that simply wraps these elements. I'm not proposing an associated style class be introduced into Vanilla. The div would remain unstyled in Vanilla. 

A user can choose to hang a class on the div or not. The user can style individual components like that pictured below or apply styles across all components more generally. If they choose to broadly style all components, they can override styles on individual components. Either way, the responsibility remains with the course author to use it correctly to achieve the desired effect. Nothing different from many divs we have now.

![ex2](https://cloud.githubusercontent.com/assets/9489014/13288694/c6c2da3e-dad2-11e5-9d02-0fded06a0b6f.png)

**Comment by guywillis** [comment]
Apologies if I wasn't clear - I agree with you that it would be nice to have these wrapping divs around the title, body, and instruction that are not styled in the vanilla theme. It would then be up to the course author to implement any changes correctly.

**Comment by guywillis** [comment]
Created a PR in the vanilla theme to implement the above.

https://github.com/adaptlearning/adapt-contrib-vanilla/pull/188

**Comment by guywillis** [comment]
PR merged
