### ISSUE TITLE
adapt-cli nodejs version

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#968]
minimum 4.3  
throw error if lower

**Comment by gorhgorh** [comment]
I still have the code that make the warning somewhere if needed

**Comment by oliverfoster** [comment]
If you could that would be awesome

**Comment by gorhgorh** [comment]
code is here

https://github.com/gorhgorh/adapt-cli/commit/00a043715449f2b02a07625508ac0fde8621b06a

do you want a proper pull request or just pick it up ?(both works, but
expect a one day delay for a pr)


2016-02-22 17:17 GMT+01:00 Oliver Foster <notifications@github.com>:

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-cli/pull/51  did it with your name all over

**Comment by oliverfoster** [comment]
thanks man

**Comment by gorhgorh** [comment]
you are more thank welcome happy to help )
