### ISSUE TITLE
Performance issue in Grunt getIncludes() helper

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#972]
This function appears to enumerate the entire contents of the plugin directories via a `readdirSync()` followed by a `statSync()` to check if a directory or not.  

- [x] Exclude anything which isn't in the list of included plugins
- [ ] Remove the blocking Sync calls

**Comment by taylortom** [comment]
Need to look into this further, but I'm not sure doing things async will be possible with the `load-grunt-config` we're using.

**Comment by taylortom** [comment]
Partial fix here: https://github.com/taylortom/adapt_framework/commit/573ec01f25acc731854a7ad1a981f3866f165a87

Have removed the stats call -- anything included in the build includes should be a folder (assumption).
