### ISSUE TITLE
Possible performance with grunt server-build command

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#979]
~~When the `build.includes` array is set in `config.json`, the `grunt server-build` command still seems to bundle **all** components and extensions.  This is not how it should work~~.

(This issue was due to the sample course being bundled.)

**Comment by brian-learningpool** [comment]
Also, `isPluginIncluded()` seems to run for every file, rather than per directory/plugin.

**Comment by oliverfoster** [comment]
the compilers don't work on a plugin by plugin basis, they just pull together all the globs we tell them to. this means we have two options, we can either check each file for compliance by hooking into the compilers, or add an exclusion glob to the globs.
