### ISSUE TITLE
Missing RTL rule for button.base style

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#982]
In the Vanilla theme there is a style for `button.base` with `text-align:left`

[buttons.less#L27](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/src/buttons.less#L27)

there should be a style for `.dir-rtl` to change it to `text-align: right` as follows

```
        .dir-rtl & {
            text-align: right;
        }
```

issue is noticeable in accordion where the icon is on right and text on left where in-fact it should be also on right

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by guywillis** [comment]
+1

**Comment by guywillis** [comment]
PR created - https://github.com/adaptlearning/adapt-contrib-vanilla/pull/189

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-vanilla/commit/8fc9173125fdf2c0b6a553a05bfe3329ee5f2cc0
