### ISSUE TITLE
Clean install grunt build cannot find config.json

### ISSUE THREAD

**Issue by Si1kIfY** [adaptlearning/adapt_framework#984]
Fresh install doesn't seem to be working:

```
$ grunt build
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "/Users/Si1kIfY/dev/ucopea/build/course/config.json" file (Error code: ENOENT).
```

I'll try to remove / re-install and report back

**Comment by moloko** [comment]
Is this on a Mac by any chance?

**Comment by Si1kIfY** [comment]
Yep on Mac

**Comment by moloko** [comment]
Quite a few people are seeing this, we're looking into it

**Comment by moloko** [comment]
Problem seems to have been introduced in #971 - the replace code is attempting to read a file from the build folder before the build folder has been created.
