### ISSUE TITLE
JSON order has no effect on component output

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#985]
https://github.com/adaptlearning/adapt_framework/blame/master/src/core/js/models/adaptModel.js#L194-L201

this code breaks the assumption that the order of the json determines the order of the render. this is especially problematic when a right-hand graphic aside should appear above its sibling on mobile.

**Comment by tomgreenfield** [comment]
Older reference: https://github.com/adaptlearning/adapt_framework/issues/636.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/pull/987 pr to fix
