### ISSUE TITLE
Framework - Missing RTL on component-left/right styles

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt_framework#990]
I've noticed that there's no RTL style for `.component-left` or `.component-right` in base.less. 

```
.component-left {
    width:100%;
    float:none;
    @media all and (min-width:(@device-width-medium + 1px)) {
        width:50%;
        float:left;
        .component-inner {
            margin-right:5%;
        }
    }
}
```

I'd be interested to hear the thoughts of the community on whether an RTL style is required here or whether the left / right position of components is decided entirely by the `_layout` attribute.

**Comment by moloko** [comment]
any update on this?

**Comment by guywillis** [comment]
In hindsight, I feel that it would be confusing if your component layout attribute stated left but the component was displaying on the right hand side of the screen.

As such, I'm happy to close the question.
