### ISSUE TITLE
index.html does not validate

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#997]
if validated using https://validator.w3.org/, two errors and a smattering of warnings are shown

**Comment by oliverfoster** [comment]
What are we validating against? This has to be part html4, part html5, part iOS + IE hacks.

**Comment by moloko** [comment]
I'm just chucking src/index.html in to the above validator, nothing more...

**Comment by moloko** [comment]
for example it highlighted that the accessibility button had `role='button"` which is obviously not needed - assume it was just from when we used to use anchor tags for things like this

**Comment by oliverfoster** [comment]
Yea, that's fair.

**Comment by moloko** [comment]
see https://github.com/adaptlearning/adapt_framework/pull/998

I'll also need to do the files in contrib-spoor; will do that once this is accepted
